#!/usr/bin/env bash
# Generated by Cursor. 2026-09-02
# Frames-only dump of longest-tw trajectories listed in inventory.csv.
# q_i = P_i / sqrt(A_i); skip first 20% of records (stateCompareDump -s 0.2).
# No sbatch. Requires CELLGPU_SCRATCH and a built stateCompareDump.out.
#
# Usage (from repo root or this directory):
#   bash dump_q_map.sh
#   bash dump_q_map.sh --force

set -euo pipefail

ROOT="${CELLGPU_ROOT:-}"
if [[ -z "$ROOT" ]]; then
    ROOT="$(cd "$(dirname "$0")/../../../.." && pwd)"
fi
HERE="$ROOT/glassyDynamicsProject/analyseScripts/vertexTauAlpha/vertexModel_qMap"
INV="${INV:-$HERE/inventory.csv}"
DUMPDIR="$HERE/dumps"
FORCE=0
if [[ "${1:-}" == "--force" ]]; then
    FORCE=1
fi

NVHPC_ROOT="${NVHPC_ROOT:-/opt/nvidia/hpc_sdk/Linux_x86_64/26.5}"
export LD_LIBRARY_PATH="${NVHPC_ROOT}/compilers/lib:${NVHPC_ROOT}/cuda/12.9/lib64:${NVHPC_ROOT}/math_libs/12.9/lib64:${HOME}/opt/netcdf-cxx-legacy/lib:${LD_LIBRARY_PATH:-}"

EXE=""
for cand in \
    "$ROOT/glassyDynamicsProject/stateCompareDump.out" \
    "$ROOT/build-state-compare/glassyDynamicsProject/stateCompareDump.out" \
    "$ROOT/build-state-compare/stateCompareDump.out"; do
    if [[ -x "$cand" ]]; then
        EXE="$cand"
        break
    fi
done
if [[ -z "$EXE" ]]; then
    echo "missing stateCompareDump.out; rebuild the dump target" >&2
    exit 1
fi

mkdir -p "$DUMPDIR"
if command -v git >/dev/null 2>&1; then
    echo "HEAD=$(git -C "$ROOT" rev-parse HEAD 2>/dev/null || echo unknown)"
fi
echo "exe=$EXE"
echo "inv=$INV"

# Skip CSV header; columns: model,n,p0,T,tw,idx,tree,size,path,status,...
while IFS=',' read -r model n p0 T tw idx tree size path status rest; do
    if [[ "$status" != "ok" ]]; then
        echo "SKIP missing $model p0=$p0 T=$T"
        continue
    fi
    stem="${model}_p${p0}_T${T}"
    out="$DUMPDIR/$stem"
    frames="${out}_frames.csv"
    if [[ -s "$frames" && "$FORCE" -eq 0 ]]; then
        echo "exists $frames"
        continue
    fi
    echo "dump $model n=$n p0=$p0 T=$T -> $frames"
    if ! OMP_NUM_THREADS=1 "$EXE" -m "$model" -f "$path" -o "$out" -n "$n" -p "$p0" -s 0.2 -k frames \
            >/dev/null; then
        echo "FAIL $path" >&2
    fi
done < <(tail -n +2 "$INV")

echo "done"
