#!/usr/bin/env python3
"""
Generated by Cursor. 2026-09-02
List longest-tw vertex (batches 2-4 longest-crossed) and Voronoi production
NetCDFs for the <q>(p0, T) harvest. Missing files are rows with status=missing.

Physics: q_i = P_i / sqrt(A_i); we dump only after locating the aged snapshot
(longest valid waitingTime, skip stubs < 1 MB). Units: mean cell area 1.

Usage:
  python3 inventory_q_map.py
  CELLGPU_SCRATCH=... python3 inventory_q_map.py -o inventory.csv
"""

from __future__ import annotations

import argparse
import csv
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
SC = HERE.parent / "vertexModel_stateCompare"
if str(SC) not in sys.path:
    sys.path.insert(0, str(SC))

from find_state_files import (  # noqa: E402
    N_DEFAULT,
    TrajFile,
    _best_stat,
    list_glassy_names,
    list_voronoi_best,
    scratch_root,
)

CROSSED = HERE.parent / "vertexModel_tauAlpha_final" / "vertex_longest_crossed.csv"
P0_KEEP = (3.750, 3.775, 3.800, 3.815, 3.825, 3.850)


def load_crossed(path: Path):
    rows = []
    with path.open() as f:
        for r in csv.DictReader(f):
            p0 = float(r["p0"])
            if not any(abs(p0 - p) < 1e-4 for p in P0_KEEP):
                continue
            rows.append(
                {
                    "p0": p0,
                    "T": float(r["T"]),
                    "waitingTime": int(float(r["waitingTime"])),
                    "tauAlpha": float(r["tauAlpha"]),
                    "batch": r.get("batch", ""),
                }
            )
    return rows


def rec_row(model: str, n: int, p0: float, T: float, traj: TrajFile | None, extra: dict):
    out = {
        "model": model,
        "n": n,
        "p0": f"{p0:.3f}",
        "T": f"{T:.8g}",
        "tw": "",
        "idx": "",
        "tree": "",
        "size": "",
        "path": "",
        "status": "missing",
        "note": extra.get("note", ""),
        "tauAlpha": extra.get("tauAlpha", ""),
        "batch": extra.get("batch", ""),
    }
    if traj is None:
        return out
    out.update(
        {
            "tw": traj.tw,
            "idx": traj.idx,
            "tree": traj.tree,
            "size": traj.size,
            "path": str(traj.path),
            "status": "ok",
        }
    )
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("-o", type=Path, default=HERE / "inventory.csv")
    ap.add_argument("-n", type=int, default=N_DEFAULT)
    args = ap.parse_args()
    n = args.n
    fields = [
        "model",
        "n",
        "p0",
        "T",
        "tw",
        "idx",
        "tree",
        "size",
        "path",
        "status",
        "note",
        "tauAlpha",
        "batch",
    ]
    rows = []
    print(f"scratch={scratch_root()}", flush=True)
    crossed = load_crossed(CROSSED)
    # One directory listing per p0 (do not re-stat the folder for every T).
    vertex_by_p0 = {}
    for p0 in P0_KEEP:
        root = scratch_root() / f"N{n}" / "vertex" / f"p{p0:.3f}"
        print(f"list vertex {root}", flush=True)
        vertex_by_p0[p0] = [
            c for c in list_glassy_names(root, "vertex") if c.idx == 0
        ]
    seen = set()
    for r in crossed:
        key = (round(r["p0"], 3), round(r["T"], 8))
        if key in seen:
            continue
        seen.add(key)
        p0 = min(P0_KEEP, key=lambda p: abs(p - r["p0"]))
        cands = [c for c in vertex_by_p0[p0] if abs(c.T - r["T"]) < 1e-6]
        traj = _best_stat(cands, prefer_idx=0)
        note = ""
        if traj is not None and abs(traj.tw - r["waitingTime"]) > 1:
            note = f"csv_tw={r['waitingTime']}"
        rows.append(
            rec_row(
                "vertex",
                n,
                r["p0"],
                r["T"],
                traj,
                {"note": note, "tauAlpha": r["tauAlpha"], "batch": r["batch"]},
            )
        )
        if traj is None:
            print(f"MISSING vertex p0={r['p0']:.3f} T={r['T']}", flush=True)
    print("list voronoi production", flush=True)
    for traj in list_voronoi_best(n, P0_KEEP):
        if not any(abs(traj.p0 - p) < 1e-4 for p in P0_KEEP):
            continue
        rows.append(
            rec_row(
                "voronoi",
                traj.n,
                traj.p0,
                traj.T,
                traj,
                {},
            )
        )
    args.o.parent.mkdir(parents=True, exist_ok=True)
    with args.o.open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        for row in rows:
            w.writerow(row)
    nok = sum(1 for r in rows if r["status"] == "ok")
    nmiss = sum(1 for r in rows if r["status"] != "ok")
    print(f"wrote {args.o} ({len(rows)} rows, ok={nok} missing={nmiss})")


if __name__ == "__main__":
    main()
