#!/usr/bin/env python3
"""
Generated by Cursor. 2026-09-02
Mean shape index from longest-tw frames dumps; map vertex <q> onto Voronoi.

Physics:
  q_i = P_i / sqrt(A_i) (same as Simple2DCell::reportq). KA=KP=1, A0=1.
  <q> is the time average of per-frame mean_q after skipping the first 20%
  of records in the longest waiting-time trajectory.
  At overlapping T (Voronoi T inside the vertex T window for >=2 p0),
  invert vertex <q>(p0) at that T to p0^v such that
    <q>_v(p0^v, T) = <q>_V(p0^V, T).
  tau_alpha: CRSISF 1/e (vertex cell centroids, q=6.80) vs Voronoi SISF table.
  Interpolate log tau vs 1/T within each p0 curve, then log tau vs p0.
  Units: mean cell area 1, reduced kT, reduced time.

Usage:
  python3 plot_q_map.py
"""

from __future__ import annotations

import csv
import math
import sys
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

HERE = Path(__file__).resolve().parent
SC = HERE.parent / "vertexModel_stateCompare"
if str(SC) not in sys.path:
    sys.path.insert(0, str(SC))

P0_ORDER = (3.750, 3.775, 3.800, 3.815, 3.825, 3.850)
DUMPDIR = HERE / "dumps"
CROSSED = HERE.parent / "vertexModel_tauAlpha_final" / "vertex_longest_crossed.csv"
VORONOI_TAU = (
    HERE.parent.parent / "TauAlphaTable" / "data_2DVoronoi" / "tauAlpha_2DVoronoi_all.csv"
)


def p0_color(p0: float):
    cmap = plt.cm.coolwarm
    i = min(range(len(P0_ORDER)), key=lambda k: abs(P0_ORDER[k] - p0))
    return cmap(i / max(len(P0_ORDER) - 1, 1))


def load_frames_mean(path: Path):
    with path.open() as f:
        r = csv.DictReader(f)
        cols = {k: [] for k in ("mean_q", "p6", "p5p7", "eP", "mean_P")}
        for row in r:
            for k in cols:
                cols[k].append(float(row[k]))
    if not cols["mean_q"]:
        return None
    out = {k: float(np.mean(v)) for k, v in cols.items()}
    out["n_frames"] = len(cols["mean_q"])
    out["std_mean_q"] = float(np.std(cols["mean_q"], ddof=0))
    return out


def dump_stem_parts(path: Path):
    # vertex_p3.750_T0.1507937_frames.csv
    name = path.name
    if not name.endswith("_frames.csv"):
        return None
    body = name[: -len("_frames.csv")]
    if body.startswith("vertex_"):
        model = "vertex"
        rest = body[len("vertex_") :]
    elif body.startswith("voronoi_"):
        model = "voronoi"
        rest = body[len("voronoi_") :]
    else:
        return None
    if not rest.startswith("p"):
        return None
    try:
        ppart, tpart = rest.split("_T", 1)
        p0 = float(ppart[1:])
        T = float(tpart)
    except ValueError:
        return None
    return model, p0, T


def collect_dumps(dumpdir: Path):
    rows = []
    for p in sorted(dumpdir.glob("*_frames.csv")):
        parts = dump_stem_parts(p)
        if parts is None:
            continue
        model, p0, T = parts
        stats = load_frames_mean(p)
        if stats is None:
            continue
        rec = {"model": model, "p0": p0, "T": T, **stats}
        rec["mean_q_minus_p0"] = rec["mean_q"] - p0
        rows.append(rec)
    return rows


def load_tau_csv(path: Path, p0_key="p0", t_key="T", tau_key="tauAlpha"):
    by = {p: [] for p in P0_ORDER}
    with path.open() as f:
        for r in csv.DictReader(f):
            p0 = float(r[p0_key])
            match = min(P0_ORDER, key=lambda p: abs(p - p0))
            if abs(match - p0) > 1e-4:
                continue
            tau = float(r[tau_key])
            T = float(r[t_key])
            if not (math.isfinite(tau) and tau > 0 and math.isfinite(T) and T > 0):
                continue
            by[match].append((T, tau))
    for p in P0_ORDER:
        by[p].sort(key=lambda z: z[0])
    return by


def interp_xy(x, xs, ys):
    xs = np.asarray(xs, dtype=float)
    ys = np.asarray(ys, dtype=float)
    if xs.size < 2:
        return None
    if x < xs.min() or x > xs.max():
        return None
    return float(np.interp(x, xs, ys))


def interp_logtau_arrhenius(T, curve):
    """log tau vs 1/T; T must lie in the curve's T range."""
    if len(curve) < 2 or T <= 0:
        return None
    Ts = np.array([c[0] for c in curve], dtype=float)
    taus = np.array([c[1] for c in curve], dtype=float)
    if T < Ts.min() or T > Ts.max():
        return None
    x = 1.0 / Ts
    y = np.log(taus)
    order = np.argsort(x)
    val = np.interp(1.0 / T, x[order], y[order])
    return float(math.exp(val))


def write_csv(path: Path, fieldnames, rows):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames)
        w.writeheader()
        for r in rows:
            w.writerow(r)
    print(f"wrote {path} ({len(rows)} rows)")


def group_q(rows, model):
    by = {p: [] for p in P0_ORDER}
    for r in rows:
        if r["model"] != model:
            continue
        p0 = min(P0_ORDER, key=lambda p: abs(p - r["p0"]))
        if abs(p0 - r["p0"]) > 1e-4:
            continue
        by[p0].append(r)
    for p in P0_ORDER:
        by[p].sort(key=lambda z: z["T"])
    return by


def invert_p0_for_q(q_target, p0s, qs):
    p0s = np.asarray(p0s, dtype=float)
    qs = np.asarray(qs, dtype=float)
    if p0s.size < 2:
        return None, "few_p0"
    order = np.argsort(qs)
    qs_s = qs[order]
    p_s = p0s[order]
    if q_target < qs_s[0] or q_target > qs_s[-1]:
        return None, "q_outside_vertex"
    # Require weakly monotone q vs p0 after sorting by p0 for a sanity flag.
    p_ord = np.argsort(p0s)
    dq = np.diff(qs[p_ord])
    how = "interp_q"
    if np.any(dq < 0) and np.any(dq > 0):
        how = "interp_q_nonmonotone"
    p0v = float(np.interp(q_target, qs_s, p_s))
    return p0v, how


def match_overlap(vq, oq, vtau, otau):
    """For each Voronoi (p0,T,<q>), invert vertex p0 at that T if in range."""
    rows = []
    for pV in P0_ORDER:
        for rec in oq[pV]:
            T = rec["T"]
            qV = rec["mean_q"]
            p0s = []
            qs = []
            taus_at_T = []
            for p in P0_ORDER:
                vr = vq[p]
                if len(vr) < 2:
                    continue
                qv = interp_xy(T, [z["T"] for z in vr], [z["mean_q"] for z in vr])
                if qv is None:
                    continue
                p0s.append(p)
                qs.append(qv)
                tv = interp_logtau_arrhenius(T, vtau[p])
                taus_at_T.append(tv)
            p0v, how = invert_p0_for_q(qV, p0s, qs)
            tauV = interp_logtau_arrhenius(T, otau[pV])
            if tauV is None:
                # exact table lookup
                tauV = next(
                    (t for TT, t in otau[pV] if abs(TT - T) < 1e-8),
                    None,
                )
            tau_v = None
            if p0v is not None:
                known = [
                    (p, t)
                    for p, t in zip(p0s, taus_at_T)
                    if t is not None
                ]
                if len(known) >= 2:
                    ps = [k[0] for k in known]
                    lt = [math.log(k[1]) for k in known]
                    order = np.argsort(ps)
                    if min(ps) <= p0v <= max(ps):
                        tau_v = float(
                            math.exp(np.interp(p0v, np.array(ps)[order], np.array(lt)[order]))
                        )
            ratio = ""
            if tau_v is not None and tauV is not None and tauV > 0:
                ratio = tau_v / tauV
            rows.append(
                {
                    "p0_voronoi": pV,
                    "T": T,
                    "mean_q_voronoi": qV,
                    "p0_vertex_match": "" if p0v is None else p0v,
                    "how": how if p0v is not None else (how or "no_overlap"),
                    "n_vertex_p0_at_T": len(p0s),
                    "tau_voronoi": "" if tauV is None else tauV,
                    "tau_vertex_match": "" if tau_v is None else tau_v,
                    "tau_ratio_v_over_V": ratio,
                }
            )
    return rows


def plot_q_vs_T(vq, oq, outpath: Path):
    fig, axes = plt.subplots(1, 2, figsize=(9.2, 4.2))
    ax0, ax1 = axes
    for p0 in P0_ORDER:
        c = p0_color(p0)
        if vq[p0]:
            ax0.plot(
                [r["T"] for r in vq[p0]],
                [r["mean_q"] for r in vq[p0]],
                "o-",
                color=c,
                ms=4,
                label=rf"$p_0={p0:.3f}$",
            )
            ax1.plot(
                [r["T"] for r in vq[p0]],
                [r["mean_q_minus_p0"] for r in vq[p0]],
                "o-",
                color=c,
                ms=4,
            )
        if oq[p0]:
            ax0.plot(
                [r["T"] for r in oq[p0]],
                [r["mean_q"] for r in oq[p0]],
                "s--",
                color=c,
                ms=4,
                mfc="none",
            )
            ax1.plot(
                [r["T"] for r in oq[p0]],
                [r["mean_q_minus_p0"] for r in oq[p0]],
                "s--",
                color=c,
                ms=4,
                mfc="none",
            )
    ax0.set_xscale("log")
    ax1.set_xscale("log")
    ax0.set_xlabel(r"$T$")
    ax1.set_xlabel(r"$T$")
    ax0.set_ylabel(r"$\langle q\rangle$")
    ax1.set_ylabel(r"$\langle q\rangle-p_0$")
    ax0.set_title("filled: vertex; open: Voronoi")
    ax0.legend(fontsize=7, ncol=2)
    fig.tight_layout()
    fig.savefig(outpath, dpi=160)
    plt.close(fig)
    print(f"wrote {outpath}")


def plot_tau_match(match_rows, outpath: Path):
    fig, ax = plt.subplots(figsize=(5.2, 4.2))
    plotted = False
    for p0 in P0_ORDER:
        xs = []
        yV = []
        yv = []
        for r in match_rows:
            if abs(float(r["p0_voronoi"]) - p0) > 1e-9:
                continue
            if r["tau_voronoi"] == "" or r["tau_vertex_match"] == "":
                continue
            xs.append(float(r["T"]))
            yV.append(float(r["tau_voronoi"]))
            yv.append(float(r["tau_vertex_match"]))
        if not xs:
            continue
        c = p0_color(p0)
        ax.loglog(xs, yV, "s", color=c, mfc="none", label=rf"Voronoi $p_0={p0:.3f}$")
        ax.loglog(xs, yv, "o", color=c, label=rf"vertex $p_0(\langle q\rangle)$")
        plotted = True
    ax.set_xlabel(r"$T$")
    ax.set_ylabel(r"$\tau_\alpha$")
    ax.set_title(r"$\tau_\alpha$ at matched $\langle q\rangle$ (overlap $T$ only)")
    if plotted:
        ax.legend(fontsize=6)
    else:
        ax.text(0.5, 0.5, "no overlap $T$ with invertible $p_0$", ha="center", transform=ax.transAxes)
    fig.tight_layout()
    fig.savefig(outpath, dpi=160)
    plt.close(fig)
    print(f"wrote {outpath}")


def main():
    rows = collect_dumps(DUMPDIR)
    if not rows:
        print(f"no dumps in {DUMPDIR}; run dump_q_map.sh first", file=sys.stderr)
        sys.exit(1)
    q_fields = [
        "p0",
        "T",
        "mean_q",
        "std_mean_q",
        "mean_q_minus_p0",
        "mean_P",
        "p6",
        "p5p7",
        "eP",
        "n_frames",
    ]
    vrows = [{k: r[k] for k in q_fields} for r in rows if r["model"] == "vertex"]
    orows = [{k: r[k] for k in q_fields} for r in rows if r["model"] == "voronoi"]
    write_csv(HERE / "vertex_q_vs_T.csv", q_fields, vrows)
    write_csv(HERE / "voronoi_q_vs_T.csv", q_fields, orows)

    vq = group_q(rows, "vertex")
    oq = group_q(rows, "voronoi")
    vtau = load_tau_csv(CROSSED)
    otau = load_tau_csv(VORONOI_TAU)
    match = match_overlap(vq, oq, vtau, otau)
    mfields = [
        "p0_voronoi",
        "T",
        "mean_q_voronoi",
        "p0_vertex_match",
        "how",
        "n_vertex_p0_at_T",
        "tau_voronoi",
        "tau_vertex_match",
        "tau_ratio_v_over_V",
    ]
    write_csv(HERE / "q_match_at_overlap_T.csv", mfields, match)
    plot_q_vs_T(vq, oq, HERE / "q_vs_T_vertex_voronoi.png")
    plot_tau_match(match, HERE / "tau_at_matched_q.png")


if __name__ == "__main__":
    main()
