#!/usr/bin/env python3
"""
Generated by Cursor. 2026-09-07
Match vertex and Voronoi <q> at fixed p0 (different T); compare tau_alpha.

Physics:
  q_i = P_i / sqrt(A_i) (Simple2DCell::reportq). KA=KP=1, A0=1.
  <q> is the time average of per-frame mean_q after skipping the first 20%
  of the longest waiting-time trajectory (existing q-map CSVs).
  At fixed p0, invert vertex <q>(T) so
    <q>_v(p0, T_v) = <q>_V(p0, T_V).
  Matching <q> at the same p0 means vertex colder, Voronoi hotter.
  tau_alpha: vertex CRSISF 1/e (cell centroids, wavevector 6.80) vs Voronoi
  SISF 1/e. Interpolate log tau vs 1/T. Units: mean cell area 1, reduced kT,
  reduced time.

Usage:
  python3 plot_q_match_same_p0.py
"""

from __future__ import annotations

import csv
import math
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

HERE = Path(__file__).resolve().parent
PARENT = HERE.parent
P0_ORDER = (3.750, 3.775, 3.800, 3.815, 3.825, 3.850)
VERTEX_Q = HERE / "vertex_q_vs_T.csv"
VORONOI_Q = HERE / "voronoi_q_vs_T.csv"
CROSSED = PARENT / "vertexModel_tauAlpha_final" / "vertex_longest_crossed.csv"
VORONOI_TAU = PARENT.parent / "TauAlphaTable" / "data_2DVoronoi" / "tauAlpha_2DVoronoi_all.csv"


def p0_color(p0: float):
    cmap = plt.cm.coolwarm
    i = min(range(len(P0_ORDER)), key=lambda k: abs(P0_ORDER[k] - p0))
    return cmap(i / max(len(P0_ORDER) - 1, 1))


def snap_p0(p0: float):
    match = min(P0_ORDER, key=lambda p: abs(p - p0))
    if abs(match - p0) > 1e-4:
        return None
    return match


def load_q_csv(path: Path):
    by = {p: [] for p in P0_ORDER}
    with path.open() as f:
        for r in csv.DictReader(f):
            p0 = snap_p0(float(r["p0"]))
            if p0 is None:
                continue
            by[p0].append(
                {
                    "p0": p0,
                    "T": float(r["T"]),
                    "mean_q": float(r["mean_q"]),
                }
            )
    for p in P0_ORDER:
        by[p].sort(key=lambda z: z["T"])
    return by


def load_tau_csv(path: Path):
    by = {p: [] for p in P0_ORDER}
    with path.open() as f:
        for r in csv.DictReader(f):
            p0 = snap_p0(float(r["p0"]))
            if p0 is None:
                continue
            tau = float(r["tauAlpha"])
            T = float(r["T"])
            if not (math.isfinite(tau) and tau > 0 and math.isfinite(T) and T > 0):
                continue
            by[p0].append((T, tau))
    for p in P0_ORDER:
        by[p].sort(key=lambda z: z[0])
    return by


def interp_logtau_arrhenius(T, curve):
    """log tau vs 1/T; T must lie in the curve's T range."""
    if len(curve) < 2 or T <= 0:
        return None
    Ts = np.array([c[0] for c in curve], dtype=float)
    taus = np.array([c[1] for c in curve], dtype=float)
    if T < Ts.min() or T > Ts.max():
        return None
    x = 1.0 / Ts
    y = np.log(taus)
    order = np.argsort(x)
    val = np.interp(1.0 / T, x[order], y[order])
    return float(math.exp(val))


def lookup_tau(T, curve, rel_tol=1e-6, abs_tol=1e-10):
    for TT, tau in curve:
        if abs(TT - T) <= max(abs_tol, rel_tol * max(abs(T), abs(TT))):
            return tau
    return interp_logtau_arrhenius(T, curve)


def invert_T_for_q(q_target, recs):
    """T such that <q>(T) = q_target; sort on q (weakly increasing with T)."""
    if len(recs) < 2:
        return None, "few_T"
    qs = np.array([r["mean_q"] for r in recs], dtype=float)
    Ts = np.array([r["T"] for r in recs], dtype=float)
    if q_target < qs.min() or q_target > qs.max():
        return None, "q_outside_vertex"
    order = np.argsort(qs)
    Tv = float(np.interp(q_target, qs[order], Ts[order]))
    t_ord = np.argsort(Ts)
    dq = np.diff(qs[t_ord])
    how = "interp_T"
    if np.any(dq < 0) and np.any(dq > 0):
        how = "interp_T_nonmonotone"
    return Tv, how


def write_csv(path: Path, fieldnames, rows):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames)
        w.writeheader()
        for r in rows:
            w.writerow(r)
    print(f"wrote {path} ({len(rows)} rows)")


def measured_tau_q(q_by, tau_by):
    """Join <q>(p0,T) to tau at the same T (table lookup, else Arrhenius)."""
    out = {p: [] for p in P0_ORDER}
    for p0 in P0_ORDER:
        for rec in q_by[p0]:
            tau = lookup_tau(rec["T"], tau_by[p0])
            if tau is None:
                continue
            out[p0].append(
                {
                    "p0": p0,
                    "T": rec["T"],
                    "mean_q": rec["mean_q"],
                    "tauAlpha": tau,
                }
            )
        out[p0].sort(key=lambda z: z["mean_q"])
    return out


def match_same_p0(vq, oq, vtau, otau):
    rows = []
    for p0 in P0_ORDER:
        for rec in oq[p0]:
            T_V = rec["T"]
            qV = rec["mean_q"]
            T_v, how = invert_T_for_q(qV, vq[p0])
            tau_V = lookup_tau(T_V, otau[p0])
            tau_v = None
            if T_v is not None:
                tau_v = interp_logtau_arrhenius(T_v, vtau[p0])
            ratio = ""
            if tau_v is not None and tau_V is not None and tau_V > 0:
                ratio = tau_v / tau_V
            rows.append(
                {
                    "p0": p0,
                    "T_voronoi": T_V,
                    "mean_q": qV,
                    "T_vertex": "" if T_v is None else T_v,
                    "how": how if T_v is not None else (how or "no_match"),
                    "tau_voronoi": "" if tau_V is None else tau_V,
                    "tau_vertex": "" if tau_v is None else tau_v,
                    "tau_ratio_v_over_V": ratio,
                }
            )
    return rows


def plot_tau_vs_q(vmeas, omeas, outpath: Path):
    fig, ax = plt.subplots(figsize=(5.6, 4.4))
    for p0 in P0_ORDER:
        c = p0_color(p0)
        if vmeas[p0]:
            ax.semilogy(
                [r["mean_q"] for r in vmeas[p0]],
                [r["tauAlpha"] for r in vmeas[p0]],
                "o-",
                color=c,
                ms=4,
                label=rf"vertex $p_0={p0:.3f}$",
            )
        if omeas[p0]:
            ax.semilogy(
                [r["mean_q"] for r in omeas[p0]],
                [r["tauAlpha"] for r in omeas[p0]],
                "s--",
                color=c,
                ms=4,
                mfc="none",
                label=rf"Voronoi $p_0={p0:.3f}$",
            )
    ax.set_xlabel(r"$\langle q\rangle$")
    ax.set_ylabel(r"$\tau_\alpha$")
    ax.set_title(r"$\tau_\alpha$ vs $\langle q\rangle$ at the same $p_0$")
    ax.legend(fontsize=6, ncol=2)
    fig.tight_layout()
    fig.savefig(outpath, dpi=160)
    plt.close(fig)
    print(f"wrote {outpath}")


def plot_matched(match_rows, outpath: Path):
    fig, axes = plt.subplots(1, 2, figsize=(9.4, 4.2))
    ax0, ax1 = axes
    plotted = False
    for p0 in P0_ORDER:
        xs = []
        yV = []
        yv = []
        ratios = []
        for r in match_rows:
            if abs(float(r["p0"]) - p0) > 1e-9:
                continue
            if r["tau_voronoi"] == "" or r["tau_vertex"] == "":
                continue
            xs.append(float(r["mean_q"]))
            yV.append(float(r["tau_voronoi"]))
            yv.append(float(r["tau_vertex"]))
            if r["tau_ratio_v_over_V"] != "":
                ratios.append(float(r["tau_ratio_v_over_V"]))
            else:
                ratios.append(float("nan"))
        if not xs:
            continue
        c = p0_color(p0)
        ax0.semilogy(xs, yV, "s", color=c, mfc="none", label=rf"Voronoi $p_0={p0:.3f}$")
        ax0.semilogy(xs, yv, "o", color=c, label=rf"vertex $p_0={p0:.3f}$")
        ax1.semilogy(xs, ratios, "D", color=c, ms=5, label=rf"$p_0={p0:.3f}$")
        plotted = True
    ax0.set_xlabel(r"$\langle q\rangle$")
    ax0.set_ylabel(r"$\tau_\alpha$")
    ax0.set_title(r"matched $\langle q\rangle$ at same $p_0$ (not same $T$)")
    ax1.set_xlabel(r"$\langle q\rangle$")
    ax1.set_ylabel(r"$\tau_\alpha^v/\tau_\alpha^V$")
    ax1.set_title(r"ratio at matched $\langle q\rangle$")
    if plotted:
        ax0.legend(fontsize=6, ncol=2)
        ax1.legend(fontsize=6)
    else:
        ax0.text(
            0.5,
            0.5,
            r"no overlapping $\langle q\rangle$ at same $p_0$",
            ha="center",
            transform=ax0.transAxes,
        )
    fig.tight_layout()
    fig.savefig(outpath, dpi=160)
    plt.close(fig)
    print(f"wrote {outpath}")


def plot_ratio(match_rows, outpath: Path):
    fig, ax = plt.subplots(figsize=(5.2, 4.2))
    plotted = False
    for p0 in P0_ORDER:
        xs = []
        ys = []
        for r in match_rows:
            if abs(float(r["p0"]) - p0) > 1e-9:
                continue
            if r["tau_ratio_v_over_V"] == "":
                continue
            xs.append(float(r["mean_q"]))
            ys.append(float(r["tau_ratio_v_over_V"]))
        if not xs:
            continue
        ax.semilogy(xs, ys, "o-", color=p0_color(p0), ms=5, label=rf"$p_0={p0:.3f}$")
        plotted = True
    ax.set_xlabel(r"$\langle q\rangle$")
    ax.set_ylabel(r"$\tau_\alpha^v/\tau_\alpha^V$")
    ax.set_title(r"same $p_0$, matched $\langle q\rangle$")
    if plotted:
        ax.legend(fontsize=7)
    fig.tight_layout()
    fig.savefig(outpath, dpi=160)
    plt.close(fig)
    print(f"wrote {outpath}")


def main():
    if not VERTEX_Q.is_file() or not VORONOI_Q.is_file():
        raise SystemExit(f"missing {VERTEX_Q} or {VORONOI_Q}; run plot_q_map.py first")
    vq = load_q_csv(VERTEX_Q)
    oq = load_q_csv(VORONOI_Q)
    vtau = load_tau_csv(CROSSED)
    otau = load_tau_csv(VORONOI_TAU)
    vmeas = measured_tau_q(vq, vtau)
    omeas = measured_tau_q(oq, otau)
    match = match_same_p0(vq, oq, vtau, otau)
    mfields = [
        "p0",
        "T_voronoi",
        "mean_q",
        "T_vertex",
        "how",
        "tau_voronoi",
        "tau_vertex",
        "tau_ratio_v_over_V",
    ]
    write_csv(HERE / "q_match_at_same_p0.csv", mfields, match)
    n_ok = sum(1 for r in match if r["tau_ratio_v_over_V"] != "")
    ratios = [float(r["tau_ratio_v_over_V"]) for r in match if r["tau_ratio_v_over_V"] != ""]
    print(f"matched pairs with both tau: {n_ok}")
    if ratios:
        print(
            "ratio min/median/max: "
            f"{min(ratios):.4g} {float(np.median(ratios)):.4g} {max(ratios):.4g}"
        )
    plot_tau_vs_q(vmeas, omeas, HERE / "tau_vs_q_same_p0.png")
    plot_matched(match, HERE / "tau_at_matched_q_same_p0.png")
    plot_ratio(match, HERE / "tau_ratio_same_p0.png")


if __name__ == "__main__":
    main()
