#!/usr/bin/env python3
"""
Generated by Cursor. 2026-09-08
Vertex vs Voronoi static PDFs at each p0, all T (no state-point matching).

Physics (mean cell area 1, KA=KP=1):
  E/N = <(A-1)^2> + <(P-p0)^2>
  Standardized per (model, p0, T) over cells pooled from the last 8
  log-spaced frames:
    hat x = (x - <x>) / sigma_x
  Overlay N(0,1) on P(hat A) and P(hat P).
  Edge lengths ell stay raw (vertex T1 wall at 0.01; hexagon side ~0.620).

Usage:
  python3 plot_stat_dist.py
  python3 plot_stat_dist.py --dump-only --p0 3.800
  python3 plot_stat_dist.py --plot-only
"""

from __future__ import annotations

import argparse
import csv
import math
import os
import subprocess
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
QMAP = HERE.parent / "vertexModel_qMap"
INVENTORY = QMAP / "inventory.csv"
P0_ORDER = (3.750, 3.775, 3.800, 3.815, 3.825, 3.850)
N_KEEP = 8
ELL_T1 = 0.01
HEX_SIDE = 3.0 ** (-0.75) * math.sqrt(2.0)


def repo_root() -> Path:
    env = os.environ.get("CELLGPU_ROOT")
    if env:
        return Path(env)
    return HERE.parents[3]


def dump_env() -> dict:
    env = os.environ.copy()
    extras = []
    nv = os.environ.get("NVHPC_ROOT", "/opt/nvidia/hpc_sdk/Linux_x86_64/26.5")
    extras.append(str(Path(nv) / "compilers" / "lib"))
    extras.append(str(Path(nv) / "cuda" / "12.9" / "lib64"))
    home = Path.home() / "opt" / "netcdf-cxx-legacy" / "lib"
    if home.is_dir():
        extras.append(str(home))
    old = env.get("LD_LIBRARY_PATH", "")
    env["LD_LIBRARY_PATH"] = ":".join(extras + ([old] if old else []))
    return env


def dump_binary() -> Path:
    root = repo_root()
    cand = [
        root / "glassyDynamicsProject" / "stateCompareDump.out",
        root / "build-state-compare" / "glassyDynamicsProject" / "stateCompareDump.out",
        root / "build-state-compare" / "stateCompareDump.out",
    ]
    for p in cand:
        if p.is_file():
            return p
    return cand[0]


def load_inventory(path: Path = INVENTORY):
    rows = []
    with path.open() as f:
        for r in csv.DictReader(f):
            if r.get("status") != "ok":
                continue
            nc = Path(r["path"])
            rows.append(
                {
                    "model": r["model"],
                    "n": int(r["n"]),
                    "p0": float(r["p0"]),
                    "T": float(r["T"]),
                    "tw": int(float(r["tw"])) if r.get("tw") else 0,
                    "idx": int(r["idx"]),
                    "tree": r.get("tree", ""),
                    "path": nc,
                }
            )
    return rows


def dump_stem(model: str, p0: float, T: float) -> str:
    return f"{model}_p{p0:.3f}_T{T:.8f}"


def run_dump(model: str, nc: Path, prefix: Path, n: int, p0: float, nkeep: int) -> None:
    exe = dump_binary()
    if not exe.is_file():
        raise FileNotFoundError(f"missing {exe}; build stateCompareDump.out first")
    prefix.parent.mkdir(parents=True, exist_ok=True)
    cmd = [
        str(exe),
        "-m",
        model,
        "-f",
        str(nc),
        "-o",
        str(prefix),
        "-n",
        str(n),
        "-p",
        f"{p0:.8g}",
        "-k",
        "all",
        "-d",
        str(nkeep),
    ]
    print(" ".join(cmd), flush=True)
    subprocess.check_call(cmd, env=dump_env())


def load_col(path: Path, name: str):
    with path.open() as f:
        r = csv.DictReader(f)
        return np.array([float(row[name]) for row in r], dtype=float)


def skew_kurt(x: np.ndarray):
    x = x[np.isfinite(x)]
    n = x.size
    if n < 4:
        return math.nan, math.nan
    m = float(np.mean(x))
    s = float(np.std(x, ddof=0))
    if s <= 0:
        return 0.0, 0.0
    z = (x - m) / s
    g1 = float(np.mean(z**3))
    g2 = float(np.mean(z**4) - 3.0)
    return g1, g2


def dump_all(rows, outdir: Path, p0_filter: float | None, nkeep: int) -> list:
    dumps = outdir / "dumps"
    jobs = []
    for row in rows:
        if p0_filter is not None and abs(row["p0"] - p0_filter) > 1e-4:
            continue
        if not row["path"].is_file():
            print(f"MISSING {row['model']} p0={row['p0']} T={row['T']} {row['path']}")
            continue
        pref = dumps / dump_stem(row["model"], row["p0"], row["T"])
        cells = Path(str(pref) + "_cells.csv")
        if cells.is_file():
            print(f"skip existing {cells.name}")
            jobs.append(row)
            continue
        try:
            run_dump(row["model"], row["path"], pref, row["n"], row["p0"], nkeep)
            jobs.append(row)
        except subprocess.CalledProcessError as exc:
            print(f"dump failed {row['model']} p0={row['p0']} T={row['T']}: {exc}")
    return jobs


def collect_state(outdir: Path, row: dict):
    pref = outdir / "dumps" / dump_stem(row["model"], row["p0"], row["T"])
    cells = Path(str(pref) + "_cells.csv")
    edges = Path(str(pref) + "_edges.csv")
    if not cells.is_file() or not edges.is_file():
        return None
    A = load_col(cells, "A")
    P = load_col(cells, "P")
    ell = load_col(edges, "ell")
    rec = load_col(cells, "rec")
    n_frames = int(np.unique(rec).size) if rec.size else 0
    g1A, g2A = skew_kurt(A)
    g1P, g2P = skew_kurt(P)
    return {
        "model": row["model"],
        "p0": row["p0"],
        "T": row["T"],
        "A": A,
        "P": P,
        "ell": ell,
        "mean_A": float(np.mean(A)),
        "std_A": float(np.std(A, ddof=0)),
        "mean_P": float(np.mean(P)),
        "std_P": float(np.std(P, ddof=0)),
        "skew_A": g1A,
        "kurt_A": g2A,
        "skew_P": g1P,
        "kurt_P": g2P,
        "median_ell": float(np.median(ell)) if ell.size else math.nan,
        "f_ell_lt_T1": float(np.mean(ell < ELL_T1)) if ell.size else math.nan,
        "n_cells": int(A.size),
        "n_ell": int(ell.size),
        "n_frames": n_frames,
    }


def standardize(x: np.ndarray):
    m = float(np.mean(x))
    s = float(np.std(x, ddof=0))
    if s <= 0:
        return np.zeros_like(x)
    return (x - m) / s


def norm_pdf(x):
    return np.exp(-0.5 * x * x) / math.sqrt(2.0 * math.pi)


def plot_p0(states, p0: float, outpath: Path):
    import matplotlib.pyplot as plt
    from matplotlib.cm import ScalarMappable
    from matplotlib.colors import LogNorm

    pts = [s for s in states if abs(s["p0"] - p0) < 1e-4]
    if not pts:
        print(f"no dumps for p0={p0}")
        return
    Ts = [s["T"] for s in pts]
    tmin, tmax = min(Ts), max(Ts)
    if tmax <= tmin:
        tmax = tmin * 1.01
    cmap = plt.get_cmap("coolwarm")
    norm = LogNorm(vmin=tmin, vmax=tmax)

    fig, axes = plt.subplots(1, 3, figsize=(12.6, 4.2))
    axA, axP, axL = axes
    xg = np.linspace(-4.5, 4.5, 400)
    yg = norm_pdf(xg)
    axA.plot(xg, yg, color="k", lw=1.4, zorder=5, label=r"$\mathcal{N}(0,1)$")
    axP.plot(xg, yg, color="k", lw=1.4, zorder=5, label=r"$\mathcal{N}(0,1)$")
    axL.axvline(ELL_T1, color="k", ls=":", lw=1.1, label=rf"$\ell_{{T1}}={ELL_T1}$")
    axL.axvline(HEX_SIDE, color="0.4", ls="--", lw=0.9, label=r"$s_{\mathrm{hex}}$")

    bins_z = np.linspace(-4.5, 4.5, 49)
    ell_pos = np.concatenate([s["ell"] for s in pts if s["ell"].size])
    ell_pos = ell_pos[ell_pos > 0]
    if ell_pos.size:
        lmin = max(1e-4, float(np.percentile(ell_pos, 0.5)))
        lmax = float(np.percentile(ell_pos, 99.5))
        lbins = np.logspace(np.log10(lmin), np.log10(max(lmax, lmin * 1.1)), 50)
    else:
        lbins = np.logspace(-3, 0.3, 50)

    for s in sorted(pts, key=lambda z: -z["T"]):
        c = cmap(norm(s["T"]))
        ls = "-" if s["model"] == "vertex" else "--"
        Ah = standardize(s["A"])
        Ph = standardize(s["P"])
        axA.hist(Ah, bins=bins_z, density=True, histtype="step", color=c, ls=ls, lw=1.1)
        axP.hist(Ph, bins=bins_z, density=True, histtype="step", color=c, ls=ls, lw=1.1)
        ell = s["ell"]
        ell = ell[ell > 0]
        if ell.size:
            axL.hist(ell, bins=lbins, density=True, histtype="step", color=c, ls=ls, lw=1.1)

    axA.plot([], [], color="0.3", ls="-", label="vertex")
    axA.plot([], [], color="0.3", ls="--", label="Voronoi")
    axA.set_xlabel(r"$\hat A=(A-\langle A\rangle)/\sigma_A$")
    axA.set_ylabel(r"$P(\hat A)$")
    axA.set_xlim(-4.5, 4.5)
    axA.legend(fontsize=7, loc="upper right")
    axP.set_xlabel(r"$\hat P=(P-\langle P\rangle)/\sigma_P$")
    axP.set_ylabel(r"$P(\hat P)$")
    axP.set_xlim(-4.5, 4.5)
    axL.set_xlabel(r"$\ell$")
    axL.set_ylabel(r"$P(\ell)$")
    axL.set_xscale("log")
    axL.legend(fontsize=7, loc="upper right")
    sm = ScalarMappable(norm=norm, cmap=cmap)
    sm.set_array([])
    cbar = fig.colorbar(sm, ax=axes, fraction=0.03, pad=0.02)
    cbar.set_label(r"$T$ (hot red, cold blue)")
    fig.suptitle(rf"$p_0={p0:.3f}$, $N=4096$, last {N_KEEP} log-spaced frames")
    fig.savefig(outpath, dpi=160, bbox_inches="tight")
    plt.close(fig)
    print(f"wrote {outpath}")


def write_moments(states, path: Path):
    keys = [
        "model",
        "p0",
        "T",
        "mean_A",
        "std_A",
        "skew_A",
        "kurt_A",
        "mean_P",
        "std_P",
        "skew_P",
        "kurt_P",
        "median_ell",
        "f_ell_lt_T1",
        "n_cells",
        "n_ell",
        "n_frames",
    ]
    with path.open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=keys)
        w.writeheader()
        for s in sorted(states, key=lambda z: (z["p0"], z["model"], -z["T"])):
            w.writerow({k: s[k] for k in keys})
    print(f"wrote {path}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--inventory", type=Path, default=INVENTORY)
    ap.add_argument("--p0", type=float, default=None)
    ap.add_argument("--dump-only", action="store_true")
    ap.add_argument("--plot-only", action="store_true")
    ap.add_argument("--nkeep", type=int, default=N_KEEP)
    ap.add_argument("--smoke", action="store_true", help="dump one vertex and one Voronoi at p0=3.800")
    args = ap.parse_args()
    outdir = HERE
    rows = load_inventory(args.inventory)
    print(f"inventory {args.inventory} n_ok={len(rows)} exe={dump_binary()}")

    if args.smoke:
        v = next(r for r in rows if r["model"] == "vertex" and abs(r["p0"] - 3.8) < 1e-4)
        o = next(r for r in rows if r["model"] == "voronoi" and abs(r["p0"] - 3.8) < 1e-4)
        rows = [v, o]
        print(f"smoke vertex T={v['T']} voronoi T={o['T']}")

    if not args.plot_only:
        dump_all(rows, outdir, args.p0, args.nkeep)

    if args.dump_only:
        return

    states = []
    for row in rows:
        if args.p0 is not None and abs(row["p0"] - args.p0) > 1e-4:
            continue
        s = collect_state(outdir, row)
        if s is None:
            print(f"skip plot {row['model']} p0={row['p0']} T={row['T']}: no dump")
            continue
        states.append(s)
    if not states:
        print("no states to plot")
        return
    write_moments(states, outdir / "moments.csv")
    p0s = sorted({round(s["p0"], 3) for s in states})
    for p0 in p0s:
        plot_p0(states, p0, outdir / f"stat_dist_p{p0:.3f}.png")


if __name__ == "__main__":
    sys.exit(main() or 0)
