#include "std_include.h"
#include "cuda_runtime.h"
#include "Simulation.h"
#include "vertexQuadraticEnergy.h"
#include "NoseHooverChainNVT.h"
#include "nvtAVMRestartDatabase.h"
#include <filesystem>

// Generated by Cursor. 2026-08-21
// High-T (T=0.1) monodisperse vertex-model fluids for later NVT tau_alpha runs.
// Writes nvtAVMRestartDatabase (vertices, topology, velocities, NH bath) on scratch.

int main(int argc, char*argv[])
{
    int numpts = 200;
    int USE_GPU = -1;
    int tSteps = 200000;
    int initSteps = 100000;
    double dt = 0.01;
    double p0 = 3.8;
    double a0 = 1.0;
    double T = 0.1;
    int Nchain = 4;
    int Nsave = 10000;
    int c;
    while((c=getopt(argc,argv,"n:g:m:s:r:a:i:v:b:x:y:z:p:t:e:")) != -1)
        switch(c)
        {
            case 'n': numpts = atoi(optarg); break;
            case 't': tSteps = atoi(optarg); break;
            case 'g': USE_GPU = atoi(optarg); break;
            case 'i': initSteps = atoi(optarg); break;
            case 'e': dt = atof(optarg); break;
            case 'p': p0 = atof(optarg); break;
            case 'a': a0 = atof(optarg); break;
            case 'v': T = atof(optarg); break;
            case '?':
                    return 1;
            default:
                       abort();
        };

    bool reproducible = true;
    bool initializeGPU = true;
    bool gpu = chooseGPU(USE_GPU);
    if (!gpu)
        initializeGPU = false;

    const char *scratchEnv = getenv("CELLGPU_SCRATCH");
    string scratch = scratchEnv ? scratchEnv : "/scratch/bbtm/cli6/glassyDynamics/data";
    char dirbuf[512];
    sprintf(dirbuf,"%s/N%i/vertex/fluidConfigurations",scratch.c_str(),numpts);
    std::filesystem::create_directories(dirbuf);
    cout << "initializing " << numpts << " vertex-model cells at T = " << T << endl;
    // Random Delaunay vertex mesh (same as vertexSigmaXY). Inner SPV relax in
    // setCellsVoronoiTesselation defaults to GPU Voronoi and aborts on CPU login nodes.
    shared_ptr<VertexQuadraticEnergy> avm = make_shared<VertexQuadraticEnergy>(numpts,a0,p0,reproducible,false,initializeGPU);
    if (!initializeGPU)
        avm->setCPU();
    avm->setCellPreferencesUniform(a0,p0);
    avm->setVertexVelocitiesMaxwellBoltzmann(T);
    int Nvert = avm->Nvertices;
    shared_ptr<NoseHooverChainNVT> nvt = make_shared<NoseHooverChainNVT>(Nvert,Nchain,initializeGPU);
    nvt->setT(T);

    char dataname[512];
    sprintf(dataname,"%s/vertexMonodisperseFluidConfigurations_N%i_TEq%.8f_p%.5f.nc",dirbuf,numpts,T,p0);
    cout << "writing fluids to " << dataname << endl;
    nvtAVMRestartDatabase ncdat(Nvert,Nchain,dataname,NcFile::Replace);

    SimulationPtr sim = make_shared<Simulation>();
    sim->setConfiguration(avm);
    sim->addUpdater(nvt,avm);
    sim->setIntegrationTimestep(dt);
    sim->setCPUOperation(!initializeGPU);
    if (!gpu)
        sim->setOmpThreads(abs(USE_GPU));
    sim->setReproducible(reproducible);

    printf("starting initialization\n");
    for(long long int ii = 0; ii < initSteps; ++ii)
        sim->performTimestep();
    avm->enforceTopology();
    avm->computeForces();
    printf("Finished with initialization, mean q = %f\n", avm->reportq());

    for(long long int ii = 0; ii < tSteps; ++ii)
        {
        if (ii%Nsave==0)
            {
            avm->enforceTopology();
            avm->computeForces();
            ncdat.writeState(avm,nvt);
            }
        sim->performTimestep();
        };

    if(initializeGPU)
        cudaDeviceReset();
    return 0;
};
