#include "std_include.h"
#include "cuda_runtime.h"
#include "Simulation.h"
#include "vertexQuadraticEnergy.h"
#include "NoseHooverChainNVT.h"
#include "nvtAVMRestartDatabase.h"
#include "vertexTrajectoryDatabase.h"
#include "twoValuesDatabase.h"
#include "logEquilibrationStateWriter.h"
#include "autocorrelator.h"
#include "profiler.h"
#include <filesystem>

// Generated by Cursor. 2026-08-21
// Vertex-model tau_alpha scouting: load high-T fluid, equilibrate tau_block=max(tau_alpha,1000),
// then 15 log-spaced vertex trajectories. SAC (acdat) starts after 10 tau_block of production.
// sigma_xy every 100 dt from the start of production.
// Before sigma/trajectory writes: enforceTopology + computeForces (NH half-step delay).

int main(int argc, char*argv[])
{
    int numpts = 200;
    int USE_GPU = -1;
    double tauEstimate = 10;
    double dt = 0.01;
    double T = 0.01;
    double T0 = 0.1;
    double p0 = 3.8;
    int recordIndex = 0;
    int Nchain = 4;
    double statesSavedPerDecadeOfTime = 20.;
    int c;
    while((c=getopt(argc,argv,"n:g:m:s:r:a:i:v:l:p:t:e:w:")) != -1)
        switch(c)
        {
            case 'n': numpts = atoi(optarg); break;
            case 'g': USE_GPU = atoi(optarg); break;
            case 't': tauEstimate = atof(optarg); break;
            case 'e': dt = atof(optarg); break;
            case 'v': T = atof(optarg); break;
            case 'l': T0 = atof(optarg); break;
            case 'p': p0 = atof(optarg); break;
            case 's': statesSavedPerDecadeOfTime = atof(optarg); break;
            case 'r': recordIndex = atoi(optarg); break;
            case '?':
                    return 1;
            default:
                       abort();
        };

    bool reproducible = true;
    bool initializeGPU = true;
    bool gpu = chooseGPU(USE_GPU);
    if (!gpu)
        initializeGPU = false;

    const char *scratchEnv = getenv("CELLGPU_SCRATCH");
    string scratch = scratchEnv ? scratchEnv : "/scratch/bbtm/cli6/glassyDynamics/data";

    char loadDatabaseName[512];
    sprintf(loadDatabaseName,"%s/N%i/vertex/fluidConfigurations/vertexMonodisperseFluidConfigurations_N%i_TEq%.8f_p%.5f.nc",
            scratch.c_str(),numpts,numpts,T0,p0);
    cout << "reading record " << recordIndex << " from " << loadDatabaseName << endl;
    int Nvert = 2*numpts;
    nvtAVMRestartDatabase fluidConfigurations(Nvert,Nchain,loadDatabaseName,NcFile::ReadOnly);

    double tauBlock = max(1000.0, tauEstimate);
    long long int equilibrationTimesteps = (long long int)floor(tauBlock / dt);
    long long int runTimesteps = 15 * equilibrationTimesteps;
    long long int sigmaStride = 100;
    cout << "Voronoi tauAlpha estimate = " << tauEstimate << ", tau_block = " << tauBlock << endl;
    cout << "equilibration timesteps = " << equilibrationTimesteps << ", production timesteps = " << runTimesteps << endl;

    char saveDirName[512];
    sprintf(saveDirName, "%s/N%i/vertex/p%.3f/",scratch.c_str(),numpts,p0);
    std::filesystem::create_directories(saveDirName);

    logEquilibrationStateWriter lewriter((1.0/statesSavedPerDecadeOfTime));
    char dataname[512];
    for (int k = 0; k < 15; ++k)
        {
        long long int offset = k * equilibrationTimesteps;
        sprintf(dataname,"%sglassyDynamics_N%i_p%.4f_T%.8f_waitingTime%.0f_idx%i.nc",
                saveDirName,numpts,p0,T,offset*dt,recordIndex);
        shared_ptr<vertexTrajectoryDatabase> trajdat=make_shared<vertexTrajectoryDatabase>(Nvert,dataname,NcFile::Replace);
        lewriter.addDatabase(trajdat,(int)offset);
        }
    lewriter.identifyNextFrame();

    char SACname[512];
    char SACname10[512];
    sprintf(SACname,"%sSACtime_N%i_p%.4f_T%.8f_waitingTime%.0f_idx%i.nc",saveDirName,numpts,p0,T,tauBlock,recordIndex);
    sprintf(SACname10,"%sSACtimeAfter10_N%i_p%.4f_T%.8f_waitingTime%.0f_idx%i.nc",saveDirName,numpts,p0,T,tauBlock,recordIndex);
    shared_ptr<twoValuesDatabase> SACtime=make_shared<twoValuesDatabase>(SACname,NcFile::Replace);
    shared_ptr<twoValuesDatabase> SACtime10=make_shared<twoValuesDatabase>(SACname10,NcFile::Replace);
    shared_ptr<autocorrelator> acdat = make_shared<autocorrelator>(16,2,dt);

    char sigmaName[512];
    sprintf(sigmaName,"%ssigmaXY_N%i_p%.4f_T%.8f_idx%i.nc",saveDirName,numpts,p0,T,recordIndex);
    shared_ptr<twoValuesDatabase> sigmadat=make_shared<twoValuesDatabase>(sigmaName,NcFile::Replace);

    cout << "Data are saved in " << saveDirName << endl;

    shared_ptr<VertexQuadraticEnergy> avm = make_shared<VertexQuadraticEnergy>(numpts,1.0,p0,reproducible,false,initializeGPU);
    if (!initializeGPU)
        avm->setCPU();
    avm->setCellPreferencesUniform(1.0,p0);
    Nvert = avm->Nvertices;
    shared_ptr<NoseHooverChainNVT> nvt = make_shared<NoseHooverChainNVT>(Nvert,Nchain,initializeGPU);

    if(recordIndex < fluidConfigurations.GetNumRecs())
        {
        // Load vertices/vel/topology; do not restore T=0.1 bath into the target-T run.
        fluidConfigurations.readState(avm,nvt,recordIndex,true,false);
        double qLoad = avm->reportq();
        printf("after restart load, q = %f\n", qLoad);
        if (!isfinite(qLoad))
            {
            printf("restart load produced non-finite q; aborting\n");
            return 1;
            }
        }
    else
        {
        cout << "You have tried to load a frame from a database which doesn't exist" << endl;
        return 0;
        }
    nvt->setT(T);

    SimulationPtr sim = make_shared<Simulation>();
    sim->setConfiguration(avm);
    sim->addUpdater(nvt,avm);
    sim->setIntegrationTimestep(dt);
    sim->setCurrentTime(0.0);
    sim->setCPUOperation(!initializeGPU);
    if (!gpu)
        sim->setOmpThreads(abs(USE_GPU));
    sim->setReproducible(reproducible);

    printf("starting equilibration run\n");
    for(long long int ii = 0; ii < equilibrationTimesteps; ++ii)
        sim->performTimestep();
    avm->enforceTopology();
    avm->computeForces();
    printf("Finished with initialization, current q = %f\n", avm->reportq());

    // SAC samples start after 10 completed production blocks of length tau_block.
    long long int sacStart = 10 * equilibrationTimesteps;
    profiler simulationrunProfiler("simulationrun");

    printf("starting glassy dynamics run\n");
    for(long long int ii = 0; ii < runTimesteps+2; ++ii)
        {
        simulationrunProfiler.start();
        avm->enforceTopology();
        avm->computeForces();
        double sigma = avm->getSigmaXY();
        if (ii >= sacStart)
            acdat->add(sigma,0);
        if (ii % sigmaStride == 0)
            sigmadat->writeValues(ii*dt, sigma);
        if (ii == lewriter.nextFrameToSave)
            lewriter.writeState(avm,ii);
        sim->performTimestep();
        simulationrunProfiler.end();
        };

    acdat->evaluate(false);
    for(int j = 0; j < acdat->correlator.size(); ++j)
        {
        SACtime->writeValues(acdat->correlator[j].y,acdat->correlator[j].x);
        SACtime10->writeValues(acdat->correlator[j].y,acdat->correlator[j].x);
        }
    simulationrunProfiler.print();

    if(initializeGPU)
        cudaDeviceReset();
    return 0;
};
