#include "std_include.h"
#include "cuda_runtime.h"
#include "Simulation.h"
#include "vertexQuadraticEnergy.h"
#include "NoseHooverChainNVT.h"
#include "nvtAVMRestartDatabase.h"
#include "vertexTrajectoryDatabase.h"
#include "twoValuesDatabase.h"
#include "logEquilibrationStateWriter.h"
#include "autocorrelator.h"
#include "profiler.h"
#include <filesystem>
#include <cmath>

// Generated by Cursor. 2026-08-21
// Vertex-model tau_alpha scouting: load high-T fluid, equilibrate tau_block=max(tau_alpha,1000),
// then 15 log-spaced vertex trajectories. SAC (acdat) starts after 10 tau_block of production.
// sigma_xy every 100 dt from the start of production.
// Before sigma/trajectory writes: enforceTopology + computeForces (NH half-step delay).
// Optional -a l_T1: T1 fires when edge length < l_T1 (default 0.01, mean cell area 1).
// When -a is set, write under t1Scan/t1_<tag>/ so the default-threshold p0 folder is untouched.
// Optional -c (Wave A compact): tau_block=max(tau_est,1000). Equilibrate 10*tau_block
// with no trajectory I/O, then record one log-spaced trajectory for 5*tau_block
// (waitingTime = 10*tau_block). Default remains 1*tau_block eq + 15 trajectories.

// Folder tag for l_T1: exact decade 10^n -> 1e-4 (old scratch dirs);
// otherwise %g so 0.02 and 0.03 do not both become 1e-2.
static void formatT1Tag(double t1t, char *out, int n)
    {
    double lg = log10(t1t);
    int e = (int)lround(lg);
    if (fabs(lg - (double)e) < 1e-8)
        snprintf(out, n, "1e%d", e);
    else
        snprintf(out, n, "%g", t1t);
    }

int main(int argc, char*argv[])
{
    int numpts = 200;
    int USE_GPU = -1;
    double tauEstimate = 10;
    double dt = 0.01;
    double T = 0.01;
    double T0 = 0.1;
    double p0 = 3.8;
    double t1t = -1.0;
    bool compactSave = false;
    int recordIndex = 0;
    int Nchain = 4;
    double statesSavedPerDecadeOfTime = 20.;
    int c;
    while((c=getopt(argc,argv,"n:g:m:s:r:a:i:v:l:p:t:e:w:c")) != -1)
        switch(c)
        {
            case 'n': numpts = atoi(optarg); break;
            case 'g': USE_GPU = atoi(optarg); break;
            case 't': tauEstimate = atof(optarg); break;
            case 'e': dt = atof(optarg); break;
            case 'v': T = atof(optarg); break;
            case 'l': T0 = atof(optarg); break;
            case 'p': p0 = atof(optarg); break;
            case 'a': t1t = atof(optarg); break;
            case 's': statesSavedPerDecadeOfTime = atof(optarg); break;
            case 'r': recordIndex = atoi(optarg); break;
            case 'c': compactSave = true; break;
            case '?':
                    return 1;
            default:
                       abort();
        };

    bool reproducible = true;
    bool initializeGPU = true;
    bool gpu = chooseGPU(USE_GPU);
    if (!gpu)
        initializeGPU = false;

    const char *scratchEnv = getenv("CELLGPU_SCRATCH");
    string scratch = scratchEnv ? scratchEnv : "/scratch/bbtm/cli6/glassyDynamics/data";

    char loadDatabaseName[512];
    sprintf(loadDatabaseName,"%s/N%i/vertex/fluidConfigurations/vertexMonodisperseFluidConfigurations_N%i_TEq%.8f_p%.5f.nc",
            scratch.c_str(),numpts,numpts,T0,p0);
    cout << "reading record " << recordIndex << " from " << loadDatabaseName << endl;
    int Nvert = 2*numpts;
    nvtAVMRestartDatabase fluidConfigurations(Nvert,Nchain,loadDatabaseName,NcFile::ReadOnly);

    double tauBlock = max(1000.0, tauEstimate);
    int nEqBlocks = compactSave ? 10 : 1;
    int nProdBlocks = compactSave ? 5 : 15;
    long long int stepsPerBlock = (long long int)floor(tauBlock / dt);
    long long int equilibrationTimesteps = nEqBlocks * stepsPerBlock;
    long long int runTimesteps = nProdBlocks * stepsPerBlock;
    long long int sigmaStride = 100;
    cout << "Voronoi tauAlpha estimate = " << tauEstimate << ", tau_block = " << tauBlock
         << (compactSave ? " compact -c: eq 10*tau_block, record 5*tau_block" : "") << endl;
    cout << "equilibration timesteps = " << equilibrationTimesteps << ", production timesteps = " << runTimesteps << endl;

    bool t1Scan = (t1t > 0.0);
    if (!t1Scan)
        t1t = 0.01;
    char t1tag[32];
    formatT1Tag(t1t, t1tag, 32);
    cout << "T1Threshold l_T1 = " << t1t << " tag=" << t1tag << (t1Scan ? " (t1Scan)" : " (default path)") << endl;

    char saveDirName[512];
    if (t1Scan)
        sprintf(saveDirName, "%s/N%i/vertex/t1Scan/t1_%s/p%.3f/",scratch.c_str(),numpts,t1tag,p0);
    else
        sprintf(saveDirName, "%s/N%i/vertex/p%.3f/",scratch.c_str(),numpts,p0);
    std::filesystem::create_directories(saveDirName);

    logEquilibrationStateWriter lewriter((1.0/statesSavedPerDecadeOfTime));
    char dataname[512];
    if (compactSave)
        {
        // Production frame 0 is already after 10*tau_block of equilibration.
        double tw = nEqBlocks * tauBlock;
        sprintf(dataname,"%sglassyDynamics_N%i_p%.4f_T%.8f_waitingTime%.0f_idx%i.nc",
                saveDirName,numpts,p0,T,tw,recordIndex);
        shared_ptr<vertexTrajectoryDatabase> trajdat=make_shared<vertexTrajectoryDatabase>(Nvert,dataname,NcFile::Replace);
        lewriter.addDatabase(trajdat,0);
        }
    else
        {
        for (int k = 0; k < nProdBlocks; ++k)
            {
            long long int offset = k * stepsPerBlock;
            sprintf(dataname,"%sglassyDynamics_N%i_p%.4f_T%.8f_waitingTime%.0f_idx%i.nc",
                    saveDirName,numpts,p0,T,offset*dt,recordIndex);
            shared_ptr<vertexTrajectoryDatabase> trajdat=make_shared<vertexTrajectoryDatabase>(Nvert,dataname,NcFile::Replace);
            lewriter.addDatabase(trajdat,(int)offset);
            }
        }
    lewriter.identifyNextFrame();

    char SACname[512];
    char SACname10[512];
    sprintf(SACname,"%sSACtime_N%i_p%.4f_T%.8f_waitingTime%.0f_idx%i.nc",saveDirName,numpts,p0,T,
            compactSave ? nEqBlocks * tauBlock : tauBlock,recordIndex);
    sprintf(SACname10,"%sSACtimeAfter10_N%i_p%.4f_T%.8f_waitingTime%.0f_idx%i.nc",saveDirName,numpts,p0,T,
            compactSave ? nEqBlocks * tauBlock : tauBlock,recordIndex);
    shared_ptr<twoValuesDatabase> SACtime=make_shared<twoValuesDatabase>(SACname,NcFile::Replace);
    shared_ptr<twoValuesDatabase> SACtime10=make_shared<twoValuesDatabase>(SACname10,NcFile::Replace);
    shared_ptr<autocorrelator> acdat = make_shared<autocorrelator>(16,2,dt);

    char sigmaName[512];
    sprintf(sigmaName,"%ssigmaXY_N%i_p%.4f_T%.8f_idx%i.nc",saveDirName,numpts,p0,T,recordIndex);
    shared_ptr<twoValuesDatabase> sigmadat=make_shared<twoValuesDatabase>(sigmaName,NcFile::Replace);

    cout << "Data are saved in " << saveDirName << endl;

    shared_ptr<VertexQuadraticEnergy> avm = make_shared<VertexQuadraticEnergy>(numpts,1.0,p0,reproducible,false,initializeGPU);
    if (!initializeGPU)
        avm->setCPU();
    avm->setCellPreferencesUniform(1.0,p0);
    Nvert = avm->Nvertices;
    shared_ptr<NoseHooverChainNVT> nvt = make_shared<NoseHooverChainNVT>(Nvert,Nchain,initializeGPU);

    if(recordIndex < fluidConfigurations.GetNumRecs())
        {
        // Load vertices/vel/topology; do not restore T=0.1 bath into the target-T run.
        fluidConfigurations.readState(avm,nvt,recordIndex,true,false);
        avm->setT1Threshold(t1t);
        double qLoad = avm->reportq();
        printf("after restart load, q = %f\n", qLoad);
        if (!isfinite(qLoad))
            {
            printf("restart load produced non-finite q; aborting\n");
            return 1;
            }
        }
    else
        {
        cout << "You have tried to load a frame from a database which doesn't exist" << endl;
        return 0;
        }
    nvt->setT(T);

    SimulationPtr sim = make_shared<Simulation>();
    sim->setConfiguration(avm);
    sim->addUpdater(nvt,avm);
    sim->setIntegrationTimestep(dt);
    sim->setCurrentTime(0.0);
    sim->setCPUOperation(!initializeGPU);
    if (!gpu)
        sim->setOmpThreads(abs(USE_GPU));
    sim->setReproducible(reproducible);

    printf("starting equilibration run\n");
    for(long long int ii = 0; ii < equilibrationTimesteps; ++ii)
        sim->performTimestep();
    avm->enforceTopology();
    avm->computeForces();
    printf("Finished with initialization, current q = %f\n", avm->reportq());

    // Default: SAC after 10 production blocks. Compact: whole 5*tau_block record window.
    long long int sacStart = compactSave ? 0 : 10 * stepsPerBlock;
    profiler simulationrunProfiler("simulationrun");

    printf("starting glassy dynamics run\n");
    for(long long int ii = 0; ii < runTimesteps+2; ++ii)
        {
        simulationrunProfiler.start();
        avm->enforceTopology();
        avm->computeForces();
        double sigma = avm->getSigmaXY();
        if (ii >= sacStart)
            acdat->add(sigma,0);
        if (ii % sigmaStride == 0)
            sigmadat->writeValues(ii*dt, sigma);
        if (ii == lewriter.nextFrameToSave)
            lewriter.writeState(avm,ii);
        sim->performTimestep();
        simulationrunProfiler.end();
        };

    acdat->evaluate(false);
    for(int j = 0; j < acdat->correlator.size(); ++j)
        {
        SACtime->writeValues(acdat->correlator[j].y,acdat->correlator[j].x);
        SACtime10->writeValues(acdat->correlator[j].y,acdat->correlator[j].x);
        }
    simulationrunProfiler.print();

    if(initializeGPU)
        cudaDeviceReset();
    return 0;
};
