#include "std_include.h"
#include "cuda_runtime.h"
#include "vertexQuadraticEnergy.h"
#include "vertexTrajectoryDatabase.h"
#include "twoValuesDatabase.h"
#include "analysisPackage.h"
#include "periodicBoundaries.h"
#include <filesystem>
#include <cmath>

// Generated by Cursor. 2026-09-21
// Cage-relative SISF of AVM vertex positions from production trajectories.
// F_s^CR(q, dt) = (1/N_v) sum_j J_0(q |dr_j^CR|), tracer = vertex coordinate.
// Cage at t_w (first stored frame): 1-hop mesh neighbors (directly connected)
// union 2-hop (next-directly connected). Typical n_i = 3+6 = 9 on a 3-valent foam.
// q is set with -k after the vertex-position S(q) first peak.
// Writes (dt, Fs) with dt = t - t0 under productionRuns/vertexPositionFs/.

// Frozen cage: vertexNeighbors 1-hop and their neighbors except self and 1-hop.
static void fillVertexHop12Neighbors(shared_ptr<VertexQuadraticEnergy> avm,
                                     GPUArray<int> &neigh,
                                     GPUArray<int> &neighNum,
                                     Index2D &nidx)
    {
    int Nv = avm->Nvertices;
    int vmax = 16;
    nidx = Index2D(vmax, Nv);
    neighNum.resize(Nv);
    neigh.resize(vmax * Nv);

    ArrayHandle<int> h_vn(avm->vertexNeighbors, access_location::host, access_mode::read);
    ArrayHandle<int> h_nn(neighNum, access_location::host, access_mode::overwrite);
    ArrayHandle<int> h_n(neigh, access_location::host, access_mode::overwrite);

    for (int v = 0; v < Nv; ++v)
        {
        int ngot = 0;
        int hop1[3];
        for (int ff = 0; ff < 3; ++ff)
            {
            int w = h_vn.data[3 * v + ff];
            hop1[ff] = w;
            if (w < 0 || w >= Nv || ngot >= vmax)
                continue;
            h_n.data[nidx(ngot, v)] = w;
            ngot += 1;
            }
        for (int ff = 0; ff < 3; ++ff)
            {
            int w = hop1[ff];
            if (w < 0 || w >= Nv)
                continue;
            for (int gg = 0; gg < 3; ++gg)
                {
                int u = h_vn.data[3 * w + gg];
                if (u == v || u < 0 || u >= Nv)
                    continue;
                bool dup = false;
                for (int kk = 0; kk < ngot; ++kk)
                    if (h_n.data[nidx(kk, v)] == u)
                        {
                        dup = true;
                        break;
                        }
                if (dup || ngot >= vmax)
                    continue;
                h_n.data[nidx(ngot, v)] = u;
                ngot += 1;
                }
            }
        h_nn.data[v] = ngot;
        }
    }

int main(int argc, char *argv[])
    {
    int numpts = 200;
    int USE_GPU = -1;
    double waitingtime = 0;
    double T = 0.01;
    double p0 = 3.8;
    int recordIndex = 0;
    double ks = 6.80;

    int c;
    while ((c = getopt(argc, argv, "n:g:m:r:p:v:k:")) != -1)
        switch (c)
            {
            case 'n': numpts = atoi(optarg); break;
            case 'g': USE_GPU = atoi(optarg); break;
            case 'm': waitingtime = atof(optarg); break;
            case 'v': T = atof(optarg); break;
            case 'p': p0 = atof(optarg); break;
            case 'k': ks = atof(optarg); break;
            case 'r': recordIndex = atoi(optarg); break;
            case '?':
                return 1;
            default:
                abort();
            };

    bool reproducible = true;
    bool initializeGPU = true;
    bool gpu = chooseGPU(USE_GPU);
    if (!gpu)
        initializeGPU = false;

    const char *scratchEnv = getenv("CELLGPU_SCRATCH");
    string scratch = scratchEnv ? scratchEnv : "/scratch/bbtm/cli6/glassyDynamics/data";

    char loadfolder[512];
    char savefolder[512];
    char loaddataname[512];
    char saveDataName[512];
    sprintf(loadfolder, "%s/N%i/vertex/productionRuns/p%.3f/", scratch.c_str(), numpts, p0);
    sprintf(savefolder, "%s/N%i/vertex/productionRuns/vertexPositionFs/p%.3f/",
            scratch.c_str(), numpts, p0);
    sprintf(loaddataname, "%sglassyDynamics_N%i_p%.4f_T%.8f_waitingTime%.0f_idx%i.nc",
            loadfolder, numpts, p0, T, waitingtime, recordIndex);
    sprintf(saveDataName, "%stimeVertexCRSISF_N%i_p%.4f_T%.8f_k%.3f_waitingTime%.0f_idx%i.nc",
            savefolder, numpts, p0, T, ks, waitingtime, recordIndex);

    namespace fs = std::filesystem;
    if (!fs::exists(loaddataname))
        {
        cout << loaddataname << " does not exist; skip" << endl;
        return 0;
        }
    fs::create_directories(savefolder);
    cout << "reading " << loaddataname << endl;
    cout << "writing " << saveDataName << endl;
    cout << "q = " << ks << endl;

    int Nvert = 2 * numpts;
    vertexTrajectoryDatabase traj(Nvert, loaddataname, NcFile::ReadOnly);
    int nrec = traj.GetNumRecs();
    if (nrec < 20)
        {
        cout << "records = " << nrec << " < 20; skip" << endl;
        return 0;
        }

    shared_ptr<VertexQuadraticEnergy> avm =
        make_shared<VertexQuadraticEnergy>(numpts, 1.0, p0, reproducible, false, initializeGPU);
    if (!initializeGPU)
        avm->setCPU();
    avm->setCellPreferencesUniform(1.0, p0);

    traj.readState(avm, 0, false);
    GPUArray<int> cageNeigh;
    GPUArray<int> cageNeighNum;
    cageNeigh.neverGPU = true;
    cageNeighNum.neverGPU = true;
    Index2D cageIdx;
    fillVertexHop12Neighbors(avm, cageNeigh, cageNeighNum, cageIdx);

    dynamicalFeatures dynFeat(avm->vertexPositions, avm->Box);
    dynFeat.setCageNeighbors(cageNeigh, cageNeighNum, cageIdx);

    shared_ptr<twoValuesDatabase> out = make_shared<twoValuesDatabase>(saveDataName, NcFile::Replace);
    double t0 = avm->currentTime;
    for (int rec = 0; rec < nrec; ++rec)
        {
        traj.readState(avm, rec, false);
        double time = avm->currentTime;
        if (rec > 10 && time < 1e-12)
            break;
        double dt = time - t0;
        out->writeValues(dt, dynFeat.computeCageRelativeSISF(avm->vertexPositions, ks));
        }

    if (initializeGPU)
        cudaDeviceReset();
    return 0;
    };
