#include "std_include.h"
#include "cuda_runtime.h"
#include "vertexQuadraticEnergy.h"
#include "vertexTrajectoryDatabase.h"
#include "twoValuesDatabase.h"
#include "periodicBoundaries.h"
#include <filesystem>
#include <glob.h>
#include <cstdio>
#include <vector>

// Generated by Cursor. 2026-09-21
// Isotropic tension Sigma = (sigma_xx + sigma_yy)/2 from vertex production
// trajectories. Virials are VertexQuadraticEnergy::getSigmaXX/YY:
//   sigma_xx = (1/A) dE/d eps_x = -sum F_x x_rel / A_box
//   sigma_yy = (1/A) dE/d eps_y = -sum F_y y_rel / A_box
// Per (p0, T): last nKeep log-spaced records of each idx (default 10, idx=0..9).
// Writes twoValuesDatabase (t, Sigma) under productionRuns/sigmaIso/, frames
// in idx order, nKeep complete frames per replica (skip short/missing idx).

static string findTrajectory(const string &dir, int N, double p0, double T, int idx)
    {
    char globpat[1024];
    snprintf(globpat, sizeof(globpat),
             "%sglassyDynamics_N%i_p%.4f_T%.8f_waitingTime*_idx%i.nc",
             dir.c_str(), N, p0, T, idx);
    glob_t g;
    g.gl_offs = 0;
    int rc = glob(globpat, 0, NULL, &g);
    string out;
    if (rc == 0 && g.gl_pathc > 0)
        out = g.gl_pathv[0];
    globfree(&g);
    return out;
    }

int main(int argc, char *argv[])
    {
    int numpts = 4096;
    int USE_GPU = -1;
    double T = 0.01;
    double p0 = 3.8;
    int nKeep = 10;
    int idxLo = 0;
    int idxHi = 9;

    int c;
    while ((c = getopt(argc, argv, "n:g:p:v:s:i:j:")) != -1)
        switch (c)
            {
            case 'n': numpts = atoi(optarg); break;
            case 'g': USE_GPU = atoi(optarg); break;
            case 'v': T = atof(optarg); break;
            case 'p': p0 = atof(optarg); break;
            case 's': nKeep = atoi(optarg); break;
            case 'i': idxLo = atoi(optarg); break;
            case 'j': idxHi = atoi(optarg); break;
            case '?':
                return 1;
            default:
                abort();
            };

    bool reproducible = true;
    bool initializeGPU = true;
    bool gpu = chooseGPU(USE_GPU);
    if (!gpu)
        initializeGPU = false;

    const char *scratchEnv = getenv("CELLGPU_SCRATCH");
    string scratch = scratchEnv ? scratchEnv : "/scratch/bbtm/cli6/glassyDynamics/data";

    char loadfolder[512];
    char savefolder[512];
    char saveDataName[512];
    snprintf(loadfolder, sizeof(loadfolder), "%s/N%i/vertex/productionRuns/p%.3f/",
             scratch.c_str(), numpts, p0);
    snprintf(savefolder, sizeof(savefolder), "%s/N%i/vertex/productionRuns/sigmaIso/",
             scratch.c_str(), numpts);
    snprintf(saveDataName, sizeof(saveDataName), "%ssigmaIso_N%i_p%.4f_T%.8f.nc",
             savefolder, numpts, p0, T);

    namespace fs = std::filesystem;
    fs::create_directories(savefolder);

    cout << "p0 = " << p0 << " T = " << T << " nKeep = " << nKeep
         << " idx = " << idxLo << ".." << idxHi << endl;
    cout << "load dir " << loadfolder << endl;
    cout << "write " << saveDataName << endl;

    int Nvert = 2 * numpts;
    shared_ptr<VertexQuadraticEnergy> avm =
        make_shared<VertexQuadraticEnergy>(numpts, 1.0, p0, reproducible, false, initializeGPU);
    if (!initializeGPU)
        avm->setCPU();
    avm->setCellPreferencesUniform(1.0, p0);

    vector<double> times;
    vector<double> sigmas;
    int nUsed = 0;
    int nMissing = 0;
    int nShort = 0;

    for (int idx = idxLo; idx <= idxHi; ++idx)
        {
        string loaddataname = findTrajectory(string(loadfolder), numpts, p0, T, idx);
        if (loaddataname.empty())
            {
            cout << "missing idx=" << idx << endl;
            nMissing += 1;
            continue;
            }
        cout << "reading " << loaddataname << endl;
        vertexTrajectoryDatabase traj(Nvert, loaddataname, NcFile::ReadOnly);
        int nrec = traj.GetNumRecs();
        if (nrec < nKeep)
            {
            cout << "records = " << nrec << " < " << nKeep << "; skip idx=" << idx << endl;
            nShort += 1;
            continue;
            }
        int rec0 = nrec - nKeep;
        for (int rec = rec0; rec < nrec; ++rec)
            {
            traj.readState(avm, rec, true);
            double sxx = avm->getSigmaXX();
            double syy = avm->getSigmaYY();
            double Sigma = 0.5 * (sxx + syy);
            times.push_back(avm->currentTime);
            sigmas.push_back(Sigma);
            nUsed += 1;
            }
        }

    cout << "n_used = " << nUsed << " n_missing = " << nMissing << " n_short = " << nShort << endl;
    if (nUsed == 0)
        {
        cout << "no Sigma accumulated; abort" << endl;
        return 1;
        }

    shared_ptr<twoValuesDatabase> out = make_shared<twoValuesDatabase>(saveDataName, NcFile::Replace);
    for (size_t i = 0; i < times.size(); ++i)
        out->writeValues(times[i], sigmas[i]);

    if (initializeGPU)
        cudaDeviceReset();
    return 0;
    }
