#include "std_include.h"
#include "cuda_runtime.h"
#include "Simulation.h"
#include "vertexQuadraticEnergy.h"
#include "NoseHooverChainNVT.h"
#include "nvtAVMRestartDatabase.h"
#include "vertexTrajectoryDatabase.h"
#include "twoValuesDatabase.h"
#include "logEquilibrationStateWriter.h"
#include "autocorrelator.h"
#include "profiler.h"
#include <filesystem>
#include <cmath>

// Generated by Cursor. 2026-09-12
// Vertex production: load T=0.1 fluid, tau_block=max(tau_est,1000).
// Equilibrate 10*tau_block with no I/O, then record 10*tau_block of
// SAC(sigma_xy), sigma_xy every 100 dt, and one log-spaced trajectory
// for later CRSISF Fs. Writes under vertex/productionRuns/ (not scouting p*/).
// Before sigma/trajectory writes: enforceTopology + computeForces (NH half-step).
// Default l_T1=0.01. -m sets record multiples of tau_block (default 10).

int main(int argc, char*argv[])
{
    int numpts = 200;
    int USE_GPU = -1;
    double tauEstimate = 10;
    double dt = 0.01;
    double T = 0.01;
    double T0 = 0.1;
    double p0 = 3.8;
    double t1t = 0.01;
    int nEqBlocks = 10;
    int nProdBlocks = 10;
    int recordIndex = 0;
    int Nchain = 4;
    double statesSavedPerDecadeOfTime = 20.;
    int c;
    while((c=getopt(argc,argv,"n:g:m:s:r:v:l:p:t:e:")) != -1)
        switch(c)
        {
            case 'n': numpts = atoi(optarg); break;
            case 'g': USE_GPU = atoi(optarg); break;
            case 't': tauEstimate = atof(optarg); break;
            case 'e': dt = atof(optarg); break;
            case 'v': T = atof(optarg); break;
            case 'l': T0 = atof(optarg); break;
            case 'p': p0 = atof(optarg); break;
            case 's': statesSavedPerDecadeOfTime = atof(optarg); break;
            case 'r': recordIndex = atoi(optarg); break;
            case 'm': nProdBlocks = atoi(optarg); break;
            case '?':
                    return 1;
            default:
                       abort();
        };

    bool reproducible = true;
    bool initializeGPU = true;
    bool gpu = chooseGPU(USE_GPU);
    if (!gpu)
        initializeGPU = false;

    const char *scratchEnv = getenv("CELLGPU_SCRATCH");
    string scratch = scratchEnv ? scratchEnv : "/scratch/bbtm/cli6/glassyDynamics/data";

    char loadDatabaseName[512];
    sprintf(loadDatabaseName,"%s/N%i/vertex/fluidConfigurations/vertexMonodisperseFluidConfigurations_N%i_TEq%.8f_p%.5f.nc",
            scratch.c_str(),numpts,numpts,T0,p0);
    cout << "reading record " << recordIndex << " from " << loadDatabaseName << endl;
    int Nvert = 2*numpts;
    nvtAVMRestartDatabase fluidConfigurations(Nvert,Nchain,loadDatabaseName,NcFile::ReadOnly);

    double tauBlock = max(1000.0, tauEstimate);
    long long int stepsPerBlock = (long long int)floor(tauBlock / dt);
    long long int equilibrationTimesteps = nEqBlocks * stepsPerBlock;
    long long int runTimesteps = nProdBlocks * stepsPerBlock;
    long long int sigmaStride = 100;
    double tw = nEqBlocks * tauBlock;
    cout << "tau_est = " << tauEstimate << ", tau_block = " << tauBlock
         << ", eq " << nEqBlocks << "*tau_block, record " << nProdBlocks << "*tau_block" << endl;
    cout << "equilibration timesteps = " << equilibrationTimesteps << ", production timesteps = " << runTimesteps << endl;
    cout << "T1Threshold l_T1 = " << t1t << endl;

    char saveDirName[512];
    sprintf(saveDirName, "%s/N%i/vertex/productionRuns/p%.3f/",scratch.c_str(),numpts,p0);
    std::filesystem::create_directories(saveDirName);

    logEquilibrationStateWriter lewriter((1.0/statesSavedPerDecadeOfTime));
    char dataname[512];
    sprintf(dataname,"%sglassyDynamics_N%i_p%.4f_T%.8f_waitingTime%.0f_idx%i.nc",
            saveDirName,numpts,p0,T,tw,recordIndex);
    shared_ptr<vertexTrajectoryDatabase> trajdat=make_shared<vertexTrajectoryDatabase>(Nvert,dataname,NcFile::Replace);
    lewriter.addDatabase(trajdat,0);
    lewriter.identifyNextFrame();

    char SACname[512];
    sprintf(SACname,"%sSACtime_N%i_p%.4f_T%.8f_waitingTime%.0f_idx%i.nc",saveDirName,numpts,p0,T,tw,recordIndex);
    shared_ptr<twoValuesDatabase> SACtime=make_shared<twoValuesDatabase>(SACname,NcFile::Replace);
    shared_ptr<autocorrelator> acdat = make_shared<autocorrelator>(16,2,dt);

    char sigmaName[512];
    sprintf(sigmaName,"%ssigmaXY_N%i_p%.4f_T%.8f_idx%i.nc",saveDirName,numpts,p0,T,recordIndex);
    shared_ptr<twoValuesDatabase> sigmadat=make_shared<twoValuesDatabase>(sigmaName,NcFile::Replace);

    cout << "Data are saved in " << saveDirName << endl;

    shared_ptr<VertexQuadraticEnergy> avm = make_shared<VertexQuadraticEnergy>(numpts,1.0,p0,reproducible,false,initializeGPU);
    if (!initializeGPU)
        avm->setCPU();
    avm->setCellPreferencesUniform(1.0,p0);
    Nvert = avm->Nvertices;
    shared_ptr<NoseHooverChainNVT> nvt = make_shared<NoseHooverChainNVT>(Nvert,Nchain,initializeGPU);

    if(recordIndex < fluidConfigurations.GetNumRecs())
        {
        fluidConfigurations.readState(avm,nvt,recordIndex,true,false);
        avm->setT1Threshold(t1t);
        double qLoad = avm->reportq();
        printf("after restart load, q = %f\n", qLoad);
        if (!isfinite(qLoad))
            {
            printf("restart load produced non-finite q; aborting\n");
            return 1;
            }
        }
    else
        {
        cout << "You have tried to load a frame from a database which doesn't exist" << endl;
        return 0;
        }
    nvt->setT(T);

    SimulationPtr sim = make_shared<Simulation>();
    sim->setConfiguration(avm);
    sim->addUpdater(nvt,avm);
    sim->setIntegrationTimestep(dt);
    sim->setCurrentTime(0.0);
    sim->setCPUOperation(!initializeGPU);
    if (!gpu)
        sim->setOmpThreads(abs(USE_GPU));
    sim->setReproducible(reproducible);

    printf("starting equilibration run\n");
    for(long long int ii = 0; ii < equilibrationTimesteps; ++ii)
        sim->performTimestep();
    avm->enforceTopology();
    avm->computeForces();
    printf("Finished with initialization, current q = %f\n", avm->reportq());

    profiler simulationrunProfiler("simulationrun");

    printf("starting glassy dynamics run\n");
    for(long long int ii = 0; ii < runTimesteps+2; ++ii)
        {
        simulationrunProfiler.start();
        avm->enforceTopology();
        avm->computeForces();
        double sigma = avm->getSigmaXY();
        acdat->add(sigma,0);
        if (ii % sigmaStride == 0)
            sigmadat->writeValues(ii*dt, sigma);
        if (ii == lewriter.nextFrameToSave)
            lewriter.writeState(avm,ii);
        sim->performTimestep();
        simulationrunProfiler.end();
        };

    acdat->evaluate(false);
    for(int j = 0; j < acdat->correlator.size(); ++j)
        SACtime->writeValues(acdat->correlator[j].y,acdat->correlator[j].x);
    simulationrunProfiler.print();

    if(initializeGPU)
        cudaDeviceReset();
    return 0;
};
