#include "std_include.h"
#include "cuda_runtime.h"
#include "vertexQuadraticEnergy.h"
#include "vertexTrajectoryDatabase.h"
#include "twoValuesDatabase.h"
#include "analysisPackage.h"
#include "periodicBoundaries.h"
#include <filesystem>
#include <cmath>

// Optional -a l_T1: read/write t1Scan/t1_<tag>/ (same tag as vertexTauAlphaTest).
static void formatT1Tag(double t1t, char *out, int n)
    {
    double lg = log10(t1t);
    int e = (int)lround(lg);
    if (fabs(lg - (double)e) < 1e-8)
        snprintf(out, n, "1e%d", e);
    else
        snprintf(out, n, "%g", t1t);
    }

// Generated by Cursor. 2026-08-24
// Cage-relative SISF of AVM cell centroids from log-spaced vertex trajectories.
// F_s^CR(q, dt) = (1/N) sum_j J_0(q |dr_j^CR|), cage = t_w cell-cell neighbors.
// q default 6.80 (same k as Voronoi tauAlphaTableAnalyse.cpp CRSISF).
// Writes (dt, Fs) with dt = t - t0. Data on $CELLGPU_SCRATCH.

// Dual of the 3-valent mesh: an edge (v,w) bounding cell cc is shared with
// exactly one other cell. Uses public vertexNeighbors / vertexCellNeighbors.
static void fillCellCellNeighborsFromRing(shared_ptr<VertexQuadraticEnergy> avm,
                                          GPUArray<int> &neigh,
                                          GPUArray<int> &neighNum,
                                          Index2D &nidx)
    {
    int Nc = avm->Ncells;
    int Nv = avm->Nvertices;
    int vmax = (int)avm->n_idx.getW();
    if (vmax < 8)
        vmax = 32;
    nidx = Index2D(vmax, Nc);
    neighNum.resize(Nc);
    neigh.resize(vmax * Nc);

    ArrayHandle<int> h_vn(avm->vertexNeighbors, access_location::host, access_mode::read);
    ArrayHandle<int> h_vcn(avm->vertexCellNeighbors, access_location::host, access_mode::read);
    ArrayHandle<int> h_nn(neighNum, access_location::host, access_mode::overwrite);
    ArrayHandle<int> h_n(neigh, access_location::host, access_mode::overwrite);

    auto vertexHasCell = [&](int v, int cc) -> bool
        {
        if (v < 0 || v >= Nv)
            return false;
        for (int ff = 0; ff < 3; ++ff)
            if (h_vcn.data[3 * v + ff] == cc)
                return true;
        return false;
        };

    auto otherCell = [&](int v1, int v2, int cc) -> int
        {
        if (v1 < 0 || v1 >= Nv || v2 < 0 || v2 >= Nv)
            return -1;
        for (int ff = 0; ff < 3; ++ff)
            {
            int c = h_vcn.data[3 * v1 + ff];
            if (c == cc || c < 0 || c >= Nc)
                continue;
            for (int gg = 0; gg < 3; ++gg)
                if (h_vcn.data[3 * v2 + gg] == c)
                    return c;
            }
        return -1;
        };

    for (int cc = 0; cc < Nc; ++cc)
        {
        int ngot = 0;
        for (int vv = 0; vv < Nv; ++vv)
            {
            if (!vertexHasCell(vv, cc))
                continue;
            for (int ff = 0; ff < 3; ++ff)
                {
                int w = h_vn.data[3 * vv + ff];
                if (w <= vv)
                    continue;
                if (!vertexHasCell(w, cc))
                    continue;
                int oc = otherCell(vv, w, cc);
                if (oc < 0)
                    continue;
                bool dup = false;
                for (int kk = 0; kk < ngot; ++kk)
                    if (h_n.data[nidx(kk, cc)] == oc)
                        {
                        dup = true;
                        break;
                        }
                if (dup || ngot >= vmax)
                    continue;
                h_n.data[nidx(ngot, cc)] = oc;
                ngot += 1;
                }
            }
        h_nn.data[cc] = ngot;
        }
    }

int main(int argc, char *argv[])
    {
    int numpts = 200;
    int USE_GPU = -1;
    double waitingtime = 0;
    double T = 0.01;
    double p0 = 3.8;
    double t1t = -1.0;
    int recordIndex = 0;
    double ks = 6.80;

    int c;
    while ((c = getopt(argc, argv, "n:g:m:r:p:v:k:a:")) != -1)
        switch (c)
            {
            case 'n': numpts = atoi(optarg); break;
            case 'g': USE_GPU = atoi(optarg); break;
            case 'm': waitingtime = atof(optarg); break;
            case 'v': T = atof(optarg); break;
            case 'p': p0 = atof(optarg); break;
            case 'k': ks = atof(optarg); break;
            case 'a': t1t = atof(optarg); break;
            case 'r': recordIndex = atoi(optarg); break;
            case '?':
                return 1;
            default:
                abort();
            };

    bool reproducible = true;
    bool initializeGPU = true;
    bool gpu = chooseGPU(USE_GPU);
    if (!gpu)
        initializeGPU = false;

    const char *scratchEnv = getenv("CELLGPU_SCRATCH");
    string scratch = scratchEnv ? scratchEnv : "/scratch/bbtm/cli6/glassyDynamics/data";

    bool t1Scan = (t1t > 0.0);
    if (!t1Scan)
        t1t = 0.01;
    char t1tag[32];
    formatT1Tag(t1t, t1tag, 32);

    char loadfolder[512];
    char savefolder[512];
    char loaddataname[512];
    char saveDataName[512];
    if (t1Scan)
        {
        sprintf(loadfolder, "%s/N%i/vertex/t1Scan/t1_%s/p%.3f/", scratch.c_str(), numpts, t1tag, p0);
        sprintf(savefolder, "%s/N%i/vertex/t1Scan/t1_%s/tauAlphaData/p%.3f/", scratch.c_str(), numpts, t1tag, p0);
        }
    else
        {
        sprintf(loadfolder, "%s/N%i/vertex/p%.3f/", scratch.c_str(), numpts, p0);
        sprintf(savefolder, "%s/N%i/vertex/tauAlphaData/p%.3f/", scratch.c_str(), numpts, p0);
        }
    sprintf(loaddataname, "%sglassyDynamics_N%i_p%.4f_T%.8f_waitingTime%.0f_idx%i.nc",
            loadfolder, numpts, p0, T, waitingtime, recordIndex);
    sprintf(saveDataName, "%stimeCRSISF_N%i_p%.4f_T%.8f_k%.3f_waitingTime%.0f_idx%i.nc",
            savefolder, numpts, p0, T, ks, waitingtime, recordIndex);

    namespace fs = std::filesystem;
    if (!fs::exists(loaddataname))
        {
        cout << loaddataname << " does not exist; skip" << endl;
        return 0;
        }
    fs::create_directories(savefolder);
    cout << "reading " << loaddataname << endl;
    cout << "writing " << saveDataName << endl;

    int Nvert = 2 * numpts;
    vertexTrajectoryDatabase traj(Nvert, loaddataname, NcFile::ReadOnly);
    int nrec = traj.GetNumRecs();
    if (nrec < 20)
        {
        cout << "records = " << nrec << " < 20; skip" << endl;
        return 0;
        }

    shared_ptr<VertexQuadraticEnergy> avm = make_shared<VertexQuadraticEnergy>(numpts, 1.0, p0, reproducible, false, initializeGPU);
    if (!initializeGPU)
        avm->setCPU();
    avm->setCellPreferencesUniform(1.0, p0);

    traj.readState(avm, 0, true);
    GPUArray<int> cageNeigh;
    GPUArray<int> cageNeighNum;
    cageNeigh.neverGPU = true;
    cageNeighNum.neverGPU = true;
    Index2D cageIdx;
    fillCellCellNeighborsFromRing(avm, cageNeigh, cageNeighNum, cageIdx);

    dynamicalFeatures dynFeat(avm->cellPositions, avm->Box);
    dynFeat.setCageNeighbors(cageNeigh, cageNeighNum, cageIdx);

    shared_ptr<twoValuesDatabase> out = make_shared<twoValuesDatabase>(saveDataName, NcFile::Replace);
    double t0 = avm->currentTime;
    for (int rec = 0; rec < nrec; ++rec)
        {
        traj.readState(avm, rec, true);
        double time = avm->currentTime;
        if (rec > 10 && time < 1e-12)
            break;
        double dt = time - t0;
        out->writeValues(dt, dynFeat.computeCageRelativeSISF(avm->cellPositions, ks));
        }

    if (initializeGPU)
        cudaDeviceReset();
    return 0;
    };
