# Generated by Cursor. 2026-08-19.
# Log-log plot of mean |σ_ana − σ_num| vs δγ for vertex-model getSigmaXY.
# Overlays A (δγ)^2 (truncation) and B/δγ (roundoff), fitted on p0=3.8.

import csv
import os

import matplotlib.pyplot as plt
import numpy as np

# Mean abs error of σ_xy; CSV from vertexSigmaXY_pScan.out
CSV = os.path.join(os.path.dirname(__file__), "data", "vertexSigmaXY_pScan.csv")
OUTDIR = "/home/chengling/Research/researchUpdates/chengling/weeklyUpdates"
LOCAL_FIG = os.path.join(os.path.dirname(__file__), "data")


def load_csv(path):
    by_p = {}
    with open(path) as f:
        for row in csv.DictReader(f):
            p0 = float(row["p0"])
            by_p.setdefault(p0, []).append(
                (float(row["dgamma"]), float(row["meanAbs"]))
            )
    for p0 in by_p:
        by_p[p0].sort()
    return by_p


def fit_power(x, y, exponent):
    """Least-squares A in y = A x^exponent, log-space mean of y / x^exp."""
    ratio = y / np.power(x, exponent)
    return np.exp(np.mean(np.log(ratio)))


def main():
    data = load_csv(CSV)
    colors = {3.7: "#1f77b4", 3.8: "#d62728", 3.9: "#2ca02c"}
    markers = {3.7: "o", 3.8: "s", 3.9: "^"}

    x38, y38 = np.array(data[3.8]).T
    # Truncation branch: δγ = 10^{-2} .. 10^{-4}
    left = (x38 >= 9e-5) & (x38 <= 1.1e-2)
    A = fit_power(x38[left], y38[left], 2.0)
    # Roundoff branch: δγ = 10^{-6} .. 10^{-8}
    right = (x38 <= 1.1e-6) & (x38 >= 9e-9)
    B = fit_power(x38[right], y38[right], -1.0)

    xfit_left = np.logspace(-4.3, -1.9, 40)
    xfit_right = np.logspace(-8.2, -5.5, 40)
    fig, ax = plt.subplots(figsize=(6.2, 4.6))
    for p0 in sorted(data):
        x, y = np.array(data[p0]).T
        ax.loglog(
            x,
            y,
            marker=markers[p0],
            color=colors[p0],
            linestyle="-",
            linewidth=1.0,
            markersize=6,
            label=r"$p_0=%.1f$" % p0,
        )
    ax.loglog(
        xfit_left,
        A * xfit_left**2,
        "--",
        color="0.35",
        linewidth=1.4,
        label=r"$A\,(\delta\gamma)^2$",
    )
    ax.loglog(
        xfit_right,
        B / xfit_right,
        ":",
        color="0.15",
        linewidth=1.6,
        label=r"$B/\delta\gamma$",
    )
    ax.set_xlabel(r"$\delta\gamma$", fontsize=12)
    ax.set_ylabel(r"$\langle|\sigma_{xy}^{\mathrm{ana}}-\sigma_{xy}^{\mathrm{num}}|\rangle$", fontsize=12)
    ax.set_xlim(5e-9, 2e-2)
    ax.legend(frameon=False, fontsize=10)
    ax.tick_params(which="both", direction="in")
    fig.tight_layout()

    os.makedirs(OUTDIR, exist_ok=True)
    os.makedirs(LOCAL_FIG, exist_ok=True)
    for folder in (OUTDIR, LOCAL_FIG):
        fig.savefig(os.path.join(folder, "Chengling_2026_08_19_sigmaXY_abserr.pdf"))
        fig.savefig(os.path.join(folder, "Chengling_2026_08_19_sigmaXY_abserr.png"), dpi=200)
    print("A (truncation, y=A dgamma^2) = %.6e" % A)
    print("B (roundoff, y=B/dgamma)     = %.6e" % B)
    print("wrote figures to", OUTDIR)


if __name__ == "__main__":
    main()
