// Generated by Cursor. 2026-08-19.
// Finite-difference check of per-cell ∂E_i/∂γ from VertexQuadraticEnergy::getdEdgamma.
// Physics: E_i = KA(A_i-A0)^2 + KP(P_i-P0)^2; simple shear F = [[1, γ], [0, 1]].
// Numeric: (E_i(+δγ) − E_i(−δγ)) / (2 δγ). Topology held fixed after NVT eq.
// Equilibrate with Nose–Hoover NVT at T=0.001 (default 10000 steps, dt=0.01).
// Mean abs/rel error is over Ncells of one snapshot.

#include "std_include.h"
#include "cuda_runtime.h"

#include "Simulation.h"
#include "vertexQuadraticEnergy.h"
#include "NoseHooverChainNVT.h"
#include "periodicBoundaries.h"
#include "functions.h"

/*!
Count edges shorter than T1Threshold after a shear, without performing T1s.
Each undirected edge is counted once (vertex1 < vertex2).
*/
int countShortEdges(shared_ptr<VertexQuadraticEnergy> avm)
    {
    ArrayHandle<double2> h_v(avm->vertexPositions,access_location::host,access_mode::read);
    ArrayHandle<int> h_vn(avm->vertexNeighbors,access_location::host,access_mode::read);
    int nShort = 0;
    double2 edge;
    for (int v1 = 0; v1 < avm->Nvertices; ++v1)
        {
        for (int vv = 0; vv < 3; ++vv)
            {
            int v2 = h_vn.data[3*v1+vv];
            if (v1 < v2)
                {
                avm->Box->minDist(h_v.data[v1],h_v.data[v2],edge);
                if (norm(edge) < avm->T1Threshold)
                    nShort += 1;
                };
            };
        };
    return nShort;
    };

/*!
Apply affine simple shear γ to saved vertex positions and the periodic box:
x → x + γ y, box → [[Lx, γ Ly], [0, Ly]]. Area is unchanged.
Does not call enforceTopology.
*/
void applySimpleShear(shared_ptr<VertexQuadraticEnergy> avm,
                      const vector<double2> &v0,
                      double Lx, double Ly, double gamma)
    {
    avm->Box->setGeneral(Lx, gamma*Ly, 0.0, Ly);
    ArrayHandle<double2> h_v(avm->vertexPositions,access_location::host,access_mode::overwrite);
    for (int i = 0; i < avm->Nvertices; ++i)
        {
        h_v.data[i].x = v0[i].x + gamma * v0[i].y;
        h_v.data[i].y = v0[i].y;
        avm->Box->putInBoxReal(h_v.data[i]);
        };
    avm->forcesUpToDate = false;
    };

//! E_i = KA (A-A0)^2 + KP (P-P0)^2 from the current AreaPeri arrays.
void copyCellEnergies(shared_ptr<VertexQuadraticEnergy> avm, vector<double> &Ei)
    {
    ArrayHandle<double2> h_AP(avm->returnAreaPeri(),access_location::host,access_mode::read);
    ArrayHandle<double2> h_APP(avm->returnAreaPeriPreferences(),access_location::host,access_mode::read);
    Ei.resize(avm->Ncells);
    for (int i = 0; i < avm->Ncells; ++i)
        {
        double dA = h_AP.data[i].x - h_APP.data[i].x;
        double dP = h_AP.data[i].y - h_APP.data[i].y;
        Ei[i] = dA*dA + dP*dP;
        };
    };

int main(int argc, char*argv[])
    {
    int numpts = 4096;
    int USE_GPU = -1;
    int Ntests = 1;
    int initSteps = 10000;
    int Nchain = 4;
    int c;
    double p0 = 3.8;
    double a0 = 1.0;
    double T = 0.001;
    double dt = 0.01;
    const double dgammaList[] = {1e-2, 1e-3, 1e-4, 1e-5, 1e-6, 1e-7};
    const int nGamma = 6;

    while((c=getopt(argc,argv,"n:g:p:a:c:v:i:e:")) != -1)
        switch(c)
            {
            case 'n': numpts = atoi(optarg); break;
            case 'g': USE_GPU = atoi(optarg); break;
            case 'p': p0 = atof(optarg); break;
            case 'a': a0 = atof(optarg); break;
            case 'c': Ntests = atoi(optarg); break;
            case 'v': T = atof(optarg); break;
            case 'i': initSteps = atoi(optarg); break;
            case 'e': dt = atof(optarg); break;
            case '?':
                    if(optopt=='c')
                        std::cerr<<"Option -" << optopt << "requires an argument.\n";
                    else if(isprint(optopt))
                        std::cerr<<"Unknown option '-" << optopt << "'.\n";
                    else
                        std::cerr << "Unknown option character.\n";
                    return 1;
            default:
                       abort();
            };

    bool initializeGPU = true;
    if (USE_GPU >= 0)
        {
        bool gpu = chooseGPU(USE_GPU);
        if (!gpu) return 0;
        cudaSetDevice(USE_GPU);
        }
    else
        initializeGPU = false;

    printf("per-cell dEdgamma FD: Ncells=%i  p0=%.4f  T=%.6f  NVT steps=%i  dt=%.4f  GPU=%i\n",
           numpts,p0,T,initSteps,dt,(int)initializeGPU);
    printf("dgamma set:");
    for (int ig = 0; ig < nGamma; ++ig)
        printf("  %.3e", dgammaList[ig]);
    printf("\n");

    shared_ptr<VertexQuadraticEnergy> avm =
        make_shared<VertexQuadraticEnergy>(numpts,a0,p0,false,false,initializeGPU);
    if (!initializeGPU)
        avm->setCPU();

    avm->setVertexVelocitiesMaxwellBoltzmann(T);
    int Nvert = avm->Nvertices;
    shared_ptr<NoseHooverChainNVT> nvt =
        make_shared<NoseHooverChainNVT>(Nvert, Nchain, initializeGPU);
    nvt->setT(T);
    SimulationPtr sim = make_shared<Simulation>();
    sim->setConfiguration(avm);
    sim->addUpdater(nvt, avm);
    sim->setIntegrationTimestep(dt);
    sim->setCPUOperation(!initializeGPU);
    for (int timestep = 0; timestep < initSteps; ++timestep)
        sim->performTimestep();
    avm->enforceTopology();
    avm->forcesUpToDate = false;

    vector<double> dEdgAna;
    avm->getdEdgamma(dEdgAna);
    double E0 = avm->computeEnergy();
    double meanAbsdEdg = 0.0;
    for (int i = 0; i < avm->Ncells; ++i)
        meanAbsdEdg += fabs(dEdgAna[i]);
    meanAbsdEdg /= avm->Ncells;

    vector<double2> v0(avm->Nvertices);
        {
        ArrayHandle<double2> h_v(avm->vertexPositions,access_location::host,access_mode::read);
        for (int i = 0; i < avm->Nvertices; ++i)
            v0[i] = h_v.data[i];
        };
    double Lx,xy,yx,Ly;
    avm->Box->getBoxDims(Lx,xy,yx,Ly);

    printf("E = %.6e   mean |dE_i/dgamma| = %.6e   Ncells = %i\n",
           E0, meanAbsdEdg, avm->Ncells);
    printf("%12s %14s %14s %14s %14s %8s\n",
           "dgamma", "meanRel", "maxRel", "meanAbs", "maxAbs", "nShort");

    int Ncells = avm->Ncells;
    for (int ig = 0; ig < nGamma; ++ig)
        {
        double dgamma = dgammaList[ig];
        applySimpleShear(avm,v0,Lx,Ly,+dgamma);
        avm->computeEnergy();
        vector<double> Eplus;
        copyCellEnergies(avm, Eplus);
        int nShortPlus = countShortEdges(avm);

        applySimpleShear(avm,v0,Lx,Ly,-dgamma);
        avm->computeEnergy();
        vector<double> Eminus;
        copyCellEnergies(avm, Eminus);
        int nShortMinus = countShortEdges(avm);

        double sumAbs = 0.0;
        double sumRel = 0.0;
        double maxRel = 0.0;
        double maxAbs = 0.0;
        for (int i = 0; i < Ncells; ++i)
            {
            double dEdgNum = (Eplus[i] - Eminus[i])/(2.0*dgamma);
            double absDiff = fabs(dEdgAna[i] - dEdgNum);
            double denom = max(max(fabs(dEdgAna[i]),fabs(dEdgNum)),1e-30);
            double rel = absDiff/denom;
            sumAbs += absDiff;
            sumRel += rel;
            if (rel > maxRel) maxRel = rel;
            if (absDiff > maxAbs) maxAbs = absDiff;
            };
        printf("%12.3e %14.6e %14.6e %14.6e %14.6e %8i\n",
               dgamma, sumRel/Ncells, maxRel, sumAbs/Ncells, maxAbs,
               nShortPlus+nShortMinus);
        };

    if (initializeGPU)
        cudaDeviceReset();
    return 0;
    };
