// Generated by Cursor. 2026-08-19.
// Random-init FD scan of VertexQuadraticEnergy::getSigmaXY vs δγ at several p0.
// Physics: σ_xy = (1/A) ∂E/∂γ; numeric (E(+δγ)−E(−δγ))/(2 δγ A). Topology frozen.
// Mean |Δσ| is over Nsnapshots independent random Voronoi initializations (no eq).
// Writes localTest/data/vertexSigmaXY_pScan.csv (p0, dgamma, meanAbs, meanAbsSigma, meanE).

#include "std_include.h"
#include "cuda_runtime.h"

#include "vertexQuadraticEnergy.h"
#include "periodicBoundaries.h"
#include "functions.h"

#include <fstream>

/*!
Affine simple shear γ: x → x + γ y, box → [[Lx, γ Ly], [0, Ly]]. No T1s.
*/
void applySimpleShear(shared_ptr<VertexQuadraticEnergy> avm,
                      const vector<double2> &v0,
                      double Lx, double Ly, double gamma)
    {
    avm->Box->setGeneral(Lx, gamma*Ly, 0.0, Ly);
    ArrayHandle<double2> h_v(avm->vertexPositions,access_location::host,access_mode::overwrite);
    for (int i = 0; i < avm->Nvertices; ++i)
        {
        h_v.data[i].x = v0[i].x + gamma * v0[i].y;
        h_v.data[i].y = v0[i].y;
        avm->Box->putInBoxReal(h_v.data[i]);
        };
    avm->forcesUpToDate = false;
    };

int main(int argc, char*argv[])
    {
    int numpts = 4096;
    int USE_GPU = -1;
    int Ntests = 100;
    int c;
    double a0 = 1.0;
    const double p0List[] = {3.7, 3.8, 3.9};
    const int nP0 = 3;
    const double dgammaList[] = {1e-2, 1e-3, 1e-4, 1e-5, 1e-6, 1e-7, 1e-8};
    const int nGamma = 7;

    while((c=getopt(argc,argv,"n:g:a:c:")) != -1)
        switch(c)
            {
            case 'n': numpts = atoi(optarg); break;
            case 'g': USE_GPU = atoi(optarg); break;
            case 'a': a0 = atof(optarg); break;
            case 'c': Ntests = atoi(optarg); break;
            case '?':
                    return 1;
            default:
                       abort();
            };

    bool initializeGPU = true;
    if (USE_GPU >= 0)
        {
        bool gpu = chooseGPU(USE_GPU);
        if (!gpu) return 0;
        cudaSetDevice(USE_GPU);
        }
    else
        initializeGPU = false;

    printf("vertex sigmaXY p-scan: Ncells=%i  Nsnap=%i  GPU=%i\n",
           numpts,Ntests,(int)initializeGPU);
    printf("p0:");
    for (int ip = 0; ip < nP0; ++ip)
        printf("  %.2f", p0List[ip]);
    printf("\n dgamma:");
    for (int ig = 0; ig < nGamma; ++ig)
        printf("  %.3e", dgammaList[ig]);
    printf("\n");

    FILE *csv = fopen("localTest/data/vertexSigmaXY_pScan.csv","w");
    if (!csv)
        {
        fprintf(stderr,"could not open localTest/data/vertexSigmaXY_pScan.csv (mkdir localTest/data)\n");
        return 1;
        };
    fprintf(csv,"p0,dgamma,meanAbs,meanAbsSigma,meanE\n");

    for (int ip = 0; ip < nP0; ++ip)
        {
        double p0 = p0List[ip];
        vector<double> sumAbs(nGamma, 0.0);
        double sumAbsSigma = 0.0;
        double sumE = 0.0;

        for (int snap = 0; snap < Ntests; ++snap)
            {
            shared_ptr<VertexQuadraticEnergy> avm =
                make_shared<VertexQuadraticEnergy>(numpts,a0,p0,false,false,initializeGPU);
            if (!initializeGPU)
                avm->setCPU();

            double sigmaAna = avm->getSigmaXY();
            double E0 = avm->computeEnergy();
            sumAbsSigma += fabs(sigmaAna);
            sumE += E0;

            vector<double2> v0(avm->Nvertices);
                {
                ArrayHandle<double2> h_v(avm->vertexPositions,access_location::host,access_mode::read);
                for (int i = 0; i < avm->Nvertices; ++i)
                    v0[i] = h_v.data[i];
                };
            double Lx,xy,yx,Ly;
            avm->Box->getBoxDims(Lx,xy,yx,Ly);
            double area = Lx*Ly;

            for (int ig = 0; ig < nGamma; ++ig)
                {
                double dgamma = dgammaList[ig];
                applySimpleShear(avm,v0,Lx,Ly,+dgamma);
                double Eplus = avm->computeEnergy();
                applySimpleShear(avm,v0,Lx,Ly,-dgamma);
                double Eminus = avm->computeEnergy();
                applySimpleShear(avm,v0,Lx,Ly,0.0);
                double sigmaNum = (Eplus - Eminus)/(2.0*dgamma*area);
                sumAbs[ig] += fabs(sigmaAna - sigmaNum);
                };
            };

        printf("p0=%.2f  meanE=%.6e  mean|sigma|=%.6e\n",
               p0, sumE/Ntests, sumAbsSigma/Ntests);
        printf("%12s %14s\n", "dgamma", "meanAbs");
        for (int ig = 0; ig < nGamma; ++ig)
            {
            double meanAbs = sumAbs[ig]/Ntests;
            printf("%12.3e %14.6e\n", dgammaList[ig], meanAbs);
            fprintf(csv,"%.2f,%.8e,%.8e,%.8e,%.8e\n",
                    p0, dgammaList[ig], meanAbs,
                    sumAbsSigma/Ntests, sumE/Ntests);
            };
        };

    fclose(csv);
    if (initializeGPU)
        cudaDeviceReset();
    return 0;
    };
