// Generated by Cursor. 2026-09-20.
// Random-init FD scan of VertexQuadraticEnergy::getSigmaYY vs δε at several p0.
// Physics: σ_yy = (1/A) ∂E/∂ε_y; numeric (E(+δε)−E(−δε))/(2 δε A). Topology frozen.
// Uniaxial: y → (1+ε)y, Ly → (1+ε)Ly. Mean |Δσ| over Nsnapshots random inits (no eq).
// Writes localTest/data/vertexSigmaYY_pScan.csv (p0, deps, meanAbs, meanAbsSigma, meanE).

#include "std_include.h"
#include "cuda_runtime.h"

#include "vertexQuadraticEnergy.h"
#include "periodicBoundaries.h"
#include "functions.h"

#include <fstream>

/*!
Affine uniaxial strain ε_y: y → (1+ε)y, box → [[Lx, 0], [0, (1+ε)Ly]]. No T1s.
*/
void applyUniaxialY(shared_ptr<VertexQuadraticEnergy> avm,
                    const vector<double2> &v0,
                    double Lx, double Ly, double eps)
    {
    avm->Box->setSquare(Lx, (1.0+eps)*Ly);
    ArrayHandle<double2> h_v(avm->vertexPositions,access_location::host,access_mode::overwrite);
    for (int i = 0; i < avm->Nvertices; ++i)
        {
        h_v.data[i].x = v0[i].x;
        h_v.data[i].y = (1.0+eps)*v0[i].y;
        avm->Box->putInBoxReal(h_v.data[i]);
        };
    avm->forcesUpToDate = false;
    };

int main(int argc, char*argv[])
    {
    int numpts = 4096;
    int USE_GPU = -1;
    int Ntests = 10;
    int c;
    double a0 = 1.0;
    const double p0List[] = {3.7, 3.8, 3.9};
    const int nP0 = 3;
    const double depsList[] = {1e-2, 1e-3, 1e-4, 1e-5, 1e-6, 1e-7, 1e-8};
    const int nEps = 7;

    while((c=getopt(argc,argv,"n:g:a:c:")) != -1)
        switch(c)
            {
            case 'n': numpts = atoi(optarg); break;
            case 'g': USE_GPU = atoi(optarg); break;
            case 'a': a0 = atof(optarg); break;
            case 'c': Ntests = atoi(optarg); break;
            case '?':
                    return 1;
            default:
                       abort();
            };

    bool initializeGPU = true;
    if (USE_GPU >= 0)
        {
        bool gpu = chooseGPU(USE_GPU);
        if (!gpu) return 0;
        cudaSetDevice(USE_GPU);
        }
    else
        initializeGPU = false;

    printf("vertex sigmaYY p-scan: Ncells=%i  Nsnap=%i  GPU=%i\n",
           numpts,Ntests,(int)initializeGPU);
    printf("p0:");
    for (int ip = 0; ip < nP0; ++ip)
        printf("  %.2f", p0List[ip]);
    printf("\n deps:");
    for (int ie = 0; ie < nEps; ++ie)
        printf("  %.3e", depsList[ie]);
    printf("\n");

    FILE *csv = fopen("localTest/data/vertexSigmaYY_pScan.csv","w");
    if (!csv)
        {
        fprintf(stderr,"could not open localTest/data/vertexSigmaYY_pScan.csv (mkdir localTest/data)\n");
        return 1;
        };
    fprintf(csv,"p0,deps,meanAbs,meanAbsSigma,meanE\n");

    for (int ip = 0; ip < nP0; ++ip)
        {
        double p0 = p0List[ip];
        vector<double> sumAbs(nEps, 0.0);
        double sumAbsSigma = 0.0;
        double sumE = 0.0;

        for (int snap = 0; snap < Ntests; ++snap)
            {
            shared_ptr<VertexQuadraticEnergy> avm =
                make_shared<VertexQuadraticEnergy>(numpts,a0,p0,false,false,initializeGPU);
            if (!initializeGPU)
                avm->setCPU();

            double sigmaAna = avm->getSigmaYY();
            double E0 = avm->computeEnergy();
            sumAbsSigma += fabs(sigmaAna);
            sumE += E0;

            vector<double2> v0(avm->Nvertices);
                {
                ArrayHandle<double2> h_v(avm->vertexPositions,access_location::host,access_mode::read);
                for (int i = 0; i < avm->Nvertices; ++i)
                    v0[i] = h_v.data[i];
                };
            double Lx,xy,yx,Ly;
            avm->Box->getBoxDims(Lx,xy,yx,Ly);
            double area = Lx*Ly;

            for (int ie = 0; ie < nEps; ++ie)
                {
                double deps = depsList[ie];
                applyUniaxialY(avm,v0,Lx,Ly,+deps);
                double Eplus = avm->computeEnergy();
                applyUniaxialY(avm,v0,Lx,Ly,-deps);
                double Eminus = avm->computeEnergy();
                applyUniaxialY(avm,v0,Lx,Ly,0.0);
                double sigmaNum = (Eplus - Eminus)/(2.0*deps*area);
                sumAbs[ie] += fabs(sigmaAna - sigmaNum);
                };
            };

        printf("p0=%.2f  meanE=%.6e  mean|sigmaYY|=%.6e\n",
               p0, sumE/Ntests, sumAbsSigma/Ntests);
        printf("%12s %14s\n", "deps", "meanAbs");
        for (int ie = 0; ie < nEps; ++ie)
            {
            double meanAbs = sumAbs[ie]/Ntests;
            printf("%12.3e %14.6e\n", depsList[ie], meanAbs);
            fprintf(csv,"%.2f,%.8e,%.8e,%.8e,%.8e\n",
                    p0, depsList[ie], meanAbs,
                    sumAbsSigma/Ntests, sumE/Ntests);
            };
        };

    fclose(csv);
    if (initializeGPU)
        cudaDeviceReset();
    return 0;
    };
