#!/usr/bin/env python3
"""
Generated by Cursor. 2026-09-02
Locate longest valid glassyDynamics NetCDF at matched (p0, T) under CELLGPU_SCRATCH.

Skip stubs (default min size 1 MB). Vertex idx=0; Voronoi prefers productionRuns idx=10.
T1-scan files are optional overlays at nearest T, not Voronoi-matched.
"""

from __future__ import annotations

import os
import re
from dataclasses import dataclass
from pathlib import Path

NAME = re.compile(
    r"glassyDynamics_N(?P<n>\d+)_p(?P<p0>[0-9.]+)_T(?P<T>[0-9.]+)"
    r"_waitingTime(?P<tw>\d+)_idx(?P<idx>\d+)\.nc$"
)

DEFAULT_SCRATCH = "/scratch/bbtm/cli6/glassyDynamics/data"
MIN_BYTES = 1_000_000
P0_FIRST = 3.800
T_PRIMARY = (0.016, 0.010, 0.008)
T_COLD = (0.005,)
N_DEFAULT = 4096
VORONOI_IDX_PREF = 10


def scratch_root() -> Path:
    return Path(os.environ.get("CELLGPU_SCRATCH", DEFAULT_SCRATCH))


@dataclass
class TrajFile:
    path: Path
    n: int
    p0: float
    T: float
    tw: int
    idx: int
    size: int
    tree: str


def _parse_name(path: Path, tree: str, size: int = -1) -> TrajFile | None:
    m = NAME.search(path.name)
    if not m:
        return None
    return TrajFile(
        path=path,
        n=int(m.group("n")),
        p0=float(m.group("p0")),
        T=float(m.group("T")),
        tw=int(m.group("tw")),
        idx=int(m.group("idx")),
        size=size,
        tree=tree,
    )


def _stat_size(path: Path) -> int:
    try:
        return path.stat().st_size
    except OSError:
        return 0


def _parse(path: Path, tree: str) -> TrajFile | None:
    rec = _parse_name(path, tree)
    if rec is None:
        return None
    rec.size = _stat_size(path)
    return rec


def _best(cands: list[TrajFile], prefer_idx: int | None) -> TrajFile | None:
    ok = [c for c in cands if c.size < 0 or c.size >= MIN_BYTES]
    if not ok:
        return None
    if prefer_idx is not None:
        pref = [c for c in ok if c.idx == prefer_idx]
        if pref:
            ok = pref
    return max(ok, key=lambda c: (c.tw, c.size, -c.idx))


def _best_stat(cands: list[TrajFile], prefer_idx: int | None) -> TrajFile | None:
    """Rank by waitingTime without statting every file; stat from longest down."""
    if not cands:
        return None
    pool = cands
    if prefer_idx is not None:
        pref = [c for c in cands if c.idx == prefer_idx]
        if pref:
            pool = pref
    pool = sorted(pool, key=lambda c: (c.tw, -c.idx), reverse=True)
    for rec in pool:
        rec.size = _stat_size(rec.path)
        if rec.size >= MIN_BYTES:
            return rec
    return None


def list_glassy_names(dirpath: Path, tree: str) -> list[TrajFile]:
    if not dirpath.is_dir():
        return []
    out = []
    for p in dirpath.glob("glassyDynamics_N*.nc"):
        rec = _parse_name(p, tree)
        if rec is not None:
            out.append(rec)
    return out


def list_glassy(dirpath: Path, tree: str) -> list[TrajFile]:
    if not dirpath.is_dir():
        return []
    out = []
    for p in dirpath.glob("glassyDynamics_N*.nc"):
        rec = _parse(p, tree)
        if rec is not None:
            out.append(rec)
    return out


def find_vertex(n: int, p0: float, T: float, atol: float = 1e-6) -> TrajFile | None:
    root = scratch_root() / f"N{n}" / "vertex" / f"p{p0:.3f}"
    cands = [c for c in list_glassy(root, "vertex") if abs(c.T - T) < atol and c.idx == 0]
    return _best(cands, prefer_idx=0)


def find_voronoi(n: int, p0: float, T: float, atol: float = 1e-6) -> TrajFile | None:
    root = scratch_root() / f"N{n}"
    trees = [
        ("productionRuns", root / "productionRuns" / f"p{p0:.3f}"),
        ("N4096", root / f"p{p0:.3f}"),
        ("additional", root / "additional" / f"p{p0:.3f}"),
    ]
    allc = []
    for name, d in trees:
        for c in list_glassy(d, name):
            if abs(c.T - T) < atol:
                allc.append(c)
    prod = [c for c in allc if c.tree == "productionRuns"]
    pick = _best(prod, prefer_idx=VORONOI_IDX_PREF)
    if pick is not None:
        return pick
    return _best(allc, prefer_idx=VORONOI_IDX_PREF)


def list_voronoi_best(n: int = N_DEFAULT, p0s=None) -> list[TrajFile]:
    """One longest valid traj per (p0, T). Prefer productionRuns idx=10."""
    if p0s is None:
        p0s = (3.750, 3.775, 3.800, 3.815, 3.825, 3.850)
    root = scratch_root() / f"N{n}"
    by_key: dict[tuple[float, float], list[TrajFile]] = {}
    for p0 in p0s:
        prod_d = root / "productionRuns" / f"p{p0:.3f}"
        trees = [
            ("productionRuns", prod_d),
            ("additional", root / "additional" / f"p{p0:.3f}"),
        ]
        if not prod_d.is_dir():
            trees.append(("N4096", root / f"p{p0:.3f}"))
        for name, d in trees:
            for c in list_glassy_names(d, name):
                if c.n != n:
                    continue
                by_key.setdefault((round(c.p0, 3), c.T), []).append(c)
    out = []
    for _k, cands in sorted(by_key.items()):
        prod = [c for c in cands if c.tree == "productionRuns"]
        pick = _best_stat(prod, prefer_idx=VORONOI_IDX_PREF)
        if pick is None:
            pick = _best_stat(cands, prefer_idx=VORONOI_IDX_PREF)
        if pick is not None:
            out.append(pick)
    return out


def find_t1_scan_nearest(n: int, p0: float, T_target: float) -> list[TrajFile]:
    """One longest-tw file per t1_* tag, nearest T to T_target (not a silent T substitute)."""
    root = scratch_root() / f"N{n}" / "vertex" / "t1Scan"
    rows = []
    if not root.is_dir():
        return rows
    for tagdir in sorted(root.glob("t1_*")):
        # ell_T1=0.1 production was heap-unstable; skip for this overlay.
        if tagdir.name == "t1_1e-1":
            continue
        d = tagdir / f"p{p0:.3f}"
        cands = [c for c in list_glassy(d, tagdir.name) if c.idx == 0]
        if not cands:
            continue
        nearest_T = min({c.T for c in cands}, key=lambda t: abs(t - T_target))
        at = [c for c in cands if abs(c.T - nearest_T) < 1e-12]
        best = _best(at, prefer_idx=0)
        if best is not None:
            rows.append(best)
    return rows


def first_pass_pairs(n: int = N_DEFAULT, p0: float = P0_FIRST, include_cold: bool = False):
    Ts = list(T_PRIMARY)
    if include_cold:
        Ts.extend(T_COLD)
    pairs = []
    for T in Ts:
        v = find_vertex(n, p0, T)
        o = find_voronoi(n, p0, T)
        pairs.append({"T": T, "p0": p0, "n": n, "vertex": v, "voronoi": o})
    return pairs
