#!/usr/bin/env python3
"""
Generated by Cursor. 2026-09-02
Static Voronoi vs vertex comparison at matched (p0, T), not matched tau_alpha.

q_i = P_i / sqrt(A_i). Energy: KA=KP=1, A0=1,
  <E>/N = <(A-1)^2> + <(P-p0)^2>.
Edge lengths in units with mean cell area 1. Vertex T1 cutoff default ell_T1=0.01.

Usage:
  CELLGPU_SCRATCH=... python3 plot_state_compare.py
  python3 plot_state_compare.py --dump-only
  python3 plot_state_compare.py --plot-only
"""

from __future__ import annotations

import argparse
import csv
import math
import os
import subprocess
import sys
from pathlib import Path

import numpy as np

HERE = Path(__file__).resolve().parent
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))

from find_state_files import (
    P0_FIRST,
    T_PRIMARY,
    find_t1_scan_nearest,
    first_pass_pairs,
    scratch_root,
)

ELL_T1_DEFAULT = 0.01
DQ_MATCH = 0.01
DP57_MATCH = 0.02
Q_FS = 6.80


def repo_root() -> Path:
    env = os.environ.get("CELLGPU_ROOT")
    if env:
        return Path(env)
    return HERE.parents[3]


def dump_env() -> dict:
    env = os.environ.copy()
    extras = []
    nv = os.environ.get("NVHPC_ROOT", "/opt/nvidia/hpc_sdk/Linux_x86_64/26.5")
    extras.append(str(Path(nv) / "compilers" / "lib"))
    extras.append(str(Path(nv) / "cuda" / "12.9" / "lib64"))
    home = Path.home() / "opt" / "netcdf-cxx-legacy" / "lib"
    if home.is_dir():
        extras.append(str(home))
    old = env.get("LD_LIBRARY_PATH", "")
    env["LD_LIBRARY_PATH"] = ":".join(extras + ([old] if old else []))
    return env


def dump_binary() -> Path:
    root = repo_root()
    cand = [
        root / "glassyDynamicsProject" / "stateCompareDump.out",
        root / "build-state-compare" / "glassyDynamicsProject" / "stateCompareDump.out",
    ]
    for p in cand:
        if p.is_file():
            return p
    return cand[0]


def stem(model: str, T: float, extra: str = "") -> str:
    tag = extra + f"T{T:.8f}"
    return f"{model}_{tag}"


def run_dump(model: str, nc: Path, prefix: Path, n: int, p0: float) -> None:
    exe = dump_binary()
    if not exe.is_file():
        raise FileNotFoundError(f"missing {exe}; build stateCompareDump.out first")
    prefix.parent.mkdir(parents=True, exist_ok=True)
    cmd = [
        str(exe),
        "-m",
        model,
        "-f",
        str(nc),
        "-o",
        str(prefix),
        "-n",
        str(n),
        "-p",
        f"{p0:.8g}",
        "-s",
        "0.2",
    ]
    print(" ".join(cmd), flush=True)
    subprocess.check_call(cmd, env=dump_env())


def load_col(path: Path, name: str):
    with path.open() as f:
        r = csv.DictReader(f)
        return np.array([float(row[name]) for row in r], dtype=float)


def summarize_cells(cells: Path, edges: Path, frames: Path, p0: float):
    q = load_col(cells, "q")
    z = load_col(cells, "z")
    A = load_col(cells, "A")
    P = load_col(cells, "P")
    ell = load_col(edges, "ell")
    eA = float(np.mean(load_col(frames, "eA")))
    eP = float(np.mean(load_col(frames, "eP")))
    eN = float(np.mean(load_col(frames, "eN")))
    tkin = load_col(frames, "Tkin")
    tkin = tkin[np.isfinite(tkin)]
    pz = {k: float(np.mean(z == k)) for k in range(4, 9)}
    meanq = float(np.mean(q))
    return {
        "mean_q": meanq,
        "std_q": float(np.std(q, ddof=0)),
        "mean_q_minus_p0": meanq - p0,
        "p4": pz[4],
        "p5": pz[5],
        "p6": pz[6],
        "p7": pz[7],
        "p8": pz[8],
        "p5p7": pz[5] + pz[7],
        "eA": eA,
        "eP": eP,
        "eN": eN,
        "var_A": float(np.var(A)),
        "var_P": float(np.var(P)),
        "f_ell_lt_T1": float(np.mean(ell < ELL_T1_DEFAULT)) if ell.size else math.nan,
        "median_ell": float(np.median(ell)) if ell.size else math.nan,
        "Tkin": float(np.mean(tkin)) if tkin.size else math.nan,
        "n_q": int(q.size),
        "n_ell": int(ell.size),
        "q": q,
        "z": z,
        "ell": ell,
    }


def decide(vtx, vor):
    dq = abs(vtx["mean_q"] - vor["mean_q"])
    dp57 = abs(vtx["p5p7"] - vor["p5p7"])
    pile = (vtx["f_ell_lt_T1"] + 1e-12) < 0.25 * (vor["f_ell_lt_T1"] + 1e-12)
    hexatic = vtx["p6"] - vor["p6"] > 0.03
    q_ok = dq <= DQ_MATCH
    z_ok = dp57 <= DP57_MATCH
    if q_ok and z_ok and not pile:
        return "similar_state"
    if q_ok and (not z_ok or pile or hexatic):
        return "t1_starved_or_hexatic"
    return "not_same_mechanical_state"


def dump_all(pairs, outdir: Path, t1_overlay: bool):
    jobs = []
    for row in pairs:
        T = row["T"]
        p0 = row["p0"]
        n = row["n"]
        if row["vertex"] is None:
            print(f"MISSING vertex p0={p0} T={T}")
            continue
        if row["voronoi"] is None:
            print(f"MISSING voronoi p0={p0} T={T}")
            continue
        print(
            f"T={T} vertex tw={row['vertex'].tw} {row['vertex'].path.name} "
            f"({row['vertex'].size} B) | voronoi tw={row['voronoi'].tw} idx={row['voronoi'].idx} "
            f"{row['voronoi'].tree} ({row['voronoi'].size} B)"
        )
        vp = outdir / "dumps" / stem("vertex", T)
        op = outdir / "dumps" / stem("voronoi", T)
        run_dump("vertex", row["vertex"].path, vp, n, p0)
        run_dump("voronoi", row["voronoi"].path, op, n, p0)
        jobs.append(row)
    if t1_overlay:
        Tref = T_PRIMARY[-1]
        for rec in find_t1_scan_nearest(pairs[0]["n"], pairs[0]["p0"], Tref):
            print(
                f"t1Scan overlay {rec.tree} T={rec.T} (nearest to {Tref}, not identical) tw={rec.tw}"
            )
            pref = outdir / "dumps" / f"{rec.tree}_{stem('vertex', rec.T)}"
            try:
                run_dump("vertex", rec.path, pref, rec.n, rec.p0)
            except subprocess.CalledProcessError as exc:
                print(f"t1Scan dump failed ({rec.tree}): {exc}")
    return jobs


def plot_all(pairs, outdir: Path, p0: float, t1_overlay: bool):
    import matplotlib.pyplot as plt

    rows_out = []
    data = []
    for row in pairs:
        T = row["T"]
        vp = outdir / "dumps" / (stem("vertex", T) + "_cells.csv")
        if not vp.is_file():
            print(f"skip plot T={T}: no dump")
            continue
        vtx = summarize_cells(
            outdir / "dumps" / (stem("vertex", T) + "_cells.csv"),
            outdir / "dumps" / (stem("vertex", T) + "_edges.csv"),
            outdir / "dumps" / (stem("vertex", T) + "_frames.csv"),
            p0,
        )
        vor = summarize_cells(
            outdir / "dumps" / (stem("voronoi", T) + "_cells.csv"),
            outdir / "dumps" / (stem("voronoi", T) + "_edges.csv"),
            outdir / "dumps" / (stem("voronoi", T) + "_frames.csv"),
            p0,
        )
        verdict = decide(vtx, vor)
        print(
            f"T={T}: <q>_v={vtx['mean_q']:.4f} <q>_o={vor['mean_q']:.4f} dq={abs(vtx['mean_q']-vor['mean_q']):.4f} "
            f"p5+p7 v={vtx['p5p7']:.4f} o={vor['p5p7']:.4f} "
            f"f(ell<ell_T1) v={vtx['f_ell_lt_T1']:.4g} o={vor['f_ell_lt_T1']:.4g} -> {verdict}"
        )
        data.append((T, vtx, vor, verdict))
        for model, s in (("vertex", vtx), ("voronoi", vor)):
            rec = {
                "p0": p0,
                "T": T,
                "model": model,
                "verdict": verdict,
                **{k: s[k] for k in s if k not in ("q", "z", "ell")},
            }
            rows_out.append(rec)

    csv_path = outdir / "means_vs_T.csv"
    if rows_out:
        keys = [k for k in rows_out[0] if k != "verdict"] + ["verdict"]
        with csv_path.open("w", newline="") as f:
            w = csv.DictWriter(f, fieldnames=keys)
            w.writeheader()
            for r in rows_out:
                w.writerow({k: r[k] for k in keys})
        print(f"wrote {csv_path}")

    if not data:
        return

    fig, axes = plt.subplots(2, 2, figsize=(10.5, 8.2))
    axq, axz, axl, axe = axes.ravel()
    colors = plt.cm.viridis(np.linspace(0.15, 0.85, len(data)))
    zvals = np.arange(4, 9)

    for i, (T, vtx, vor, verdict) in enumerate(data):
        c = colors[i]
        lab = rf"$T={T:g}$"
        qbins = np.linspace(
            min(vtx["q"].min(), vor["q"].min()),
            max(vtx["q"].max(), vor["q"].max()),
            48,
        )
        axq.hist(vor["q"], bins=qbins, density=True, histtype="step", color=c, ls="--", label=lab + " Voronoi")
        axq.hist(vtx["q"], bins=qbins, density=True, histtype="step", color=c, ls="-", label=lab + " vertex")
        w = 0.18
        axz.bar(zvals - 0.2 + i * 0.02, [vor["p4"], vor["p5"], vor["p6"], vor["p7"], vor["p8"]], width=w, color=c, alpha=0.35)
        axz.bar(zvals + 0.2 + i * 0.02, [vtx["p4"], vtx["p5"], vtx["p6"], vtx["p7"], vtx["p8"]], width=w, color=c, fill=False, edgecolor=c)
        lbins = np.logspace(-4, 0.5, 60)
        axl.hist(vor["ell"], bins=lbins, density=True, histtype="step", color=c, ls="--")
        axl.hist(vtx["ell"], bins=lbins, density=True, histtype="step", color=c, ls="-")

    axl.axvline(ELL_T1_DEFAULT, color="k", ls=":", lw=1.2, label=r"$\ell_{T1}=0.01$")
    if t1_overlay:
        Tref = T_PRIMARY[-1]
        for rec in find_t1_scan_nearest(4096, p0, Tref):
            ep = outdir / "dumps" / f"{rec.tree}_{stem('vertex', rec.T)}_edges.csv"
            if not ep.is_file():
                continue
            ell = load_col(ep, "ell")
            axl.hist(ell, bins=np.logspace(-4, 0.5, 60), density=True, histtype="step", ls="-.", alpha=0.8, label=f"{rec.tree} T={rec.T:g}")

    Ts = [d[0] for d in data]
    axe.plot(Ts, [d[2]["eN"] for d in data], "s--", color="0.3", label=r"Voronoi $\langle E\rangle/N$")
    axe.plot(Ts, [d[1]["eN"] for d in data], "o-", color="0.3", label=r"vertex $\langle E\rangle/N$")
    axe.plot(Ts, [d[2]["eA"] for d in data], "s--", color="#4c78a8", label=r"$\langle(A-1)^2\rangle$")
    axe.plot(Ts, [d[1]["eA"] for d in data], "o-", color="#4c78a8")
    axe.plot(Ts, [d[2]["eP"] for d in data], "s--", color="#e45756", label=r"$\langle(P-p_0)^2\rangle$")
    axe.plot(Ts, [d[1]["eP"] for d in data], "o-", color="#e45756")

    axq.set_xlabel(r"$q=P/\sqrt{A}$")
    axq.set_ylabel(r"$P(q)$")
    axq.legend(fontsize=7, ncol=2)
    axz.set_xlabel(r"$z$")
    axz.set_ylabel(r"$P(z)$")
    axz.set_xticks(zvals)
    axl.set_xlabel(r"$\ell$")
    axl.set_ylabel(r"$P(\ell)$")
    axl.set_xscale("log")
    axl.set_yscale("log")
    axl.legend(fontsize=7)
    axe.set_xlabel(r"$T$")
    axe.set_ylabel("energy pieces")
    axe.set_xscale("log")
    axe.legend(fontsize=7)
    fig.suptitle(rf"$p_0={p0:.3f}$, $N=4096$, matched $(p_0,T)$; CRSISF $q={Q_FS}$ not used here")
    fig.tight_layout()
    png = outdir / "state_compare_p3.800.png"
    fig.savefig(png, dpi=160)
    print(f"wrote {png}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--n", type=int, default=4096)
    ap.add_argument("--p0", type=float, default=P0_FIRST)
    ap.add_argument("--include-cold", action="store_true")
    ap.add_argument("--dump-only", action="store_true")
    ap.add_argument("--plot-only", action="store_true")
    ap.add_argument("--no-t1-overlay", action="store_true")
    args = ap.parse_args()
    outdir = HERE
    t1 = not args.no_t1_overlay
    pairs = first_pass_pairs(args.n, args.p0, include_cold=args.include_cold)
    print(f"scratch={scratch_root()}")
    for row in pairs:
        v = row["vertex"]
        o = row["voronoi"]
        print(
            f"  T={row['T']}: vertex={'OK tw='+str(v.tw) if v else 'MISSING'} "
            f"voronoi={'OK tw='+str(o.tw)+' idx='+str(o.idx)+' '+o.tree if o else 'MISSING'}"
        )
    if not args.plot_only:
        dump_all(pairs, outdir, t1)
    if not args.dump_only:
        plot_all(pairs, outdir, args.p0, t1)


if __name__ == "__main__":
    main()
