// Generated by Cursor. 2026-09-02
// Dump static geometry from vertexTrajectoryDatabase or nvtModelDatabase.
// q_i = P_i / sqrt(A_i) (same as Simple2DCell::reportq). Units: mean cell area 1.
// Energy pieces: KA=KP=1, A0=1, E/N = <(A-1)^2> + <(P-p0)^2>.
// Vertex edges: unique 3-valent mesh edges, box minDist.
// Voronoi edges: unique Voronoi polygon sides (dual of Delaunay i<j).

#include "std_include.h"
#include "cuda_runtime.h"
#include "vertexQuadraticEnergy.h"
#include "voronoiQuadraticEnergy.h"
#include "vertexTrajectoryDatabase.h"
#include "nvtModelDatabase.h"
#include <cmath>
#include <fstream>
#include <iomanip>
#include <string>

static double skipFrac = 0.2;
// -d nKeep: last n records (log-spaced late frames). -1 = unset, use skipFrac.
static int nKeep = -1;
// "all" writes cells+edges+frames; "frames" writes only *_frames.csv (q-map harvest).
static bool writeCellsEdges = true;

static int firstRec(int nrec)
    {
    int rec0;
    if (nKeep > 0)
        rec0 = nrec - nKeep;
    else
        rec0 = (int)floor(skipFrac * nrec);
    if (rec0 < 0)
        rec0 = 0;
    if (nrec > 0 && rec0 >= nrec)
        rec0 = nrec - 1;
    return rec0;
    }

static void writeFrameHeader(ofstream &f)
    {
    f << "rec,time,nCells,mean_q,std_q,mean_q_minus_p0,mean_A,var_A,mean_P,var_P,"
         "eA,eP,eN,p4,p5,p6,p7,p8,p5p7,Tkin\n";
    }

static void dumpVertex(const string &fn, int numpts, double p0, const string &prefix)
    {
    int Nvert = 2 * numpts;
    bool initializeGPU = false;
    bool gpu = chooseGPU(-1);
    (void)gpu;
    shared_ptr<VertexQuadraticEnergy> avm =
        make_shared<VertexQuadraticEnergy>(numpts, 1.0, p0, true, false, initializeGPU);
    avm->setCPU();
    avm->setCellPreferencesUniform(1.0, p0);

    vertexTrajectoryDatabase traj(Nvert, fn, NcFile::ReadOnly);
    int nrec = traj.GetNumRecs();
    int rec0 = firstRec(nrec);
    printf("vertex %s nrec=%d rec0=%d nKeep=%d skipFrac=%g\n",
           fn.c_str(), nrec, rec0, nKeep, skipFrac);

    ofstream fcells;
    ofstream fedges;
    ofstream fframes(prefix + "_frames.csv");
    if (writeCellsEdges)
        {
        fcells.open(prefix + "_cells.csv");
        fedges.open(prefix + "_edges.csv");
        fcells << "rec,time,q,z,A,P\n";
        fedges << "rec,time,ell\n";
        fcells << std::setprecision(10);
        fedges << std::setprecision(10);
        }
    writeFrameHeader(fframes);
    fframes << std::setprecision(10);

    for (int rec = rec0; rec < nrec; ++rec)
        {
        traj.readState(avm, rec, true);
        double t = avm->currentTime;
        ArrayHandle<double2> h_AP(avm->returnAreaPeri(), access_location::host, access_mode::read);
        ArrayHandle<double2> h_APP(avm->returnAreaPeriPreferences(), access_location::host, access_mode::read);
        ArrayHandle<int> h_zn(avm->cellVertexNum, access_location::host, access_mode::read);

        double sumq = 0, sumq2 = 0, sumA = 0, sumA2 = 0, sumP = 0, sumP2 = 0, eA = 0, eP = 0;
        int cz[16] = {0};
        int Nc = avm->Ncells;
        for (int i = 0; i < Nc; ++i)
            {
            double A = h_AP.data[i].x;
            double P = h_AP.data[i].y;
            double q = P / sqrt(A);
            int z = h_zn.data[i];
            if (writeCellsEdges)
                fcells << rec << "," << t << "," << q << "," << z << "," << A << "," << P << "\n";
            sumq += q;
            sumq2 += q * q;
            sumA += A;
            sumA2 += A * A;
            sumP += P;
            sumP2 += P * P;
            double A0 = h_APP.data[i].x;
            double P0 = h_APP.data[i].y;
            eA += (A - A0) * (A - A0);
            eP += (P - P0) * (P - P0);
            if (z >= 0 && z < 16)
                cz[z] += 1;
            }
        double inv = 1.0 / (double)Nc;
        double meanq = sumq * inv;
        double varq = sumq2 * inv - meanq * meanq;
        if (varq < 0)
            varq = 0;
        double meanA = sumA * inv;
        double varA = sumA2 * inv - meanA * meanA;
        double meanP = sumP * inv;
        double varP = sumP2 * inv - meanP * meanP;
        eA *= inv;
        eP *= inv;
        fframes << rec << "," << t << "," << Nc << "," << meanq << "," << sqrt(varq) << ","
                << (meanq - p0) << "," << meanA << "," << varA << "," << meanP << "," << varP << ","
                << eA << "," << eP << "," << (eA + eP) << ","
                << cz[4] * inv << "," << cz[5] * inv << "," << cz[6] * inv << ","
                << cz[7] * inv << "," << cz[8] * inv << "," << (cz[5] + cz[7]) * inv << ",nan\n";

        if (writeCellsEdges)
            {
            ArrayHandle<double2> h_v(avm->vertexPositions, access_location::host, access_mode::read);
            ArrayHandle<int> h_vn(avm->vertexNeighbors, access_location::host, access_mode::read);
            int Nv = avm->Nvertices;
            for (int v1 = 0; v1 < Nv; ++v1)
                {
                for (int k = 0; k < 3; ++k)
                    {
                    int v2 = h_vn.data[3 * v1 + k];
                    if (v2 <= v1)
                        continue;
                    double2 edge;
                    avm->Box->minDist(h_v.data[v1], h_v.data[v2], edge);
                    double ell = sqrt(edge.x * edge.x + edge.y * edge.y);
                    fedges << rec << "," << t << "," << ell << "\n";
                    }
                }
            }
        }
    }

static void dumpVoronoi(const string &fn, int numpts, double p0, const string &prefix)
    {
    bool initializeGPU = false;
    bool gpu = chooseGPU(-1);
    (void)gpu;
    shared_ptr<VoronoiQuadraticEnergy> vor =
        make_shared<VoronoiQuadraticEnergy>(numpts, 1.0, p0, true, initializeGPU);
    vor->setCPU();
    vor->setCellPreferencesUniform(1.0, p0);

    nvtModelDatabase traj(numpts, fn, NcFile::ReadOnly);
    int nrec = traj.GetNumRecs();
    int rec0 = firstRec(nrec);
    printf("voronoi %s nrec=%d rec0=%d nKeep=%d skipFrac=%g\n",
           fn.c_str(), nrec, rec0, nKeep, skipFrac);

    ofstream fcells;
    ofstream fedges;
    ofstream fframes(prefix + "_frames.csv");
    if (writeCellsEdges)
        {
        fcells.open(prefix + "_cells.csv");
        fedges.open(prefix + "_edges.csv");
        fcells << "rec,time,q,z,A,P\n";
        fedges << "rec,time,ell\n";
        fcells << std::setprecision(10);
        fedges << std::setprecision(10);
        }
    writeFrameHeader(fframes);
    fframes << std::setprecision(10);

    for (int rec = rec0; rec < nrec; ++rec)
        {
        traj.readState(vor, rec, true);
        double t = vor->currentTime;
        ArrayHandle<double2> h_AP(vor->returnAreaPeri(), access_location::host, access_mode::read);
        ArrayHandle<double2> h_APP(vor->returnAreaPeriPreferences(), access_location::host, access_mode::read);
        ArrayHandle<int> h_zn(vor->neighborNum, access_location::host, access_mode::read);
        ArrayHandle<double2> h_vel(vor->returnVelocities(), access_location::host, access_mode::read);

        double sumq = 0, sumq2 = 0, sumA = 0, sumA2 = 0, sumP = 0, sumP2 = 0, eA = 0, eP = 0;
        int cz[16] = {0};
        int Nc = vor->Ncells;
        for (int i = 0; i < Nc; ++i)
            {
            double A = h_AP.data[i].x;
            double P = h_AP.data[i].y;
            double q = P / sqrt(A);
            int z = h_zn.data[i];
            if (writeCellsEdges)
                fcells << rec << "," << t << "," << q << "," << z << "," << A << "," << P << "\n";
            sumq += q;
            sumq2 += q * q;
            sumA += A;
            sumA2 += A * A;
            sumP += P;
            sumP2 += P * P;
            double A0 = h_APP.data[i].x;
            double P0 = h_APP.data[i].y;
            eA += (A - A0) * (A - A0);
            eP += (P - P0) * (P - P0);
            if (z >= 0 && z < 16)
                cz[z] += 1;
            }
        double inv = 1.0 / (double)Nc;
        double meanq = sumq * inv;
        double varq = sumq2 * inv - meanq * meanq;
        if (varq < 0)
            varq = 0;
        double meanA = sumA * inv;
        double varA = sumA2 * inv - meanA * meanA;
        double meanP = sumP * inv;
        double varP = sumP2 * inv - meanP * meanP;
        eA *= inv;
        eP *= inv;
        double v2 = 0.0;
        for (int i = 0; i < Nc; ++i)
            v2 += h_vel.data[i].x * h_vel.data[i].x + h_vel.data[i].y * h_vel.data[i].y;
        // 2D, mass 1: <vx^2+vy^2> = 2 T  =>  Tkin = sum v^2 / (2 N)
        double Tkin = v2 / (2.0 * (double)Nc);

        fframes << rec << "," << t << "," << Nc << "," << meanq << "," << sqrt(varq) << ","
                << (meanq - p0) << "," << meanA << "," << varA << "," << meanP << "," << varP << ","
                << eA << "," << eP << "," << (eA + eP) << ","
                << cz[4] * inv << "," << cz[5] * inv << "," << cz[6] * inv << ","
                << cz[7] * inv << "," << cz[8] * inv << "," << (cz[5] + cz[7]) * inv << ","
                << Tkin << "\n";

        if (writeCellsEdges)
            {
            ArrayHandle<int> h_n(vor->neighbors, access_location::host, access_mode::read);
            ArrayHandle<double2> h_p(vor->cellPositions, access_location::host, access_mode::read);
            // Voronoi vertex = circumcenter of (i, nlast, nnext); unique edges for Delaunay i<j.
            for (int i = 0; i < Nc; ++i)
                {
                int neigh = h_zn.data[i];
                if (neigh < 3)
                    continue;
                vector<double2> voro(neigh);
                double2 pi = h_p.data[i];
                double2 rij, rik, circumcent;
                int nlast = h_n.data[vor->n_idx(neigh - 1, i)];
                vor->Box->minDist(h_p.data[nlast], pi, rij);
                for (int nn = 0; nn < neigh; ++nn)
                    {
                    int nnext = h_n.data[vor->n_idx(nn, i)];
                    vor->Box->minDist(h_p.data[nnext], pi, rik);
                    Circumcenter(rij, rik, circumcent);
                    voro[nn] = circumcent;
                    rij = rik;
                    }
                for (int nn = 0; nn < neigh; ++nn)
                    {
                    int j = h_n.data[vor->n_idx(nn, i)];
                    if (j <= i)
                        continue;
                    int nn1 = (nn + 1) % neigh;
                    double dx = voro[nn].x - voro[nn1].x;
                    double dy = voro[nn].y - voro[nn1].y;
                    double ell = sqrt(dx * dx + dy * dy);
                    fedges << rec << "," << t << "," << ell << "\n";
                    }
                }
            }
        }
    }

int main(int argc, char *argv[])
    {
    string model = "vertex";
    string fn;
    string prefix = "stateDump";
    int numpts = 4096;
    double p0 = 3.8;
    int c;
    while ((c = getopt(argc, argv, "m:f:o:n:p:s:k:d:")) != -1)
        switch (c)
            {
            case 'm': model = optarg; break;
            case 'f': fn = optarg; break;
            case 'o': prefix = optarg; break;
            case 'n': numpts = atoi(optarg); break;
            case 'p': p0 = atof(optarg); break;
            case 's': skipFrac = atof(optarg); break;
            case 'd': nKeep = atoi(optarg); break;
            case 'k':
                if (string(optarg) == "frames")
                    writeCellsEdges = false;
                else if (string(optarg) == "all")
                    writeCellsEdges = true;
                else
                    {
                    printf("unknown -k %s (use frames|all)\n", optarg);
                    return 1;
                    }
                break;
            case '?':
                return 1;
            default:
                abort();
            }
    if (fn.empty())
        {
        printf("usage: stateCompareDump.out -m vertex|voronoi -f file.nc -o prefix -n N -p p0 [-s skipFrac] [-d nKeep] [-k frames|all]\n");
        return 1;
        }
    if (model == "vertex")
        dumpVertex(fn, numpts, p0, prefix);
    else if (model == "voronoi")
        dumpVoronoi(fn, numpts, p0, prefix);
    else
        {
        printf("unknown model %s\n", model.c_str());
        return 1;
        }
    return 0;
    }
