#!/usr/bin/env python3
"""
Generated by Cursor. 2026-09-22.
Replica mean and std of vertex-position CRSISF for the KWW HMC fit.

Physics:
  F_s^CR(q, dt) = (1/N_v) sum_j J_0(q |dr_j^CR|), tracer = vertex position.
  q is the vertex-position S(q) first-peak value used by plot_vertex_position_fs.py.
  Per (p0, T), interpolate idx=0..9 onto a common geomspace dt grid, then
  take the arithmetic mean and sample standard deviation (ddof=1).
  SEM = std / sqrt(n_idx). dt is simulation time; Fs is dimensionless.

Writes vertexModel_vertexPositionFs/Fs_combined_mean.csv.

Usage:
  python3 combine_vertex_position_fs.py
  python3 combine_vertex_position_fs.py --q 6.7
"""

from __future__ import annotations

import argparse
import math

import numpy as np
import pandas as pd

from combine_vertex_production_fs import STD_FLOOR, curves_for_state, mean_std_curve
from plot_vertex_position_fs import (
    OUTDIR,
    Q_FILE as VERTEX_Q_FILE,
    VERTEX_FS_NAME,
    median_q_peak,
    scratch_fs,
)
from plot_vertex_production_fs import load_state_points, match_p0
from measure_and_plot_tau_alpha import read_two_values


def resolve_q(q: float | None) -> float:
    if q is not None:
        return q
    if VERTEX_Q_FILE.is_file():
        text = VERTEX_Q_FILE.read_text().strip()
        if text:
            return float(text)
    peak = median_q_peak()
    if peak is None:
        raise SystemExit("no --q and no sq_first_peak.csv")
    return peak


def load_by_key(root, q_use: float):
    from collections import defaultdict

    by_key = defaultdict(list)
    nfile = 0
    if not root.is_dir():
        return by_key
    for nc in sorted(root.glob("p*/timeVertexCRSISF_*.nc")):
        m = VERTEX_FS_NAME.search(nc.name)
        if not m:
            continue
        if abs(float(m.group("k")) - q_use) > 0.02:
            continue
        p0 = match_p0(float(m.group("p0")))
        if p0 is None:
            continue
        T = float(m.group("T"))
        dt, fs = read_two_values(nc)
        by_key[(p0, T)].append((dt, fs))
        nfile += 1
    print(f"loaded {nfile} vertex CRSISF files from {root} at q={q_use:g}")
    return by_key


def main() -> None:
    parser = argparse.ArgumentParser(description="Combine vertex-position CRSISF replicas.")
    parser.add_argument("--q", type=float, default=None)
    parser.add_argument("--std-floor", type=float, default=STD_FLOOR)
    args = parser.parse_args()
    q_use = resolve_q(args.q)

    OUTDIR.mkdir(parents=True, exist_ok=True)
    by_key = load_by_key(scratch_fs(), q_use)
    expected = load_state_points()
    rows: list[dict] = []
    missing: list[tuple[float, float]] = []

    for p0_raw, T in expected:
        p0 = match_p0(p0_raw)
        if p0 is None:
            continue
        curves = curves_for_state(by_key, p0, T)
        if not curves:
            missing.append((p0, T))
            continue
        tgrid, mean, std, n_idx = mean_std_curve(curves)
        if tgrid.size == 0:
            missing.append((p0, T))
            continue
        std = np.maximum(std, args.std_floor)
        sem = std / math.sqrt(n_idx)
        for t, y, s, e in zip(tgrid, mean, std, sem):
            rows.append(
                {
                    "p0": p0,
                    "T": T,
                    "q": q_use,
                    "t": float(t),
                    "Fs_mean": float(y),
                    "Fs_std": float(s),
                    "Fs_sem": float(e),
                    "n_idx": n_idx,
                }
            )

    df = pd.DataFrame(rows)
    out = OUTDIR / "Fs_combined_mean.csv"
    df.to_csv(out, index=False)
    n_state = df.groupby(["p0", "T"]).ngroups if not df.empty else 0
    print(f"wrote {out} ({len(df)} rows, {n_state} state points, q={q_use:g})")
    if missing:
        print(f"missing {len(missing)} (p0, T):")
        for p0, T in missing:
            print(f"  p0={p0:.3f} T={T:.8f}")
        raise SystemExit(1)


if __name__ == "__main__":
    main()
