#!/usr/bin/env python3
"""
Generated by Cursor. 2026-09-14.
Joint Bayesian KWW (stretched-exponential) fit of production CRSISF tails.

Physics:
  mu(t) = A * exp(-(t / tau)^beta), baseline B=0.
  tau is the KWW scale: mu(tau) = A/e (not the CRSISF 1/e crossing unless A=1).
  Likelihood: Fs_mean(t) ~ Normal(mu(t), sigma) with sigma = Fs_std or Fs_sem.
  Tail window in Fs space: fs_min <= Fs_mean <= fs_max.

Sharing (--share):
  global:       one A, one beta, one tau per (p0, T)
  per_p0:       one (A, beta) per p0, one tau per (p0, T)
  independent:  one (A, beta, tau) per (p0, T)

Usage:
  python3 fit_vertex_fs_kww_hmc.py --share global
  PYTENSOR_FLAGS='cxx=,mode=NUMBA' python3 fit_vertex_fs_kww_hmc.py --share per_p0
"""

from __future__ import annotations

import argparse
import os
from pathlib import Path

# Conda g++ 15 vs glibc headers fails PyTensor C compile on this host.
os.environ.setdefault("PYTENSOR_FLAGS", "cxx=,mode=NUMBA")

import numpy as np
import pandas as pd

from measure_and_plot_tau_alpha import INV_E, tau_alpha_one_over_e
from plot_vertex_production_fs import OUTDIR, P0_ORDER

HERE = Path(__file__).resolve().parent
CSV_COMBINED = OUTDIR / "Fs_combined_mean.csv"


def load_fs_max_table(path: Path) -> dict[tuple[float, float], float]:
    """Optional CSV with columns p0, T, fs_max."""
    df = pd.read_csv(path, comment="#")
    out: dict[tuple[float, float], float] = {}
    for r in df.itertuples(index=False):
        out[(float(r.p0), float(r.T))] = float(r.fs_max)
    return out


def match_state_T(T_table: float, T_curve: float) -> bool:
    return abs(T_table - T_curve) / max(abs(T_curve), 1e-30) < 1e-5


def fs_max_for_row(
    p0: float,
    T: float,
    default: float,
    table: dict[tuple[float, float], float] | None,
) -> float:
    if not table:
        return default
    if (p0, T) in table:
        return table[(p0, T)]
    for (p, Tt), v in table.items():
        if abs(p - p0) < 1e-4 and match_state_T(Tt, T):
            return v
    return default


def tail_after_plateau(g: pd.DataFrame, fs_min: float, fs_max: float) -> pd.DataFrame:
    """Keep the late Fs window, not the early cage-relative dip that also crosses fs_max."""
    g = g.sort_values("t")
    y = g["Fs_mean"].to_numpy(float)
    above = y > fs_max
    start = int(np.where(above)[0][-1] + 1) if np.any(above) else 0
    late = g.iloc[start:]
    return late[(late["Fs_mean"] >= fs_min) & (late["Fs_mean"] <= fs_max)]


def one_over_e_from_curve(g: pd.DataFrame) -> tuple[float, bool]:
    dt = g["t"].to_numpy(float)
    fs = g["Fs_mean"].to_numpy(float)
    order = np.argsort(dt)
    return tau_alpha_one_over_e(dt[order], fs[order])


def build_model(share: str, t_all, y_all, y_std, state_id, p0_id, M, n_p0):
    import pymc as pm

    with pm.Model() as model:
        logtau = pm.Normal("logtau", mu=np.log(10.0), sigma=5.0, shape=M)
        tau = pm.Deterministic("tau", pm.math.exp(logtau))
        if share == "global":
            qbeta = pm.Normal("qbeta", mu=0.0, sigma=1.0)
            qA = pm.Normal("qA", mu=0.0, sigma=1.0)
            beta = pm.Deterministic("beta", pm.math.sigmoid(qbeta))
            A = pm.Deterministic("A", pm.math.sigmoid(qA))
            tau_i = tau[state_id]
            mu_i = A * pm.math.exp(-((t_all / tau_i) ** beta))
        elif share == "per_p0":
            qbeta = pm.Normal("qbeta", mu=0.0, sigma=1.0, shape=n_p0)
            qA = pm.Normal("qA", mu=0.0, sigma=1.0, shape=n_p0)
            beta = pm.Deterministic("beta", pm.math.sigmoid(qbeta))
            A = pm.Deterministic("A", pm.math.sigmoid(qA))
            gid = p0_id[state_id]
            tau_i = tau[state_id]
            mu_i = A[gid] * pm.math.exp(-((t_all / tau_i) ** beta[gid]))
        elif share == "independent":
            qbeta = pm.Normal("qbeta", mu=0.0, sigma=1.0, shape=M)
            qA = pm.Normal("qA", mu=0.0, sigma=1.0, shape=M)
            beta = pm.Deterministic("beta", pm.math.sigmoid(qbeta))
            A = pm.Deterministic("A", pm.math.sigmoid(qA))
            tau_i = tau[state_id]
            mu_i = A[state_id] * pm.math.exp(-((t_all / tau_i) ** beta[state_id]))
        else:
            raise ValueError(f"unknown --share {share}")
        pm.Normal("y_obs", mu=mu_i, sigma=y_std, observed=y_all)
    return model


def main() -> None:
    parser = argparse.ArgumentParser(description="PyMC KWW fit of CRSISF tails.")
    parser.add_argument("--share", choices=("global", "per_p0", "independent"), default="global")
    parser.add_argument("--sigma", choices=("std", "sem"), default="std")
    parser.add_argument("--fs-min", type=float, default=0.001)
    parser.add_argument("--fs-max", type=float, default=0.45)
    parser.add_argument("--fs-max-csv", type=Path, default=None)
    parser.add_argument("--draws", type=int, default=2000)
    parser.add_argument("--tune", type=int, default=2000)
    parser.add_argument("--chains", type=int, default=4)
    parser.add_argument("--target-accept", type=float, default=0.95)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--input", type=Path, default=CSV_COMBINED)
    args = parser.parse_args()

    import arviz as az
    import pymc as pm

    OUTDIR.mkdir(parents=True, exist_ok=True)
    df = pd.read_csv(args.input)
    df = df[np.isfinite(df["t"]) & np.isfinite(df["Fs_mean"])].copy()
    sigma_col = "Fs_sem" if args.sigma == "sem" else "Fs_std"

    fs_max_table = load_fs_max_table(args.fs_max_csv) if args.fs_max_csv else None
    df["fs_max"] = [
        fs_max_for_row(float(p0), float(T), args.fs_max, fs_max_table)
        for p0, T in zip(df["p0"], df["T"])
    ]
    pieces = []
    for (p0, T), g in df.groupby(["p0", "T"], sort=False):
        fs_max = float(g["fs_max"].iloc[0])
        piece = tail_after_plateau(g, args.fs_min, fs_max)
        if len(piece) >= 5:
            pieces.append(piece)
        else:
            print(f"skip p0={p0} T={T}: {len(piece)} tail points")
    tail = pd.concat(pieces, ignore_index=True) if pieces else pd.DataFrame()
    if tail.empty:
        raise SystemExit("no tail points; relax --fs-min / --fs-max")

    # Stable state order: P0_ORDER then increasing T.
    states = (
        tail[["p0", "T"]]
        .drop_duplicates()
        .assign(_p0rank=lambda x: x["p0"].map({p: i for i, p in enumerate(P0_ORDER)}))
        .sort_values(["_p0rank", "T"])
        .drop(columns="_p0rank")
        .reset_index(drop=True)
    )
    M = len(states)
    state_key = list(zip(states["p0"].astype(float), states["T"].astype(float)))
    key_to_id = {k: i for i, k in enumerate(state_key)}
    p0_list = [p for p in P0_ORDER if any(abs(k[0] - p) < 1e-4 for k in state_key)]
    p0_to_gid = {p: i for i, p in enumerate(p0_list)}
    n_p0 = len(p0_list)

    tail["state_id"] = [
        key_to_id[(float(p0), float(T))] for p0, T in zip(tail["p0"], tail["T"])
    ]
    t_all = tail["t"].to_numpy(float)
    y_all = tail["Fs_mean"].to_numpy(float)
    y_std = np.maximum(tail[sigma_col].to_numpy(float), 1e-4)
    state_id = tail["state_id"].to_numpy(int)
    p0_id_states = np.array(
        [p0_to_gid[min(p0_list, key=lambda p: abs(p - k[0]))] for k in state_key],
        dtype=int,
    )

    print(
        f"tail points {len(tail)} / {len(df)}; M={M} states; "
        f"share={args.share}; sigma={args.sigma}"
    )

    model = build_model(
        args.share, t_all, y_all, y_std, state_id, p0_id_states, M, n_p0
    )
    with model:
        sample_kw = dict(
            draws=args.draws,
            tune=args.tune,
            chains=args.chains,
            target_accept=args.target_accept,
            random_seed=args.seed,
        )
        try:
            idata = pm.sample(**sample_kw)
            idata = pm.compute_log_likelihood(idata)
        except TypeError:
            idata = pm.sample(**sample_kw)

    tau_da = idata.posterior["tau"]
    tau_mean = tau_da.mean(dim=("chain", "draw")).values
    tau_std = tau_da.std(dim=("chain", "draw")).values
    A_da = idata.posterior["A"]
    beta_da = idata.posterior["beta"]
    A_mean = A_da.mean(dim=("chain", "draw")).values
    A_std = A_da.std(dim=("chain", "draw")).values
    beta_mean = beta_da.mean(dim=("chain", "draw")).values
    beta_std = beta_da.std(dim=("chain", "draw")).values

    full = df.copy()
    rows = []
    for i, (p0, T) in enumerate(state_key):
        if args.share == "global":
            Ai, Asi = float(A_mean), float(A_std)
            bi, bsi = float(beta_mean), float(beta_std)
        elif args.share == "per_p0":
            gid = int(p0_id_states[i])
            Ai, Asi = float(A_mean[gid]), float(A_std[gid])
            bi, bsi = float(beta_mean[gid]), float(beta_std[gid])
        else:
            Ai, Asi = float(A_mean[i]), float(A_std[i])
            bi, bsi = float(beta_mean[i]), float(beta_std[i])
        g = full[(np.isclose(full["p0"], p0)) & (np.isclose(full["T"], T))]
        tau_1e, crossed = one_over_e_from_curve(g)
        n_tail = int((tail["state_id"] == i).sum())
        rows.append(
            {
                "p0": p0,
                "T": T,
                "share": args.share,
                "sigma": args.sigma,
                "fs_min": args.fs_min,
                "fs_max": fs_max_for_row(p0, T, args.fs_max, fs_max_table),
                "n_tail": n_tail,
                "A": Ai,
                "A_std": Asi,
                "beta": bi,
                "beta_std": bsi,
                "tau_kww": float(tau_mean[i]),
                "tau_kww_std": float(tau_std[i]),
                "tau_1e": tau_1e,
                "crossed_1e": int(crossed),
            }
        )

    tau_csv = OUTDIR / f"kww_{args.share}_tau.csv"
    pd.DataFrame(rows).to_csv(tau_csv, index=False)
    print(f"wrote {tau_csv}")

    idata_path = OUTDIR / f"kww_{args.share}_idata.nc"
    idata.to_netcdf(idata_path)
    print(f"wrote {idata_path}")

    loo_path = OUTDIR / f"kww_{args.share}_loo.txt"
    try:
        loo = az.loo(idata)
        waic = az.waic(idata)
        text = f"{loo}\n\n{waic}\n"
        loo_path.write_text(text)
        print(f"wrote {loo_path}")
        print(text)
    except Exception as exc:
        loo_path.write_text(f"LOO/WAIC failed: {exc}\n")
        print(f"LOO/WAIC failed: {exc}")

    print(
        f"A ~ {np.mean(A_mean):.4f}, beta ~ {np.mean(beta_mean):.4f}, "
        f"tau_kww range {np.nanmin(tau_mean):.4g} .. {np.nanmax(tau_mean):.4g}"
    )


if __name__ == "__main__":
    main()
