#!/usr/bin/env python3
"""
Generated by Cursor. 2026-08-25.
Per-curve vertex tau_alpha for third-batch T grid from CRSISF 1/e.

Physics:
  F_s^CR(q, dt) with q = 6.80. tau_alpha is the first 1/e crossing.
  Black markers are the batch-3 targets tau_k used as -t.

Usage:
  python3 measure_and_plot_tau_alpha_batch3.py
"""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib.pyplot as plt
from matplotlib.cm import ScalarMappable
from matplotlib.colors import Normalize

from measure_and_plot_tau_alpha import collect_rows, scratch_root, write_csv
from measure_and_plot_tau_alpha_batch2 import filter_batch2, load_batch2_points

HERE = Path(__file__).resolve().parent
STATE_CSV = HERE / "vertexModel_tauAlpha_batch3" / "state_points.csv"


def plot_per_p0(rows, outdir: Path):
    outdir.mkdir(parents=True, exist_ok=True)
    p0s = sorted({r["p0"] for r in rows})
    cmap = plt.get_cmap("coolwarm_r")
    for p0 in p0s:
        sub = [r for r in rows if abs(r["p0"] - p0) < 1e-6]
        fig, ax = plt.subplots(figsize=(7.2, 5.0))
        ks = []
        for r in sub:
            tb = r["tauBlock"]
            if tb and tb == tb and tb > 0:
                ks.append(r["waitingTime"] / tb)
        kmax = max(ks) if ks else 14.0
        norm = Normalize(vmin=0.0, vmax=max(kmax, 1.0))
        for r in sub:
            if not r["crossed"] or not (r["tauAlpha"] == r["tauAlpha"]):
                continue
            tb = r["tauBlock"]
            kval = r["waitingTime"] / tb if tb and tb == tb and tb > 0 else 0.0
            ax.scatter(
                r["T"],
                r["tauAlpha"],
                c=[cmap(norm(kval))],
                s=28,
                zorder=3,
                edgecolors="none",
            )
        seen_T = set()
        for r in sub:
            T = r["T"]
            est = r["tauAlphaEst"]
            if T in seen_T or est is None or not (est == est):
                continue
            seen_T.add(T)
            ax.scatter(
                T,
                est,
                c="black",
                s=55,
                marker="o",
                zorder=4,
                label=r"target $\tau_\alpha$" if len(seen_T) == 1 else None,
            )
        ax.set_xscale("log")
        ax.set_yscale("log")
        ax.set_xlabel(r"$T$")
        ax.set_ylabel(r"$\tau_\alpha$ (CRSISF $1/e$)")
        ax.set_title(rf"vertex model batch 3, $N=4096$, $p_0={p0:.3f}$")
        sm = ScalarMappable(norm=norm, cmap=cmap)
        sm.set_array([])
        cbar = fig.colorbar(sm, ax=ax)
        cbar.set_label(r"$t_w / \tau_{\mathrm{block}}$ (red short, blue long)")
        ax.legend(loc="best", frameon=False)
        fig.tight_layout()
        out = outdir / f"vertexModel_tauAlpha_batch3_vs_T_p{p0:.3f}.png"
        fig.savefig(out, dpi=150)
        plt.close(fig)
        print(f"wrote {out}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("-n", type=int, default=4096)
    ap.add_argument("--outdir", type=Path, default=None)
    ap.add_argument("--state-csv", type=Path, default=STATE_CSV)
    args = ap.parse_args()
    pts = load_batch2_points(args.state_csv)
    rows = filter_batch2(collect_rows(args.n), pts)
    here = Path(__file__).resolve().parent
    outdir = args.outdir or (here / "vertexModel_tauAlpha_batch3")
    scratch = scratch_root(args.n)
    write_csv(rows, scratch / "tauAlpha_vertex_batch3_per_curve.csv")
    write_csv(rows, outdir / "vertexModel_tauAlpha_batch3_per_curve.csv")
    n_cross = sum(1 for r in rows if r["crossed"])
    print(f"batch3 FS curves: {len(rows)}, crossed 1/e: {n_cross}")
    if rows:
        plot_per_p0(rows, outdir)


if __name__ == "__main__":
    main()
