#!/usr/bin/env python3
"""
Generated by Cursor. 2026-08-24.
Per-curve vertex-model tau_alpha from cage-relative SISF 1/e crossing.

Physics:
  F_s^CR(q, dt) stored as (dt, Fs) in timeCRSISF NetCDF (q = 6.80 unless -k).
  tau_alpha is the first lag where a straight line between consecutive samples
  crosses 1/e. No extrapolation if Fs never drops through 1/e.

Plots (one per p0): tau_alpha vs T, scatter colored red (short t_w) to blue
(long t_w), Voronoi estimate as black circles.

Repo output (figures + CSV) defaults to
  glassyDynamicsProject/analyseScripts/vertexTauAlpha/vertexModel_tauAlpha_test/

Usage:
  python3 measure_and_plot_tau_alpha.py
  CELLGPU_SCRATCH=... python3 measure_and_plot_tau_alpha.py --n 4096
"""

from __future__ import annotations

import argparse
import csv
import math
import os
import re
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.colors import Normalize
from matplotlib.cm import ScalarMappable

INV_E = math.e ** -1
# Default CRSISF wavevector; skip leftover k=6.283 files if both exist.
Q_DEFAULT = 6.80

# Same (p0, T, tauAlphaEst) list as local/submit/submitVertexTauAlpha.sh
STATE_POINTS = [
    (3.750, 0.025, 13.32),
    (3.750, 0.020, 25.46),
    (3.750, 0.016, 65.05),
    (3.750, 0.014, 175.2),
    (3.750, 0.013, 243.7),
    (3.750, 0.012, 622.3),
    (3.750, 0.0115, 913.2),
    (3.750, 0.0105, 2655),
    (3.750, 0.010, 4716),
    (3.750, 0.0093, 10694),
    (3.775, 0.020, 12.91),
    (3.775, 0.016, 23.32),
    (3.775, 0.012, 63.68),
    (3.775, 0.010, 134.5),
    (3.775, 0.009, 215.1),
    (3.775, 0.008, 530.8),
    (3.775, 0.007, 1380),
    (3.775, 0.0063, 2856),
    (3.775, 0.0056, 7228),
    (3.775, 0.0054, 8666),
    (3.800, 0.016, 13.33),
    (3.800, 0.010, 38.71),
    (3.800, 0.008, 61.58),
    (3.800, 0.0063, 113.7),
    (3.800, 0.005, 225.1),
    (3.800, 0.00385, 550.2),
    (3.800, 0.0031, 1423),
    (3.800, 0.0028, 2572),
    (3.800, 0.0025, 4591),
    (3.800, 0.0022, 8307),
    (3.815, 0.010, 17.39),
    (3.815, 0.0063, 40.53),
    (3.815, 0.005, 63.19),
    (3.815, 0.00385, 123.0),
    (3.815, 0.0028, 245.2),
    (3.815, 0.0022, 473.6),
    (3.815, 0.0015, 1783),
    (3.815, 0.0012, 4555),
    (3.815, 0.001, 9590),
    (3.825, 0.016, 8.18),
    (3.825, 0.010, 18.62),
    (3.825, 0.0063, 38.93),
    (3.825, 0.00385, 85.99),
    (3.825, 0.0022, 191.1),
    (3.825, 0.0015, 477.8),
    (3.825, 0.001, 1166),
    (3.825, 0.00067, 4460),
    (3.850, 0.010, 8.87),
    (3.850, 0.005, 23.07),
    (3.850, 0.0025, 52.14),
    (3.850, 0.001, 184.8),
    (3.850, 0.00067, 318.2),
    (3.850, 0.0005, 470.0),
    (3.850, 0.00033, 928.9),
    (3.850, 0.00018, 2305),
    (3.850, 0.00014, 3734),
    (3.850, 0.000077, 9930),
]

FS_NAME = re.compile(
    r"timeCRSISF_N(?P<n>\d+)_p(?P<p0>[0-9.]+)_T(?P<T>[0-9.eE+-]+)"
    r"_k(?P<k>[0-9.]+)_waitingTime(?P<tw>[0-9.]+)_idx(?P<idx>\d+)\.nc$"
)


def read_two_values(path: Path):
    """Load (dt, Fs) from twoValuesDatabase NetCDF."""
    try:
        from netCDF4 import Dataset

        with Dataset(path, "r") as ds:
            dt = np.array(ds.variables["firstValue"][:], dtype=float)
            fs = np.array(ds.variables["secondValue"][:], dtype=float)
        return dt, fs
    except Exception:
        pass
    from scipy.io import netcdf_file

    with netcdf_file(path, "r", mmap=False) as ds:
        dt = np.array(ds.variables["firstValue"].data, dtype=float)
        fs = np.array(ds.variables["secondValue"].data, dtype=float)
    return dt, fs


def tau_alpha_one_over_e(dt, fs):
    """First 1/e crossing by linear interpolation in lag time. nan if none."""
    if dt.size < 2:
        return math.nan, False
    for i in range(len(fs) - 1):
        f0, f1 = fs[i], fs[i + 1]
        if f0 >= INV_E > f1:
            denom = f0 - f1
            if denom == 0:
                return float(dt[i]), True
            tau = dt[i] + (dt[i + 1] - dt[i]) * (f0 - INV_E) / denom
            return float(tau), True
    return math.nan, False


def scratch_root(n: int) -> Path:
    env = os.environ.get("CELLGPU_SCRATCH", "/scratch/bbtm/cli6/glassyDynamics/data")
    return Path(env) / f"N{n}" / "vertex" / "tauAlphaData"


def collect_rows(n: int):
    root = scratch_root(n)
    rows = []
    if not root.is_dir():
        print(f"no FS dir {root}")
        return rows
    for nc in sorted(root.glob("p*/timeCRSISF_*.nc")):
        m = FS_NAME.search(nc.name)
        if not m:
            continue
        p0 = float(m.group("p0"))
        T = float(m.group("T"))
        tw = float(m.group("tw"))
        qk = float(m.group("k"))
        if abs(qk - Q_DEFAULT) > 0.02:
            continue
        dt, fs = read_two_values(nc)
        tau, crossed = tau_alpha_one_over_e(dt, fs)
        est = None
        for sp0, sT, stau in STATE_POINTS:
            if abs(sp0 - p0) < 1e-6 and abs(sT - T) / max(sT, 1e-30) < 1e-5:
                est = stau
                break
        tau_block = max(1000.0, est) if est is not None else math.nan
        rows.append(
            {
                "p0": p0,
                "T": T,
                "waitingTime": tw,
                "tauAlphaEst": est if est is not None else math.nan,
                "tauBlock": tau_block,
                "tauAlpha": tau,
                "crossed": int(crossed),
                "n": int(m.group("n")),
                "idx": int(m.group("idx")),
                "file": str(nc),
            }
        )
    return rows


def write_csv(rows, path: Path):
    path.parent.mkdir(parents=True, exist_ok=True)
    fields = ["p0", "T", "waitingTime", "tauAlphaEst", "tauBlock", "tauAlpha", "crossed", "n", "idx"]
    with path.open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fields, extrasaction="ignore")
        w.writeheader()
        for r in rows:
            out = dict(r)
            for k in ("p0", "T", "waitingTime", "tauAlphaEst", "tauBlock", "tauAlpha"):
                v = out[k]
                out[k] = "" if v is None or (isinstance(v, float) and math.isnan(v)) else v
            w.writerow(out)
    print(f"wrote {path} ({len(rows)} rows)")


def plot_per_p0(rows, outdir: Path):
    outdir.mkdir(parents=True, exist_ok=True)
    p0s = sorted({r["p0"] for r in rows})
    # Color by waiting index k = tw / tau_block so short vs long is comparable across T.
    cmap = plt.get_cmap("coolwarm_r")  # red short -> blue long
    for p0 in p0s:
        sub = [r for r in rows if abs(r["p0"] - p0) < 1e-6]
        fig, ax = plt.subplots(figsize=(7.2, 5.0))
        ks = []
        for r in sub:
            tb = r["tauBlock"]
            if tb and tb == tb and tb > 0:
                ks.append(r["waitingTime"] / tb)
        kmax = max(ks) if ks else 14.0
        norm = Normalize(vmin=0.0, vmax=max(kmax, 1.0))
        for r in sub:
            if not r["crossed"] or not (r["tauAlpha"] == r["tauAlpha"]):
                continue
            tb = r["tauBlock"]
            kval = r["waitingTime"] / tb if tb and tb == tb and tb > 0 else 0.0
            ax.scatter(
                r["T"],
                r["tauAlpha"],
                c=[cmap(norm(kval))],
                s=28,
                zorder=3,
                edgecolors="none",
            )
        # Voronoi estimates once per T
        seen_T = set()
        for r in sub:
            T = r["T"]
            est = r["tauAlphaEst"]
            if T in seen_T or est is None or not (est == est):
                continue
            seen_T.add(T)
            ax.scatter(
                T,
                est,
                c="black",
                s=55,
                marker="o",
                zorder=4,
                label="Voronoi estimate" if len(seen_T) == 1 else None,
            )
        ax.set_xscale("log")
        ax.set_yscale("log")
        ax.set_xlabel(r"$T$")
        ax.set_ylabel(r"$\tau_\alpha$ (CRSISF $1/e$)")
        ax.set_title(rf"vertex model $N=4096$, $p_0={p0:.3f}$")
        sm = ScalarMappable(norm=norm, cmap=cmap)
        sm.set_array([])
        cbar = fig.colorbar(sm, ax=ax)
        cbar.set_label(r"$t_w / \tau_{\mathrm{block}}$ (red short, blue long)")
        ax.legend(loc="best", frameon=False)
        fig.tight_layout()
        out = outdir / f"vertexModel_tauAlpha_test_vs_T_p{p0:.3f}.png"
        fig.savefig(out, dpi=150)
        plt.close(fig)
        print(f"wrote {out}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("-n", type=int, default=4096)
    ap.add_argument(
        "--outdir",
        type=Path,
        default=None,
        help="figures and CSV; default: vertexModel_tauAlpha_test/ next to this script",
    )
    args = ap.parse_args()
    rows = collect_rows(args.n)
    here = Path(__file__).resolve().parent
    outdir = args.outdir or (here / "vertexModel_tauAlpha_test")
    scratch = scratch_root(args.n)
    write_csv(rows, scratch / "tauAlpha_vertex_per_curve.csv")
    write_csv(rows, outdir / "vertexModel_tauAlpha_test_per_curve.csv")
    plot_per_p0(rows, outdir)


if __name__ == "__main__":
    main()
