#!/usr/bin/env python3
"""
Generated by Cursor. 2026-09-09.
2x3 p0 panels: vertex vs Voronoi <P>(T) and <q>(T), plus vertex P(hat P) Gaussianity.

Physics (KA=KP=1, mean cell area A0=1, T=kT):
  q_i = P_i / sqrt(A_i)
  E/N = <(A-1)^2> + <(P-p0)^2>
  hat P = (P - <P>) / sigma_P  compared to N(0,1)
  <P>, <q> from longest-tw frame averages in the q-map CSVs.
  Gaussian histograms pool the last 8 log-spaced frames in statDist dumps.

Usage:
  python3 glassyDynamicsProject/analyseScripts/vertexTauAlpha/plot_stat_compare_panels.py
"""

from __future__ import annotations

import csv
import math
from collections import defaultdict
from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt
from matplotlib.cm import ScalarMappable
from matplotlib.colors import LogNorm

HERE = Path(__file__).resolve().parent
QMAP = HERE / "vertexModel_qMap"
STAT = HERE / "vertexModel_statDist"
DUMPS = STAT / "dumps"
P0_ORDER = (3.750, 3.775, 3.800, 3.815, 3.825, 3.850)
N_KEEP = 8

FS_TITLE = 17
FS_LABEL = 16
FS_TICK = 14
FS_CBAR = 15
FS_LEGEND = 11


def match_p0(p0: float) -> float | None:
    m = min(P0_ORDER, key=lambda p: abs(p - p0))
    if abs(m - p0) > 1e-4:
        return None
    return m


def load_mean_csv(path: Path) -> dict[float, list[tuple[float, float, float]]]:
    """p0 -> list of (T, mean_P, mean_q), sorted by T."""
    by: dict[float, list[tuple[float, float, float]]] = {p: [] for p in P0_ORDER}
    with path.open() as f:
        for r in csv.DictReader(f):
            p0 = match_p0(float(r["p0"]))
            if p0 is None:
                continue
            T = float(r["T"])
            mean_P = float(r["mean_P"])
            mean_q = float(r["mean_q"])
            if not all(math.isfinite(x) and x > 0 for x in (T, mean_P, mean_q)):
                continue
            by[p0].append((T, mean_P, mean_q))
    for p in P0_ORDER:
        by[p].sort(key=lambda z: z[0])
    return by


def parse_dump_cells(path: Path):
    # vertex_p3.750_T0.15079370_cells.csv
    name = path.name
    if not name.startswith("vertex_") or not name.endswith("_cells.csv"):
        return None
    body = name[len("vertex_") : -len("_cells.csv")]
    if not body.startswith("p") or "_T" not in body:
        return None
    ppart, tpart = body.split("_T", 1)
    try:
        p0 = match_p0(float(ppart[1:]))
        T = float(tpart)
    except ValueError:
        return None
    if p0 is None or not math.isfinite(T) or T <= 0:
        return None
    return p0, T


def load_P(path: Path) -> np.ndarray:
    with path.open() as f:
        r = csv.DictReader(f)
        return np.array([float(row["P"]) for row in r], dtype=float)


def standardize(x: np.ndarray) -> np.ndarray:
    m = float(np.mean(x))
    s = float(np.std(x, ddof=0))
    if s <= 0:
        return np.zeros_like(x)
    return (x - m) / s


def norm_pdf(x: np.ndarray) -> np.ndarray:
    return np.exp(-0.5 * x * x) / math.sqrt(2.0 * math.pi)


def _combined_axes(fig_w: float = 13.6, fig_h: float = 8.0, cbar: bool = False):
    fig = plt.figure(figsize=(fig_w, fig_h))
    ncols = 4 if cbar else 3
    width_ratios = [1.0, 1.0, 1.0] + ([0.055] if cbar else [])
    gs = fig.add_gridspec(
        2,
        ncols,
        width_ratios=width_ratios,
        left=0.07,
        right=0.94 if cbar else 0.98,
        top=0.95,
        bottom=0.09,
        wspace=0.26,
        hspace=0.24,
    )
    axes = []
    for i, p0 in enumerate(P0_ORDER):
        row, col = divmod(i, 3)
        ax = fig.add_subplot(gs[row, col])
        ax.set_title(rf"$p_0={p0:.3f}$", fontsize=FS_TITLE, pad=4)
        ax.tick_params(labelsize=FS_TICK)
        axes.append(ax)
    cax = fig.add_subplot(gs[:, 3]) if cbar else None
    return fig, axes, cax


def plot_mean_vs_T(vertex, voronoi, ykey: str, ylabel: str, outpath: Path):
    yi = 1 if ykey == "P" else 2
    fig, axes, _ = _combined_axes(cbar=False)
    for i, p0 in enumerate(P0_ORDER):
        ax = axes[i]
        row, col = divmod(i, 3)
        vv = vertex[p0]
        oo = voronoi[p0]
        if vv:
            ax.plot(
                [z[0] for z in vv],
                [z[yi] for z in vv],
                "o-",
                color="C0",
                ms=4,
                lw=1.2,
                label="vertex",
            )
        if oo:
            ax.plot(
                [z[0] for z in oo],
                [z[yi] for z in oo],
                "s--",
                color="C1",
                ms=4,
                lw=1.2,
                mfc="none",
                label="Voronoi",
            )
        ax.axhline(p0, color="0.5", ls=":", lw=1.0, zorder=0)
        ax.set_xscale("log")
        if row == 1:
            ax.set_xlabel(r"$T$", fontsize=FS_LABEL)
        if col == 0:
            ax.set_ylabel(ylabel, fontsize=FS_LABEL)
        if i == 0:
            ax.legend(loc="best", frameon=False, fontsize=FS_LEGEND)
    fig.savefig(outpath, dpi=150)
    plt.close(fig)
    print(f"wrote {outpath}")


def collect_vertex_P():
    by = defaultdict(list)
    for p in sorted(DUMPS.glob("vertex_*_cells.csv")):
        parts = parse_dump_cells(p)
        if parts is None:
            continue
        p0, T = parts
        P = load_P(p)
        P = P[np.isfinite(P)]
        if P.size == 0:
            continue
        by[p0].append((T, P))
    for p0 in by:
        by[p0].sort(key=lambda z: -z[0])
    return by


def plot_gaussian(by_p0, outpath: Path):
    Ts = [T for p0 in P0_ORDER for T, _ in by_p0.get(p0, [])]
    if not Ts:
        raise SystemExit(f"no vertex *_cells.csv under {DUMPS}")
    tmin, tmax = min(Ts), max(Ts)
    if tmax <= tmin:
        tmax = tmin * 1.01
    cmap = plt.get_cmap("coolwarm")
    tnorm = LogNorm(vmin=tmin, vmax=tmax)
    fig, axes, cax = _combined_axes(cbar=True)
    xg = np.linspace(-4.5, 4.5, 400)
    yg = norm_pdf(xg)
    bins_z = np.linspace(-4.5, 4.5, 49)
    for i, p0 in enumerate(P0_ORDER):
        ax = axes[i]
        row, col = divmod(i, 3)
        ax.plot(xg, yg, color="k", lw=1.4, zorder=5, label=r"$\mathcal{N}(0,1)$")
        for T, P in by_p0.get(p0, []):
            Ph = standardize(P)
            ax.hist(
                Ph,
                bins=bins_z,
                density=True,
                histtype="step",
                color=cmap(tnorm(T)),
                lw=1.0,
            )
        ax.set_xlim(-4.5, 4.5)
        if row == 1:
            ax.set_xlabel(r"$\hat P=(P-\langle P\rangle)/\sigma_P$", fontsize=FS_LABEL)
        if col == 0:
            ax.set_ylabel(r"$P(\hat P)$", fontsize=FS_LABEL)
        if i == 0:
            ax.legend(loc="upper right", frameon=False, fontsize=FS_LEGEND)
    sm = ScalarMappable(norm=tnorm, cmap=cmap)
    sm.set_array([])
    cb = fig.colorbar(sm, cax=cax)
    cb.set_label(r"$T$ (hot red, cold blue)", fontsize=FS_CBAR)
    cb.ax.tick_params(labelsize=FS_TICK)
    fig.savefig(outpath, dpi=150)
    plt.close(fig)
    print(f"wrote {outpath}")


def main():
    vpath = QMAP / "vertex_q_vs_T.csv"
    opath = QMAP / "voronoi_q_vs_T.csv"
    if not vpath.is_file() or not opath.is_file():
        raise SystemExit(f"missing {vpath.name} or {opath.name}; run plot_q_map.py first")
    vertex = load_mean_csv(vpath)
    voronoi = load_mean_csv(opath)
    STAT.mkdir(parents=True, exist_ok=True)
    plot_mean_vs_T(
        vertex,
        voronoi,
        "P",
        r"$\langle P\rangle$",
        STAT / "mean_P_vs_T_all_p0.png",
    )
    plot_mean_vs_T(
        vertex,
        voronoi,
        "q",
        r"$\langle q\rangle$",
        STAT / "mean_q_vs_T_all_p0.png",
    )
    plot_gaussian(collect_vertex_P(), STAT / "vertex_P_gaussian_all_p0.png")


if __name__ == "__main__":
    main()
