#!/usr/bin/env python3
"""
Generated by Cursor. 2026-09-08.
tau_alpha vs l_T1, one series per T, one figure per p0.

Physics:
  T1 fires when edge length < l_T1 (mean cell area 1). tau_alpha is the
  longest-tw CRSISF 1/e of cell centroids at q=6.80. Color is T: red hot,
  blue cold (log T). Uses t1Scan rows only (same recommended T grid);
  default l_T1=0.01 scouting T do not match that grid.

Usage:
  python3 glassyDynamicsProject/analyseScripts/vertexTauAlpha/plot_vertex_t1_tau_vs_lth.py
"""

from __future__ import annotations

import csv
import math
from collections import defaultdict
from pathlib import Path

import matplotlib.pyplot as plt
from matplotlib.cm import ScalarMappable
from matplotlib.colors import LogNorm

HERE = Path(__file__).resolve().parent
OUTDIR = HERE / "vertexModel_t1Scan"
P0 = 3.800
P0_ORDER = (3.750, 3.775, 3.800, 3.815, 3.825, 3.850)
N = 4096


def csv_for_p0(p0: float) -> Path:
    tagged = OUTDIR / f"vertex_t1_tau_vs_T_p{p0:.3f}.csv"
    if tagged.is_file():
        return tagged
    if abs(p0 - P0) < 1e-6:
        return OUTDIR / "vertex_t1_tau_vs_T.csv"
    return tagged


def load_t1scan(path: Path, p0: float):
    rows = []
    with path.open() as f:
        for r in csv.DictReader(f):
            if r["source"] != "t1Scan":
                continue
            if abs(float(r["p0"]) - p0) > 1e-4:
                continue
            t1 = r["t1"].strip()
            if not t1:
                continue
            tau = float(r["tauAlpha"])
            if not (math.isfinite(tau) and tau > 0):
                continue
            rows.append({"t1": float(t1), "T": float(r["T"]), "tauAlpha": tau})
    return rows


def plot_one(rows, p0: float, path: Path):
    by_T = defaultdict(list)
    for r in rows:
        by_T[r["T"]].append(r)
    Ts = sorted(by_T, reverse=True)
    cmap = plt.get_cmap("coolwarm")
    norm = LogNorm(vmin=min(Ts), vmax=max(Ts))

    fig, ax = plt.subplots(figsize=(6.8, 5.0))
    for T in Ts:
        sub = sorted(by_T[T], key=lambda r: r["t1"])
        ax.plot(
            [r["t1"] for r in sub],
            [r["tauAlpha"] for r in sub],
            color=cmap(norm(T)),
            marker="o",
            markersize=5,
            lw=1.2,
        )
    ax.set_xscale("log")
    ax.set_yscale("log")
    ax.set_xlabel(r"$\ell_{T1}$")
    ax.set_ylabel(r"$\tau_\alpha$ (CRSISF $1/e$)")
    ax.set_title(rf"$N={N}$, $p_0={p0:.3f}$")
    sm = ScalarMappable(norm=norm, cmap=cmap)
    sm.set_array([])
    cbar = fig.colorbar(sm, ax=ax)
    cbar.set_label(r"$T$ (red hot, blue cold)")
    fig.tight_layout()
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, dpi=150)
    plt.close(fig)
    print(f"wrote {path} ({len(Ts)} T, {len(rows)} points)")


def main():
    n_ok = 0
    for p0 in P0_ORDER:
        csv_path = csv_for_p0(p0)
        if not csv_path.is_file():
            print(f"skip p0={p0:.3f}: no {csv_path.name}")
            continue
        rows = load_t1scan(csv_path, p0)
        if not rows:
            print(f"skip p0={p0:.3f}: no t1Scan rows in {csv_path.name}")
            continue
        tag = f"p{p0:.3f}"
        plot_one(rows, p0, OUTDIR / f"vertex_t1_tau_vs_lth_{tag}.png")
        if abs(p0 - P0) < 1e-6:
            plot_one(rows, p0, OUTDIR / "vertex_t1_tau_vs_lth.png")
        n_ok += 1
    if n_ok == 0:
        raise SystemExit("no t1Scan rows for any p0")


if __name__ == "__main__":
    main()
