#!/usr/bin/env python3
"""
Generated by Cursor. 2026-09-21.
Replica-mean isotropic tension Sigma of vertex production runs.

Physics:
  Sigma = (sigma_xx + sigma_yy) / 2, with
    sigma_xx = (1/A_box) dE/d eps_x = -sum F_x x_rel / A_box
    sigma_yy = (1/A_box) dE/d eps_y = -sum F_y y_rel / A_box
  from VertexQuadraticEnergy (uniaxial virials). Positive Sigma means
  extension raises E (tension). Reduced units: A0=1, KA=KP=1, kT=T.

  Driver vertexProductionSigmaIso writes last nKeep=10 log-spaced frames
  of idx=0..9 as (t, Sigma), nKeep frames per complete replica in idx order.
  Per replica: mean of those nKeep frames. Per (p0,T): mean and sample
  std over replicas.

Usage:
  python3 plot_vertex_production_sigma_iso.py
  CELLGPU_SCRATCH=... python3 plot_vertex_production_sigma_iso.py
"""

from __future__ import annotations

import csv
import math
import os
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

HERE = Path(__file__).resolve().parent
OUTDIR = HERE / "vertexModel_productionSigmaIso"
CSV_STATES = HERE / "vertexModel_tauAlpha_final" / "production_state_points.csv"
CSV_FILL = HERE / "vertexModel_productionKwwFill" / "state_points.csv"
CSV_OUT = OUTDIR / "production_sigmaIso_mean.csv"
FIG_OUT = OUTDIR / "production_sigmaIso_vs_T.png"
P0_ORDER = (3.750, 3.775, 3.800, 3.815, 3.825, 3.850)
N = 4096
NKEEP = 10
IDX_MAX = 9

FS_TITLE = 17
FS_LABEL = 16
FS_TICK = 14
FS_LEGEND = 12


def scratch_prod() -> Path:
    env = os.environ.get("CELLGPU_SCRATCH")
    root = Path(env) if env else Path("/scratch/bbtm/cli6/glassyDynamics/data")
    return root / f"N{N}" / "vertex" / "productionRuns"


def sigma_iso_path(p0: float, T: float) -> Path:
    return scratch_prod() / "sigmaIso" / f"sigmaIso_N{N}_p{p0:.4f}_T{T:.8f}.nc"


def read_two_values(path: Path):
    try:
        from netCDF4 import Dataset

        with Dataset(path, "r") as ds:
            a = np.array(ds.variables["firstValue"][:], dtype=float)
            b = np.array(ds.variables["secondValue"][:], dtype=float)
        return a, b
    except Exception:
        pass
    from scipy.io import netcdf_file

    with netcdf_file(path, "r", mmap=False) as ds:
        a = np.array(ds.variables["firstValue"].data, dtype=float)
        b = np.array(ds.variables["secondValue"].data, dtype=float)
    return a, b


def load_states() -> list[dict]:
    """Production + fill (p0,T,tauAlphaEst,batch)."""
    rows: list[dict] = []
    for path in (CSV_STATES, CSV_FILL):
        if not path.is_file():
            continue
        with path.open() as f:
            lines = (ln for ln in f if ln.strip() and not ln.lstrip().startswith("#"))
            for r in csv.DictReader(lines):
                p0 = float(r["p0"])
                T = float(r["T"])
                est = float(r["tauAlphaEst"])
                batch = r.get("batch", "fill")
                dup = any(
                    abs(p0 - z["p0"]) < 1e-4
                    and abs(T - z["T"]) / max(abs(T), 1e-30) < 1e-5
                    for z in rows
                )
                if dup:
                    continue
                rows.append(
                    {
                        "p0": p0,
                        "T": T,
                        "tauAlphaEst": est,
                        "tauBlock": max(1000.0, est),
                        "batch": batch,
                    }
                )
    rows.sort(
        key=lambda z: (
            P0_ORDER.index(min(P0_ORDER, key=lambda p: abs(p - z["p0"]))),
            -z["T"],
        )
    )
    return rows


def replica_means(sig: np.ndarray, nkeep: int = NKEEP) -> np.ndarray:
    """Mean Sigma per replica: nkeep consecutive frames, idx order."""
    n = int(sig.size)
    n_rep = n // nkeep
    if n_rep == 0:
        return np.array([], dtype=float)
    used = n_rep * nkeep
    if used != n:
        print(f"warn: {n} frames not a multiple of nKeep={nkeep}; using first {used}")
    block = sig[:used].reshape(n_rep, nkeep)
    return np.mean(block, axis=1)


def geom_mean_anchor(Ts: np.ndarray, ys: np.ndarray) -> tuple[float, float] | None:
    mask = (Ts > 0) & (ys > 0) & np.isfinite(Ts) & np.isfinite(ys)
    if np.count_nonzero(mask) == 0:
        return None
    return float(np.exp(np.mean(np.log(Ts[mask])))), float(
        np.exp(np.mean(np.log(ys[mask])))
    )


def main() -> None:
    OUTDIR.mkdir(parents=True, exist_ok=True)
    states = load_states()
    print(f"state points={len(states)}  scratch={scratch_prod()}")
    csv_rows = []
    plot_pts: list[tuple[float, float, float, float]] = []
    n_miss = 0
    n_nonpos = 0
    for st in states:
        p0, T = st["p0"], st["T"]
        path = sigma_iso_path(p0, T)
        if not path.is_file():
            n_miss += 1
            mean_s = float("nan")
            std_s = float("nan")
            n_ok = 0
            n_samp = 0
        else:
            try:
                _t, sig = read_two_values(path)
            except Exception as e:
                print(f"read fail {path}: {e}")
                n_miss += 1
                mean_s = float("nan")
                std_s = float("nan")
                n_ok = 0
                n_samp = 0
            else:
                means = replica_means(sig)
                n_ok = int(means.size)
                n_samp = int(min(sig.size, n_ok * NKEEP))
                if n_ok == 0:
                    n_miss += 1
                    mean_s = float("nan")
                    std_s = float("nan")
                else:
                    mean_s = float(np.mean(means))
                    std_s = float(np.std(means, ddof=1)) if n_ok > 1 else 0.0
        csv_rows.append(
            {
                "p0": f"{p0:.3f}",
                "T": f"{T:.8g}",
                "batch": st["batch"],
                "tauAlphaEst": f"{st['tauAlphaEst']:.8g}",
                "tauBlock": f"{st['tauBlock']:.8g}",
                "nReplica": n_ok,
                "nSamp": n_samp,
                "sigmaIso_mean": f"{mean_s:.8g}" if math.isfinite(mean_s) else "",
                "sigmaIso_std": f"{std_s:.8g}" if math.isfinite(std_s) else "",
            }
        )
        if math.isfinite(mean_s) and mean_s > 0:
            plot_pts.append((p0, T, mean_s, std_s))
        elif math.isfinite(mean_s):
            n_nonpos += 1
            print(f"non-positive Sigma at p0={p0:.3f} T={T:.8g}: {mean_s:.6g}")

    with CSV_OUT.open("w", newline="") as f:
        w = csv.DictWriter(
            f,
            fieldnames=[
                "p0",
                "T",
                "batch",
                "tauAlphaEst",
                "tauBlock",
                "nReplica",
                "nSamp",
                "sigmaIso_mean",
                "sigmaIso_std",
            ],
        )
        w.writeheader()
        w.writerows(csv_rows)
    print(f"wrote {CSV_OUT} ({len(csv_rows)} rows, {n_miss} missing, {n_nonpos} non-positive)")

    fig, ax = plt.subplots(figsize=(7.2, 5.6))
    ax.tick_params(labelsize=FS_TICK)
    # Same p0 colors as the scouting sigma(T) overlay: low p0 red, high p0 blue.
    cmap = plt.get_cmap("coolwarm_r")
    p0_colors = cmap(np.linspace(0.05, 0.95, len(P0_ORDER)))
    T_all = []
    y_all = []
    for i, p0 in enumerate(P0_ORDER):
        pts = [(T, y, e) for pp, T, y, e in plot_pts if abs(pp - p0) < 1e-4]
        if not pts:
            continue
        pts.sort(key=lambda z: z[0])
        Ts = np.array([z[0] for z in pts])
        ys = np.array([z[1] for z in pts])
        es = np.array([z[2] for z in pts])
        color = p0_colors[i]
        ax.errorbar(
            Ts,
            ys,
            yerr=es,
            fmt="none",
            ecolor=color,
            elinewidth=0.8,
            capsize=2,
            alpha=0.7,
            zorder=1,
        )
        ax.scatter(
            Ts,
            ys,
            c=[color],
            s=32,
            zorder=2,
            edgecolors="0.2",
            linewidths=0.4,
            label=rf"$p_0={p0:.3f}$",
        )
        T_all.extend(Ts.tolist())
        y_all.extend(ys.tolist())

    T_all = np.array(T_all, dtype=float)
    y_all = np.array(y_all, dtype=float)
    if T_all.size > 0:
        T_med = float(np.median(T_all))
        cold = (T_all < T_med) & (y_all > 0)
        hot = (T_all > T_med) & (y_all > 0)
        Tmin, Tmax = float(T_all.min()), float(T_all.max())
        Tg = np.logspace(math.log10(Tmin), math.log10(Tmax), 80)
        a_cold = geom_mean_anchor(T_all[cold], y_all[cold])
        a_hot = geom_mean_anchor(T_all[hot], y_all[hot])
        if a_cold is not None:
            T0, Y0 = a_cold
            ax.plot(
                Tg,
                Y0 * (Tg / T0) ** 1.0,
                "k--",
                lw=1.2,
                zorder=0,
                label=r"$\Sigma\propto T$ (low $T$)",
            )
        if a_hot is not None:
            T0, Y0 = a_hot
            ax.plot(
                Tg,
                Y0 * (Tg / T0) ** 0.5,
                color="0.35",
                ls="--",
                lw=1.2,
                zorder=0,
                label=r"$\Sigma\propto T^{1/2}$ (high $T$)",
            )

    ax.set_xscale("log")
    ax.set_yscale("log")
    ax.set_xlabel(r"$T$", fontsize=FS_LABEL)
    ax.set_ylabel(r"$\Sigma$", fontsize=FS_LABEL)
    ax.set_title(
        r"Production $\Sigma=(\sigma_{xx}+\sigma_{yy})/2$ (last 10 frames, idx=0..9)",
        fontsize=FS_TITLE,
    )
    ax.legend(fontsize=FS_LEGEND, loc="best", frameon=False)
    fig.tight_layout()
    fig.savefig(FIG_OUT, dpi=200)
    fig.savefig(FIG_OUT.with_suffix(".pdf"))
    plt.close(fig)
    print(f"wrote {FIG_OUT}")


if __name__ == "__main__":
    main()
