#!/usr/bin/env python3
"""
Generated by Cursor. 2026-09-23.
Overlay every production CRSISF replica at p0=3.825 and the coldest T.

Physics:
  F_s^CR(q, dt) = (1/N) sum_j J_0(q |dr_j^CR|), tracer = cell centroid.
  q=6.7, N=4096, waiting time stored in the filename.
  Each curve is one idx (independent initial condition). The black curve is
  the mean on the overlapping positive-dt window. Horizontal line is 1/e.

Usage:
  python3 plot_fs_replicas_p3825_cold.py
"""

from __future__ import annotations

import re
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np

from measure_and_plot_tau_alpha import INV_E, read_two_values
from plot_vertex_production_fs import mean_curve, scratch_fs

HERE = Path(__file__).resolve().parent
ROOT = scratch_fs() / "p3.825"
OUT = HERE / "vertexModel_productionFs" / "round2" / "fs_replicas_p3.825_Tmin.png"
P0 = 3.825
Q = 6.7
NAME = re.compile(
    r"timeCRSISF_N\d+_p(?P<p0>[0-9.]+)_T(?P<T>[0-9.eE+-]+)"
    r"_k(?P<k>[0-9.]+)_waitingTime(?P<tw>[0-9.]+)_idx(?P<idx>\d+)\.nc$"
)


def main() -> None:
    files = []
    for nc in sorted(ROOT.glob("timeCRSISF_*.nc")):
        m = NAME.search(nc.name)
        if not m or abs(float(m.group("k")) - Q) > 0.02:
            continue
        files.append((float(m.group("T")), int(m.group("idx")), float(m.group("tw")), nc))
    if not files:
        raise SystemExit(f"no CRSISF files in {ROOT}")
    tmin = min(t for t, _, _, _ in files)
    cold = [(idx, tw, nc) for T, idx, tw, nc in files if abs(T - tmin) / tmin < 1e-5]
    cold.sort()

    curves = []
    fig, ax = plt.subplots(figsize=(8.4, 5.2))
    cmap = plt.get_cmap("tab10")
    for i, (idx, tw, nc) in enumerate(cold):
        dt, fs = read_two_values(nc)
        order = np.argsort(dt)
        dt, fs = dt[order], fs[order]
        curves.append((dt, fs))
        ax.plot(dt, fs, color=cmap(i % 10), lw=1.15, alpha=0.9, label=f"idx {idx}")
    tgrid, mean = mean_curve(curves)
    ax.plot(tgrid, mean, color="k", lw=2.2, label="mean", zorder=5)
    ax.axhline(INV_E, color="0.45", ls=":", lw=1.0, label=r"$1/e$")
    ax.set_xscale("log")
    ax.set_ylim(-0.05, 1.08)
    ax.set_xlabel(r"$\Delta t$")
    ax.set_ylabel(r"$F_s^{\mathrm{CR}}(q=6.7)$")
    ax.set_title(rf"$p_0={P0:.3f}$, $T={tmin:.6g}$, $t_w={cold[0][1]:.0f}$")
    ax.legend(fontsize=8, ncol=1, frameon=False, loc="center left", bbox_to_anchor=(1.02, 0.5))
    fig.tight_layout()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(OUT, dpi=150)
    plt.close(fig)
    print(f"wrote {OUT}  n={len(cold)}  T={tmin}")


if __name__ == "__main__":
    main()
