#!/usr/bin/env python3
"""
Generated by Cursor. 2026-09-15.
Mean off-diagonal stress sigma_xy of vertex production runs.

Physics:
  sigma_xy is the area-normalized virial (getSigmaXY): for the vertex
  quadratic energy, -sum_f f_x r_y / Area. Production records after
  10 tau_block of NVT eq, every 100 dt for 10 tau_block (dt=0.01).
  File time is production-clock (t=0 at start of recording), so the
  time mean of each file is the production-window mean.

  Per replica: <sigma_xy>_t. Per (p0,T): mean and sample std over idx=0..9.

Usage:
  python3 plot_vertex_production_sigma.py
  CELLGPU_SCRATCH=... python3 plot_vertex_production_sigma.py
"""

from __future__ import annotations

import csv
import math
import os
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.colors import LogNorm

HERE = Path(__file__).resolve().parent
OUTDIR = HERE / "vertexModel_tauAlpha_final"
CSV_STATES = OUTDIR / "production_state_points.csv"
CSV_FILL = HERE / "vertexModel_productionKwwFill" / "state_points.csv"
CSV_OUT = OUTDIR / "production_sigmaXY_mean.csv"
FIG_OUT = OUTDIR / "production_sigmaXY_mean_vs_T.png"
P0_ORDER = (3.750, 3.775, 3.800, 3.815, 3.825, 3.850)
N = 4096
IDX_MAX = 9

FS_TITLE = 17
FS_LABEL = 16
FS_TICK = 14


def scratch_prod() -> Path:
    env = os.environ.get("CELLGPU_SCRATCH")
    root = Path(env) if env else Path("/scratch/bbtm/cli6/glassyDynamics/data")
    return root / f"N{N}" / "vertex" / "productionRuns"


def read_two_values(path: Path):
    try:
        from netCDF4 import Dataset

        with Dataset(path, "r") as ds:
            a = np.array(ds.variables["firstValue"][:], dtype=float)
            b = np.array(ds.variables["secondValue"][:], dtype=float)
        return a, b
    except Exception:
        pass
    from scipy.io import netcdf_file

    with netcdf_file(path, "r", mmap=False) as ds:
        a = np.array(ds.variables["firstValue"].data, dtype=float)
        b = np.array(ds.variables["secondValue"].data, dtype=float)
    return a, b


def load_states() -> list[dict]:
    """Production + fill (p0,T,tauAlphaEst,batch)."""
    rows: list[dict] = []
    for path in (CSV_STATES, CSV_FILL):
        if not path.is_file():
            continue
        with path.open() as f:
            lines = (ln for ln in f if ln.strip() and not ln.lstrip().startswith("#"))
            for r in csv.DictReader(lines):
                p0 = float(r["p0"])
                T = float(r["T"])
                est = float(r["tauAlphaEst"])
                batch = r.get("batch", "fill")
                dup = any(
                    abs(p0 - z["p0"]) < 1e-4
                    and abs(T - z["T"]) / max(abs(T), 1e-30) < 1e-5
                    for z in rows
                )
                if dup:
                    continue
                rows.append(
                    {
                        "p0": p0,
                        "T": T,
                        "tauAlphaEst": est,
                        "tauBlock": max(1000.0, est),
                        "batch": batch,
                    }
                )
    rows.sort(key=lambda z: (P0_ORDER.index(min(P0_ORDER, key=lambda p: abs(p - z["p0"]))), -z["T"]))
    return rows


def sigma_path(p0: float, T: float, idx: int) -> Path:
    return (
        scratch_prod()
        / f"p{p0:.3f}"
        / f"sigmaXY_N{N}_p{p0:.4f}_T{T:.8f}_idx{idx}.nc"
    )


def replica_mean(path: Path) -> tuple[float, int]:
    _t, sig = read_two_values(path)
    if sig.size == 0:
        return float("nan"), 0
    return float(np.mean(sig)), int(sig.size)


def main() -> None:
    OUTDIR.mkdir(parents=True, exist_ok=True)
    states = load_states()
    print(f"state points={len(states)}  scratch={scratch_prod()}")
    csv_rows = []
    by_p0: dict[float, list[tuple[float, float, float]]] = {p: [] for p in P0_ORDER}
    n_miss = 0
    for st in states:
        p0, T = st["p0"], st["T"]
        means = []
        n_samp = 0
        n_ok = 0
        for idx in range(IDX_MAX + 1):
            path = sigma_path(p0, T, idx)
            if not path.is_file():
                continue
            try:
                m, n = replica_mean(path)
            except Exception as e:
                print(f"read fail {path}: {e}")
                continue
            if n <= 0 or not math.isfinite(m):
                continue
            means.append(m)
            n_samp += n
            n_ok += 1
        if n_ok == 0:
            n_miss += 1
            mean_s = float("nan")
            std_s = float("nan")
        else:
            mean_s = float(np.mean(means))
            std_s = float(np.std(means, ddof=1)) if n_ok > 1 else 0.0
        csv_rows.append(
            {
                "p0": f"{p0:.3f}",
                "T": f"{T:.8g}",
                "batch": st["batch"],
                "tauAlphaEst": f"{st['tauAlphaEst']:.8g}",
                "tauBlock": f"{st['tauBlock']:.8g}",
                "nReplica": n_ok,
                "nSamp": n_samp,
                "sigmaXY_mean": f"{mean_s:.8g}" if math.isfinite(mean_s) else "",
                "sigmaXY_std": f"{std_s:.8g}" if math.isfinite(std_s) else "",
            }
        )
        pkey = min(P0_ORDER, key=lambda p: abs(p - p0))
        if math.isfinite(mean_s):
            by_p0[pkey].append((T, mean_s, std_s))

    with CSV_OUT.open("w", newline="") as f:
        w = csv.DictWriter(
            f,
            fieldnames=[
                "p0",
                "T",
                "batch",
                "tauAlphaEst",
                "tauBlock",
                "nReplica",
                "nSamp",
                "sigmaXY_mean",
                "sigmaXY_std",
            ],
        )
        w.writeheader()
        w.writerows(csv_rows)
    print(f"wrote {CSV_OUT} ({len(csv_rows)} rows, {n_miss} missing)")

    fig = plt.figure(figsize=(13.6, 8.0))
    gs = fig.add_gridspec(
        2, 3, left=0.07, right=0.98, top=0.93, bottom=0.09, wspace=0.26, hspace=0.32
    )
    for i, p0 in enumerate(P0_ORDER):
        row, col = divmod(i, 3)
        ax = fig.add_subplot(gs[row, col])
        pts = sorted(by_p0[p0], key=lambda z: z[0])
        ax.set_title(rf"$p_0={p0:.3f}$", fontsize=FS_TITLE, pad=4)
        ax.tick_params(labelsize=FS_TICK)
        ax.axhline(0.0, color="0.5", lw=0.7, zorder=0)
        if not pts:
            continue
        Ts = np.array([z[0] for z in pts])
        ys = np.array([z[1] for z in pts])
        es = np.array([z[2] for z in pts])
        cmap = plt.get_cmap("coolwarm")
        norm = LogNorm(vmin=Ts.min(), vmax=Ts.max())
        colors = cmap(norm(Ts))
        ax.errorbar(
            Ts,
            ys,
            yerr=es,
            fmt="none",
            ecolor="0.6",
            elinewidth=0.8,
            capsize=2,
            zorder=1,
        )
        ax.scatter(Ts, ys, c=colors, s=28, zorder=2, edgecolors="0.3", linewidths=0.4)
        ax.set_xscale("log")
        if i >= 3:
            ax.set_xlabel(r"$T$", fontsize=FS_LABEL)
        if i % 3 == 0:
            ax.set_ylabel(r"$\overline{\sigma}_{xy}$", fontsize=FS_LABEL)
    fig.suptitle(
        r"Production $\overline{\sigma}_{xy}$ (time mean, then idx=0..9)",
        fontsize=FS_TITLE,
    )
    fig.savefig(FIG_OUT, dpi=200)
    fig.savefig(FIG_OUT.with_suffix(".pdf"))
    plt.close(fig)
    print(f"wrote {FIG_OUT}")


if __name__ == "__main__":
    main()
