#!/usr/bin/env python3
"""
Generated by Cursor. 2026-09-09.
Wave A / t1Scan tau_alpha panels for all p0.

Physics:
  T1 when edge length < l_T1 (mean cell area 1). tau_alpha is the longest-tw
  CRSISF 1/e of cell centroids at q=6.80. Keep a point if it crosses 1/e.
  Default also requires tau_alpha <= 5 * tau_est except p0=3.800, which uses
  the earlier 15-tau t1Scan table (vertex_t1_tau_vs_T.csv) as-is.
  --nocut keeps every crossing. t1Scan only (no default-0.01, no Voronoi).

Usage:
  python3 glassyDynamicsProject/analyseScripts/vertexTauAlpha/plot_vertex_t1_waveA_panels.py
  python3 glassyDynamicsProject/analyseScripts/vertexTauAlpha/plot_vertex_t1_waveA_panels.py --nocut
"""

from __future__ import annotations

import csv
import math
import sys
from collections import defaultdict
from pathlib import Path

import matplotlib.pyplot as plt
from matplotlib.cm import ScalarMappable
from matplotlib.colors import LogNorm

HERE = Path(__file__).resolve().parent
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))

from plot_vertex_t1_tau_alpha import (
    MARKERS,
    N,
    P0_ORDER,
    T1_ORDER,
    collect_t1_scan_rows,
    t1_label,
)

OUTDIR = HERE / "vertexModel_t1Scan"
REC = HERE / "vertexModel_tauAlpha_final" / "recommended_T.csv"
P38_ARCHIVE = OUTDIR / "vertex_t1_tau_vs_T.csv"
CSV_OUT = OUTDIR / "vertex_t1_tau_waveA.csv"
CUT = 5.0
P38 = 3.800
# Combined 2x3: readable labels, modest row gap (xlabel only on bottom row).
FS_TITLE = 15
FS_LABEL = 14
FS_TICK = 12
FS_CBAR = 13
FS_LEGEND = 8
FS_LEGEND_SINGLE = 10
FS_SUP = 16


def load_tau_est(path: Path) -> list[tuple[float, float, float]]:
    rows = []
    with path.open() as f:
        for r in csv.DictReader(f):
            rows.append((float(r["p0"]), float(r["T"]), float(r["tauAlphaEst"])))
    return rows


def load_p38_archive(path: Path) -> list[dict]:
    """Earlier p0=3.800 t1Scan tau_alpha (longest tw that crossed 1/e)."""
    out = []
    if not path.is_file():
        return out
    with path.open() as f:
        for r in csv.DictReader(f):
            if r.get("source") != "t1Scan":
                continue
            if abs(float(r["p0"]) - P38) > 1e-4:
                continue
            tau = float(r["tauAlpha"])
            if not (math.isfinite(tau) and tau > 0):
                continue
            out.append(
                {
                    "t1": float(r["t1"]),
                    "p0": P38,
                    "T": float(r["T"]),
                    "waitingTime": float(r["waitingTime"]) if r["waitingTime"] else 0.0,
                    "tauAlpha": tau,
                    "crossed": 1,
                    "n": N,
                    "idx": 0,
                    "source": "t1Scan",
                }
            )
    return out


def replace_p38(scan: list[dict], archive: list[dict]) -> list[dict]:
    if not archive:
        print("no p0=3.800 archive; using harvest")
        return scan
    kept = [r for r in scan if abs(r["p0"] - P38) > 1e-4]
    print(f"p0=3.800: drop {len(scan) - len(kept)} harvest files, use {len(archive)} archive crossings")
    return kept + archive


def tau_est_of(ests, p0: float, T: float) -> float | None:
    best = None
    best_d = 1e9
    for p, t, te in ests:
        if abs(p - p0) > 1e-4:
            continue
        d = abs(t / T - 1.0) if T != 0 else abs(t - T)
        if d < best_d:
            best_d = d
            best = te
    if best is None or best_d > 1e-3:
        return None
    return best


def build_table(scan: list[dict], ests, cut: float | None) -> list[dict]:
    groups = defaultdict(list)
    for r in scan:
        groups[(round(r["p0"], 5), r["t1"], r["T"])].append(r)
    out = []
    for (_p, t1, T), grp in groups.items():
        p0 = grp[0]["p0"]
        te = tau_est_of(ests, p0, T)
        crossed = [
            r
            for r in grp
            if r["crossed"] and math.isfinite(r["tauAlpha"]) and r["tauAlpha"] > 0
        ]
        if crossed:
            best = max(crossed, key=lambda r: r["waitingTime"])
            tau = float(best["tauAlpha"])
            # p0=3.800 archive used 15-tau production; do not apply the compact 5*tau_est cut.
            if cut is None or abs(p0 - P38) < 1e-4:
                kept = 1
            else:
                kept = int(te is not None and tau <= cut * te)
            tw = best["waitingTime"]
        else:
            tau = grp[0]["tauAlpha"] if math.isfinite(grp[0]["tauAlpha"]) else ""
            kept = 0
            tw = max(r["waitingTime"] for r in grp)
        out.append(
            {
                "p0": p0,
                "T": T,
                "t1": t1,
                "tauAlpha": tau,
                "tauAlphaEst": te if te is not None else "",
                "waitingTime": tw,
                "kept": kept,
            }
        )
    out.sort(key=lambda r: (r["p0"], r["t1"], r["T"]))
    return out


def kept_rows(table: list[dict], p0: float) -> list[dict]:
    return [
        r
        for r in table
        if r["kept"] == 1 and abs(float(r["p0"]) - p0) < 1e-4
    ]


def write_csv(path: Path, rows: list[dict]):
    path.parent.mkdir(parents=True, exist_ok=True)
    fields = ["p0", "T", "t1", "tauAlpha", "tauAlphaEst", "waitingTime", "kept"]
    with path.open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        w.writerows(rows)
    nkeep = sum(1 for r in rows if r["kept"] == 1)
    print(f"wrote {path} ({len(rows)} rows, kept={nkeep})")


def _apply_fonts():
    plt.rcParams.update(
        {
            "font.size": 12,
            "axes.titlesize": FS_TITLE,
            "axes.labelsize": FS_LABEL,
            "xtick.labelsize": FS_TICK,
            "ytick.labelsize": FS_TICK,
            "legend.fontsize": FS_LEGEND,
            "figure.titlesize": FS_SUP,
        }
    )


def _style_ax(ax):
    ax.tick_params(axis="both", which="both", labelsize=FS_TICK, length=5, width=1.0)
    ax.tick_params(axis="both", which="minor", length=3)


def plot_tau_vs_lth(rows: list[dict], ax, colorbar_norm=None, xlabel=True, ylabel=True):
    by_T = defaultdict(list)
    for r in rows:
        by_T[float(r["T"])].append(r)
    if not by_T:
        ax.set_axis_off()
        return None
    Ts = sorted(by_T, reverse=True)
    cmap = plt.get_cmap("coolwarm")
    norm = colorbar_norm or LogNorm(vmin=min(Ts), vmax=max(Ts))
    for T in Ts:
        sub = sorted(by_T[T], key=lambda r: float(r["t1"]))
        ax.plot(
            [float(r["t1"]) for r in sub],
            [float(r["tauAlpha"]) for r in sub],
            color=cmap(norm(T)),
            marker="o",
            markersize=4,
            lw=1.0,
        )
    ax.set_xscale("log")
    ax.set_yscale("log")
    if xlabel:
        ax.set_xlabel(r"$\ell_{T1}$", fontsize=FS_LABEL)
    if ylabel:
        ax.set_ylabel(r"$\tau_\alpha$", fontsize=FS_LABEL)
    _style_ax(ax)
    return norm


def plot_tau_vs_T(rows: list[dict], ax, t1_norm=None, xlabel=True, ylabel=True):
    by_t1 = defaultdict(list)
    for r in rows:
        by_t1[float(r["t1"])].append(r)
    if not by_t1:
        ax.set_axis_off()
        return None, []
    t1s = sorted(by_t1)
    cmap = plt.get_cmap("viridis")
    found = [t1 for t1 in T1_ORDER if any(abs(x / t1 - 1.0) < 1e-6 for x in t1s)]
    if not found:
        found = t1s
    norm = t1_norm or LogNorm(vmin=min(found), vmax=max(found))
    for i, t1 in enumerate(found):
        sub = sorted(
            (r for r in rows if abs(float(r["t1"]) / t1 - 1.0) < 1e-6),
            key=lambda r: float(r["T"]),
        )
        if not sub:
            continue
        ax.plot(
            [float(r["T"]) for r in sub],
            [float(r["tauAlpha"]) for r in sub],
            color=cmap(norm(t1)),
            marker=MARKERS[i % len(MARKERS)],
            markersize=4,
            lw=1.0,
            label=t1_label(t1),
        )
    ax.set_xscale("log")
    ax.set_yscale("log")
    if xlabel:
        ax.set_xlabel(r"$T$", fontsize=FS_LABEL)
    if ylabel:
        ax.set_ylabel(r"$\tau_\alpha$", fontsize=FS_LABEL)
    _style_ax(ax)
    return norm, found


def plot_tau_lth_vs_T(rows: list[dict], ax, t1_norm=None, xlabel=True, ylabel=True):
    by_t1 = defaultdict(list)
    for r in rows:
        by_t1[float(r["t1"])].append(r)
    if not by_t1:
        ax.set_axis_off()
        return None, []
    t1s = sorted(by_t1)
    cmap = plt.get_cmap("viridis")
    found = [t1 for t1 in T1_ORDER if any(abs(x / t1 - 1.0) < 1e-6 for x in t1s)]
    if not found:
        found = t1s
    norm = t1_norm or LogNorm(vmin=min(found), vmax=max(found))
    for i, t1 in enumerate(found):
        sub = sorted(
            (r for r in rows if abs(float(r["t1"]) / t1 - 1.0) < 1e-6),
            key=lambda r: float(r["T"]),
        )
        if not sub:
            continue
        ax.plot(
            [float(r["T"]) for r in sub],
            [float(r["tauAlpha"]) * t1 for r in sub],
            color=cmap(norm(t1)),
            marker=MARKERS[i % len(MARKERS)],
            markersize=4,
            lw=1.0,
            label=t1_label(t1),
        )
    ax.set_xscale("log")
    ax.set_yscale("log")
    if xlabel:
        ax.set_xlabel(r"$T$", fontsize=FS_LABEL)
    if ylabel:
        ax.set_ylabel(r"$\tau_\alpha\,\ell_{T1}$", fontsize=FS_LABEL)
    _style_ax(ax)
    return norm, found


def save_single(fig, path: Path):
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.tight_layout()
    fig.savefig(path, dpi=150)
    plt.close(fig)
    print(f"wrote {path}")


def plot_per_p0(table: list[dict], suffix: str = ""):
    _apply_fonts()
    all_T = [float(r["T"]) for r in table if r["kept"] == 1]
    all_t1 = [float(r["t1"]) for r in table if r["kept"] == 1]
    Tnorm = LogNorm(vmin=min(all_T), vmax=max(all_T)) if all_T else None
    t1norm = LogNorm(vmin=min(all_t1), vmax=max(all_t1)) if all_t1 else None
    for p0 in P0_ORDER:
        rows = kept_rows(table, p0)
        tag = f"p{p0:.3f}{suffix}"
        fig, ax = plt.subplots(figsize=(6.8, 5.0))
        plot_tau_vs_lth(rows, ax, Tnorm)
        ax.set_title(rf"$p_0={p0:.3f}$", fontsize=FS_TITLE)
        if Tnorm is not None:
            sm = ScalarMappable(norm=Tnorm, cmap=plt.get_cmap("coolwarm"))
            sm.set_array([])
            cb = fig.colorbar(sm, ax=ax)
            cb.set_label(r"$T$ (red hot, blue cold)", fontsize=FS_CBAR)
            cb.ax.tick_params(labelsize=FS_TICK)
        save_single(fig, OUTDIR / f"vertex_t1_tau_vs_lth_{tag}.png")

        fig, ax = plt.subplots(figsize=(7.2, 5.2))
        plot_tau_vs_T(rows, ax, t1norm)
        ax.set_title(rf"$p_0={p0:.3f}$", fontsize=FS_TITLE)
        ax.legend(loc="best", frameon=False, fontsize=FS_LEGEND_SINGLE)
        save_single(fig, OUTDIR / f"vertex_t1_tau_vs_T_{tag}.png")

        fig, ax = plt.subplots(figsize=(7.2, 5.2))
        plot_tau_lth_vs_T(rows, ax, t1norm)
        ax.set_title(rf"$p_0={p0:.3f}$", fontsize=FS_TITLE)
        ax.legend(loc="best", frameon=False, fontsize=FS_LEGEND_SINGLE)
        save_single(fig, OUTDIR / f"vertex_t1_tau_lth_vs_T_{tag}.png")


def _combined_axes(plot_fn, table, norm, cbar_label, cmap, tag, kind, legend=False):
    _apply_fonts()
    fig = plt.figure(figsize=(13.6, 8.0))
    gs = fig.add_gridspec(
        2,
        4,
        width_ratios=[1.0, 1.0, 1.0, 0.055],
        left=0.07,
        right=0.94,
        top=0.95,
        bottom=0.09,
        wspace=0.26,
        hspace=0.24,
    )
    for i, p0 in enumerate(P0_ORDER):
        row, col = divmod(i, 3)
        ax = fig.add_subplot(gs[row, col])
        plot_fn(
            kept_rows(table, p0),
            ax,
            norm,
            xlabel=(row == 1),
            ylabel=(col == 0),
        )
        ax.set_title(rf"$p_0={p0:.3f}$", fontsize=FS_TITLE, pad=4)
        if legend:
            ax.legend(loc="best", frameon=False, fontsize=FS_LEGEND)
    cax = fig.add_subplot(gs[:, 3])
    sm = ScalarMappable(norm=norm, cmap=plt.get_cmap(cmap))
    sm.set_array([])
    cb = fig.colorbar(sm, cax=cax)
    cb.set_label(cbar_label, fontsize=FS_CBAR)
    cb.ax.tick_params(labelsize=FS_TICK)
    out = OUTDIR / f"vertex_t1_tau_{kind}_{tag}.png"
    fig.savefig(out, dpi=150)
    plt.close(fig)
    print(f"wrote {out}")


def plot_combined(table: list[dict], suffix: str = ""):
    all_T = [float(r["T"]) for r in table if r["kept"] == 1]
    all_t1 = [float(r["t1"]) for r in table if r["kept"] == 1]
    if not all_T:
        raise SystemExit("no kept points")
    Tnorm = LogNorm(vmin=min(all_T), vmax=max(all_T))
    t1norm = LogNorm(vmin=min(all_t1), vmax=max(all_t1))
    tag = f"all_p0{suffix}"
    _combined_axes(
        plot_tau_vs_lth,
        table,
        Tnorm,
        r"$T$ (red hot, blue cold)",
        "coolwarm",
        tag,
        "vs_lth",
    )
    _combined_axes(
        plot_tau_vs_T,
        table,
        t1norm,
        r"$\ell_{T1}$",
        "viridis",
        tag,
        "vs_T",
        legend=True,
    )
    _combined_axes(
        plot_tau_lth_vs_T,
        table,
        t1norm,
        r"$\ell_{T1}$",
        "viridis",
        tag,
        "lth_vs_T",
        legend=True,
    )


def _emit(table: list[dict], nocut: bool):
    if nocut:
        write_csv(OUTDIR / "vertex_t1_tau_waveA_nocut.csv", table)
        plot_per_p0(table, suffix="_nocut")
        plot_combined(table, suffix="_nocut")
    else:
        write_csv(CSV_OUT, table)
        plot_per_p0(table)
        plot_combined(table)


def main():
    only_nocut = "--nocut" in sys.argv
    only_cut = "--cut" in sys.argv
    ests = load_tau_est(REC)
    scan = collect_t1_scan_rows(N)
    print(f"t1Scan CRSISF files: {len(scan)}")
    if not scan:
        sys.exit("no t1Scan CRSISF; wait for Wave A FS")
    scan = replace_p38(scan, load_p38_archive(P38_ARCHIVE))
    if only_nocut:
        _emit(build_table(scan, ests, None), True)
    elif only_cut:
        _emit(build_table(scan, ests, CUT), False)
    else:
        _emit(build_table(scan, ests, CUT), False)
        _emit(build_table(scan, ests, None), True)


if __name__ == "__main__":
    main()
