#!/usr/bin/env python3
"""
Generated by Cursor. 2026-09-14.
Plots for the production CRSISF KWW HMC fit: tail overlays, t/tau collapse,
tau_kww vs 1/e, optional beta(p0,T), and a tail RMS collapse score.

Physics:
  Overlay: mu(t) = A * exp(-(t/tau)^beta).
  Collapse: Fs vs u = t/tau_kww on log-log axes (positive Fs only).
  Collapse RMS: on a common u-grid in the fitted tail, RMS of Fs minus the
  mean master curve (dimensionless).

Usage:
  python3 plot_vertex_fs_kww.py --share global
"""

from __future__ import annotations

import argparse
import math
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from matplotlib.colors import LogNorm

from fit_vertex_fs_kww_hmc import tail_after_plateau
from plot_vertex_production_fs import OUTDIR, P0_ORDER

FS_TITLE = 17
FS_LABEL = 16
FS_TICK = 14


def _combined_axes(fig_w: float = 13.6, fig_h: float = 8.0):
    fig = plt.figure(figsize=(fig_w, fig_h))
    gs = fig.add_gridspec(
        2, 3, left=0.07, right=0.98, top=0.95, bottom=0.09, wspace=0.26, hspace=0.28
    )
    axes = []
    for i, p0 in enumerate(P0_ORDER):
        row, col = divmod(i, 3)
        ax = fig.add_subplot(gs[row, col])
        ax.set_title(rf"$p_0={p0:.3f}$", fontsize=FS_TITLE, pad=4)
        ax.tick_params(labelsize=FS_TICK)
        axes.append(ax)
    return fig, axes


def kww(t, A, beta, tau):
    t = np.asarray(t, dtype=float)
    tau = max(float(tau), 1e-30)
    return A * np.exp(-np.power(t / tau, beta))


def color_for_T(cmap, norm, T: float):
    if norm is None:
        return cmap(0.5)
    return cmap(norm(T))


def p0_norm(Ts: list[float]):
    tmin, tmax = min(Ts), max(Ts)
    if tmin <= 0 or tmin == tmax:
        return None
    return LogNorm(vmin=tmin, vmax=tmax)


def collapse_rms(
    fs: pd.DataFrame,
    tau_df: pd.DataFrame,
    u_lo: float = 0.05,
    u_hi: float = 20.0,
    n_u: int = 40,
) -> pd.DataFrame:
    """RMS of tail Fs vs mean master curve on a common u = t/tau grid."""
    ugrid = np.geomspace(u_lo, u_hi, n_u)
    rows = []
    stacked_all = []
    for p0 in P0_ORDER:
        stacked_p0 = []
        sub_tau = tau_df[np.isclose(tau_df["p0"], p0)]
        for r in sub_tau.itertuples(index=False):
            g = fs[(np.isclose(fs["p0"], r.p0)) & (np.isclose(fs["T"], r.T))]
            if g.empty or not math.isfinite(r.tau_kww) or r.tau_kww <= 0:
                continue
            t = g["t"].to_numpy(float)
            y = g["Fs_mean"].to_numpy(float)
            u = t / r.tau_kww
            order = np.argsort(u)
            u, y = u[order], y[order]
            if u.size < 2:
                continue
            yi = np.interp(ugrid, u, y, left=np.nan, right=np.nan)
            stacked_p0.append(yi)
            stacked_all.append(yi)
        if stacked_p0:
            arr = np.vstack(stacked_p0)
            master = np.nanmean(arr, axis=0)
            resid = arr - master
            rms = float(np.sqrt(np.nanmean(resid**2)))
        else:
            rms = math.nan
        rows.append({"p0": p0, "scope": "per_p0", "collapse_rms": rms, "n_curves": len(stacked_p0)})
    if stacked_all:
        arr = np.vstack(stacked_all)
        master = np.nanmean(arr, axis=0)
        rms_all = float(np.sqrt(np.nanmean((arr - master) ** 2)))
        n_all = len(stacked_all)
    else:
        rms_all = math.nan
        n_all = 0
    rows.append({"p0": math.nan, "scope": "global", "collapse_rms": rms_all, "n_curves": n_all})
    return pd.DataFrame(rows)


def main() -> None:
    parser = argparse.ArgumentParser(description="Plot KWW HMC fit and t/tau collapse.")
    parser.add_argument("--share", choices=("global", "per_p0", "independent"), default="global")
    parser.add_argument("--input", type=Path, default=OUTDIR / "Fs_combined_mean.csv")
    args = parser.parse_args()

    OUTDIR.mkdir(parents=True, exist_ok=True)
    fs = pd.read_csv(args.input)
    tau_path = OUTDIR / f"kww_{args.share}_tau.csv"
    tau_df = pd.read_csv(tau_path)
    cmap = plt.get_cmap("coolwarm")

    # --- overlays: raw Fs + KWW on tail ---
    fig, axes = _combined_axes()
    for i, p0 in enumerate(P0_ORDER):
        ax = axes[i]
        sub_tau = tau_df[np.isclose(tau_df["p0"], p0)].sort_values("T")
        Ts = [float(T) for T in sub_tau["T"]]
        norm = p0_norm(Ts) if Ts else None
        for r in sub_tau.itertuples(index=False):
            g = fs[(np.isclose(fs["p0"], r.p0)) & (np.isclose(fs["T"], r.T))].sort_values("t")
            if g.empty:
                continue
            color = color_for_T(cmap, norm, float(r.T))
            t = g["t"].to_numpy(float)
            y = g["Fs_mean"].to_numpy(float)
            ax.plot(t, y, color=color, lw=1.0, alpha=0.85)
            piece = tail_after_plateau(g, float(r.fs_min), float(r.fs_max))
            if not piece.empty:
                ax.plot(piece["t"], piece["Fs_mean"], color=color, lw=2.0)
            if t.size:
                tt = np.geomspace(max(t.min(), 1e-6), t.max(), 200)
                ax.plot(tt, kww(tt, r.A, r.beta, r.tau_kww), color=color, ls="--", lw=0.9)
        ax.set_xscale("log")
        ax.set_ylim(-0.05, 1.08)
        row, col = divmod(i, 3)
        if row == 1:
            ax.set_xlabel(r"$\Delta t$", fontsize=FS_LABEL)
        if col == 0:
            ax.set_ylabel(r"$F_s^{\mathrm{CR}}$", fontsize=FS_LABEL)
    png = OUTDIR / f"kww_{args.share}_overlay.png"
    fig.savefig(png, dpi=150)
    plt.close(fig)
    print(f"wrote {png}")

    def plot_collapse(normalize_A: bool, suffix: str, ylabel: str) -> None:
        fig, axes = _combined_axes()
        for i, p0 in enumerate(P0_ORDER):
            ax = axes[i]
            sub_tau = tau_df[np.isclose(tau_df["p0"], p0)].sort_values("T")
            Ts = [float(T) for T in sub_tau["T"]]
            norm = p0_norm(Ts) if Ts else None
            A_ref = float(sub_tau["A"].iloc[0]) if not sub_tau.empty else 1.0
            b_ref = float(sub_tau["beta"].iloc[0]) if not sub_tau.empty else 1.0
            for r in sub_tau.itertuples(index=False):
                g = fs[(np.isclose(fs["p0"], r.p0)) & (np.isclose(fs["T"], r.T))].sort_values("t")
                if g.empty or r.tau_kww <= 0:
                    continue
                color = color_for_T(cmap, norm, float(r.T))
                t = g["t"].to_numpy(float)
                y = g["Fs_mean"].to_numpy(float)
                u = t / r.tau_kww
                yy = y / r.A if normalize_A and r.A > 0 else y
                m = (u > 0) & (yy > 0)
                ax.plot(u[m], yy[m], color=color, lw=1.3)
            uu = np.geomspace(1e-2, 30, 200)
            if normalize_A:
                yk = np.exp(-(uu**b_ref))
            else:
                yk = kww(uu * 1.0, A_ref, b_ref, 1.0)
            ax.plot(uu[yk > 0], yk[yk > 0], color="k", ls="--", lw=0.9, zorder=5)
            ax.set_xscale("log")
            ax.set_yscale("log")
            ax.set_ylim(1e-3, 2.0)
            row, col = divmod(i, 3)
            if row == 1:
                ax.set_xlabel(r"$t/\tau_{\mathrm{KWW}}$", fontsize=FS_LABEL)
            if col == 0:
                ax.set_ylabel(ylabel, fontsize=FS_LABEL)
        out = OUTDIR / f"kww_{args.share}_collapse{suffix}_by_p0.png"
        fig.savefig(out, dpi=150)
        plt.close(fig)
        print(f"wrote {out}")

        # All (p0, T) on one master curve (same alpha branch).
        fig, ax = plt.subplots(figsize=(7.4, 5.6))
        p0_cmap = plt.get_cmap("tab10")
        A_ref = float(tau_df["A"].iloc[0]) if not tau_df.empty else 1.0
        b_ref = float(tau_df["beta"].iloc[0]) if not tau_df.empty else 1.0
        drawn = set()
        for r in tau_df.itertuples(index=False):
            g = fs[(np.isclose(fs["p0"], r.p0)) & (np.isclose(fs["T"], r.T))].sort_values("t")
            if g.empty or r.tau_kww <= 0:
                continue
            p0 = float(r.p0)
            ip = P0_ORDER.index(min(P0_ORDER, key=lambda p: abs(p - p0)))
            t = g["t"].to_numpy(float)
            y = g["Fs_mean"].to_numpy(float)
            u = t / r.tau_kww
            yy = y / r.A if normalize_A and r.A > 0 else y
            m = (u > 0) & (yy > 0)
            label = rf"$p_0={P0_ORDER[ip]:.3f}$" if ip not in drawn else None
            ax.plot(u[m], yy[m], color=p0_cmap(ip), lw=1.1, alpha=0.85, label=label)
            drawn.add(ip)
        uu = np.geomspace(1e-2, 30, 200)
        if normalize_A:
            yk = np.exp(-(uu**b_ref))
            kww_label = rf"$\exp(-u^{{\beta}})$, $\beta={b_ref:.3f}$"
        else:
            yk = kww(uu * 1.0, A_ref, b_ref, 1.0)
            kww_label = rf"$A\exp(-u^{{\beta}})$, $A={A_ref:.3f}$, $\beta={b_ref:.3f}$"
        ax.plot(uu[yk > 0], yk[yk > 0], color="k", ls="--", lw=1.4, zorder=5, label=kww_label)
        ax.set_xscale("log")
        ax.set_yscale("log")
        ax.set_ylim(1e-3, 2.0)
        ax.set_xlabel(r"$t/\tau_{\mathrm{KWW}}$", fontsize=FS_LABEL)
        ax.set_ylabel(ylabel, fontsize=FS_LABEL)
        ax.tick_params(labelsize=FS_TICK)
        ax.legend(fontsize=10, frameon=False, loc="lower left")
        out = OUTDIR / f"kww_{args.share}_collapse{suffix}.png"
        fig.savefig(out, dpi=150)
        plt.close(fig)
        print(f"wrote {out}")

    plot_collapse(False, "", r"$F_s^{\mathrm{CR}}$")
    plot_collapse(True, "_overA", r"$F_s^{\mathrm{CR}}/A$")

    # tau_kww vs 1/e
    fig, axes = _combined_axes()
    for i, p0 in enumerate(P0_ORDER):
        ax = axes[i]
        sub = tau_df[np.isclose(tau_df["p0"], p0)].sort_values("T")
        ax.loglog(sub["T"], sub["tau_kww"], "o-", color="C0", label=r"$\tau_{\mathrm{KWW}}$")
        ax.loglog(sub["T"], sub["tau_1e"], "s--", color="C1", label=r"$1/e$")
        row, col = divmod(i, 3)
        if row == 1:
            ax.set_xlabel(r"$T$", fontsize=FS_LABEL)
        if col == 0:
            ax.set_ylabel(r"$\tau_\alpha$", fontsize=FS_LABEL)
        if i == 0:
            ax.legend(fontsize=11, frameon=False)
    tau_png = OUTDIR / f"kww_{args.share}_tau_vs_T.png"
    fig.savefig(tau_png, dpi=150)
    plt.close(fig)
    print(f"wrote {tau_png}")

    if args.share == "independent":
        fig, ax = plt.subplots(figsize=(7.2, 5.0))
        for i, p0 in enumerate(P0_ORDER):
            sub = tau_df[np.isclose(tau_df["p0"], p0)].sort_values("T")
            ax.plot(sub["T"], sub["beta"], "o-", color=plt.get_cmap("tab10")(i), label=rf"$p_0={p0:.3f}$")
        ax.set_xscale("log")
        ax.set_xlabel(r"$T$", fontsize=FS_LABEL)
        ax.set_ylabel(r"$\beta$", fontsize=FS_LABEL)
        ax.legend(fontsize=10, frameon=False)
        ax.tick_params(labelsize=FS_TICK)
        bpng = OUTDIR / f"kww_{args.share}_beta_vs_T.png"
        fig.savefig(bpng, dpi=150)
        plt.close(fig)
        print(f"wrote {bpng}")

    rms = collapse_rms(fs, tau_df)
    rms["share"] = args.share
    rms_path = OUTDIR / f"kww_{args.share}_collapse_rms.csv"
    rms.to_csv(rms_path, index=False)
    print(f"wrote {rms_path}")
    print(rms.to_string(index=False))


if __name__ == "__main__":
    main()
