#!/usr/bin/env python3
"""
Generated by Cursor. 2026-08-26.
Vertex vs Voronoi tau_alpha comparison and recommended production T.

Physics:
  tau_alpha is the CRSISF 1/e crossing at q = 6.80. Vertex tracers are cell
  centroids (polygon centroid of the vertex ring). Per (p0, T) we keep the
  longest waiting time whose F_s^CR still crosses 1/e.
  Batches 2-4 only (same tau_block = max(tau_est, 1000) protocol). Later
  batch overrides the same T.
  Recommended T: read T off the measured tau(T) curve at tau_k = 10**(1+k/3)
  by walking log tau vs 1/T (hotter than the table: log tau vs log T).
  Tg is T where tau_alpha = 1e4, same interpolation. Units: reduced kT, p0
  target shape index, tau in reduced time.

Usage:
  python3 plot_vertex_voronoi_comparison.py
"""

from __future__ import annotations

import csv
import math
import sys
from pathlib import Path

import matplotlib.pyplot as plt

HERE = Path(__file__).resolve().parent
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))

from propose_vertex_tau_alpha_batch4 import (
    CURVE_B2,
    CURVE_B3,
    P0_ORDER,
    TAU_TARGETS,
    invert_T_for_tau_meas,
    load_curves,
    longest_crossed_tw_rows,
    meas_table,
    merge_anchors,
)

CURVE_B4 = HERE / "vertexModel_tauAlpha_batch4" / "vertexModel_tauAlpha_batch4_per_curve.csv"
VORONOI_CSV = (
    HERE.parent / "TauAlphaTable" / "data_2DVoronoi" / "tauAlpha_2DVoronoi_all.csv"
)
OUTDIR = HERE / "vertexModel_tauAlpha_final"
TAU_G = 1.0e4


def load_voronoi(path: Path):
    rows = []
    with path.open() as f:
        for r in csv.DictReader(f):
            p0 = float(r["p0"])
            if not any(abs(p0 - p) < 1e-4 for p in P0_ORDER):
                continue
            tau = float(r["tauAlpha"])
            if not (math.isfinite(tau) and tau > 0):
                continue
            rows.append({"p0": p0, "T": float(r["T"]), "tauAlpha": tau})
    return rows


def write_csv(path: Path, fieldnames, rows):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames)
        w.writeheader()
        for r in rows:
            w.writerow(r)
    print(f"wrote {path} ({len(rows)} rows)")


def tg_how(table):
    T, how = invert_T_for_tau_meas(table, TAU_G)
    tau_cold = table[-1][1]
    if TAU_G > tau_cold * (1.0 + 1e-9):
        how = "1/T-extrap"
    return T, how


def plot_comparison(vertex, voronoi, Tg_v, Tg_o, outpath: Path):
    colors = plt.cm.viridis([0.05, 0.22, 0.40, 0.58, 0.76, 0.93])
    fig, axes = plt.subplots(1, 2, figsize=(11.0, 4.6))
    ax_t, ax_a = axes

    for i, p0 in enumerate(P0_ORDER):
        c = colors[i]
        vv = [a for a in vertex if abs(a["p0"] - p0) < 1e-4]
        vo = [a for a in voronoi if abs(a["p0"] - p0) < 1e-4]
        lab_v = rf"$p_0={p0:.3f}$ vertex" if i == 0 else rf"$p_0={p0:.3f}$"
        ax_t.scatter(
            [a["T"] for a in vv],
            [a["tauAlpha"] for a in vv],
            c=[c],
            s=36,
            marker="o",
            zorder=4,
            label=lab_v,
        )
        ax_t.scatter(
            [a["T"] for a in vo],
            [a["tauAlpha"] for a in vo],
            facecolors="none",
            edgecolors=[c],
            s=40,
            marker="s",
            zorder=3,
            label="Voronoi" if i == 0 else None,
        )
        ax_a.scatter(
            [Tg_v[p0] / a["T"] for a in vv],
            [a["tauAlpha"] for a in vv],
            c=[c],
            s=36,
            marker="o",
            zorder=4,
        )
        ax_a.scatter(
            [Tg_o[p0] / a["T"] for a in vo],
            [a["tauAlpha"] for a in vo],
            facecolors="none",
            edgecolors=[c],
            s=40,
            marker="s",
            zorder=3,
        )

    ax_t.set_xscale("log")
    ax_t.set_yscale("log")
    ax_t.set_xlabel(r"$T$")
    ax_t.set_ylabel(r"$\tau_\alpha$")
    ax_t.set_title(r"$\tau_\alpha$ vs $T$")
    ax_t.legend(loc="best", fontsize=7, frameon=False, ncol=2)

    ax_a.set_yscale("log")
    ax_a.set_xlabel(r"$T_g/T$")
    ax_a.set_ylabel(r"$\tau_\alpha$")
    ax_a.set_title(r"Angell: $\tau_\alpha$ vs $T_g/T$")
    ax_a.axhline(TAU_G, color="0.6", lw=0.8, ls="--", zorder=1)
    ax_a.text(
        0.02,
        0.04,
        r"filled $○$ vertex, open $□$ Voronoi; $T_g$: $\tau_\alpha=10^4$",
        transform=ax_a.transAxes,
        fontsize=7,
        color="0.3",
    )

    fig.tight_layout()
    outpath.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(outpath, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"wrote {outpath}")


def main():
    a2 = longest_crossed_tw_rows(load_curves(CURVE_B2), 2)
    a3 = longest_crossed_tw_rows(load_curves(CURVE_B3), 3)
    a4 = longest_crossed_tw_rows(load_curves(CURVE_B4), 4)
    anchors = merge_anchors(a2, a3, a4)
    vertex = [
        a
        for a in anchors
        if a["crossed"] == 1
        and math.isfinite(a["tauAlpha"])
        and a["tauAlpha"] > 0
        and a["batch"] >= 2
    ]
    voronoi = load_voronoi(VORONOI_CSV)

    rec_rows = []
    tg_rows = []
    Tg_v = {}
    Tg_o = {}
    for p0 in P0_ORDER:
        vtab = meas_table(vertex, p0)
        otab = [(z["T"], z["tauAlpha"]) for z in voronoi if abs(z["p0"] - p0) < 1e-4]
        otab.sort(key=lambda x: -x[0])
        if len(vtab) < 2 or len(otab) < 2:
            raise SystemExit(f"need >=2 points for p0={p0}")
        Tv, how_v = tg_how(vtab)
        To, how_o = tg_how(otab)
        Tg_v[p0] = Tv
        Tg_o[p0] = To
        tg_rows.append(
            {
                "p0": f"{p0:.3f}",
                "Tg_vertex": f"{Tv:.8g}",
                "how_vertex": how_v,
                "Tg_voronoi": f"{To:.8g}",
                "how_voronoi": how_o,
                "Tg_vertex_over_Tg_voronoi": f"{Tv / To:.6g}",
            }
        )
        for tau_k in TAU_TARGETS:
            T, how = invert_T_for_tau_meas(vtab, tau_k)
            rec_rows.append(
                {
                    "p0": f"{p0:.3f}",
                    "tauAlphaEst": f"{tau_k:.6g}",
                    "T": f"{T:.8g}",
                    "how": how,
                }
            )

    OUTDIR.mkdir(parents=True, exist_ok=True)
    write_csv(
        OUTDIR / "vertex_longest_crossed.csv",
        ["p0", "T", "waitingTime", "tauAlpha", "batch"],
        [
            {
                "p0": f"{a['p0']:.3f}",
                "T": f"{a['T']:.8g}",
                "waitingTime": f"{a['waitingTime']:.8g}",
                "tauAlpha": f"{a['tauAlpha']:.8g}",
                "batch": a["batch"],
            }
            for a in sorted(vertex, key=lambda z: (z["p0"], -z["T"]))
        ],
    )
    write_csv(
        OUTDIR / "recommended_T.csv",
        ["p0", "T", "tauAlphaEst", "how"],
        rec_rows,
    )
    write_csv(
        OUTDIR / "Tg.csv",
        [
            "p0",
            "Tg_vertex",
            "how_vertex",
            "Tg_voronoi",
            "how_voronoi",
            "Tg_vertex_over_Tg_voronoi",
        ],
        tg_rows,
    )
    plot_comparison(
        vertex,
        voronoi,
        Tg_v,
        Tg_o,
        OUTDIR / "vertex_voronoi_tau_and_Angell.png",
    )


if __name__ == "__main__":
    main()
