#!/usr/bin/env python3
"""
Generated by Cursor. 2026-09-23.
Replica CRSISF at the four coldest T of each p0, one panel per p0.

Physics:
  F_s^CR(q, dt) = (1/N) sum_j J_0(q |dr_j^CR|), tracer = cell centroid, q=6.7.
  Thin lines are idx replicas. The thick line is their mean on the overlapping
  positive-dt window. Color is temperature within that panel (cold blue, warm red).
  Dotted line is 1/e.

Usage:
  python3 plot_fs_replicas_cold4.py
"""

from __future__ import annotations

from collections import defaultdict
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.colors import LogNorm

from measure_and_plot_tau_alpha import FS_NAME, INV_E, read_two_values
from plot_vertex_production_fs import P0_ORDER, Q, _combined_axes, match_p0, mean_curve, scratch_fs

HERE = Path(__file__).resolve().parent
OUT = HERE / "vertexModel_productionFs" / "round2" / "fs_replicas_cold4.png"
N_COLD = 4


def main() -> None:
    by_key: dict[tuple[float, float], list[tuple[np.ndarray, np.ndarray]]] = defaultdict(list)
    root = scratch_fs()
    for nc in sorted(root.glob("p*/timeCRSISF_*.nc")):
        m = FS_NAME.search(nc.name)
        if not m or abs(float(m.group("k")) - Q) > 0.02:
            continue
        p0 = match_p0(float(m.group("p0")))
        if p0 is None:
            continue
        T = float(m.group("T"))
        dt, fs = read_two_values(nc)
        order = np.argsort(dt)
        by_key[(p0, T)].append((dt[order], fs[order]))

    fig, axes = _combined_axes(fig_w=14.2, fig_h=8.2)
    cmap = plt.get_cmap("coolwarm")
    for ax, p0 in zip(axes, P0_ORDER):
        Ts = sorted({T for pp, T in by_key if abs(pp - p0) < 1e-6})
        cold = Ts[:N_COLD]
        if len(cold) < 2 or cold[0] <= 0 or cold[0] == cold[-1]:
            norm = None
        else:
            norm = LogNorm(vmin=cold[0], vmax=cold[-1])
        for T in cold:
            color = cmap(0.5 if norm is None else norm(T))
            curves = by_key[(p0, T)]
            for dt, fs in curves:
                ax.plot(dt, fs, color=color, lw=0.7, alpha=0.45)
            tgrid, mean = mean_curve(curves)
            ax.plot(tgrid, mean, color=color, lw=2.0, label=rf"$T={T:.4g}$", zorder=5)
            print(f"p0={p0:.3f} T={T:.8g} n={len(curves)}")
        ax.axhline(INV_E, color="0.45", ls=":", lw=1.0)
        ax.set_xscale("log")
        ax.set_ylim(-0.05, 1.08)
        row, col = divmod(P0_ORDER.index(p0), 3)
        if row == 1:
            ax.set_xlabel(r"$\Delta t$", fontsize=16)
        if col == 0:
            ax.set_ylabel(r"$F_s^{\mathrm{CR}}$", fontsize=16)
        ax.legend(fontsize=8, frameon=False, loc="lower left")
    png = OUT
    png.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(png, dpi=150)
    plt.close(fig)
    print(f"wrote {png}")


if __name__ == "__main__":
    main()
