#!/usr/bin/env python3
"""
Generated by Cursor. 2026-09-14.
Plot mean S(q) of vertex production cell centroids, one panel per p0.

Physics:
  S(q) is the isotropic annular average of |sum_n exp(i K · r_n)|^2 / N
  with r_n = cell centroids, K on the first-quadrant 2 pi / L lattice
  (same as structuralFeatures::computeStructureFactor). Each (p0, T) is
  the mean over the last 10 log-spaced frames of idx=0..9.
  First-peak q is the argmax on q in [5, 8] with 3-point parabola.

Color: coolwarm, independent LogNorm per p0 (coldest T blue, hottest red).
No colorbars.

Usage:
  python3 plot_vertex_production_sq.py
  CELLGPU_SCRATCH=... python3 plot_vertex_production_sq.py
"""

from __future__ import annotations

import csv
import math
import os
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.colors import LogNorm

HERE = Path(__file__).resolve().parent
OUTDIR = HERE / "vertexModel_productionSq"
CSV_STATES = HERE / "vertexModel_tauAlpha_final" / "production_state_points.csv"
P0_ORDER = (3.750, 3.775, 3.800, 3.815, 3.825, 3.850)
N = 4096
Q_PEAK_LO = 5.0
Q_PEAK_HI = 8.0
Q_PLOT_LO = 1.0
Q_PLOT_HI = 12.0

FS_TITLE = 17
FS_LABEL = 16
FS_TICK = 14


def scratch_root() -> Path:
    env = os.environ.get("CELLGPU_SCRATCH")
    if env:
        return Path(env)
    return Path("/scratch/bbtm/cli6/glassyDynamics/data")


def sq_path(p0: float, T: float) -> Path:
    return (
        scratch_root()
        / f"N{N}"
        / "vertex"
        / "productionRuns"
        / "structureFactor"
        / f"sq_N{N}_p{p0:.4f}_T{T:.8f}.nc"
    )


def read_two_values(path: Path):
    try:
        from netCDF4 import Dataset

        with Dataset(path, "r") as ds:
            q = np.array(ds.variables["firstValue"][:], dtype=float)
            s = np.array(ds.variables["secondValue"][:], dtype=float)
        return q, s
    except Exception:
        pass
    from scipy.io import netcdf_file

    with netcdf_file(path, "r", mmap=False) as ds:
        q = np.array(ds.variables["firstValue"].data, dtype=float)
        s = np.array(ds.variables["secondValue"].data, dtype=float)
    return q, s


def load_state_points() -> list[tuple[float, float]]:
    rows: list[tuple[float, float]] = []
    with CSV_STATES.open() as f:
        lines = (ln for ln in f if ln.strip() and not ln.lstrip().startswith("#"))
        for r in csv.DictReader(lines):
            p0 = float(r["p0"])
            T = float(r["T"])
            if math.isfinite(p0) and math.isfinite(T) and T > 0:
                rows.append((p0, T))
    return rows


def match_p0(p0: float) -> float | None:
    m = min(P0_ORDER, key=lambda p: abs(p - p0))
    if abs(m - p0) > 1e-4:
        return None
    return m


def q_peak(q: np.ndarray, s: np.ndarray) -> tuple[float, float]:
    """Argmax of S on [5, 8], then 3-point parabolic interpolation."""
    mask = (q >= Q_PEAK_LO) & (q <= Q_PEAK_HI) & np.isfinite(s)
    if not np.any(mask):
        return math.nan, math.nan
    qi = q[mask]
    si = s[mask]
    i = int(np.argmax(si))
    smax = float(si[i])
    if i <= 0 or i >= si.size - 1:
        return float(qi[i]), smax
    y0, y1, y2 = float(si[i - 1]), float(si[i]), float(si[i + 1])
    denom = y0 - 2.0 * y1 + y2
    if abs(denom) < 1e-18:
        return float(qi[i]), smax
    delta = 0.5 * (y0 - y2) / denom
    if abs(delta) > 1.0:
        return float(qi[i]), smax
    dq = float(qi[i] - qi[i - 1])
    qhat = float(qi[i]) + delta * dq
    shat = y1 - 0.25 * (y0 - y2) * delta
    return qhat, float(shat)


def _combined_axes(fig_w: float = 13.6, fig_h: float = 8.0):
    fig = plt.figure(figsize=(fig_w, fig_h))
    gs = fig.add_gridspec(
        2,
        3,
        left=0.07,
        right=0.98,
        top=0.95,
        bottom=0.09,
        wspace=0.26,
        hspace=0.24,
    )
    axes = []
    for i, p0 in enumerate(P0_ORDER):
        row, col = divmod(i, 3)
        ax = fig.add_subplot(gs[row, col])
        ax.set_title(rf"$p_0={p0:.3f}$", fontsize=FS_TITLE, pad=4)
        ax.tick_params(labelsize=FS_TICK)
        axes.append(ax)
    return fig, axes


def main() -> None:
    OUTDIR.mkdir(parents=True, exist_ok=True)
    by_p0: dict[float, list[tuple[float, np.ndarray, np.ndarray]]] = {p: [] for p in P0_ORDER}
    peaks: list[tuple[float, float, float, float]] = []
    missing: list[tuple[float, float]] = []

    for p0_raw, T in load_state_points():
        p0 = match_p0(p0_raw)
        if p0 is None:
            continue
        path = sq_path(p0, T)
        if not path.is_file():
            missing.append((p0, T))
            continue
        q, s = read_two_values(path)
        by_p0[p0].append((T, q, s))
        qp, sp = q_peak(q, s)
        peaks.append((p0, T, qp, sp))

    if missing:
        print(f"missing {len(missing)} S(q) files:")
        for p0, T in missing:
            print(f"  p0={p0:.3f} T={T:.8f} -> {sq_path(p0, T)}")

    cmap = plt.get_cmap("coolwarm")
    fig, axes = _combined_axes()
    for i, p0 in enumerate(P0_ORDER):
        ax = axes[i]
        curves = sorted(by_p0[p0], key=lambda z: z[0])
        if not curves:
            ax.text(0.5, 0.5, "no data", ha="center", va="center", transform=ax.transAxes)
            continue
        Ts = [z[0] for z in curves]
        tmin, tmax = min(Ts), max(Ts)
        if tmin <= 0 or tmin == tmax:
            norm = None
        else:
            norm = LogNorm(vmin=tmin, vmax=tmax)
        for T, q, s in curves:
            if norm is None:
                color = cmap(0.5)
            else:
                color = cmap(norm(T))
            m = (q >= Q_PLOT_LO) & (q <= Q_PLOT_HI)
            ax.plot(q[m], s[m], color=color, lw=1.3)
        ax.set_xlim(Q_PLOT_LO, Q_PLOT_HI)
        ax.set_ylim(bottom=0)
        row, col = divmod(i, 3)
        if row == 1:
            ax.set_xlabel(r"$q$", fontsize=FS_LABEL)
        if col == 0:
            ax.set_ylabel(r"$S(q)$", fontsize=FS_LABEL)

    png = OUTDIR / "sq_vs_q_all_p0.png"
    fig.savefig(png, dpi=150)
    plt.close(fig)
    print(f"wrote {png}")

    peak_csv = OUTDIR / "sq_first_peak.csv"
    with peak_csv.open("w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["p0", "T", "q_peak", "S_peak"])
        for row in peaks:
            w.writerow([f"{row[0]:.3f}", f"{row[1]:.8g}", f"{row[2]:.6f}", f"{row[3]:.6f}"])
    print(f"wrote {peak_csv}")

    print()
    print("| p0 | T | q_peak | S_peak |")
    print("| --- | --- | --- | --- |")
    for p0, T, qp, sp in peaks:
        print(f"| {p0:.3f} | {T:.8g} | {qp:.4f} | {sp:.4f} |")
    if missing:
        raise SystemExit(1)


if __name__ == "__main__":
    main()
