#!/usr/bin/env python3
"""
Generated by Cursor. 2026-08-31.
Vertex-model stress autocorrelation and mean sigma_xy for tau_alpha scouting.

Physics:
  C_sigma(dt) = <sigma_xy(t) sigma_xy(t+dt)> from the Ramirez multi-tau
  correlator (evaluate(false); not mean-subtracted). The driver starts SAC
  samples after 10 production blocks of length
  tau_block = max(tau_est, 1000) (reduced time). sigma_xy is sampled every
  100 dt from the start of production; we average only t >= 10 tau_block.
  SAC figure: log Delta t vs log (C_sigma / T). C_sigma/T is the
  temperature-normalized correlator (Green-Kubo G(t) factor, no extra
  volume prefactor). Positive C_sigma only.

  SAC NetCDF: firstValue = C_sigma, secondValue = dt.
  sigmaXY NetCDF: firstValue = t, secondValue = sigma_xy.
  Units: reduced kT, target shape index p0, reduced time.

Usage:
  python3 plot_vertex_sac_and_sigma.py
  CELLGPU_SCRATCH=... python3 plot_vertex_sac_and_sigma.py --n 4096
"""

from __future__ import annotations

import argparse
import csv
import os
import re
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.cm import ScalarMappable
from matplotlib.colors import Normalize

HERE = Path(__file__).resolve().parent
OUTDIR = HERE / "vertexModel_tauAlpha_final"
CROSSED_CSV = OUTDIR / "vertex_longest_crossed.csv"
STATE_CSVS = (
    HERE / "vertexModel_tauAlpha_batch2" / "state_points.csv",
    HERE / "vertexModel_tauAlpha_batch3" / "state_points.csv",
    HERE / "vertexModel_tauAlpha_batch4" / "state_points.csv",
)
P0_ORDER = (3.750, 3.775, 3.800, 3.815, 3.825, 3.850)
N_DEFAULT = 4096
IDX = 0

SAC_RE = re.compile(
    r"SACtime_N(?P<n>\d+)_p(?P<p0>[0-9.]+)_T(?P<T>[0-9.eE+-]+)"
    r"_waitingTime(?P<tw>[0-9.]+)_idx(?P<idx>\d+)\.nc$"
)
SIG_RE = re.compile(
    r"sigmaXY_N(?P<n>\d+)_p(?P<p0>[0-9.]+)_T(?P<T>[0-9.eE+-]+)"
    r"_idx(?P<idx>\d+)\.nc$"
)


def read_two_values(path: Path):
    """Load (firstValue, secondValue) from twoValuesDatabase NetCDF."""
    try:
        from netCDF4 import Dataset

        with Dataset(path, "r") as ds:
            a = np.array(ds.variables["firstValue"][:], dtype=float)
            b = np.array(ds.variables["secondValue"][:], dtype=float)
        return a, b
    except Exception:
        pass
    from scipy.io import netcdf_file

    with netcdf_file(path, "r", mmap=False) as ds:
        a = np.array(ds.variables["firstValue"].data, dtype=float)
        b = np.array(ds.variables["secondValue"].data, dtype=float)
    return a, b


def load_crossed(path: Path):
    rows = []
    with path.open() as f:
        for r in csv.DictReader(f):
            rows.append(
                {
                    "p0": float(r["p0"]),
                    "T": float(r["T"]),
                    "waitingTime": float(r["waitingTime"]),
                    "tauAlpha": float(r["tauAlpha"]),
                    "batch": int(r["batch"]),
                }
            )
    return rows


def load_tau_est_map():
    """(p0, T) -> tauAlphaEst; later batch files override."""
    out = {}
    for path in STATE_CSVS:
        with path.open() as f:
            for r in csv.DictReader(f):
                p0 = float(r["p0"])
                T = float(r["T"])
                est = float(r["tauAlphaEst"])
                out[(p0, T)] = est
    return out


def tau_block(tau_est: float) -> float:
    return max(1000.0, tau_est)


def match_T(T_file: float, T_csv: float, rel: float = 2e-5) -> bool:
    return abs(T_file - T_csv) / max(abs(T_csv), 1e-30) < rel


def match_p0(p_file: float, p_csv: float) -> bool:
    return abs(p_file - p_csv) < 1e-4


def lookup_tau_est(est_map, p0: float, T: float):
    for (p, t), est in est_map.items():
        if match_p0(p, p0) and match_T(t, T):
            return est
    return None


def index_dir(folder: Path, n: int, kind: str):
    """Map (p0, T rounded from filename) -> path. Prefer exact n and idx=0."""
    if kind == "sac":
        pat = f"SACtime_N{n}_p*_T*_waitingTime*_idx{IDX}.nc"
        cre = SAC_RE
    else:
        pat = f"sigmaXY_N{n}_p*_T*_idx{IDX}.nc"
        cre = SIG_RE
    by_key = {}
    if not folder.is_dir():
        return by_key
    for path in folder.glob(pat):
        m = cre.search(path.name)
        if m is None:
            continue
        p0 = float(m.group("p0"))
        T = float(m.group("T"))
        extra = {}
        if kind == "sac":
            extra["waitingTime"] = float(m.group("tw"))
        by_key[(p0, T)] = (path, extra)
    return by_key


def find_file(index, p0: float, T: float):
    for (p, t), val in index.items():
        if match_p0(p, p0) and match_T(t, T):
            return val
    return None


def p0_dir(scratch: Path, n: int, p0: float) -> Path:
    return scratch / f"N{n}" / "vertex" / f"p{p0:.3f}"


def collect_points(scratch: Path, n: int, rows, est_map):
    sac_found = []
    sig_found = []
    miss_sac = []
    miss_sig = []
    sac_index = {}
    sig_index = {}
    for p0 in P0_ORDER:
        d = p0_dir(scratch, n, p0)
        sac_index[p0] = index_dir(d, n, "sac")
        sig_index[p0] = index_dir(d, n, "sig")

    for r in rows:
        p0, T = r["p0"], r["T"]
        est = lookup_tau_est(est_map, p0, T)
        tb = tau_block(est) if est is not None else None
        sac_hit = find_file(sac_index[p0], p0, T)
        if sac_hit is None:
            miss_sac.append((p0, T, r["batch"]))
        else:
            path, extra = sac_hit
            tw = extra.get("waitingTime")
            if tb is None and tw is not None:
                tb = tw
            sac_found.append(
                {
                    **r,
                    "path": path,
                    "tauAlphaEst": est,
                    "tauBlock": tb if tb is not None else tw,
                }
            )
        sig_hit = find_file(sig_index[p0], p0, T)
        if sig_hit is None:
            miss_sig.append((p0, T, r["batch"]))
        else:
            path, _ = sig_hit
            sig_found.append(
                {
                    **r,
                    "path": path,
                    "tauAlphaEst": est,
                    "tauBlock": tb,
                }
            )
    return sac_found, sig_found, miss_sac, miss_sig


def t_color(T: float, tmin: float, tmax: float, cmap):
    if tmax <= tmin:
        x = 0.5
    else:
        x = (T - tmin) / (tmax - tmin)
    return cmap(x)


def plot_sac_grid(sac_found, outpath: Path):
    cmap = plt.get_cmap("coolwarm")
    fig, axes = plt.subplots(2, 3, figsize=(11.5, 7.2), sharex=True)
    axes = axes.ravel()
    tmin = min(r["T"] for r in sac_found)
    tmax = max(r["T"] for r in sac_found)
    n_ok = 0
    n_fail = 0
    for ax, p0 in zip(axes, P0_ORDER):
        pts = sorted(
            [r for r in sac_found if abs(r["p0"] - p0) < 1e-4],
            key=lambda z: -z["T"],
        )
        ax.set_title(rf"$p_0={p0:.3f}$")
        ax.set_xscale("log")
        ax.set_yscale("log")
        for r in pts:
            try:
                c_sig, dt = read_two_values(r["path"])
            except Exception as e:
                print(f"SAC read fail {r['path']}: {e}")
                n_fail += 1
                continue
            order = np.argsort(dt)
            dt = dt[order]
            c_sig = c_sig[order]
            # Log-y: drop non-positive C_sigma (long-time noise around 0).
            pos = c_sig > 0
            if not np.any(pos):
                n_fail += 1
                continue
            ax.plot(
                dt[pos],
                c_sig[pos] / r["T"],
                color=t_color(r["T"], tmin, tmax, cmap),
                lw=1.1,
                alpha=0.9,
            )
            n_ok += 1
        ax.set_ylabel(r"$C_\sigma(\Delta t)/T$")
    for ax in axes[-3:]:
        ax.set_xlabel(r"$\Delta t$")
    sm = ScalarMappable(norm=Normalize(vmin=tmin, vmax=tmax), cmap=cmap)
    sm.set_array([])
    cbar = fig.colorbar(sm, ax=axes.tolist(), fraction=0.025, pad=0.02)
    cbar.set_label(r"$T$ (hot red, cold blue)")
    fig.suptitle(r"Vertex $C_\sigma/T$ (SAC after $10\,\tau_{\mathrm{block}}$)")
    fig.savefig(outpath, dpi=200, bbox_inches="tight")
    fig.savefig(outpath.with_suffix(".pdf"), bbox_inches="tight")
    plt.close(fig)
    print(f"wrote {outpath} ({n_ok} curves, {n_fail} read fails)")


def mean_sigma_after_wait(path: Path, t_cut: float):
    t, sig = read_two_values(path)
    mask = t >= t_cut
    if not np.any(mask):
        return float("nan"), 0
    sel = sig[mask]
    return float(np.mean(sel)), int(sel.size)


def plot_sigma_vs_T(sig_found, outpath: Path, csv_path: Path):
    cmap = plt.get_cmap("coolwarm_r")
    colors = cmap(np.linspace(0.05, 0.95, len(P0_ORDER)))
    fig, ax = plt.subplots(figsize=(6.4, 4.6))
    csv_rows = []
    for i, p0 in enumerate(P0_ORDER):
        pts = sorted(
            [r for r in sig_found if abs(r["p0"] - p0) < 1e-4],
            key=lambda z: -z["T"],
        )
        Ts = []
        means = []
        for r in pts:
            tb = r["tauBlock"]
            if tb is None or not np.isfinite(tb):
                print(f"skip sigma mean (no tau_block): p0={p0} T={r['T']}")
                continue
            t_cut = 10.0 * tb
            try:
                mean_s, n_samp = mean_sigma_after_wait(r["path"], t_cut)
            except Exception as e:
                print(f"sigmaXY read fail {r['path']}: {e}")
                continue
            csv_rows.append(
                {
                    "p0": f"{p0:.3f}",
                    "T": f"{r['T']:.8g}",
                    "batch": r["batch"],
                    "tauAlphaEst": ""
                    if r["tauAlphaEst"] is None
                    else f"{r['tauAlphaEst']:.8g}",
                    "tauBlock": f"{tb:.8g}",
                    "tCut": f"{t_cut:.8g}",
                    "nSamp": n_samp,
                    "sigmaXY_mean": f"{mean_s:.8g}" if np.isfinite(mean_s) else "",
                }
            )
            if np.isfinite(mean_s) and n_samp > 0:
                Ts.append(r["T"])
                means.append(mean_s)
        if Ts:
            ax.plot(
                Ts,
                means,
                "o-",
                color=colors[i],
                ms=5,
                lw=1.0,
                label=rf"$p_0={p0:.3f}$",
            )
    ax.axhline(0.0, color="0.5", lw=0.7, zorder=0)
    ax.set_xlabel(r"$T$")
    ax.set_ylabel(r"$\overline{\sigma}_{xy}$ ($t \geq 10\tau_{\mathrm{block}}$)")
    ax.set_xscale("log")
    ax.legend(frameon=False, fontsize=8)
    fig.tight_layout()
    fig.savefig(outpath, dpi=200)
    fig.savefig(outpath.with_suffix(".pdf"))
    plt.close(fig)
    print(f"wrote {outpath} ({len(csv_rows)} rows)")
    with csv_path.open("w", newline="") as f:
        w = csv.DictWriter(
            f,
            fieldnames=[
                "p0",
                "T",
                "batch",
                "tauAlphaEst",
                "tauBlock",
                "tCut",
                "nSamp",
                "sigmaXY_mean",
            ],
        )
        w.writeheader()
        w.writerows(csv_rows)
    print(f"wrote {csv_path}")


def print_miss(label, miss):
    if not miss:
        print(f"{label}: none missing")
        return
    print(f"{label}: {len(miss)} missing")
    for p0, T, batch in miss[:30]:
        print(f"  p0={p0:.3f} T={T:.8g} batch={batch}")
    if len(miss) > 30:
        print(f"  ... {len(miss) - 30} more")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--n", type=int, default=N_DEFAULT)
    ap.add_argument(
        "--scratch",
        type=Path,
        default=None,
        help="data root; default CELLGPU_SCRATCH or Delta scratch",
    )
    args = ap.parse_args()
    scratch = args.scratch
    if scratch is None:
        scratch = Path(
            os.environ.get(
                "CELLGPU_SCRATCH", "/scratch/bbtm/cli6/glassyDynamics/data"
            )
        )
    rows = load_crossed(CROSSED_CSV)
    est_map = load_tau_est_map()
    sac_found, sig_found, miss_sac, miss_sig = collect_points(
        scratch, args.n, rows, est_map
    )
    print(f"scratch={scratch}  N={args.n}  state points={len(rows)}")
    print(f"SAC found={len(sac_found)}  sigmaXY found={len(sig_found)}")
    print_miss("SAC", miss_sac)
    print_miss("sigmaXY", miss_sig)
    OUTDIR.mkdir(parents=True, exist_ok=True)
    if sac_found:
        plot_sac_grid(sac_found, OUTDIR / "vertex_SAC_vs_t_by_p0.png")
    else:
        print("no SAC files; skip C_sigma figure")
    if sig_found:
        plot_sigma_vs_T(
            sig_found,
            OUTDIR / "vertex_sigmaXY_mean_vs_T.png",
            OUTDIR / "vertex_sigmaXY_mean_vs_T.csv",
        )
    else:
        print("no sigmaXY files; skip mean-sigma figure")


if __name__ == "__main__":
    main()
