#!/usr/bin/env python3
"""
Generated by Cursor. 2026-09-02.
tau_alpha vs T for vertex T1-threshold scan (one figure per p0).

Physics:
  T1 fires when edge length < l_T1 (mean cell area 1). tau_alpha is the
  CRSISF 1/e crossing of cell centroids at q=6.80. Per (l_T1, T) keep the
  longest t_w that still crosses 1/e (no extrapolation).
  t1Scan: l_T1 from 1e-4 through 0.1 (p0=3.800 already on scratch; other
  p0 from state_points_all_p0.csv after those jobs finish).
  l_T1 = 0.01 is the default-threshold scouting curve (nearby T, not the
  recommended grid). Overlay 2D Voronoi SISF 1/e at the same p0.

Usage:
  python3 glassyDynamicsProject/analyseScripts/vertexTauAlpha/plot_vertex_t1_tau_alpha.py
"""

from __future__ import annotations

import csv
import math
import os
import re
import sys
from pathlib import Path

import matplotlib.pyplot as plt

HERE = Path(__file__).resolve().parent
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))

from measure_and_plot_tau_alpha import Q_DEFAULT, FS_NAME, read_two_values, tau_alpha_one_over_e

OUTDIR = HERE / "vertexModel_t1Scan"
LONGEST_CSV = HERE / "vertexModel_tauAlpha_final" / "vertex_longest_crossed.csv"
VORONOI_CSV = HERE.parent / "TauAlphaTable" / "data_2DVoronoi" / "tauAlpha_2DVoronoi_all.csv"
T1_TAG = re.compile(r"/t1_([^/]+)/")
P0 = 3.800
P0_ORDER = (3.750, 3.775, 3.800, 3.815, 3.825, 3.850)
N = 4096
MARKERS = ["o", "s", "D", "^", "v", "P", "X", "<", ">", "h", "p"]

# Small l_T1 (harder T1s) to large. Color from colormap in plot_tau_vs_T.
T1_ORDER = [
    1e-4,
    1e-3,
    0.0015,
    0.0022,
    0.0032,
    0.0046,
    0.0068,
    1e-2,
    0.02,
    0.03,
    0.04,
    0.05,
    0.06,
    0.07,
    0.08,
    0.09,
    1e-1,
]


def t1_label(t1: float) -> str:
    lg = math.log10(t1)
    e = int(round(lg))
    if abs(lg - e) < 1e-8:
        inner = rf"10^{{{e}}}"
    else:
        inner = f"{t1:g}"
    if abs(t1 / 0.01 - 1.0) < 1e-6:
        return rf"$\ell_{{T1}}={inner}$ (default)"
    return rf"$\ell_{{T1}}={inner}$"


def scratch_t1_root(n: int) -> Path:
    env = os.environ.get("CELLGPU_SCRATCH", "/scratch/bbtm/cli6/glassyDynamics/data")
    return Path(env) / f"N{n}" / "vertex" / "t1Scan"


def t1_from_path(path: Path) -> float | None:
    m = T1_TAG.search(str(path))
    if not m:
        return None
    return float(m.group(1))


def collect_t1_scan_rows(n: int) -> list[dict]:
    root = scratch_t1_root(n)
    rows = []
    if not root.is_dir():
        print(f"no t1Scan dir {root}")
        return rows
    for nc in sorted(root.glob("t1_*/tauAlphaData/p*/timeCRSISF_*.nc")):
        m = FS_NAME.search(nc.name)
        if not m:
            continue
        qk = float(m.group("k"))
        if abs(qk - Q_DEFAULT) > 0.02:
            continue
        t1 = t1_from_path(nc)
        if t1 is None:
            continue
        dt, fs = read_two_values(nc)
        tau, crossed = tau_alpha_one_over_e(dt, fs)
        rows.append(
            {
                "t1": t1,
                "p0": float(m.group("p0")),
                "T": float(m.group("T")),
                "waitingTime": float(m.group("tw")),
                "tauAlpha": tau,
                "crossed": int(crossed),
                "n": int(m.group("n")),
                "idx": int(m.group("idx")),
                "source": "t1Scan",
            }
        )
    return rows


def longest_crossed(rows: list[dict]) -> list[dict]:
    best = {}
    for r in rows:
        if not r["crossed"] or not math.isfinite(r["tauAlpha"]):
            continue
        key = (r["t1"], r["T"])
        prev = best.get(key)
        if prev is None or r["waitingTime"] > prev["waitingTime"]:
            best[key] = dict(r)
    return [best[k] for k in sorted(best)]


def load_default_threshold(path: Path, p0: float = P0) -> list[dict]:
    out = []
    with path.open() as f:
        for r in csv.DictReader(f):
            if abs(float(r["p0"]) - p0) > 1e-4:
                continue
            tau = float(r["tauAlpha"])
            if not (math.isfinite(tau) and tau > 0):
                continue
            out.append(
                {
                    "t1": 0.01,
                    "p0": p0,
                    "T": float(r["T"]),
                    "waitingTime": float(r["waitingTime"]),
                    "tauAlpha": tau,
                    "crossed": 1,
                    "n": N,
                    "idx": 0,
                    "source": "longest_crossed",
                }
            )
    return out


def load_voronoi_p0(path: Path, p0: float = P0) -> list[dict]:
    out = []
    with path.open() as f:
        for r in csv.DictReader(f):
            if abs(float(r["p0"]) - p0) > 1e-4:
                continue
            tau = float(r["tauAlpha"])
            if not (math.isfinite(tau) and tau > 0):
                continue
            out.append(
                {
                    "t1": "",
                    "p0": p0,
                    "T": float(r["T"]),
                    "waitingTime": "",
                    "tauAlpha": tau,
                    "crossed": 1,
                    "n": N,
                    "idx": 0,
                    "source": "voronoi",
                }
            )
    out.sort(key=lambda r: r["T"])
    return out


def write_csv(path: Path, rows: list[dict]):
    path.parent.mkdir(parents=True, exist_ok=True)
    fields = ["t1", "p0", "T", "waitingTime", "tauAlpha", "crossed", "n", "idx", "source"]
    with path.open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fields)
        w.writeheader()
        for r in rows:
            w.writerow(r)
    print(f"wrote {path} ({len(rows)} rows)")


def n_for_t1(t1: float, counts: dict) -> int:
    for k, v in counts.items():
        if abs(k / t1 - 1.0) < 1e-6:
            return v
    return 0


def plot_tau_vs_T(
    rows: list[dict],
    path: Path,
    n_scan_by_t1: dict | None = None,
    voronoi: list[dict] | None = None,
    p0: float = P0,
):
    fig, ax = plt.subplots(figsize=(7.2, 5.4))
    n_scan_by_t1 = n_scan_by_t1 or {}
    found = []
    for t1 in T1_ORDER:
        if any(isinstance(r["t1"], (int, float)) and abs(r["t1"] / t1 - 1.0) < 1e-6 for r in rows) or n_for_t1(
            t1, n_scan_by_t1
        ):
            found.append(t1)
    cmap = plt.get_cmap("viridis")
    nfound = max(len(found), 1)
    for i, t1 in enumerate(found):
        sub = sorted(
            (
                r
                for r in rows
                if isinstance(r["t1"], (int, float)) and r["t1"] != "" and abs(float(r["t1"]) / t1 - 1.0) < 1e-6
            ),
            key=lambda r: r["T"],
        )
        color = cmap(0.08 + 0.84 * i / max(nfound - 1, 1))
        marker = MARKERS[i % len(MARKERS)]
        label = t1_label(t1)
        nfiles = n_for_t1(t1, n_scan_by_t1)
        if not sub:
            if nfiles:
                label = label + " (no 1/e crossing)"
            ax.plot([], [], linestyle="None", color=color, marker=marker, label=label)
            continue
        if abs(t1 / 0.1 - 1.0) < 1e-6 and nfiles and nfiles < 50:
            label = label + " (partial FS)"
        ax.plot(
            [r["T"] for r in sub],
            [r["tauAlpha"] for r in sub],
            linestyle="-",
            markersize=6,
            color=color,
            marker=marker,
            label=label,
        )
    if voronoi:
        ax.plot(
            [r["T"] for r in voronoi],
            [r["tauAlpha"] for r in voronoi],
            linestyle="None",
            marker="s",
            markersize=7,
            markerfacecolor="none",
            markeredgecolor="k",
            label="Voronoi",
            zorder=5,
        )
    ax.set_xscale("log")
    ax.set_yscale("log")
    ax.set_xlabel(r"$T$")
    ax.set_ylabel(r"$\tau_\alpha$ (CRSISF $1/e$)")
    ax.set_title(rf"$N={N}$, $p_0={p0:.3f}$")
    ax.legend(loc="best", frameon=False, fontsize=8)
    fig.tight_layout()
    path.parent.mkdir(parents=True, exist_ok=True)
    fig.savefig(path, dpi=150)
    plt.close(fig)
    print(f"wrote {path}")


def main():
    scan = collect_t1_scan_rows(N)
    n_cross = sum(1 for r in scan if r["crossed"])
    print(f"t1Scan CRSISF files: {len(scan)}, crossed 1/e: {n_cross}")
    if not scan:
        sys.exit("no t1Scan CRSISF; run submitVertexTauAlphaFsT1.sh first")
    n_wrote = 0
    for p0 in P0_ORDER:
        scan_p = [r for r in scan if abs(r["p0"] - p0) < 1e-4]
        if not scan_p:
            print(f"skip p0={p0:.3f}: no t1Scan CRSISF")
            continue
        n_scan_by_t1 = {}
        for r in scan_p:
            n_scan_by_t1[r["t1"]] = n_scan_by_t1.get(r["t1"], 0) + 1
        rows = longest_crossed(scan_p)
        rows.extend(load_default_threshold(LONGEST_CSV, p0))
        rows.sort(key=lambda r: (r["t1"], r["T"]))
        voronoi = load_voronoi_p0(VORONOI_CSV, p0)
        tag = f"p{p0:.3f}"
        write_csv(OUTDIR / f"vertex_t1_tau_vs_T_{tag}.csv", rows + voronoi)
        plot_tau_vs_T(
            rows,
            OUTDIR / f"vertex_t1_tau_vs_T_{tag}.png",
            n_scan_by_t1,
            voronoi,
            p0,
        )
        if abs(p0 - P0) < 1e-6:
            write_csv(OUTDIR / "vertex_t1_tau_vs_T.csv", rows + voronoi)
            plot_tau_vs_T(
                rows, OUTDIR / "vertex_t1_tau_vs_T.png", n_scan_by_t1, voronoi, p0
            )
        n_wrote += 1
    if n_wrote == 0:
        sys.exit("no t1Scan CRSISF matched P0_ORDER")


if __name__ == "__main__":
    main()
