#!/usr/bin/env python3
"""
Generated by Cursor. 2026-09-28.
Vertex edge-length PDF from existing statDist dumps (no new C++).

Physics (mean cell area A0=1, KA=KP=1):
  Regular hexagon of area 1 has side
    s_hex = sqrt(2/(3 sqrt(3))) = 3^{-3/4} sqrt(2) ~ 0.620
  and P_hex = 6 s_hex ~ 3.722.
  Vertex S(q) first peak sits near q_* = 4 pi / (3 s_hex) ~ 6.75 (honeycomb
  Bravais spacing), not at 2 pi / s_hex. P(ell) is the bonded-shell
  distribution of unique 3-valent mesh edges (stateCompareDump).
  Last N_KEEP=8 log-spaced frames, pooled. Units: length in sqrt(A0).

Usage:
  python3 plot_vertex_edge_hex.py
  CELLGPU_SCRATCH=... python3 plot_vertex_edge_hex.py
"""

from __future__ import annotations

import csv
import math
import os
from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt

HERE = Path(__file__).resolve().parent
DUMPS = HERE / "vertexModel_statDist" / "dumps"
OUTDIR = HERE / "vertexModel_statDist"
QMAP = HERE / "vertexModel_qMap" / "vertex_q_vs_T.csv"
SQ_PEAK = HERE / "vertexModel_vertexPositionSq" / "sq_first_peak.csv"
P0_ORDER = (3.750, 3.775, 3.800, 3.815, 3.825, 3.850)
N = 4096
HEX_SIDE = 3.0 ** (-0.75) * math.sqrt(2.0)
ELL_WIN_LO = 0.55
ELL_WIN_HI = 0.70
Q_SECOND = 4.0 * math.pi / math.sqrt(3.0) / HEX_SIDE  # sqrt(3) * 4pi/(3 s)

FS_TITLE = 17
FS_LABEL = 16
FS_TICK = 14
FS_LEGEND = 10


def scratch_root() -> Path:
    env = os.environ.get("CELLGPU_SCRATCH")
    if env:
        return Path(env)
    return Path("/scratch/bbtm/cli6/glassyDynamics/data")


def sq_path(p0: float, T: float) -> Path:
    return (
        scratch_root()
        / f"N{N}"
        / "vertex"
        / "productionRuns"
        / "vertexPositionSq"
        / f"sqVertex_N{N}_p{p0:.4f}_T{T:.8f}.nc"
    )


def match_p0(p0: float) -> float | None:
    m = min(P0_ORDER, key=lambda p: abs(p - p0))
    if abs(m - p0) > 1e-4:
        return None
    return m


def parse_vertex_edges(path: Path):
    name = path.name
    if not name.startswith("vertex_") or not name.endswith("_edges.csv"):
        return None
    body = name[len("vertex_") : -len("_edges.csv")]
    if not body.startswith("p") or "_T" not in body:
        return None
    ppart, tpart = body.split("_T", 1)
    try:
        p0 = match_p0(float(ppart[1:]))
        T = float(tpart)
    except ValueError:
        return None
    if p0 is None or not math.isfinite(T) or T <= 0:
        return None
    return p0, T


def load_col(path: Path, name: str):
    with path.open() as f:
        r = csv.DictReader(f)
        return np.array([float(row[name]) for row in r], dtype=float)


def load_keyed_csv(path: Path, keys: tuple[str, ...]) -> list[dict]:
    rows = []
    if not path.is_file():
        return rows
    with path.open() as f:
        for r in csv.DictReader(f):
            rec = {}
            for k in keys:
                rec[k] = float(r[k])
            rows.append(rec)
    return rows


def nearest(rows: list[dict], p0: float, T: float, tmax: float = 1e-6):
    best = None
    best_d = math.inf
    for r in rows:
        rp = match_p0(r["p0"])
        if rp is None or abs(rp - p0) > 1e-4:
            continue
        d = abs(r["T"] - T) / max(T, r["T"])
        if d < best_d:
            best_d = d
            best = r
    if best is None or best_d > tmax:
        return None, best_d
    return best, best_d


def hist_mode(ell: np.ndarray, bins: np.ndarray) -> float:
    counts, edges = np.histogram(ell, bins=bins)
    if counts.size == 0 or int(np.max(counts)) == 0:
        return math.nan
    i = int(np.argmax(counts))
    return 0.5 * (float(edges[i]) + float(edges[i + 1]))


def summarize(ell: np.ndarray, mean_P: float) -> dict:
    ell = ell[np.isfinite(ell) & (ell > 0)]
    n = int(ell.size)
    if n == 0:
        return {
            "n_ell": 0,
            "median_ell": math.nan,
            "mean_ell": math.nan,
            "std_ell": math.nan,
            "mode_ell": math.nan,
            "f_lt_shex": math.nan,
            "f_win": math.nan,
            "mean_P": mean_P,
            "mean_P_over_6": mean_P / 6.0 if math.isfinite(mean_P) else math.nan,
        }
    bins = np.linspace(0.2, 1.2, 101)
    return {
        "n_ell": n,
        "median_ell": float(np.median(ell)),
        "mean_ell": float(np.mean(ell)),
        "std_ell": float(np.std(ell, ddof=0)),
        "mode_ell": hist_mode(ell, bins),
        "f_lt_shex": float(np.mean(ell < HEX_SIDE)),
        "f_win": float(np.mean((ell >= ELL_WIN_LO) & (ell <= ELL_WIN_HI))),
        "mean_P": mean_P,
        "mean_P_over_6": mean_P / 6.0 if math.isfinite(mean_P) else math.nan,
    }


def read_sq(path: Path):
    try:
        from netCDF4 import Dataset

        with Dataset(path, "r") as ds:
            q = np.array(ds.variables["firstValue"][:], dtype=float)
            s = np.array(ds.variables["secondValue"][:], dtype=float)
        return q, s
    except Exception:
        pass
    try:
        from scipy.io import netcdf_file

        with netcdf_file(path, "r", mmap=False) as ds:
            q = np.array(ds.variables["firstValue"].data, dtype=float)
            s = np.array(ds.variables["secondValue"].data, dtype=float)
        return q, s
    except Exception:
        return None


def sq_at_q(q: np.ndarray, s: np.ndarray, q0: float) -> tuple[float, float]:
    m = np.isfinite(q) & np.isfinite(s)
    if not np.any(m):
        return math.nan, math.nan
    i = int(np.argmin(np.abs(q[m] - q0)))
    return float(s[m][i]), float(q[m][i])


def main() -> None:
    OUTDIR.mkdir(parents=True, exist_ok=True)
    dumps: dict[float, list[tuple[float, Path]]] = {p: [] for p in P0_ORDER}
    for path in sorted(DUMPS.glob("vertex_*_edges.csv")):
        parsed = parse_vertex_edges(path)
        if parsed is None:
            continue
        p0, T = parsed
        dumps[p0].append((T, path))
    for p0 in P0_ORDER:
        dumps[p0].sort(key=lambda z: z[0])

    qmap = load_keyed_csv(QMAP, ("p0", "T", "p6", "p5p7", "mean_P", "mean_q"))
    peaks = load_keyed_csv(SQ_PEAK, ("p0", "T", "q_peak", "S_peak", "q_argmax", "S_argmax"))

    chosen: list[dict] = []
    plot_data: dict[float, list[dict]] = {p: [] for p in P0_ORDER}
    for p0 in P0_ORDER:
        pts = dumps[p0]
        if not pts:
            print(f"no vertex edge dumps for p0={p0:.3f}")
            continue
        pick = [pts[0], pts[-1]] if len(pts) > 1 else [pts[0]]
        tags = ["cold", "hot"] if len(pick) == 2 else ["cold"]
        for tag, (T, epath) in zip(tags, pick):
            ell = load_col(epath, "ell")
            cpath = Path(str(epath).replace("_edges.csv", "_cells.csv"))
            mean_P = float(np.mean(load_col(cpath, "P"))) if cpath.is_file() else math.nan
            rec = summarize(ell, mean_P)
            rec.update({"p0": p0, "T": T, "which": tag, "ell": ell})
            qm, _ = nearest(qmap, p0, T, tmax=2e-4)
            if qm is not None:
                rec["p6"] = qm["p6"]
                rec["p5p7"] = qm["p5p7"]
                rec["mean_q"] = qm["mean_q"]
            else:
                rec["p6"] = rec["p5p7"] = rec["mean_q"] = math.nan
            pk, dpk = nearest(peaks, p0, T, tmax=1.0)
            if pk is not None:
                rec["q_peak"] = pk["q_peak"]
                rec["S_peak"] = pk["S_peak"]
                rec["q_argmax"] = pk["q_argmax"]
                rec["sq_T"] = pk["T"]
                rec["sq_T_rel"] = dpk
            else:
                rec["q_peak"] = rec["S_peak"] = rec["q_argmax"] = rec["sq_T"] = rec["sq_T_rel"] = math.nan
            rec["S_q11"] = math.nan
            rec["q_near_11"] = math.nan
            rec["S_q11_over_Speak"] = math.nan
            ncp = sq_path(p0, T)
            if (not ncp.is_file()) and math.isfinite(rec.get("sq_T", math.nan)):
                ncp = sq_path(p0, rec["sq_T"])
            sq = read_sq(ncp) if ncp.is_file() else None
            if sq is not None:
                q, s = sq
                sval, qn = sq_at_q(q, s, Q_SECOND)
                rec["S_q11"] = sval
                rec["q_near_11"] = qn
                sp = rec["S_peak"]
                if math.isfinite(sp) and sp > 0:
                    rec["S_q11_over_Speak"] = sval / sp
            chosen.append(rec)
            plot_data[p0].append(rec)

    fig = plt.figure(figsize=(13.6, 8.0))
    gs = fig.add_gridspec(
        2,
        3,
        left=0.07,
        right=0.98,
        top=0.94,
        bottom=0.09,
        wspace=0.28,
        hspace=0.28,
    )
    bins = np.linspace(0.2, 1.2, 81)
    for i, p0 in enumerate(P0_ORDER):
        row, col = divmod(i, 3)
        ax = fig.add_subplot(gs[row, col])
        ax.set_title(rf"$p_0={p0:.3f}$", fontsize=FS_TITLE, pad=4)
        ax.tick_params(labelsize=FS_TICK)
        ax.axvline(HEX_SIDE, color="0.35", ls="--", lw=1.1, zorder=3)
        for rec in plot_data[p0]:
            color = "C0" if rec["which"] == "cold" else "C3"
            ell = rec["ell"]
            ell = ell[np.isfinite(ell) & (ell > 0)]
            ax.hist(
                ell,
                bins=bins,
                density=True,
                histtype="step",
                color=color,
                lw=1.4,
                label=rf"{rec['which']} $T={rec['T']:.4g}$",
            )
            p6 = rec["mean_P_over_6"]
            ls = ":" if rec["which"] == "cold" else "-."
            if math.isfinite(p6):
                ax.axvline(p6, color=color, ls=ls, lw=1.0, zorder=2)
        ax.set_xlim(0.2, 1.2)
        ax.set_ylim(bottom=0)
        if row == 1:
            ax.set_xlabel(r"$\ell$", fontsize=FS_LABEL)
        if col == 0:
            ax.set_ylabel(r"$P(\ell)$", fontsize=FS_LABEL)
        ax.legend(fontsize=FS_LEGEND, loc="upper right", frameon=False)
    fig.text(
        0.07,
        0.01,
        rf"dashed $s_{{\mathrm{{hex}}}}={HEX_SIDE:.3f}$; "
        r"dotted/dash-dot $\langle P\rangle/6$",
        fontsize=11,
    )
    png = OUTDIR / "vertex_P_ell_hex_cold_hot.png"
    fig.savefig(png, dpi=150)
    plt.close(fig)
    print(f"wrote {png}")

    keys = [
        "p0",
        "T",
        "which",
        "n_ell",
        "median_ell",
        "mean_ell",
        "std_ell",
        "mode_ell",
        "f_lt_shex",
        "f_win",
        "mean_P",
        "mean_P_over_6",
        "p6",
        "p5p7",
        "mean_q",
        "q_peak",
        "S_peak",
        "q_argmax",
        "sq_T",
        "sq_T_rel",
        "S_q11",
        "q_near_11",
        "S_q11_over_Speak",
    ]
    csv_path = OUTDIR / "vertex_edge_hex_stats.csv"
    with csv_path.open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=keys, extrasaction="ignore")
        w.writeheader()
        for rec in chosen:
            row = {k: rec.get(k, math.nan) for k in keys}
            w.writerow(row)
    print(f"wrote {csv_path}")
    print(f"s_hex={HEX_SIDE:.6f} q_second={Q_SECOND:.4f}")
    print(
        "p0 T which median mode std f(<s_hex) f(0.55-0.70) "
        "<P>/6 p6 q_peak S(q~11.7)/S_peak"
    )
    for rec in chosen:
        print(
            f"{rec['p0']:.3f} {rec['T']:.8g} {rec['which']:4s} "
            f"{rec['median_ell']:.4f} {rec['mode_ell']:.4f} {rec['std_ell']:.4f} "
            f"{rec['f_lt_shex']:.3f} {rec['f_win']:.3f} "
            f"{rec['mean_P_over_6']:.4f} {rec['p6']:.3f} "
            f"{rec['q_peak']:.4f} {rec['S_q11_over_Speak']:.3f}"
        )


if __name__ == "__main__":
    main()
