#!/usr/bin/env python3
"""
Generated by Cursor. 2026-08-24.
2x2 grid of cage-relative SISF vs lag time for vertex-model p0=3.80.

Physics:
  F_s^CR(q, dt) from timeCRSISF NetCDF (q = 6.80). One panel per T.
  Color is waiting time t_w (red short, blue long). Horizontal line is 1/e,
  the tau_alpha crossing used in vertexModel_tauAlpha_test.

Four T span the first-batch p0=3.80 set: 0.016, 0.0063, 0.0031, 0.0022.

Usage:
  python3 plot_fs_grid_p3.800.py
"""

from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.cm import ScalarMappable
from matplotlib.colors import Normalize

from measure_and_plot_tau_alpha import (
    FS_NAME,
    INV_E,
    Q_DEFAULT,
    read_two_values,
    scratch_root,
)

# (T, Voronoi tau_alpha estimate)
PANELS = [
    (0.016, 13.33),
    (0.0063, 113.7),
    (0.0031, 1423),
    (0.0022, 8307),
]
P0 = 3.80
N = 4096


def main():
    here = Path(__file__).resolve().parent
    outdir = here / "vertexModel_tauAlpha_test"
    outdir.mkdir(parents=True, exist_ok=True)
    datadir = scratch_root(N) / f"p{P0:.3f}"

    cmap = plt.get_cmap("coolwarm_r")
    fig, axes = plt.subplots(2, 2, figsize=(9.2, 7.4), sharex=False, sharey=True)
    curves = []
    for T, est in PANELS:
        tau_block = max(1000.0, est)
        panel = []
        for nc in sorted(datadir.glob(f"timeCRSISF_N{N}_p{P0:.4f}_T*.nc")):
            m = FS_NAME.search(nc.name)
            if not m:
                continue
            Tfile = float(m.group("T"))
            if abs(Tfile - T) / max(T, 1e-30) > 1e-5:
                continue
            if abs(float(m.group("k")) - Q_DEFAULT) > 0.02:
                continue
            tw = float(m.group("tw"))
            dt, fs = read_two_values(nc)
            panel.append((tw / tau_block, dt, fs))
        curves.append(panel)

    norm = Normalize(vmin=0.0, vmax=14.0)

    for ax, (T, est), panel in zip(axes.ravel(), PANELS, curves):
        panel.sort(key=lambda x: x[0])
        for kwait, dt, fs in panel:
            mask = dt > 0
            ax.plot(
                dt[mask],
                fs[mask],
                color=cmap(norm(kwait)),
                lw=1.1,
                alpha=0.9,
            )
        ax.axhline(INV_E, color="k", ls="--", lw=1.0, zorder=5)
        ax.set_xscale("log")
        ax.set_ylim(-0.05, 1.08)
        ax.set_title(rf"$T={T:g}$, $q={Q_DEFAULT:g}$, $\tau_\alpha^{{\mathrm{{est}}}}={est:g}$")
        ax.set_ylabel(r"$F_s^{\mathrm{CR}}(q,\Delta t)$")
        ax.set_xlabel(r"$\Delta t$")

    sm = ScalarMappable(norm=norm, cmap=cmap)
    sm.set_array([])
    cbar = fig.colorbar(sm, ax=axes.ravel().tolist(), fraction=0.025, pad=0.02)
    cbar.set_label(r"$t_w / \tau_{\mathrm{block}}$ (red short, blue long)")

    fig.suptitle(rf"vertex model CRSISF, $N={N}$, $p_0={P0:.2f}$ (dashed: $1/e$)", y=0.98)
    out = outdir / "vertexModel_tauAlpha_test_Fs_grid_p3.800.png"
    fig.savefig(out, dpi=160, bbox_inches="tight")
    plt.close(fig)
    print(f"wrote {out}")
    for (T, _), panel in zip(PANELS, curves):
        print(f"  T={T:g}: {len(panel)} curves")


if __name__ == "__main__":
    main()
