#!/usr/bin/env python3
"""
Generated by Cursor. 2026-09-14.
Plot production-run CRSISF F_s^CR(q, dt) at q=6.7, one panel per p0.

Physics:
  F_s^CR(q, dt) = (1/N) sum_j J_0(q |dr_j^CR|), tracer = cell centroid,
  cage = cell-cell neighbors at the first stored frame (t_w).
  q=6.7 is near the production S(q) first peak (sq_first_peak.csv).
  Per (p0, T) the solid curve is the mean over idx=0..9; tau_alpha is
  the 1/e crossing of that mean (linear in lag; no extrapolation).

Color: coolwarm, independent LogNorm per p0 (coldest T blue, hottest red).
No colorbars.

Usage:
  python3 plot_vertex_production_fs.py
  CELLGPU_SCRATCH=... python3 plot_vertex_production_fs.py
"""

from __future__ import annotations

import csv
import math
import os
from collections import defaultdict
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np
from matplotlib.colors import LogNorm

from measure_and_plot_tau_alpha import (
    FS_NAME,
    INV_E,
    read_two_values,
    tau_alpha_one_over_e,
)

HERE = Path(__file__).resolve().parent
OUTDIR = HERE / "vertexModel_productionFs"
CSV_STATES = HERE / "vertexModel_tauAlpha_final" / "production_state_points.csv"
CSV_FILL = HERE / "vertexModel_productionKwwFill" / "state_points.csv"
P0_ORDER = (3.750, 3.775, 3.800, 3.815, 3.825, 3.850)
N = 4096
Q = 6.7

FS_TITLE = 17
FS_LABEL = 16
FS_TICK = 14


def scratch_fs() -> Path:
    env = os.environ.get("CELLGPU_SCRATCH")
    root = Path(env) if env else Path("/scratch/bbtm/cli6/glassyDynamics/data")
    return root / f"N{N}" / "vertex" / "productionRuns" / "tauAlphaData"


def load_state_points() -> list[tuple[float, float]]:
    """Production T plus KWW-fill T (vertexModel_productionKwwFill)."""
    rows: list[tuple[float, float]] = []
    for path in (CSV_STATES, CSV_FILL):
        if not path.is_file():
            continue
        with path.open() as f:
            lines = (ln for ln in f if ln.strip() and not ln.lstrip().startswith("#"))
            for r in csv.DictReader(lines):
                p0 = float(r["p0"])
                T = float(r["T"])
                if not (math.isfinite(p0) and math.isfinite(T) and T > 0):
                    continue
                dup = any(
                    abs(p0 - p) < 1e-4 and abs(T - Tt) / max(T, 1e-30) < 1e-5
                    for p, Tt in rows
                )
                if not dup:
                    rows.append((p0, T))
    return rows


def match_p0(p0: float) -> float | None:
    m = min(P0_ORDER, key=lambda p: abs(p - p0))
    if abs(m - p0) > 1e-4:
        return None
    return m


def mean_curve(curves: list[tuple[np.ndarray, np.ndarray]]) -> tuple[np.ndarray, np.ndarray]:
    """Mean Fs on the union of positive dt; interpolate each replica."""
    grids = []
    for dt, fs in curves:
        m = dt > 0
        if np.count_nonzero(m) < 2:
            continue
        grids.append((dt[m], fs[m]))
    if not grids:
        return np.array([]), np.array([])
    tmin = max(g[0][0] for g in grids)
    tmax = min(g[0][-1] for g in grids)
    if not (tmax > tmin > 0):
        dt0, fs0 = grids[0]
        return dt0, fs0
    n = min(len(g[0]) for g in grids)
    n = max(n, 32)
    tgrid = np.geomspace(tmin, tmax, n)
    acc = np.zeros_like(tgrid)
    for dt, fs in grids:
        acc += np.interp(tgrid, dt, fs)
    acc /= len(grids)
    return tgrid, acc


def _combined_axes(fig_w: float = 13.6, fig_h: float = 8.0):
    fig = plt.figure(figsize=(fig_w, fig_h))
    gs = fig.add_gridspec(
        2,
        3,
        left=0.07,
        right=0.98,
        top=0.95,
        bottom=0.09,
        wspace=0.26,
        hspace=0.28,
    )
    axes = []
    for i, p0 in enumerate(P0_ORDER):
        row, col = divmod(i, 3)
        ax = fig.add_subplot(gs[row, col])
        ax.set_title(rf"$p_0={p0:.3f}$", fontsize=FS_TITLE, pad=4)
        ax.tick_params(labelsize=FS_TICK)
        axes.append(ax)
    return fig, axes


def main() -> None:
    OUTDIR.mkdir(parents=True, exist_ok=True)
    root = scratch_fs()
    by_key: dict[tuple[float, float], list[tuple[np.ndarray, np.ndarray]]] = defaultdict(list)
    nfile = 0
    if root.is_dir():
        for nc in sorted(root.glob("p*/timeCRSISF_*.nc")):
            m = FS_NAME.search(nc.name)
            if not m:
                continue
            if abs(float(m.group("k")) - Q) > 0.02:
                continue
            p0 = match_p0(float(m.group("p0")))
            if p0 is None:
                continue
            T = float(m.group("T"))
            dt, fs = read_two_values(nc)
            by_key[(p0, T)].append((dt, fs))
            nfile += 1
    print(f"loaded {nfile} CRSISF files from {root}")

    expected = load_state_points()
    missing: list[tuple[float, float]] = []
    peaks: list[tuple[float, float, float, int, int]] = []
    by_p0: dict[float, list[tuple[float, np.ndarray, np.ndarray]]] = {p: [] for p in P0_ORDER}

    for p0_raw, T in expected:
        p0 = match_p0(p0_raw)
        if p0 is None:
            continue
        curves = by_key.get((p0, T), [])
        if not curves:
            # filename T rounding can differ at 1e-8; try nearest loaded T
            cand = [k for k in by_key if k[0] == p0 and abs(k[1] - T) / max(T, 1e-30) < 1e-5]
            curves = by_key[cand[0]] if cand else []
        if not curves:
            missing.append((p0, T))
            continue
        dtm, fsm = mean_curve(curves)
        by_p0[p0].append((T, dtm, fsm))
        tau, crossed = tau_alpha_one_over_e(dtm, fsm)
        peaks.append((p0, T, tau, int(crossed), len(curves)))

    cmap = plt.get_cmap("coolwarm")
    fig, axes = _combined_axes()
    for i, p0 in enumerate(P0_ORDER):
        ax = axes[i]
        curves = sorted(by_p0[p0], key=lambda z: z[0])
        if not curves:
            ax.text(0.5, 0.5, "no data", ha="center", va="center", transform=ax.transAxes)
            continue
        Ts = [z[0] for z in curves]
        tmin, tmax = min(Ts), max(Ts)
        if tmin <= 0 or tmin == tmax:
            norm = None
        else:
            norm = LogNorm(vmin=tmin, vmax=tmax)
        for T, dt, fs in curves:
            color = cmap(0.5) if norm is None else cmap(norm(T))
            m = dt > 0
            ax.plot(dt[m], fs[m], color=color, lw=1.3)
        ax.axhline(INV_E, color="k", ls="--", lw=0.9, zorder=5)
        ax.set_xscale("log")
        ax.set_ylim(-0.05, 1.08)
        row, col = divmod(i, 3)
        if row == 1:
            ax.set_xlabel(r"$\Delta t$", fontsize=FS_LABEL)
        if col == 0:
            ax.set_ylabel(r"$F_s^{\mathrm{CR}}(q,\Delta t)$", fontsize=FS_LABEL)

    png = OUTDIR / "fs_vs_dt_all_p0.png"
    fig.savefig(png, dpi=150)
    plt.close(fig)
    print(f"wrote {png}")

    peak_csv = OUTDIR / "fs_tau_alpha.csv"
    with peak_csv.open("w", newline="") as f:
        w = csv.writer(f)
        w.writerow(["p0", "T", "q", "tau_alpha", "crossed", "n_idx"])
        for p0, T, tau, crossed, nidx in peaks:
            w.writerow(
                [f"{p0:.3f}", f"{T:.8g}", f"{Q:g}", f"{tau:.8g}", crossed, nidx]
            )
    print(f"wrote {peak_csv}")

    print()
    print("| p0 | T | tau_alpha | crossed | n_idx |")
    print("| --- | --- | --- | --- | --- |")
    for p0, T, tau, crossed, nidx in peaks:
        tau_s = f"{tau:.6g}" if math.isfinite(tau) else "nan"
        print(f"| {p0:.3f} | {T:.8g} | {tau_s} | {crossed} | {nidx} |")
    if missing:
        print(f"missing {len(missing)} (p0, T):")
        for p0, T in missing:
            print(f"  p0={p0:.3f} T={T:.8f}")
        raise SystemExit(1)


if __name__ == "__main__":
    main()
