#!/usr/bin/env python3
"""
Generated by Claude Code. 2026-09-30.
How hexagonal the vertex-model cells are, and why the centroid S(q) hides it.

Physics (mean cell area A0=1, KA=KP=1, N=4096, periodic box L=64):
  Cells are rebuilt from the production trajectories (pos, Vneighs,
  VertexCellNeighbors), last record of each idx=0..9. z_i is the number of
  sides. Euler on the torus with 3-valent vertices gives <z>=6 exactly in
  every frame, so hexagonality is the spread of z:
    p6 = fraction of 6-sided cells,  mu2 = <(z-6)^2>.
  Bond order of cell j over its edge-sharing neighbours k (centroid bonds):
    psi6_j = (1/z_j) sum_k exp(6 i theta_jk),  box-wide |Psi6| = |<psi6_j>|.
  Shape of the hexagons: q = P/sqrt(A) against the regular hexagon
  q_hex = sqrt(8 sqrt 3) ~ 3.722, and interior angles against 120 deg.
  S(q) is the stored production centroid S(q) (first-quadrant annulus
  average, last 10 frames x idx 0..9; vertexProductionSq). The 2D map is
  S(k) = |sum_n exp(i k.r_n)|^2 / N on the full 2 pi/L grid of one frame.
  tau_kww is the round-2 production centroid CRSISF KWW time (q=6.7).
  Vertex S(q) (stored, vertexPositionSq): the vertices of regular hexagons of
  area 1 form a honeycomb with side s_hex = sqrt(2/(3 sqrt 3)) ~ 0.620 on the
  same triangular lattice as the centroids. Shell G = h b1 + k b2 carries the
  basis weight |1 + exp(2 pi i (h+k)/3)|^2 = 1 or 4, so the strongest vertex
  peak is sqrt(3) q* = 4 pi/(sqrt(3) s_hex) ~ 11.69, where both ends of every
  edge scatter in phase (not 2 pi/s_hex ~ 10.1). Edge pairs alone give
  3 <J0(q ell)> to S(q); edge-length spread sigma_ell damps the 11.69 peak like
  a Debye-Waller factor exp(-G2^2 sigma_ell^2 / 2).

Output (vertexModel_hexagonality/):
  hex_metrics.csv          per-(p0,T) replica means (cached; --recompute)
  hex_snapshots.png        cells coloured by number of sides
  hex_order_vs_T.png       p6, |Psi6|, <q|z=6>, p6 vs tau_kww
  hex_vs_sq.png            S(q), P(z), S(q*) vs 1/(1-p6), 2D S(k)
  hex_vertex_sq.png        vertex S(q), P(ell), sqrt(3) q* peak vs edge spread

Usage:
  python3 plot_vertex_hexagonality.py
  python3 plot_vertex_hexagonality.py --recompute
  CELLGPU_SCRATCH=... python3 plot_vertex_hexagonality.py
Reads about 700 trajectory records (one per replica); I/O bound, ~1 min.
"""

from __future__ import annotations

import argparse
import csv
import math
import os
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
from matplotlib.collections import PolyCollection
from matplotlib.colors import LogNorm
from matplotlib.patches import Patch
from matplotlib.ticker import FixedFormatter, FixedLocator, NullLocator
from scipy.io import netcdf_file
from scipy.special import j0

HERE = Path(__file__).resolve().parent
OUTDIR = HERE / "vertexModel_hexagonality"
CSV_STATES = HERE / "vertexModel_tauAlpha_final" / "production_state_points.csv"
SQ_PEAK = HERE / "vertexModel_productionSq" / "sq_first_peak.csv"
KWW_TAU = HERE / "vertexModel_productionFs" / "round2" / "kww_global_tau.csv"
METRICS = OUTDIR / "hex_metrics.csv"

P0_ORDER = (3.750, 3.775, 3.800, 3.815, 3.825, 3.850)
N = 4096
Q_HEX = math.sqrt(8.0 * math.sqrt(3.0))  # regular hexagon P/sqrt(A)
A_TRI = math.sqrt(2.0 / math.sqrt(3.0))  # triangular-lattice spacing at unit area
Q_STAR = 4.0 * math.pi / (math.sqrt(3.0) * A_TRI)  # first Bragg shell ~ 6.75
S_HEX = A_TRI / math.sqrt(3.0)  # regular-hexagon side at unit area ~ 0.620
G2_HEX = math.sqrt(3.0) * Q_STAR  # honeycomb in-phase shell 4 pi/(sqrt3 s_hex) ~ 11.69

# Cooling series at p0=3.750 and a fixed-T (~0.012) series across p0.
T_SERIES = ((3.750, 0.1507937), (3.750, 0.021317), (3.750, 0.01499281))
P_SERIES = ((3.775, 0.01235791), (3.815, 0.01273808), (3.850, 0.01212699))
DEEPEST = (3.825, 0.00260712)

# Colours (validated with the dataviz palette checks).
# p0: one-hue ordinal ramp, darkest = lowest p0.
P0_COLOR = dict(zip(P0_ORDER, ("#0a2a52", "#104281", "#1c5cab", "#2a78d6", "#5598e7", "#86b6ef")))
# Cooling series: orange ordinal ramp, darkest = coldest.
T_COLOR = ("#f0a07c", "#eb6834", "#a8401a")
# Number of sides: diverging blue (fewer) / neutral (6) / red (more).
Z_COLOR = {4: "#184f95", 5: "#5598e7", 6: "#f0efec", 7: "#e34948", 8: "#8c2323"}
INK = "#0b0b0b"
INK2 = "#52514e"
MUTED = "#898781"

FS_TITLE = 15
FS_LABEL = 15
FS_TICK = 12
FS_LEGEND = 10
FS_NOTE = 11


def scratch_root() -> Path:
    env = os.environ.get("CELLGPU_SCRATCH")
    if env:
        return Path(env)
    return Path("/scratch/bbtm/cli6/glassyDynamics/data")


def production_dir() -> Path:
    return scratch_root() / f"N{N}" / "vertex" / "productionRuns"


def traj_paths(p0: float, T: float) -> list[Path]:
    d = production_dir() / f"p{p0:.3f}"
    return sorted(d.glob(f"glassyDynamics_N{N}_p{p0:.4f}_T{T:.8f}_waitingTime*_idx*.nc"))


def sq_path(p0: float, T: float) -> Path:
    return production_dir() / "structureFactor" / f"sq_N{N}_p{p0:.4f}_T{T:.8f}.nc"


def match_p0(p0: float) -> float | None:
    m = min(P0_ORDER, key=lambda p: abs(p - p0))
    return m if abs(m - p0) < 1e-4 else None


def state_key(p0: float, T: float) -> tuple[float, float]:
    return (round(p0, 3), round(T, 7))


# ----------------------------------------------------------------------------
# Tissue geometry
# ----------------------------------------------------------------------------


def read_frame(path: Path, rec: int = -1) -> dict:
    with netcdf_file(path, "r", mmap=True) as ds:
        nrec = ds.variables["time"].shape[0]
        r = rec if rec >= 0 else nrec + rec
        pos = np.array(ds.variables["pos"][r], dtype=float).reshape(-1, 2)
        vn = np.array(ds.variables["Vneighs"][r], dtype=np.int64).reshape(-1, 3)
        vcn = np.array(ds.variables["VertexCellNeighbors"][r], dtype=np.int64).reshape(-1, 3)
        box = np.array(ds.variables["BoxMatrix"][r], dtype=float)
    return {"pos": pos, "vn": vn, "vcn": vcn, "box": box}


def unique_edge_lengths(pos: np.ndarray, vn: np.ndarray, L: np.ndarray) -> np.ndarray:
    v = np.repeat(np.arange(pos.shape[0]), 3)
    w = vn.ravel()
    keep = v < w
    d = pos[w[keep]] - pos[v[keep]]
    d -= L * np.round(d / L)
    return np.hypot(d[:, 0], d[:, 1])


def walk_cell(verts: np.ndarray, vn: np.ndarray) -> list[int] | None:
    """Order one cell's vertices by walking mesh edges inside the cell."""
    members = set(int(v) for v in verts)
    ring = [int(verts[0])]
    prev = -1
    for _ in range(len(verts) - 1):
        cur = ring[-1]
        nxt = [int(w) for w in vn[cur] if int(w) in members and int(w) != prev and int(w) not in ring]
        if not nxt:
            return None
        prev = cur
        ring.append(nxt[0])
    return ring if len(ring) == len(verts) else None


def build_tissue(fr: dict) -> dict:
    """Cell polygons from the 3-valent mesh. Corners are ordered by angle about
    the vertex mean of each (unwrapped) cell; cells where that order does not
    follow mesh edges (non-star-shaped, mostly hot T) are re-walked along the
    edges and oriented counter-clockwise."""
    pos, vn, vcn, box = fr["pos"], fr["vn"], fr["vcn"], fr["box"]
    if abs(box[1]) > 1e-12 or abs(box[2]) > 1e-12:
        raise ValueError("only rectangular boxes are handled")
    L = np.array([box[0], box[3]])
    Nv = pos.shape[0]
    Nc = Nv // 2
    cell_of = vcn.ravel()
    vert_of = np.repeat(np.arange(Nv), 3)
    order = np.argsort(cell_of, kind="stable")
    vert_sorted = vert_of[order]
    z = np.bincount(cell_of, minlength=Nc)
    start = np.concatenate([[0], np.cumsum(z)[:-1]])
    cid = np.repeat(np.arange(Nc), z)
    ref = vert_sorted[start]
    d = pos[vert_sorted] - pos[np.repeat(ref, z)]
    d -= L * np.round(d / L)
    cm = np.add.reduceat(d, start, axis=0) / z[:, None]
    rel = d - cm[cid]
    ang = np.arctan2(rel[:, 1], rel[:, 0])
    o2 = np.lexsort((ang, cid))
    rel = rel[o2]
    vs = vert_sorted[o2]
    idx = np.arange(rel.shape[0])
    last = start + z - 1
    nxt = idx + 1
    nxt[last] = start
    adjacent = (vn[vs] == vs[nxt][:, None]).any(axis=1)
    n_rewalked = 0
    for c in np.unique(cid[~adjacent]):
        s, n = start[c], z[c]
        ring = walk_cell(vs[s : s + n], vn)
        if ring is None:
            continue
        where = {int(v): k for k, v in enumerate(vs[s : s + n])}
        new = rel[s : s + n][[where[v] for v in ring]]
        area2 = np.sum(new[:, 0] * np.roll(new[:, 1], -1) - np.roll(new[:, 0], -1) * new[:, 1])
        if area2 < 0:
            new = new[::-1]
            ring = ring[::-1]
        rel[s : s + n] = new
        vs[s : s + n] = ring
        n_rewalked += 1
    prv = idx - 1
    prv[start] = last
    x0, y0 = rel[:, 0], rel[:, 1]
    x1, y1 = rel[nxt, 0], rel[nxt, 1]
    cross = x0 * y1 - x1 * y0
    A = 0.5 * np.bincount(cid, weights=cross, minlength=Nc)
    elen = np.hypot(x1 - x0, y1 - y0)
    P = np.bincount(cid, weights=elen, minlength=Nc)
    crel = np.stack(
        [
            np.bincount(cid, weights=(x0 + x1) * cross, minlength=Nc) / (6.0 * A),
            np.bincount(cid, weights=(y0 + y1) * cross, minlength=Nc) / (6.0 * A),
        ],
        axis=1,
    )
    cen = pos[ref] + cm + crel
    cen -= L * np.floor(cen / L)
    ax_, ay_ = rel[prv, 0] - x0, rel[prv, 1] - y0
    bx_, by_ = x1 - x0, y1 - y0
    cosang = (ax_ * bx_ + ay_ * by_) / (np.hypot(ax_, ay_) * np.hypot(bx_, by_))
    theta = np.degrees(np.arccos(np.clip(cosang, -1.0, 1.0)))
    # Each mesh edge (v,w) separates the two cells common to v and w.
    v = np.repeat(np.arange(Nv), 3)
    w = vn.ravel()
    keep = v < w
    cv = vcn[v[keep]]
    cw = vcn[w[keep]]
    common = (cv[:, :, None] == cw[:, None, :]).any(axis=2)
    ok_edges = bool(np.all(common.sum(axis=1) == 2))
    pairs = cv[common].reshape(-1, 2) if ok_edges else np.zeros((0, 2), dtype=np.int64)
    poly = rel + (cen - crel)[cid]
    return {
        "z": z, "A": A, "P": P, "cen": cen, "L": L, "pairs": pairs, "theta": theta,
        "elen": elen, "cid": cid, "start": start, "poly": poly, "Nc": Nc,
        "n_rewalked": n_rewalked, "ell": unique_edge_lengths(pos, vn, L),
        "ok": ok_edges and bool(np.all(A > 0)) and abs(A.sum() - L.prod()) < 1e-6 * L.prod(),
    }


def psi6_local(g: dict) -> np.ndarray:
    cen, L, pairs, Nc = g["cen"], g["L"], g["pairs"], g["Nc"]
    i, j = pairs[:, 0], pairs[:, 1]
    d = cen[j] - cen[i]
    d -= L * np.round(d / L)
    e = np.exp(6j * np.arctan2(d[:, 1], d[:, 0]))
    s = np.zeros(Nc, dtype=complex)
    np.add.at(s, i, e)
    np.add.at(s, j, e)  # exp(6i(theta+pi)) = exp(6i theta)
    nn = np.bincount(np.concatenate([i, j]), minlength=Nc)
    return s / np.maximum(nn, 1)


FRAME_KEYS = (
    "p4", "p5", "p6", "p7", "p8", "mu2", "q_mean", "q6_mean",
    "psi6_local", "psi6_global", "angle_std6_deg", "ellcv6",
    "ell_mean", "ell_std", "ell_fnear", "edge_term_g2",
)


def frame_metrics(g: dict) -> dict:
    z = g["z"]
    hexa = z == 6
    q = g["P"] / np.sqrt(g["A"])
    ps = psi6_local(g)
    zc = z[g["cid"]]
    m1 = np.bincount(g["cid"], weights=g["elen"]) / z
    m2 = np.bincount(g["cid"], weights=g["elen"] ** 2) / z
    cv = np.sqrt(np.maximum(m2 - m1 * m1, 0.0)) / m1
    return {
        "p4": float(np.mean(z <= 4)),
        "p5": float(np.mean(z == 5)),
        "p6": float(np.mean(hexa)),
        "p7": float(np.mean(z == 7)),
        "p8": float(np.mean(z >= 8)),
        "mu2": float(np.mean((z - 6.0) ** 2)),
        "q_mean": float(q.mean()),
        "q6_mean": float(q[hexa].mean()),
        "psi6_local": float(np.abs(ps).mean()),
        "psi6_global": float(abs(ps.mean())),
        "angle_std6_deg": float(g["theta"][zc == 6].std()),
        "ellcv6": float(cv[hexa].mean()),
        "ell_mean": float(g["ell"].mean()),
        "ell_std": float(g["ell"].std()),
        "ell_fnear": float(np.mean(np.abs(g["ell"] / S_HEX - 1.0) < 0.1)),
        "edge_term_g2": float(3.0 * np.mean(j0(G2_HEX * g["ell"]))),
        "_zmean": float(z.mean()),
        "_ok": g["ok"],
    }


def state_metrics(p0: float, T: float) -> dict | None:
    paths = traj_paths(p0, T)
    if not paths:
        return None
    per = [frame_metrics(build_tissue(read_frame(p))) for p in paths]
    bad = sum(1 for m in per if not m["_ok"] or abs(m["_zmean"] - 6.0) > 1e-12)
    out = {"p0": p0, "T": T, "n_frames": len(per), "n_bad": bad}
    for k in FRAME_KEYS:
        v = np.array([m[k] for m in per])
        out[k] = float(v.mean())
        out[k + "_sd"] = float(v.std(ddof=1)) if v.size > 1 else math.nan
    return out


# ----------------------------------------------------------------------------
# Tables
# ----------------------------------------------------------------------------


def load_states() -> list[tuple[float, float]]:
    out, seen = [], set()
    with CSV_STATES.open() as f:
        lines = (ln for ln in f if ln.strip() and not ln.lstrip().startswith("#"))
        for r in csv.DictReader(lines):
            p0 = match_p0(float(r["p0"]))
            T = float(r["T"])
            if p0 is None or not (T > 0):
                continue
            k = state_key(p0, T)
            if k not in seen:
                seen.add(k)
                out.append((p0, T))
    return sorted(out)


def load_keyed(path: Path, cols: tuple[str, ...]) -> dict:
    out = {}
    if not path.is_file():
        return out
    with path.open() as f:
        for r in csv.DictReader(ln for ln in f if not ln.lstrip().startswith("#")):
            p0 = match_p0(float(r["p0"]))
            if p0 is None:
                continue
            out[state_key(p0, float(r["T"]))] = {c: float(r[c]) for c in cols}
    return out


def compute_metrics(recompute: bool) -> list[dict]:
    if METRICS.is_file() and not recompute:
        with METRICS.open() as f:
            rows = list(csv.DictReader(f))
        return [{k: float(v) for k, v in r.items()} for r in rows]
    states = load_states()
    with ThreadPoolExecutor(max_workers=8) as ex:
        res = [r for r in ex.map(lambda s: state_metrics(*s), states) if r is not None]
    sq = load_keyed(SQ_PEAK, ("q_peak", "S_peak"))
    kww = load_keyed(KWW_TAU, ("tau_kww", "crossed_1e"))
    for r in res:
        k = state_key(r["p0"], r["T"])
        r["S_peak"] = sq.get(k, {}).get("S_peak", math.nan)
        r["q_peak"] = sq.get(k, {}).get("q_peak", math.nan)
        r["tau_kww"] = kww.get(k, {}).get("tau_kww", math.nan)
        r["tau_crossed_1e"] = kww.get(k, {}).get("crossed_1e", math.nan)
        cur = read_vsq_curve(r["p0"], r["T"])
        r["q1_vert"], r["S1_vert"] = peak_in(*cur, 5.0, 8.5) if cur else (math.nan, math.nan)
        r["q2_vert"], r["S2_vert"] = peak_in(*cur, 10.0, 13.5) if cur else (math.nan, math.nan)
    OUTDIR.mkdir(parents=True, exist_ok=True)
    keys = list(res[0].keys())
    with METRICS.open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=keys)
        w.writeheader()
        for r in res:
            w.writerow({k: (f"{v:.8g}" if isinstance(v, float) else v) for k, v in r.items()})
    print(f"wrote {METRICS} ({len(res)} states)")
    return [{k: float(v) for k, v in r.items()} for r in res]


def find(rows: list[dict], p0: float, T: float) -> dict:
    k = state_key(p0, T)
    for r in rows:
        if state_key(r["p0"], r["T"]) == k:
            return r
    raise KeyError(k)


def by_p0(rows: list[dict]) -> dict[float, list[dict]]:
    out = {p: [] for p in P0_ORDER}
    for r in rows:
        out[match_p0(r["p0"])].append(r)
    for p in out:
        out[p].sort(key=lambda r: r["T"])
    return out


def read_two_values(path: Path):
    if not path.is_file():
        return None
    with netcdf_file(path, "r", mmap=False) as ds:
        q = np.array(ds.variables["firstValue"].data, dtype=float)
        s = np.array(ds.variables["secondValue"].data, dtype=float)
    return q, s


def read_sq_curve(p0: float, T: float):
    return read_two_values(sq_path(p0, T))


def read_vsq_curve(p0: float, T: float):
    return read_two_values(production_dir() / "vertexPositionSq" / f"sqVertex_N{N}_p{p0:.4f}_T{T:.8f}.nc")


def peak_in(q: np.ndarray, s: np.ndarray, lo: float, hi: float) -> tuple[float, float]:
    m = (q >= lo) & (q <= hi)
    i = int(np.argmax(s[m]))
    return float(q[m][i]), float(s[m][i])


def edge_sample(p0: float, T: float) -> np.ndarray:
    """Unique edge lengths pooled over the last record of every replica."""
    out = []
    for path in traj_paths(p0, T):
        fr = read_frame(path)
        out.append(unique_edge_lengths(fr["pos"], fr["vn"], np.array([fr["box"][0], fr["box"][3]])))
    return np.concatenate(out)


# ----------------------------------------------------------------------------
# Structure factor of one frame
# ----------------------------------------------------------------------------


def sk2d(cen: np.ndarray, L: float, kmax: float):
    nmax = int(kmax * L / (2.0 * math.pi))
    k1 = 2.0 * math.pi * np.arange(-nmax, nmax + 1) / L
    ex = np.exp(1j * np.outer(k1, cen[:, 0]))
    ey = np.exp(1j * np.outer(k1, cen[:, 1]))
    S = np.abs(ex @ ey.T) ** 2 / cen.shape[0]  # S[i,j] at (kx_i, ky_j)
    return k1, S


def ring_average_first_quadrant(k1: np.ndarray, S: np.ndarray, L: float, dk: float = 0.5):
    """Same annulus rule as structuralFeatures::computeStructureFactor."""
    KX, KY = np.meshgrid(k1, k1, indexing="ij")
    m = (KX > -1e-12) & (KY > -1e-12)
    k = np.hypot(KX[m], KY[m])
    s = S[m]
    dK = 2.0 * math.pi / L
    bw = dK * dk
    edges = np.arange(dK - 0.5 * bw, k.max(), bw)
    b = np.digitize(k, edges) - 1
    ok = (b >= 0) & (b < edges.size - 1)
    num = np.bincount(b[ok], weights=s[ok], minlength=edges.size - 1)
    cnt = np.bincount(b[ok], minlength=edges.size - 1)
    good = cnt > 0
    return (edges[:-1] + 0.5 * bw)[good], num[good] / cnt[good]


def representative_frame(p0: float, T: float) -> tuple[dict, float]:
    """Replica whose box-wide |Psi6| is the median over idx."""
    gs = [build_tissue(read_frame(p)) for p in traj_paths(p0, T)]
    psi = np.array([abs(psi6_local(g).mean()) for g in gs])
    i = int(np.argsort(psi)[len(psi) // 2])
    return gs[i], float(psi[i])


# ----------------------------------------------------------------------------
# Figures
# ----------------------------------------------------------------------------


def style_axes(ax) -> None:
    ax.tick_params(labelsize=FS_TICK, colors=INK2)
    for s in ax.spines.values():
        s.set_color(INK2)
        s.set_linewidth(0.8)


def draw_tissue(ax, g: dict, x0: float, y0: float, w: float) -> None:
    cen = g["cen"]
    sel = np.where(
        (cen[:, 0] > x0 - 1.5) & (cen[:, 0] < x0 + w + 1.5)
        & (cen[:, 1] > y0 - 1.5) & (cen[:, 1] < y0 + w + 1.5)
    )[0]
    polys, colors = [], []
    for c in sel:
        s, n = g["start"][c], g["z"][c]
        polys.append(g["poly"][s : s + n])
        colors.append(Z_COLOR[min(max(int(n), 4), 8)])
    pc = PolyCollection(polys, facecolors=colors, edgecolors="#6f6e69", linewidths=0.45)
    ax.add_collection(pc)
    ax.set_xlim(x0, x0 + w)
    ax.set_ylim(y0, y0 + w)
    ax.set_aspect("equal")
    ax.set_xticks([])
    ax.set_yticks([])
    for s in ax.spines.values():
        s.set_color(INK2)
        s.set_linewidth(0.8)


def fig_snapshots(rows: list[dict]) -> Path:
    fig, axes = plt.subplots(2, 3, figsize=(13.2, 9.6))
    fig.subplots_adjust(left=0.07, right=0.99, top=0.9, bottom=0.06, wspace=0.06, hspace=0.3)
    win = (14.0, 14.0, 20.0)
    for row, series, label in (
        (0, T_SERIES, rf"cooling at $p_0={T_SERIES[0][0]:.3f}$"),
        (1, P_SERIES, r"fixed $T\approx 0.012$, raising $p_0$"),
    ):
        for col, (p0, T) in enumerate(series):
            ax = axes[row, col]
            g = build_tissue(read_frame(traj_paths(p0, T)[0]))
            draw_tissue(ax, g, *win)
            r = find(rows, p0, T)
            ax.set_title(rf"$p_0={p0:.3f}$,  $T={T:.4g}$", fontsize=FS_TITLE, color=INK, pad=5)
            ax.text(
                0.5, -0.035,
                rf"$p_6={r['p6']:.2f}$    $S(q^*)={r['S_peak']:.1f}$",
                transform=ax.transAxes, ha="center", va="top", fontsize=FS_LABEL, color=INK,
            )
        axes[row, 0].set_ylabel(label, fontsize=FS_LABEL, color=INK, labelpad=10)
    handles = [
        Patch(facecolor=Z_COLOR[k], edgecolor="#6f6e69", label=lab)
        for k, lab in ((4, r"$\leq 4$"), (5, "5"), (6, "6"), (7, "7"), (8, r"$\geq 8$"))
    ]
    fig.legend(
        handles=handles, title="sides", loc="upper center", ncol=5, frameon=False,
        fontsize=FS_LEGEND + 2, title_fontsize=FS_LEGEND + 2, bbox_to_anchor=(0.53, 0.995),
    )
    out = OUTDIR / "hex_snapshots.png"
    fig.savefig(out, dpi=150)
    plt.close(fig)
    return out


def fig_order_vs_T(rows: list[dict]) -> Path:
    groups = by_p0(rows)
    fig, axes = plt.subplots(2, 2, figsize=(12.4, 9.4))
    fig.subplots_adjust(left=0.09, right=0.98, top=0.95, bottom=0.08, wspace=0.26, hspace=0.3)
    panels = (
        (axes[0, 0], "T", "p6", r"$p_6$ (fraction of hexagons)", "(a) topology"),
        (axes[0, 1], "T", "psi6_global", r"box-wide $|\Psi_6|$", "(b) bond orientation"),
        (axes[1, 0], "T", "q6_mean", r"$\langle q\,|\,z=6\rangle$", "(c) shape of the hexagons"),
        (axes[1, 1], "tau_kww", "p6", r"$p_6$", r"(d) $p_6$ at equal $\tau_{\mathrm{KWW}}$"),
    )
    for ax, xk, yk, ylab, title in panels:
        style_axes(ax)
        for p0 in P0_ORDER:
            pts = [(r[xk], r[yk]) for r in groups[p0] if math.isfinite(r[xk]) and math.isfinite(r[yk])]
            pts.sort()
            if not pts:
                continue
            x, y = np.array(pts).T
            ax.plot(x, y, "-o", color=P0_COLOR[p0], lw=1.6, ms=5, mec="white", mew=0.8,
                    label=rf"$p_0={p0:.3f}$")
        ax.set_xscale("log")
        ax.set_ylabel(ylab, fontsize=FS_LABEL, color=INK)
        ax.set_xlabel(r"$T$" if xk == "T" else r"$\tau_{\mathrm{KWW}}$", fontsize=FS_LABEL, color=INK)
        ax.set_title(title, fontsize=FS_TITLE, color=INK, loc="left")
    axp6 = axes[0, 0]
    axp6.axhline(1.0, color=MUTED, lw=0.9, ls=(0, (4, 3)))
    axp6.text(0.035, 0.985, "honeycomb", color=INK2, fontsize=FS_NOTE, va="top")
    axp6.set_ylim(0.45, 1.01)
    axes[1, 1].set_ylim(0.45, 1.01)
    axq = axes[1, 0]
    axq.axhline(Q_HEX, color=MUTED, lw=0.9, ls=(0, (4, 3)))
    axq.text(0.0022, Q_HEX + 0.006, rf"regular hexagon $q={Q_HEX:.3f}$", color=INK2, fontsize=FS_NOTE)
    axq.set_ylim(3.70, 4.14)
    axes[0, 1].set_ylim(0.0, 0.8)
    axes[0, 1].axhline(1.0 / math.sqrt(N), color=MUTED, lw=0.9, ls=(0, (4, 3)))
    axes[0, 1].annotate(r"random orientations, $N^{-1/2}$", xy=(0.1, 1.0 / math.sqrt(N)), xycoords="data",
                        xytext=(0.985, 0.22), textcoords="axes fraction", ha="right", color=INK2,
                        fontsize=FS_NOTE, arrowprops=dict(arrowstyle="-", color=MUTED, lw=0.8))
    for r in rows:
        if r.get("tau_crossed_1e", 1.0) == 0.0 and math.isfinite(r["tau_kww"]):
            axes[1, 1].plot(r["tau_kww"], r["p6"], "o", ms=9, mfc="white", mec=P0_COLOR[match_p0(r["p0"])],
                            mew=1.6, zorder=5)
            axes[1, 1].annotate(r"open: $F_s$ never reached $1/e$," + "\n" + r"$\tau_{\mathrm{KWW}}$ extrapolated",
                                (r["tau_kww"], r["p6"]), xytext=(4.0e5, 0.79), textcoords="data", ha="right",
                                fontsize=FS_NOTE - 1, color=INK2,
                                arrowprops=dict(arrowstyle="-", color=MUTED, lw=0.8, shrinkB=6))
    axes[0, 0].legend(fontsize=FS_LEGEND, frameon=False, loc="lower left")
    out = OUTDIR / "hex_order_vs_T.png"
    fig.savefig(out, dpi=150)
    plt.close(fig)
    return out


def inv_defect_to_p6(x):
    x = np.asarray(x, dtype=float)
    with np.errstate(divide="ignore", invalid="ignore"):
        return 1.0 - 1.0 / x


def p6_to_inv_defect(p):
    p = np.asarray(p, dtype=float)
    with np.errstate(divide="ignore", invalid="ignore"):
        return 1.0 / (1.0 - p)


def fig_vs_sq(rows: list[dict]) -> tuple[Path, list[dict]]:
    fig = plt.figure(figsize=(15.6, 10.0))
    gs = fig.add_gridspec(2, 3, left=0.06, right=0.985, top=0.95, bottom=0.07, wspace=0.28, hspace=0.34)
    trs = [find(rows, p0, T) for p0, T in T_SERIES]

    # (a) stored centroid S(q) along the cooling series.
    ax = fig.add_subplot(gs[0, 0])
    style_axes(ax)
    for color, (p0, T), r in zip(T_COLOR, T_SERIES, trs):
        cur = read_sq_curve(p0, T)
        if cur is None:
            continue
        q, s = cur
        m = (q > 1.0) & (q < 12.5)
        ax.plot(q[m], s[m], color=color, lw=1.8, label=rf"$p_6={r['p6']:.2f}$  ($T={T:.3g}$)")
    for xq, lab in ((Q_STAR, r"$q^*$"), (math.sqrt(3.0) * Q_STAR, r"$\sqrt{3}\,q^*$")):
        ax.axvline(xq, color=MUTED, lw=0.8, ls=(0, (2, 3)), zorder=0)
        ax.text(xq + 0.12, 12.1, lab, color=INK2, fontsize=FS_NOTE, va="top")
    ax.set_xlim(1.0, 12.5)
    ax.set_ylim(0, 12.5)
    ax.set_xlabel(r"$q$", fontsize=FS_LABEL, color=INK)
    ax.set_ylabel(r"$S(q)$, centroids", fontsize=FS_LABEL, color=INK)
    ax.set_title(rf"(a) S(q) on cooling, $p_0={T_SERIES[0][0]:.3f}$", fontsize=FS_TITLE, color=INK, loc="left")
    ax.legend(fontsize=FS_LEGEND, frameon=False, loc="upper right", bbox_to_anchor=(1.0, 0.86))

    # (b) P(z) of the same states; <z>=6 in all of them.
    ax = fig.add_subplot(gs[0, 1])
    style_axes(ax)
    zs = np.arange(4, 9)
    width = 0.26
    for i, (color, r) in enumerate(zip(T_COLOR, trs)):
        pz = [r["p4"], r["p5"], r["p6"], r["p7"], r["p8"]]
        ax.bar(zs + (i - 1) * width, pz, width=width, color=color, edgecolor="white", linewidth=1.5,
               label=rf"$\mu_2={r['mu2']:.2f}$")
    ax.set_xticks(zs, [r"$\leq 4$", "5", "6", "7", r"$\geq 8$"])
    ax.set_xlabel(r"sides $z$", fontsize=FS_LABEL, color=INK)
    ax.set_ylabel(r"$P(z)$", fontsize=FS_LABEL, color=INK)
    ax.set_ylim(0, 1.0)
    ax.text(0.97, 0.97, r"$\langle z\rangle = 6$ exactly (Euler)", transform=ax.transAxes,
            ha="right", va="top", fontsize=FS_NOTE + 1, color=INK)
    ax.legend(fontsize=FS_LEGEND, frameon=False, loc="upper left", title=r"$\langle(z-6)^2\rangle$",
              title_fontsize=FS_LEGEND)
    ax.set_title("(b) same states: sides per cell", fontsize=FS_TITLE, color=INK, loc="left")

    # (c) first-peak height against the inverse defect fraction, all states.
    ax = fig.add_subplot(gs[0, 2])
    style_axes(ax)
    for p0 in P0_ORDER:
        pts = [(1.0 / (1.0 - r["p6"]), r["S_peak"]) for r in rows
               if match_p0(r["p0"]) == p0 and math.isfinite(r["S_peak"])]
        if pts:
            x, y = np.array(pts).T
            ax.plot(x, y, "o", color=P0_COLOR[p0], ms=6, mec="white", mew=0.8, label=rf"$p_0={p0:.3f}$")
    xx = np.array([1.6, 60.0])
    ax.plot(xx, xx, color=INK2, lw=1.0, label=r"$S(q^*)=1/(1-p_6)$")
    ax.set_xscale("log")
    ax.set_yscale("log")
    ax.set_xlim(1.6, 60)
    ax.set_ylim(1.6, 30)
    ax.set_xlabel(r"$1/(1-p_6)$  (cells per non-hexagon)", fontsize=FS_LABEL, color=INK)
    ax.set_ylabel(r"$S(q^*)$", fontsize=FS_LABEL, color=INK)
    ax.set_title("(c) peak height vs hexagon fraction", fontsize=FS_TITLE, color=INK, loc="left", pad=40)
    # Top axis relabels the same x as p6 (not a second scale).
    top = ax.secondary_xaxis("top", functions=(inv_defect_to_p6, p6_to_inv_defect))
    top.xaxis.set_major_locator(FixedLocator([0.5, 0.7, 0.8, 0.9, 0.95]))
    top.xaxis.set_major_formatter(FixedFormatter(["0.5", "0.7", "0.8", "0.9", "0.95"]))
    top.xaxis.set_minor_locator(NullLocator())
    top.tick_params(labelsize=FS_TICK - 1, colors=INK2)
    top.set_xlabel(r"$p_6$", fontsize=FS_LABEL - 2, color=INK2, labelpad=5)
    ax.legend(fontsize=FS_LEGEND - 1, frameon=False, loc="lower right")

    # (d-f) 2D S(k) of one frame; what the annulus average keeps.
    kmax = 12.5
    norm = LogNorm(vmin=0.3, vmax=2000.0)
    maps = (T_SERIES[0], T_SERIES[2], DEEPEST)
    info = []
    im = None
    for col, (p0, T) in enumerate(maps):
        ax = fig.add_subplot(gs[1, col])
        g, psi = representative_frame(p0, T)
        k1, S = sk2d(g["cen"], float(g["L"][0]), kmax)
        qa, sa = ring_average_first_quadrant(k1, S, float(g["L"][0]))
        band = (qa > 5.5) & (qa < 8.0)
        s_ring = float(sa[band].max())
        KX, KY = np.meshgrid(k1, k1, indexing="ij")
        on_ring = (np.hypot(KX, KY) > 5.5) & (np.hypot(KX, KY) < 8.0)
        s_max = float(S[on_ring].max())
        info.append({"p0": p0, "T": T, "psi6_frame": psi, "S2d_max": s_max, "S_ring_frame": s_ring,
                     "p6": find(rows, p0, T)["p6"]})
        dk = k1[1] - k1[0]
        extent = (k1[0] - dk / 2, k1[-1] + dk / 2, k1[0] - dk / 2, k1[-1] + dk / 2)
        im = ax.imshow(np.clip(S.T, 1e-3, None), origin="lower", extent=extent, cmap="Greys", norm=norm,
                       interpolation="nearest")
        ax.set_xlim(-kmax, kmax)
        ax.set_ylim(-kmax, kmax)
        ax.set_aspect("equal")
        style_axes(ax)
        ax.set_xlabel(r"$k_x$", fontsize=FS_LABEL, color=INK)
        if col == 0:
            ax.set_ylabel(r"$k_y$", fontsize=FS_LABEL, color=INK)
        tag = "def"[col]
        ax.set_title(rf"({tag}) $p_0={p0:.3f}$, $T={T:.3g}$, $p_6={info[-1]['p6']:.2f}$",
                     fontsize=FS_TITLE - 1, color=INK, loc="left")
        ax.text(
            0.03, 0.03,
            rf"max $S(\mathbf{{k}})$ = {s_max:.0f}" + "\n" + rf"annulus average = {s_ring:.1f}",
            transform=ax.transAxes, fontsize=FS_NOTE, color=INK, va="bottom",
            bbox=dict(boxstyle="round,pad=0.25", fc="white", ec="none", alpha=0.85),
        )
    cax = fig.add_axes([0.988, 0.07, 0.008, 0.36])
    cb = fig.colorbar(im, cax=cax)
    cb.ax.tick_params(labelsize=FS_TICK - 2, colors=INK2)
    cb.set_label(r"$S(\mathbf{k})$, one frame", fontsize=FS_NOTE, color=INK)
    out = OUTDIR / "hex_vs_sq.png"
    fig.savefig(out, dpi=150, bbox_inches="tight")
    plt.close(fig)
    return out, info


def fig_vertex_sq(rows: list[dict]) -> tuple[Path, dict]:
    fig, axes = plt.subplots(2, 2, figsize=(12.8, 9.6))
    fig.subplots_adjust(left=0.08, right=0.98, top=0.95, bottom=0.08, wspace=0.25, hspace=0.32)
    trs = [find(rows, p0, T) for p0, T in T_SERIES]
    samples = [edge_sample(p0, T) for p0, T in T_SERIES]

    # (a) stored vertex S(q) on cooling, with the edge-pair term 1 + 3<J0(q ell)>.
    ax = axes[0, 0]
    style_axes(ax)
    for color, (p0, T), r in zip(T_COLOR, T_SERIES, trs):
        cur = read_vsq_curve(p0, T)
        if cur is not None:
            ax.plot(*cur, color=color, lw=1.8, label=rf"$p_6={r['p6']:.2f}$  ($T={T:.3g}$)")
    qq = np.linspace(7.5, 18.7, 400)
    for color, ell in ((T_COLOR[0], samples[0]), (T_COLOR[2], samples[2])):
        ax.plot(qq, 1.0 + 3.0 * np.array([np.mean(j0(x * ell)) for x in qq]), color=color, lw=1.1,
                ls=(0, (4, 2)))
    ax.plot([], [], color=INK2, lw=1.1, ls=(0, (4, 2)), label=r"edge pairs only, $1+3\langle J_0(q\ell)\rangle$")
    for xq, lab in ((Q_STAR, r"$q^*$"), (G2_HEX, r"$\sqrt{3}q^*$"), (2 * Q_STAR, r"$2q^*$"),
                    (math.sqrt(7.0) * Q_STAR, r"$\sqrt{7}q^*$")):
        ax.axvline(xq, color=MUTED, lw=0.8, ls=(0, (2, 3)), zorder=0)
        ax.text(xq + 0.12, 5.2, lab, color=INK2, fontsize=FS_NOTE, va="top")
    q_naive = 2.0 * math.pi / S_HEX
    ax.axvline(q_naive, color="#c3c2b7", lw=2.2, zorder=0)
    ax.text(q_naive - 0.12, 5.2, r"$2\pi/s_{\mathrm{hex}}$", color=INK2, fontsize=FS_NOTE, va="top", ha="right")
    ax.set_xlim(1.0, 18.7)
    ax.set_ylim(0, 5.3)
    ax.set_xlabel(r"$q$", fontsize=FS_LABEL, color=INK)
    ax.set_ylabel(r"$S(q)$, vertices", fontsize=FS_LABEL, color=INK)
    ax.set_title(rf"(a) vertex S(q) on cooling, $p_0={T_SERIES[0][0]:.3f}$", fontsize=FS_TITLE, color=INK, loc="left")
    ax.legend(fontsize=FS_LEGEND, frameon=False, loc="upper right", bbox_to_anchor=(1.0, 0.9))

    # (b) edge-length distribution of the same states.
    ax = axes[0, 1]
    style_axes(ax)
    bins = np.linspace(0.0, 1.4, 113)
    for color, (p0, T), r, ell in zip(T_COLOR, T_SERIES, trs, samples):
        ax.hist(ell, bins=bins, density=True, histtype="step", color=color, lw=1.8,
                label=rf"$\sigma_\ell={ell.std():.2f}$, {100 * np.mean(np.abs(ell / S_HEX - 1) < 0.1):.0f}% within $\pm10\%$")
    ax.axvline(S_HEX, color=MUTED, lw=0.9, ls=(0, (4, 3)))
    ax.text(S_HEX - 0.02, 2.55, rf"$s_{{\mathrm{{hex}}}}={S_HEX:.3f}$", color=INK2, fontsize=FS_NOTE, ha="right")
    ax.set_xlim(0.0, 1.4)
    ax.set_ylim(0, 2.7)
    ax.set_xlabel(r"edge length $\ell$", fontsize=FS_LABEL, color=INK)
    ax.set_ylabel(r"$P(\ell)$", fontsize=FS_LABEL, color=INK)
    ax.set_title("(b) edge lengths, same states", fontsize=FS_TITLE, color=INK, loc="left")
    ax.legend(fontsize=FS_LEGEND, frameon=False, loc="upper right")

    # (c) where the second vertex peak sits.
    groups = by_p0(rows)
    ax = axes[1, 0]
    style_axes(ax)
    for p0 in P0_ORDER:
        pts = [(r["T"], r["q2_vert"]) for r in groups[p0] if math.isfinite(r["q2_vert"])]
        if pts:
            x, y = np.array(pts).T
            ax.plot(x, y, "-o", color=P0_COLOR[p0], lw=1.6, ms=5, mec="white", mew=0.8, label=rf"$p_0={p0:.3f}$")
    hot_ell = np.mean([r["ell_mean"] for r in rows if r["T"] > 0.09])
    ax.axhline(G2_HEX, color=MUTED, lw=0.9, ls=(0, (4, 3)))
    ax.text(0.03, G2_HEX + 0.04, rf"honeycomb $\sqrt{{3}}q^*=4\pi/(\sqrt{{3}}s_{{\mathrm{{hex}}}})={G2_HEX:.2f}$",
            color=INK2, fontsize=FS_NOTE, transform=ax.get_yaxis_transform())
    ax.axhline(7.016 / hot_ell, color=MUTED, lw=0.9, ls=(0, (1, 2)))
    ax.text(0.03, 7.016 / hot_ell - 0.13, rf"edge-pair maximum $7.02/\langle\ell\rangle={7.016 / hot_ell:.2f}$ (hot)",
            color=INK2, fontsize=FS_NOTE, transform=ax.get_yaxis_transform())
    ax.set_xscale("log")
    ax.set_ylim(9.7, 12.0)
    ax.set_xlabel(r"$T$", fontsize=FS_LABEL, color=INK)
    ax.set_ylabel(r"second-peak position $q_2$", fontsize=FS_LABEL, color=INK)
    ax.set_title("(c) the second peak moves to the honeycomb value", fontsize=FS_TITLE, color=INK, loc="left")
    ax.legend(fontsize=FS_LEGEND - 1, frameon=False, loc="lower left", ncol=2, columnspacing=1.0)

    # (d) height of the sqrt(3) q* peak against the edge spread.
    ax = axes[1, 1]
    style_axes(ax)
    cold = [r for r in rows if math.isfinite(r["S2_vert"]) and r["q2_vert"] > 11.3]
    hot = [r for r in rows if math.isfinite(r["S2_vert"]) and r["q2_vert"] <= 11.3]
    for p0 in P0_ORDER:
        for sub, filled in ((cold, True), (hot, False)):
            pts = [(r["ell_std"], r["S2_vert"] - 1.0) for r in sub if match_p0(r["p0"]) == p0]
            if pts:
                x, y = np.array(pts).T
                ax.plot(x, y, "o", ms=6, mec=P0_COLOR[p0] if not filled else "white", mew=1.2 if not filled else 0.8,
                        mfc=P0_COLOR[p0] if filled else "white")
    xs = np.array([r["ell_std"] for r in cold])
    ys = np.log(np.array([r["S2_vert"] - 1.0 for r in cold]))
    lnA = float(np.mean(ys + 0.5 * G2_HEX ** 2 * xs ** 2))
    slope, icpt = np.polyfit(xs ** 2, ys, 1)
    sg = np.linspace(0.16, 0.31, 100)
    ax.plot(sg, np.exp(lnA - 0.5 * G2_HEX ** 2 * sg ** 2), color=INK2, lw=1.0,
            label=r"$\propto e^{-G_2^2\sigma_\ell^2/2}$, $G_2=\sqrt{3}q^*$")
    et = [(r["ell_std"], r["edge_term_g2"]) for r in cold if r["edge_term_g2"] > 0]
    if et:
        x, y = np.array(et).T
        ax.plot(x, y, "D", ms=4.5, mfc="white", mec=MUTED, mew=1.0,
                label=r"edge pairs only, $3\langle J_0(G_2\ell)\rangle$")
    ax.plot([], [], "o", ms=6, mfc=INK2, mec="white", label=r"measured, peak at $\sqrt{3}q^*$")
    ax.plot([], [], "o", ms=6, mfc="white", mec=INK2, mew=1.2, label=r"measured, hot ($q_2<11.3$)")
    ax.set_yscale("log")
    ax.set_xlim(0.155, 0.315)
    ax.set_ylim(0.03, 2.0)
    ax.set_xlabel(r"edge-length spread $\sigma_\ell$", fontsize=FS_LABEL, color=INK)
    ax.set_ylabel(r"$S(q_2)-1$", fontsize=FS_LABEL, color=INK)
    ax.set_title("(d) second-peak height vs edge spread", fontsize=FS_TITLE, color=INK, loc="left")
    ax.legend(fontsize=FS_LEGEND - 1, frameon=False, loc="upper right")
    out = OUTDIR / "hex_vertex_sq.png"
    fig.savefig(out, dpi=150)
    plt.close(fig)
    return out, {"dw_slope_fit": float(slope), "dw_slope_pred": -0.5 * G2_HEX ** 2, "n_cold": len(cold),
                 "edge_sigma": [float(e.std()) for e in samples], "edge_mean": [float(e.mean()) for e in samples]}


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--recompute", action="store_true", help="rebuild hex_metrics.csv from trajectories")
    args = ap.parse_args()
    OUTDIR.mkdir(parents=True, exist_ok=True)
    rows = compute_metrics(args.recompute)
    nbad = int(sum(r["n_bad"] for r in rows))
    if nbad:
        print(f"WARNING: {nbad} frames failed the polygon checks (sum A = L^2, <z> = 6)")
    print(f"wrote {fig_snapshots(rows)}")
    print(f"wrote {fig_order_vs_T(rows)}")
    out, info = fig_vs_sq(rows)
    print(f"wrote {out}")
    for d in info:
        print(
            f"  2D S(k) p0={d['p0']:.3f} T={d['T']:.6g}: frame |Psi6|={d['psi6_frame']:.3f} "
            f"max S(k)={d['S2d_max']:.1f} annulus max={d['S_ring_frame']:.2f}"
        )
    out, vinfo = fig_vertex_sq(rows)
    print(f"wrote {out}")
    print(
        f"  vertex sqrt(3) q* peak: ln(S2-1) slope vs sigma_ell^2 = {vinfo['dw_slope_fit']:.1f} "
        f"(Debye-Waller from edge spread: {vinfo['dw_slope_pred']:.1f}; {vinfo['n_cold']} states)"
    )
    print("p0     T          p6     mu2    |Psi6|  <q|6>  ang6   S(q*)  S*(1-p6)  tau_kww")
    for r in sorted(rows, key=lambda r: (r["p0"], r["T"])):
        print(
            f"{r['p0']:.3f} {r['T']:.7f}  {r['p6']:.3f}  {r['mu2']:.3f}  {r['psi6_global']:.3f}  "
            f"{r['q6_mean']:.3f}  {r['angle_std6_deg']:.1f}  {r['S_peak']:6.2f}  "
            f"{r['S_peak'] * (1 - r['p6']):6.3f}   {r['tau_kww']:.4g}"
        )


if __name__ == "__main__":
    main()
