#!/usr/bin/env python3
"""
Generated by Cursor. 2026-09-14.
Nine new production T from Bayesian KWW tau_alpha; do not redo existing T.

Physics:
  tau_alpha := tau_KWW from the global HMC fit,
  mu(t) = A exp(-(t/tau)^beta), F(tau) = A/e (A~0.61, not CRSISF 1/e).
  Target grid: ~10 T per p0 spanning tau_KWW from 10 to 10^4
  (tau_k = 10**(1+k/3); factor-1.5 match is enough).
  Hot end (tau=10): log tau vs log T from the hottest production KWW
  point to a scout liquid 1/e (A~0.61 does not apply in the liquid).
  p0=3.750 and 3.850 have no scout overshoot; use the mean of those
  four log-log slopes. Cold/interior: log tau vs 1/T on the KWW
  segment that contains the target.
  Units: reduced kT, p0 target shape index.
  Production -t is tauAlphaEst (KWW target); tau_block = max(tau, 1000).

Usage:
  python3 propose_vertex_production_kww_fill.py
"""

from __future__ import annotations

import csv
import math
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

HERE = Path(__file__).resolve().parent
KWW_CSV = HERE / "vertexModel_productionFs" / "kww_global_tau.csv"
PROD_CSV = HERE / "vertexModel_tauAlpha_final" / "production_state_points.csv"
SCOUT_CSV = HERE / "vertexModel_tauAlpha_final" / "vertex_longest_crossed.csv"
OUTDIR = HERE / "vertexModel_productionKwwFill"

P0_ORDER = (3.750, 3.775, 3.800, 3.815, 3.825, 3.850)
TAU_HOT = 10.0
TAU_4642 = 10.0 ** (1.0 + 8.0 / 3.0)
TAU_1E4 = 1.0e4
DUP_REL = 0.005

# (p0, tau_target, role)
FILLS = (
    (3.750, TAU_HOT, "hot"),
    (3.775, TAU_HOT, "hot"),
    (3.800, TAU_HOT, "hot"),
    (3.815, TAU_HOT, "hot"),
    (3.825, TAU_HOT, "hot"),
    (3.850, TAU_HOT, "hot"),
    (3.750, TAU_4642, "cold"),
    (3.815, TAU_1E4, "cold"),
    (3.850, TAU_1E4, "cold"),
)


def load_kww(path: Path):
    rows = []
    with path.open() as f:
        for r in csv.DictReader(f):
            rows.append(
                {
                    "p0": float(r["p0"]),
                    "T": float(r["T"]),
                    "tau_kww": float(r["tau_kww"]),
                    "tau_1e": float(r["tau_1e"]),
                }
            )
    return rows


def load_scout(path: Path):
    rows = []
    with path.open() as f:
        for r in csv.DictReader(f):
            tau_s = (r.get("tauAlpha") or "").strip()
            tau = float(tau_s) if tau_s else math.nan
            rows.append({"p0": float(r["p0"]), "T": float(r["T"]), "tau_1e": tau})
    return rows


def load_prod_T(path: Path):
    out = []
    with path.open() as f:
        lines = [ln for ln in f if ln.strip() and not ln.lstrip().startswith("#")]
    for r in csv.DictReader(lines):
        out.append((float(r["p0"]), float(r["T"])))
    return out


def match_p0(p0: float, q: float) -> bool:
    return abs(p0 - q) < 1e-4


def kww_table(kww_rows, p0):
    """(T, tau_kww) hot to cold."""
    tab = [
        (r["T"], r["tau_kww"])
        for r in kww_rows
        if match_p0(r["p0"], p0) and math.isfinite(r["tau_kww"]) and r["tau_kww"] > 0
    ]
    tab.sort(key=lambda x: -x[0])
    return tab


def production_T_set(kww_rows, prod_rows):
    pairs = [(r["p0"], r["T"]) for r in kww_rows]
    pairs.extend(prod_rows)
    return pairs


def is_dup_T(p0, T, existing) -> bool:
    for ep0, eT in existing:
        if match_p0(ep0, p0) and abs(T - eT) / max(abs(eT), 1e-30) < DUP_REL:
            return True
    return False


def invert_logT(T0, tau0, T1, tau1, tau_t):
    lx0, ly0 = math.log(T0), math.log(tau0)
    lx1, ly1 = math.log(T1), math.log(tau1)
    slope = (ly1 - ly0) / (lx1 - lx0)
    if slope == 0:
        raise ValueError("flat log-T slope")
    lx = lx0 + (math.log(tau_t) - ly0) / slope
    return math.exp(lx), slope


def invert_1T_segment(table, tau_target):
    """Walk hot-to-cold; use the last segment that contains tau_target."""
    yt = math.log(tau_target)
    hit = None
    for i in range(len(table) - 1):
        T0, tau0 = table[i]
        T1, tau1 = table[i + 1]
        lo, hi = min(tau0, tau1), max(tau0, tau1)
        if lo <= tau_target <= hi:
            if tau0 == tau1:
                hit = T0
                continue
            y0, y1 = math.log(tau0), math.log(tau1)
            x0, x1 = 1.0 / T0, 1.0 / T1
            inv_T = x0 + (yt - y0) * (x1 - x0) / (y1 - y0)
            if inv_T <= 0:
                raise ValueError(f"non-positive 1/T for tau={tau_target}")
            hit = 1.0 / inv_T
    if hit is None:
        raise ValueError(f"tau={tau_target} not on a KWW 1/T segment")
    return hit


def scout_liquid(scout_rows, p0, T_hot_prod):
    """Hottest scout T warmer than production hottest, with finite 1/e."""
    cand = []
    for r in scout_rows:
        if not match_p0(r["p0"], p0):
            continue
        if not math.isfinite(r["tau_1e"]) or r["tau_1e"] <= 0:
            continue
        if r["T"] > T_hot_prod * (1.0 + DUP_REL):
            cand.append((r["T"], r["tau_1e"]))
    if not cand:
        return None
    cand.sort(key=lambda x: -x[0])
    return cand[0]


def hot_slopes_from_scout(kww_rows, scout_rows):
    slopes = []
    anchors = {}
    for p0 in P0_ORDER:
        tab = kww_table(kww_rows, p0)
        if len(tab) < 1:
            continue
        Tm, tkm = tab[0]
        liq = scout_liquid(scout_rows, p0, Tm)
        if liq is None:
            continue
        Ts, t1e = liq
        _, slope = invert_logT(Tm, tkm, Ts, t1e, TAU_HOT)
        slopes.append(slope)
        anchors[p0] = (Tm, tkm, Ts, t1e, slope)
    if not slopes:
        raise SystemExit("need at least one scout liquid for the hot-end slope")
    return float(np.mean(slopes)), anchors


def invert_hot(p0, tab, mean_slope, scout_anchors):
    Tm, tkm = tab[0]
    if p0 in scout_anchors:
        Tm, tkm, Ts, t1e, _ = scout_anchors[p0]
        T, slope = invert_logT(Tm, tkm, Ts, t1e, TAU_HOT)
        how = "logT_prodKWW_scout1e"
        note = f"scout_T={Ts:.8g} scout_1e={t1e:.6g} slope={slope:.4g}"
        return T, how, note
    T = math.exp(math.log(Tm) + (math.log(TAU_HOT) - math.log(tkm)) / mean_slope)
    how = "logT_mean_slope"
    note = f"T_prod={Tm:.8g} kww={tkm:.6g} mean_slope={mean_slope:.4g}"
    return T, how, note


def plot_grid(kww_rows, points, outpath: Path):
    fig, axes = plt.subplots(2, 3, figsize=(11.0, 7.2), sharex=False, sharey=True)
    for i, p0 in enumerate(P0_ORDER):
        ax = axes.ravel()[i]
        kk = [r for r in kww_rows if match_p0(r["p0"], p0)]
        kk.sort(key=lambda r: -r["T"])
        ax.scatter(
            [r["T"] for r in kk],
            [r["tau_kww"] for r in kk],
            c="0.35",
            s=28,
            zorder=3,
            label=r"existing $\tau_{\mathrm{KWW}}$",
        )
        pp = [p for p in points if match_p0(float(p["p0"]), p0)]
        if pp:
            ax.scatter(
                [float(p["T"]) for p in pp],
                [float(p["tauAlphaEst"]) for p in pp],
                facecolors="none",
                edgecolors="C3",
                s=64,
                zorder=8,
                label="new production $T$",
            )
        ax.axhline(10.0, color="0.75", ls="--", lw=0.8)
        ax.axhline(1.0e4, color="0.75", ls="--", lw=0.8)
        ax.set_xscale("log")
        ax.set_yscale("log")
        ax.set_title(rf"$p_0={p0:.3f}$")
        ax.set_xlabel(r"$T$")
        ax.set_ylabel(r"$\tau_{\mathrm{KWW}}$")
        ax.legend(loc="best", fontsize=7, frameon=False)
    fig.suptitle(
        r"KWW production fill: keep existing $T$, add 9 (hot $\tau=10$ + 3 cold)",
        y=1.01,
    )
    fig.tight_layout()
    fig.savefig(outpath, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"wrote {outpath}")


def main():
    kww_rows = load_kww(KWW_CSV)
    scout_rows = load_scout(SCOUT_CSV)
    prod_T = load_prod_T(PROD_CSV)
    existing = production_T_set(kww_rows, prod_T)
    mean_slope, scout_anchors = hot_slopes_from_scout(kww_rows, scout_rows)

    points = []
    print(f"hot-end mean log-log slope = {mean_slope:.5g}  n_scout={len(scout_anchors)}")
    for p0, tau_k, role in FILLS:
        tab = kww_table(kww_rows, p0)
        if len(tab) < 2:
            raise SystemExit(f"need >=2 KWW points for p0={p0}")
        if role == "hot":
            T, how, note = invert_hot(p0, tab, mean_slope, scout_anchors)
        else:
            T = invert_1T_segment(tab, tau_k)
            how = "1/T_kww_segment"
            note = ""
        if is_dup_T(p0, T, existing):
            raise SystemExit(f"new T={T} duplicates production T at p0={p0}")
        print(
            f"  p0={p0:.3f} tau_k={tau_k:.6g} T={T:.8g} how={how} {note}"
        )
        points.append(
            {
                "p0": f"{p0:.3f}",
                "T": f"{T:.8g}",
                "tauAlphaEst": f"{tau_k:.6g}",
                "how": how,
                "note": note,
            }
        )

    if len(points) != 9:
        raise SystemExit(f"expected 9 fills, got {len(points)}")

    OUTDIR.mkdir(parents=True, exist_ok=True)
    out_csv = OUTDIR / "state_points.csv"
    with out_csv.open("w", newline="") as f:
        f.write("# Generated by Cursor. 2026-09-14\n")
        f.write(
            "# New production T from global KWW tau_alpha. "
            "Do not redo existing production T.\n"
        )
        f.write(
            "# -t is tauAlphaEst (KWW target). tau_block=max(tauAlphaEst,1000).\n"
        )
        w = csv.DictWriter(
            f, fieldnames=["p0", "T", "tauAlphaEst", "how", "note"]
        )
        w.writeheader()
        for r in points:
            w.writerow(r)
    print(f"wrote {out_csv} ({len(points)} rows)")
    plot_grid(kww_rows, points, OUTDIR / "kww_fill_tau_vs_T.png")


if __name__ == "__main__":
    main()
