#!/usr/bin/env python3
"""
Generated by Cursor. 2026-09-11.
Sixth-batch T grid at default l_T1=0.01 from batches 2-5 longest-crossed tau_alpha.

Physics:
  tau_alpha is the longest t_w whose CRSISF still crosses 1/e (q=6.80,
  cell centroids). Default T1 cutoff l_T1=0.01 (mean cell area 1).
  Batch 5 still missed the factor-1.5 cut at six tau_k. Invert log tau vs
  1/T on the *coldest* segment that contains tau_k (hot end: log T) so a
  non-monotonic jump does not map tau=10^4 onto the same T as tau=4642.
  Skip a job if T_new is within 0.5% of the last targeting T.
  Units: reduced kT, p0 target shape index.

Usage:
  python3 propose_vertex_tau_alpha_batch6.py
"""

from __future__ import annotations

import math
import sys
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

HERE = Path(__file__).resolve().parent
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))

from propose_vertex_tau_alpha_batch4 import (
    B2_STATE,
    B3_STATE,
    CURVE_B1,
    CURVE_B2,
    CURVE_B3,
    P0_ORDER,
    RATIO_CUT,
    TAU_TARGETS,
    find_state_T,
    fold_ratio,
    invert_T_loglog_hot,
    load_curves,
    load_state,
    longest_crossed_tw_rows,
    match_anchor,
    meas_table,
    merge_anchors,
    tau_meas_of_T,
    write_csv,
)
from propose_vertex_tau_alpha_batch5 import B4_STATE, CURVE_B4

CURVE_B5 = HERE / "vertexModel_tauAlpha_batch5" / "vertexModel_tauAlpha_batch5_per_curve.csv"
B5_STATE = HERE / "vertexModel_tauAlpha_batch5" / "state_points.csv"
OUTDIR = HERE / "vertexModel_tauAlpha_batch6"
DUP_REL = 0.005

# Same six (p0, tau_k) that batch 5 targeted.
GAPS = (
    (3.750, 10.0 ** (1.0 + 8.0 / 3.0)),
    (3.750, 1.0e4),
    (3.775, 10.0),
    (3.775, 1.0e4),
    (3.800, 10.0),
    (3.815, 1.0e4),
)


def is_gap(p0, tau_k):
    for gp0, gtau in GAPS:
        if abs(p0 - gp0) < 1e-4 and abs(tau_k - gtau) / gtau < 1e-4:
            return True
    return False


def invert_T_coldest_segment(table, tau_target):
    """Walk hot-to-cold; keep the last (coldest) segment containing tau_target."""
    yt = math.log(tau_target)
    tau_hot = table[0][1]
    tau_cold = table[-1][1]
    if tau_target <= tau_hot:
        return invert_T_loglog_hot(table, tau_target), "logT"
    hit = None
    for i in range(len(table) - 1):
        T0, tau0 = table[i]
        T1, tau1 = table[i + 1]
        lo, hi = min(tau0, tau1), max(tau0, tau1)
        if lo <= tau_target <= hi:
            if tau0 == tau1:
                hit = (T0, "1/T")
                continue
            y0, y1 = math.log(tau0), math.log(tau1)
            x0, x1 = 1.0 / T0, 1.0 / T1
            inv_T = x0 + (yt - y0) * (x1 - x0) / (y1 - y0)
            if inv_T <= 0:
                raise ValueError(f"non-positive 1/T for tau={tau_target}")
            hit = (1.0 / inv_T, "1/T")
    if hit is not None:
        return hit
    if tau_target >= tau_cold:
        x = [1.0 / T for T, _ in table]
        y = [math.log(tau) for _, tau in table]
        slope = (y[-1] - y[-2]) / (x[-1] - x[-2])
        if slope == 0:
            raise ValueError("flat measured tau")
        inv_T = x[-1] + (yt - y[-1]) / slope
        if inv_T <= 0:
            raise ValueError(f"non-positive 1/T for tau={tau_target}")
        return 1.0 / inv_T, "1/T"
    raise ValueError(f"could not invert tau={tau_target}")


def plot_grid(anchors, points, outpath: Path):
    fig, axes = plt.subplots(2, 3, figsize=(11.0, 7.2), sharex=False, sharey=True)
    batch_style = {
        2: dict(c="C1", s=22, zorder=3, label="batch-2"),
        3: dict(c="C3", s=28, zorder=4, label="batch-3"),
        4: dict(c="C4", s=32, zorder=5, label="batch-4"),
        5: dict(c="C5", s=36, zorder=6, label="batch-5"),
    }
    for i, p0 in enumerate(P0_ORDER):
        ax = axes.ravel()[i]
        tab = meas_table([a for a in anchors if a["batch"] >= 2], p0)
        aa = [a for a in anchors if abs(a["p0"] - p0) < 1e-4]
        for b, sty in batch_style.items():
            crossed = [
                a
                for a in aa
                if a["batch"] == b and a["crossed"] == 1 and math.isfinite(a["tauAlpha"])
            ]
            if not crossed:
                continue
            ax.scatter(
                [a["T"] for a in crossed],
                [a["tauAlpha"] for a in crossed],
                c=sty["c"],
                s=sty["s"],
                zorder=sty["zorder"],
                label=sty["label"],
            )
        if len(tab) >= 2:
            Ts = np.geomspace(min(T for T, _ in tab) * 0.6, max(T for T, _ in tab) * 1.3, 80)
            ax.plot(Ts, [tau_meas_of_T(tab, T) for T in Ts], "C0-", lw=1.1, label=r"interp $\tau(T)$")
        pp = [p for p in points if abs(float(p["p0"]) - p0) < 1e-4]
        if pp:
            ax.scatter(
                [float(p["T"]) for p in pp],
                [float(p["tauAlphaEst"]) for p in pp],
                facecolors="none",
                edgecolors="C2",
                s=52,
                zorder=8,
                label="batch-6 $T$",
            )
        ax.set_xscale("log")
        ax.set_yscale("log")
        ax.set_title(rf"$p_0={p0:.3f}$")
        ax.set_xlabel(r"$T$")
        ax.set_ylabel(r"$\tau_\alpha$")
        ax.legend(loc="best", fontsize=6, frameon=False)
    fig.suptitle(r"batch 6: default $\ell_{T1}=0.01$, coldest-segment invert", y=1.01)
    fig.tight_layout()
    fig.savefig(outpath, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"wrote {outpath}")


def main():
    a1 = longest_crossed_tw_rows(load_curves(CURVE_B1), 1)
    a2 = longest_crossed_tw_rows(load_curves(CURVE_B2), 2)
    a3 = longest_crossed_tw_rows(load_curves(CURVE_B3), 3)
    a4 = longest_crossed_tw_rows(load_curves(CURVE_B4), 4)
    a5 = longest_crossed_tw_rows(load_curves(CURVE_B5), 5)
    anchors_all = merge_anchors(a1, a2, a3, a4, a5)
    anchors_inv = merge_anchors(a2, a3, a4, a5)
    b2 = load_state(B2_STATE)
    b3 = load_state(B3_STATE)
    b4 = load_state(B4_STATE)
    b5 = load_state(B5_STATE)

    points = []
    skipped = []
    print("batch-6 reruns (default l_T1=0.01, coldest-segment invert):")
    for p0 in P0_ORDER:
        tab = meas_table(anchors_inv, p0)
        if len(tab) < 2:
            raise SystemExit(f"need >=2 measured anchors for p0={p0}")
        for tau_k in TAU_TARGETS:
            if not is_gap(p0, tau_k):
                continue
            T5 = find_state_T(b5, p0, tau_k)
            T4 = find_state_T(b4, p0, tau_k)
            T3 = find_state_T(b3, p0, tau_k)
            T2 = find_state_T(b2, p0, tau_k)
            if T5 is not None:
                T_old, src_run, pool = T5, "b5", a5
            elif T4 is not None:
                T_old, src_run, pool = T4, "b4", a4
            elif T3 is not None:
                T_old, src_run, pool = T3, "b3", a3
            else:
                T_old, src_run, pool = T2, "b2", a2
            anc = match_anchor(p0, T_old, pool) if T_old is not None else None
            meas = anc["tauAlpha"] if anc and anc["crossed"] == 1 else math.nan
            rat = fold_ratio(meas, tau_k)
            T, how = invert_T_coldest_segment(tab, tau_k)
            src = "coldest_logT" if how == "logT" else "coldest_1/T"
            dup = (
                T_old is not None
                and abs(T - T_old) / max(abs(T_old), 1e-30) < DUP_REL
            )
            print(
                f"  p0={p0:.3f} tau_k={tau_k:.6g} {src_run} T_old={T_old:.6g} "
                f"meas={meas:.4g} ratio={rat:.3g} T_new={T:.6g}"
            )
            if dup:
                print("    skip near-duplicate T")
                skipped.append((p0, tau_k, T, T_old))
                continue
            points.append(
                {
                    "p0": f"{p0:.3f}",
                    "T": f"{T:.8g}",
                    "tauAlphaEst": f"{tau_k:.6g}",
                    "T_old": "" if T_old is None else f"{T_old:.8g}",
                    "tauMeasUsed": "" if not math.isfinite(meas) else f"{meas:.8g}",
                    "ratio": "" if not math.isfinite(rat) else f"{rat:.6g}",
                    "reason": "ratio>=1.5",
                    "source": src,
                    "fromBatch": src_run,
                }
            )

    OUTDIR.mkdir(parents=True, exist_ok=True)
    write_csv(
        OUTDIR / "state_points.csv",
        [
            "p0",
            "T",
            "tauAlphaEst",
            "T_old",
            "tauMeasUsed",
            "ratio",
            "reason",
            "source",
            "fromBatch",
        ],
        points,
    )
    plot_grid(anchors_all, points, OUTDIR / "vertexModel_tauAlpha_batch6_tau_vs_T.png")
    print(f"n_jobs={len(points)} skipped_dup={len(skipped)}")
    if not (4 <= len(points) <= 6):
        raise SystemExit(f"unexpected n_jobs={len(points)}")


if __name__ == "__main__":
    main()
