#!/usr/bin/env python3
"""
Generated by Cursor. 2026-08-25.
Third-batch T grid from batch-2 longest-t_w CRSISF 1/e tau_alpha.

Physics:
  Longest waiting-time 1/e crossing is the measured tau_alpha(T).
  Rerun a target tau_k = 10**(1+k/3) if tau_k >= 1000 or the batch-2
  longest-t_w value differs from tau_k by a factor >= 1.5.
  New T from piecewise log tau_meas vs 1/T (hot end: log tau vs log T).

Usage:
  python3 propose_vertex_tau_alpha_batch3.py
"""

from __future__ import annotations

import csv
import math
from collections import defaultdict
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

HERE = Path(__file__).resolve().parent
CURVE_CSV = HERE / "vertexModel_tauAlpha_batch2" / "vertexModel_tauAlpha_batch2_per_curve.csv"
B2_STATE = HERE / "vertexModel_tauAlpha_batch2" / "state_points.csv"
OUTDIR = HERE / "vertexModel_tauAlpha_batch3"

P0_ORDER = (3.750, 3.775, 3.800, 3.815, 3.825, 3.850)
TAU_TARGETS = [10.0 ** (1.0 + k / 3.0) for k in range(10)]
RATIO_CUT = 1.5
TAU_COLD = 1000.0


def load_curves(path: Path):
    rows = []
    with path.open() as f:
        for r in csv.DictReader(f):
            tau_s = (r.get("tauAlpha") or "").strip()
            tau = float(tau_s) if tau_s else math.nan
            rows.append(
                {
                    "p0": float(r["p0"]),
                    "T": float(r["T"]),
                    "waitingTime": float(r["waitingTime"]),
                    "tauAlphaEst": float(r["tauAlphaEst"]) if r["tauAlphaEst"] else math.nan,
                    "tauAlpha": tau,
                    "crossed": int(r["crossed"]),
                }
            )
    return rows


def load_b2_state(path: Path):
    pts = []
    with path.open() as f:
        for r in csv.DictReader(f):
            pts.append((float(r["p0"]), float(r["T"]), float(r["tauAlphaEst"])))
    return pts


def longest_tw_rows(rows):
    groups = defaultdict(list)
    for r in rows:
        groups[(r["p0"], r["T"])].append(r)
    out = []
    for (p0, T), grp in sorted(groups.items()):
        best = max(grp, key=lambda z: z["waitingTime"])
        out.append(
            {
                "p0": p0,
                "T": T,
                "waitingTime": best["waitingTime"],
                "tauAlphaEst": best["tauAlphaEst"],
                "tauAlpha": best["tauAlpha"],
                "crossed": best["crossed"],
            }
        )
    return out


def match_anchor(p0, T, anchors, rel=1e-5):
    for a in anchors:
        if abs(a["p0"] - p0) < 1e-4 and abs(a["T"] - T) / max(abs(T), 1e-30) < rel:
            return a
    return None


def meas_table(anchors, p0):
    """(T, tau) hot to cold, longest t_w crossed only."""
    tab = []
    for a in anchors:
        if abs(a["p0"] - p0) > 1e-4:
            continue
        if a["crossed"] != 1 or not math.isfinite(a["tauAlpha"]) or a["tauAlpha"] <= 0:
            continue
        tab.append((a["T"], a["tauAlpha"]))
    tab.sort(key=lambda x: -x[0])
    return tab


def invT_logtau(table):
    x = np.array([1.0 / T for T, _ in table], dtype=float)
    y = np.array([math.log(tau) for _, tau in table], dtype=float)
    order = np.argsort(x)
    return x[order], y[order]


def invert_T_loglog_hot(table, tau_target):
    T0, tau0 = table[0]
    T1, tau1 = table[1]
    lx0, ly0 = math.log(T0), math.log(tau0)
    lx1, ly1 = math.log(T1), math.log(tau1)
    slope = (ly1 - ly0) / (lx1 - lx0)
    if slope == 0:
        raise ValueError("flat measured tau (log T)")
    lx = lx0 + (math.log(tau_target) - ly0) / slope
    return math.exp(lx)


def invert_T_for_tau_meas(table, tau_target):
    x, y = invT_logtau(table)
    yt = math.log(tau_target)
    if yt <= y[0]:
        return invert_T_loglog_hot(table, tau_target), "logT"
    if yt >= y[-1]:
        slope = (y[-1] - y[-2]) / (x[-1] - x[-2])
        if slope == 0:
            raise ValueError("flat measured tau")
        inv_T = x[-1] + (yt - y[-1]) / slope
        if inv_T <= 0:
            raise ValueError(f"non-positive 1/T for tau={tau_target}")
        return 1.0 / inv_T, "1/T"
    inv_T = float(np.interp(yt, y, x))
    return 1.0 / inv_T, "1/T"


def tau_meas_of_T(table, T):
    x, y = invT_logtau(table)
    inv_T = 1.0 / T
    if inv_T <= x[0]:
        slope = (y[1] - y[0]) / (x[1] - x[0])
        return math.exp(y[0] + slope * (inv_T - x[0]))
    if inv_T >= x[-1]:
        slope = (y[-1] - y[-2]) / (x[-1] - x[-2])
        return math.exp(y[-1] + slope * (inv_T - x[-1]))
    return math.exp(float(np.interp(inv_T, x, y)))


def fold_ratio(meas, est):
    if not (meas > 0 and est > 0 and math.isfinite(meas) and math.isfinite(est)):
        return math.nan
    return max(meas / est, est / meas)


def write_csv(path: Path, fieldnames, rows):
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames)
        w.writeheader()
        for r in rows:
            w.writerow(r)
    print(f"wrote {path} ({len(rows)} rows)")


def plot_grid(anchors, points, outpath: Path):
    fig, axes = plt.subplots(2, 3, figsize=(11.0, 7.2), sharex=False, sharey=True)
    for i, p0 in enumerate(P0_ORDER):
        ax = axes.ravel()[i]
        tab = meas_table(anchors, p0)
        aa = [a for a in anchors if abs(a["p0"] - p0) < 1e-4]
        crossed = [a for a in aa if a["crossed"] == 1 and math.isfinite(a["tauAlpha"])]
        ax.scatter(
            [a["T"] for a in crossed],
            [a["tauAlpha"] for a in crossed],
            c="C3",
            s=36,
            zorder=4,
            label=r"batch-2 longest $t_w$",
        )
        if len(tab) >= 2:
            Ts = np.geomspace(min(T for T, _ in tab) * 0.6, max(T for T, _ in tab) * 1.3, 80)
            ax.plot(Ts, [tau_meas_of_T(tab, T) for T in Ts], "C0-", lw=1.1, label=r"interp $\tau(T)$")
        pp = [p for p in points if abs(float(p["p0"]) - p0) < 1e-4]
        if pp:
            ax.scatter(
                [float(p["T"]) for p in pp],
                [float(p["tauAlphaEst"]) for p in pp],
                facecolors="none",
                edgecolors="C2",
                s=48,
                zorder=5,
                label="batch-3 $T$",
            )
        b2 = [a for a in aa if math.isfinite(a["tauAlphaEst"])]
        ax.scatter(
            [a["T"] for a in b2],
            [a["tauAlphaEst"] for a in b2],
            c="k",
            s=22,
            marker="x",
            zorder=3,
            label="batch-2 target",
        )
        ax.set_xscale("log")
        ax.set_yscale("log")
        ax.set_title(rf"$p_0={p0:.3f}$")
        ax.set_xlabel(r"$T$")
        ax.set_ylabel(r"$\tau_\alpha$")
        ax.legend(loc="best", fontsize=6, frameon=False)
    fig.suptitle(r"batch 3: $T$ from measured longest $t_w$ $\tau_\alpha$", y=1.01)
    fig.tight_layout()
    fig.savefig(outpath, dpi=150, bbox_inches="tight")
    plt.close(fig)
    print(f"wrote {outpath}")


def main():
    rows = load_curves(CURVE_CSV)
    b2 = load_b2_state(B2_STATE)
    anchors = longest_tw_rows(rows)

    print("batch-2 longest t_w:")
    for a in anchors:
        tau = a["tauAlpha"] if math.isfinite(a["tauAlpha"]) else float("nan")
        rat = fold_ratio(tau, a["tauAlphaEst"])
        print(
            f"  p0={a['p0']:.3f} T={a['T']:.6g} est={a['tauAlphaEst']:g} "
            f"tw={a['waitingTime']:g} crossed={a['crossed']} tau={tau:.4g} "
            f"ratio={rat:.3g}"
        )

    points = []
    print("batch-3 reruns:")
    for p0 in P0_ORDER:
        tab = meas_table(anchors, p0)
        if len(tab) < 2:
            raise SystemExit(f"need >=2 measured anchors for p0={p0}")
        for tau_k in TAU_TARGETS:
            b2pt = None
            for sp0, sT, stau in b2:
                if abs(sp0 - p0) < 1e-4 and abs(stau - tau_k) / tau_k < 1e-4:
                    b2pt = (sT, stau)
                    break
            anc = match_anchor(p0, b2pt[0], anchors) if b2pt else None
            meas = anc["tauAlpha"] if anc and anc["crossed"] == 1 else math.nan
            rat = fold_ratio(meas, tau_k)
            cold = tau_k + 1e-9 >= TAU_COLD
            hot_off = math.isfinite(rat) and rat >= RATIO_CUT
            if not (cold or hot_off):
                continue
            T, how = invert_T_for_tau_meas(tab, tau_k)
            src = "meas_inverted_logT" if how == "logT" else "meas_inverted"
            reason = "tau>=1000" if cold else "ratio>=1.5"
            print(
                f"  p0={p0:.3f} tau_k={tau_k:.6g} T_old={b2pt[0] if b2pt else math.nan:.6g} "
                f"T_new={T:.6g} meas={meas:.4g} ratio={rat:.3g} {reason} {src}"
            )
            points.append(
                {
                    "p0": f"{p0:.3f}",
                    "T": f"{T:.8g}",
                    "tauAlphaEst": f"{tau_k:.6g}",
                    "tauMeasUsed": "" if not math.isfinite(meas) else f"{meas:.8g}",
                    "ratio": "" if not math.isfinite(rat) else f"{rat:.6g}",
                    "reason": reason,
                    "source": src,
                }
            )

    OUTDIR.mkdir(parents=True, exist_ok=True)
    write_csv(
        OUTDIR / "anchors.csv",
        ["p0", "T", "waitingTime", "tauAlphaEst", "tauAlpha", "crossed"],
        [
            {
                "p0": f"{a['p0']:.3f}",
                "T": f"{a['T']:.8g}",
                "waitingTime": f"{a['waitingTime']:.8g}",
                "tauAlphaEst": f"{a['tauAlphaEst']:.8g}",
                "tauAlpha": "" if not math.isfinite(a["tauAlpha"]) else f"{a['tauAlpha']:.8g}",
                "crossed": a["crossed"],
            }
            for a in anchors
        ],
    )
    write_csv(
        OUTDIR / "state_points.csv",
        ["p0", "T", "tauAlphaEst", "tauMeasUsed", "ratio", "reason", "source"],
        points,
    )
    plot_grid(anchors, points, OUTDIR / "vertexModel_tauAlpha_batch3_tau_vs_T.png")
    print(f"n_jobs={len(points)}")


if __name__ == "__main__":
    main()
