#include "avmTopologyIO.h"
// Generated by Cursor. 2026-08-21
// Vertex-model topology I/O. VertexCellNeighbors are stored as cell tags, not vertex tags.

void AVMTopologyIO::packPositions(shared_ptr<VertexQuadraticEnergy> s, vector<double> &posdat)
    {
    int Nv = s->Nvertices;
    posdat.resize(2*Nv);
    ArrayHandle<double2> h_p(s->vertexPositions,access_location::host,access_mode::read);
    for (int ii = 0; ii < Nv; ++ii)
        {
        int pidx = s->tagToIdxVertex[ii];
        posdat[2*ii]   = h_p.data[pidx].x;
        posdat[2*ii+1] = h_p.data[pidx].y;
        };
    };

void AVMTopologyIO::packVelocities(shared_ptr<VertexQuadraticEnergy> s, vector<double> &veldat)
    {
    int Nv = s->Nvertices;
    veldat.resize(2*Nv);
    ArrayHandle<double2> h_v(s->returnVelocities(),access_location::host,access_mode::read);
    for (int ii = 0; ii < Nv; ++ii)
        {
        int pidx = s->tagToIdxVertex[ii];
        veldat[2*ii]   = h_v.data[pidx].x;
        veldat[2*ii+1] = h_v.data[pidx].y;
        };
    };

void AVMTopologyIO::packNeighbors(shared_ptr<VertexQuadraticEnergy> s, vector<int> &vndat, vector<int> &vcndat)
    {
    int Nv = s->Nvertices;
    vndat.resize(3*Nv);
    vcndat.resize(3*Nv);
    ArrayHandle<int> h_vn(s->vertexNeighbors,access_location::host,access_mode::read);
    ArrayHandle<int> h_vcn(s->vertexCellNeighbors,access_location::host,access_mode::read);
    for (int vv = 0; vv < Nv; ++vv)
        {
        int vertexIndex = s->tagToIdxVertex[vv];
        for (int ii = 0; ii < 3; ++ii)
            {
            vndat[3*vv+ii]  = s->idxToTagVertex[h_vn.data[3*vertexIndex+ii]];
            vcndat[3*vv+ii] = s->idxToTag[h_vcn.data[3*vertexIndex+ii]];
            };
        };
    };

void AVMTopologyIO::resetIdentityTags(shared_ptr<VertexQuadraticEnergy> t)
    {
    int Nv = t->Nvertices;
    int Nc = t->Ncells;
    t->tagToIdxVertex.resize(Nv);
    t->idxToTagVertex.resize(Nv);
    for (int ii = 0; ii < Nv; ++ii)
        {
        t->tagToIdxVertex[ii] = ii;
        t->idxToTagVertex[ii] = ii;
        };
    t->tagToIdx.resize(Nc);
    t->idxToTag.resize(Nc);
    for (int ii = 0; ii < Nc; ++ii)
        {
        t->tagToIdx[ii] = ii;
        t->idxToTag[ii] = ii;
        };
    };

void AVMTopologyIO::unpackPositions(shared_ptr<VertexQuadraticEnergy> t, const vector<double> &posdat)
    {
    int Nv = t->Nvertices;
    ArrayHandle<double2> h_p(t->vertexPositions,access_location::host,access_mode::overwrite);
    for (int idx = 0; idx < Nv; ++idx)
        {
        h_p.data[idx].x = posdat[2*idx];
        h_p.data[idx].y = posdat[2*idx+1];
        };
    };

void AVMTopologyIO::unpackVelocities(shared_ptr<VertexQuadraticEnergy> t, const vector<double> &veldat)
    {
    int Nv = t->Nvertices;
    ArrayHandle<double2> h_v(t->returnVelocities(),access_location::host,access_mode::overwrite);
    for (int idx = 0; idx < Nv; ++idx)
        {
        h_v.data[idx].x = veldat[2*idx];
        h_v.data[idx].y = veldat[2*idx+1];
        };
    };

void AVMTopologyIO::unpackNeighborsAndCells(shared_ptr<VertexQuadraticEnergy> t, const vector<int> &vndat, const vector<int> &vcndat)
    {
    int Nv = t->Nvertices;
    int Nc = t->Ncells;
    {
    ArrayHandle<int> h_vn(t->vertexNeighbors,access_location::host,access_mode::overwrite);
    ArrayHandle<int> h_vcn(t->vertexCellNeighbors,access_location::host,access_mode::overwrite);
    for (int vv = 0; vv < Nv; ++vv)
        {
        for (int ii = 0; ii < 3; ++ii)
            {
            h_vn.data[3*vv+ii]  = vndat[3*vv+ii];
            h_vcn.data[3*vv+ii] = vcndat[3*vv+ii];
            };
        };
    };

    vector<int> cvn(Nc,0);
    for (int vv = 0; vv < Nv; ++vv)
        for (int ii = 0; ii < 3; ++ii)
            {
            int cell = vcndat[3*vv+ii];
            if (cell >= 0 && cell < Nc)
                cvn[cell] += 1;
            };
    int nMax = 0;
    {
    ArrayHandle<int> h_nn(t->cellVertexNum,access_location::host,access_mode::overwrite);
    for (int cc = 0; cc < Nc; ++cc)
        {
        h_nn.data[cc] = cvn[cc];
        if (cvn[cc] > nMax)
            nMax = cvn[cc];
        cvn[cc] = 0;
        };
    };
    // Keep rings in the existing vertexMax-wide cellVertices layout when it already fits
    // (constructor uses vertexMax=30). Shrinking n_idx desyncs computeGeometryCPU.
    int needMax = nMax + 2;
    if (needMax > t->vertexMax)
        t->growCellVerticesList(needMax);

    int nReversed = 0;
    int nWalkFail = 0;
    {
    ArrayHandle<double2> h_p(t->vertexPositions,access_location::host,access_mode::read);
    ArrayHandle<int> h_n(t->cellVertices,access_location::host,access_mode::overwrite);
    ArrayHandle<int> h_nn(t->cellVertexNum,access_location::host,access_mode::read);
    ArrayHandle<int> h_vn(t->vertexNeighbors,access_location::host,access_mode::read);
    ArrayHandle<int> h_vcn(t->vertexCellNeighbors,access_location::host,access_mode::read);

    auto vertexHasCell = [&](int v, int cell)
        {
        for (int ff = 0; ff < 3; ++ff)
            if (h_vcn.data[3*v+ff] == cell)
                return true;
        return false;
        };

    for (int cc = 0; cc < Nc; ++cc)
        {
        int neigh = h_nn.data[cc];
        if (neigh < 3)
            continue;
        int v0 = -1;
        for (int vv = 0; vv < Nv && v0 < 0; ++vv)
            if (vertexHasCell(vv,cc))
                v0 = vv;
        if (v0 < 0)
            {
            nWalkFail += 1;
            continue;
            };
        // Walk the 3-valent mesh around cell cc (two neighbors of each vertex also bound cc).
        int vPrev = -1;
        int vCur = v0;
        int nGot = 0;
        bool ok = true;
        for (int step = 0; step < neigh; ++step)
            {
            h_n.data[t->n_idx(nGot,cc)] = vCur;
            nGot += 1;
            int vNext = -1;
            for (int ff = 0; ff < 3; ++ff)
                {
                int w = h_vn.data[3*vCur+ff];
                if (w < 0 || w >= Nv || w == vPrev)
                    continue;
                if (!vertexHasCell(w,cc))
                    continue;
                vNext = w;
                if (vPrev >= 0)
                    break;
                };
            if (vNext < 0)
                {
                ok = false;
                break;
                };
            vPrev = vCur;
            vCur = vNext;
            };
        if (!ok || nGot != neigh || vCur != v0)
            {
            nWalkFail += 1;
            continue;
            };
        double2 cellPos = h_p.data[h_n.data[t->n_idx(neigh-2,cc)]];
        int vidx = h_n.data[t->n_idx(neigh-1,cc)];
        double2 vcur, vnext;
        t->Box->minDist(h_p.data[vidx],cellPos,vcur);
        double Varea = 0.0;
        for (int nn = 0; nn < neigh; ++nn)
            {
            vidx = h_n.data[t->n_idx(nn,cc)];
            t->Box->minDist(h_p.data[vidx],cellPos,vnext);
            Varea += SignedPolygonAreaPart(vcur,vnext);
            vcur = vnext;
            };
        if (Varea < 0.0)
            {
            nReversed += 1;
            for (int vv = 0; vv < neigh/2; ++vv)
                {
                int a = t->n_idx(vv,cc);
                int b = t->n_idx(neigh-1-vv,cc);
                int tmp = h_n.data[a];
                h_n.data[a] = h_n.data[b];
                h_n.data[b] = tmp;
                };
            };
        };
    };
    printf("AVM unpack: nMax=%d reversed_rings=%d walk_fail=%d\n", nMax, nReversed, nWalkFail);

    t->initializeEdgeFlipLists();
    t->forcesUpToDate = false;
    };
