#ifndef AVM_TOPOLOGY_IO_H
#define AVM_TOPOLOGY_IO_H

// Generated by Cursor. 2026-08-21
// Shared AVM topology pack/unpack for restart and trajectory NetCDF writers.

#include "vertexQuadraticEnergy.h"

class AVMTopologyIO
    {
    public:
        //! Pack vertex positions (tag order) into posdat of length 2*Nv
        static void packPositions(shared_ptr<VertexQuadraticEnergy> s, vector<double> &posdat);
        //! Pack vertex velocities (tag order)
        static void packVelocities(shared_ptr<VertexQuadraticEnergy> s, vector<double> &veldat);
        //! Pack vertex-vertex and vertex-cell neighbor tags
        static void packNeighbors(shared_ptr<VertexQuadraticEnergy> s, vector<int> &vndat, vector<int> &vcndat);
        //! Unpack positions into current indices (assumes load in tag order, tags = 0..Nv-1)
        static void unpackPositions(shared_ptr<VertexQuadraticEnergy> t, const vector<double> &posdat);
        static void unpackVelocities(shared_ptr<VertexQuadraticEnergy> t, const vector<double> &veldat);
        //! Unpack neighbor arrays and rebuild CCW cellVertices
        static void unpackNeighborsAndCells(shared_ptr<VertexQuadraticEnergy> t, const vector<int> &vndat, const vector<int> &vcndat);
        static void resetIdentityTags(shared_ptr<VertexQuadraticEnergy> t);
    };

#endif
