#include "avmTopologyIO.h"
// Generated by Cursor. 2026-08-21
// Vertex-model topology I/O. VertexCellNeighbors are stored as cell tags, not vertex tags.

void AVMTopologyIO::packPositions(shared_ptr<VertexQuadraticEnergy> s, vector<double> &posdat)
    {
    int Nv = s->Nvertices;
    posdat.resize(2*Nv);
    ArrayHandle<double2> h_p(s->vertexPositions,access_location::host,access_mode::read);
    for (int ii = 0; ii < Nv; ++ii)
        {
        int pidx = s->tagToIdxVertex[ii];
        posdat[2*ii]   = h_p.data[pidx].x;
        posdat[2*ii+1] = h_p.data[pidx].y;
        };
    };

void AVMTopologyIO::packVelocities(shared_ptr<VertexQuadraticEnergy> s, vector<double> &veldat)
    {
    int Nv = s->Nvertices;
    veldat.resize(2*Nv);
    ArrayHandle<double2> h_v(s->returnVelocities(),access_location::host,access_mode::read);
    for (int ii = 0; ii < Nv; ++ii)
        {
        int pidx = s->tagToIdxVertex[ii];
        veldat[2*ii]   = h_v.data[pidx].x;
        veldat[2*ii+1] = h_v.data[pidx].y;
        };
    };

void AVMTopologyIO::packNeighbors(shared_ptr<VertexQuadraticEnergy> s, vector<int> &vndat, vector<int> &vcndat)
    {
    int Nv = s->Nvertices;
    vndat.resize(3*Nv);
    vcndat.resize(3*Nv);
    ArrayHandle<int> h_vn(s->vertexNeighbors,access_location::host,access_mode::read);
    ArrayHandle<int> h_vcn(s->vertexCellNeighbors,access_location::host,access_mode::read);
    for (int vv = 0; vv < Nv; ++vv)
        {
        int vertexIndex = s->tagToIdxVertex[vv];
        for (int ii = 0; ii < 3; ++ii)
            {
            vndat[3*vv+ii]  = s->idxToTagVertex[h_vn.data[3*vertexIndex+ii]];
            vcndat[3*vv+ii] = s->idxToTag[h_vcn.data[3*vertexIndex+ii]];
            };
        };
    };

void AVMTopologyIO::resetIdentityTags(shared_ptr<VertexQuadraticEnergy> t)
    {
    int Nv = t->Nvertices;
    int Nc = t->Ncells;
    t->tagToIdxVertex.resize(Nv);
    t->idxToTagVertex.resize(Nv);
    for (int ii = 0; ii < Nv; ++ii)
        {
        t->tagToIdxVertex[ii] = ii;
        t->idxToTagVertex[ii] = ii;
        };
    t->tagToIdx.resize(Nc);
    t->idxToTag.resize(Nc);
    for (int ii = 0; ii < Nc; ++ii)
        {
        t->tagToIdx[ii] = ii;
        t->idxToTag[ii] = ii;
        };
    };

void AVMTopologyIO::unpackPositions(shared_ptr<VertexQuadraticEnergy> t, const vector<double> &posdat)
    {
    int Nv = t->Nvertices;
    ArrayHandle<double2> h_p(t->vertexPositions,access_location::host,access_mode::overwrite);
    for (int idx = 0; idx < Nv; ++idx)
        {
        h_p.data[idx].x = posdat[2*idx];
        h_p.data[idx].y = posdat[2*idx+1];
        };
    };

void AVMTopologyIO::unpackVelocities(shared_ptr<VertexQuadraticEnergy> t, const vector<double> &veldat)
    {
    int Nv = t->Nvertices;
    ArrayHandle<double2> h_v(t->returnVelocities(),access_location::host,access_mode::overwrite);
    for (int idx = 0; idx < Nv; ++idx)
        {
        h_v.data[idx].x = veldat[2*idx];
        h_v.data[idx].y = veldat[2*idx+1];
        };
    };

void AVMTopologyIO::unpackNeighborsAndCells(shared_ptr<VertexQuadraticEnergy> t, const vector<int> &vndat, const vector<int> &vcndat)
    {
    int Nv = t->Nvertices;
    int Nc = t->Ncells;
    ArrayHandle<int> h_vn(t->vertexNeighbors,access_location::host,access_mode::overwrite);
    ArrayHandle<int> h_vcn(t->vertexCellNeighbors,access_location::host,access_mode::overwrite);
    for (int vv = 0; vv < Nv; ++vv)
        {
        for (int ii = 0; ii < 3; ++ii)
            {
            h_vn.data[3*vv+ii]  = vndat[3*vv+ii];
            h_vcn.data[3*vv+ii] = vcndat[3*vv+ii];
            };
        };

    vector<int> cvn(Nc,0);
    for (int vv = 0; vv < Nv; ++vv)
        for (int ii = 0; ii < 3; ++ii)
            {
            int cell = vcndat[3*vv+ii];
            if (cell >= 0 && cell < Nc)
                cvn[cell] += 1;
            };
    int nMax = 0;
    ArrayHandle<int> h_nn(t->cellVertexNum,access_location::host,access_mode::overwrite);
    for (int cc = 0; cc < Nc; ++cc)
        {
        h_nn.data[cc] = cvn[cc];
        if (cvn[cc] > nMax)
            nMax = cvn[cc];
        cvn[cc] = 0;
        };
    t->vertexMax = nMax+2;
    t->cellVertices.resize((nMax+2)*Nc);
    t->n_idx = Index2D(nMax+2,Nc);

    ArrayHandle<double2> h_p(t->vertexPositions,access_location::host,access_mode::read);
    ArrayHandle<int> h_n(t->cellVertices,access_location::host,access_mode::overwrite);
    for (int vv = 0; vv < Nv; ++vv)
        for (int ii = 0; ii < 3; ++ii)
            {
            int cell = vcndat[3*vv+ii];
            if (cell < 0 || cell >= Nc)
                continue;
            h_n.data[t->n_idx(cvn[cell],cell)] = vv;
            cvn[cell] += 1;
            };

    for (int cc = 0; cc < Nc; ++cc)
        {
        int neigh = h_nn.data[cc];
        if (neigh < 3)
            continue;
        vector<double2> Vpoints(neigh);
        int v0 = h_n.data[t->n_idx(0,cc)];
        double2 meanPos = make_double2(0.0,0.0);
        vector<int> originalVertexOrder(neigh);
        for (int vv = 0; vv < neigh; ++vv)
            {
            int v1 = h_n.data[t->n_idx(vv,cc)];
            originalVertexOrder[vv] = v1;
            t->Box->minDist(h_p.data[v0],h_p.data[v1],Vpoints[vv]);
            meanPos = meanPos + Vpoints[vv];
            };
        for (int vv = 0; vv < neigh; ++vv)
            Vpoints[vv] = Vpoints[vv] - meanPos;
        vector<pair<double,int> > CCWorder(neigh);
        for (int vv = 0; vv < neigh; ++vv)
            {
            CCWorder[vv].first = atan2(Vpoints[vv].y,Vpoints[vv].x);
            CCWorder[vv].second = vv;
            };
        sort(CCWorder.begin(),CCWorder.begin()+neigh);
        for (int vv = 0; vv < neigh; ++vv)
            {
            int orderedVertexIndex = CCWorder[neigh-1-vv].second;
            h_n.data[t->n_idx(vv,cc)] = originalVertexOrder[orderedVertexIndex];
            };
        };

    t->initializeEdgeFlipLists();
    t->forcesUpToDate = false;
    };
