#ifndef DATABASE_NVT_AVM_RESTART_H
#define DATABASE_NVT_AVM_RESTART_H

// Generated by Cursor. 2026-08-21
// Exact NVT restart for the 2D vertex model: vertices, topology, velocities, NH bath.

#include "vertexQuadraticEnergy.h"
#include "NoseHooverChainNVT.h"
#include "DatabaseNetCDF.h"

class nvtAVMRestartDatabase : public BaseDatabaseNetCDF
    {
    private:
        int Nv;
        int Nchain;
        int Nbath;
        NcDim *recDim, *NvDim, *dofDim, *NvnDim, *boxDim, *unitDim, *bathDim, *kesDim;
        NcVar *posVar, *velVar, *vneighVar, *vcneighVar, *BoxMatrixVar, *timeVar;
        NcVar *bathVar, *kesVar, *nhStepVar, *nchainVar;
        int Current;

    public:
        nvtAVMRestartDatabase(int nv, int nchain=4, string fn="temp.nc", NcFile::FileMode mode=NcFile::ReadOnly);
        ~nvtAVMRestartDatabase(){File.close();};

        int GetNumRecs()
            {
            recDim = File.get_dim("rec");
            return recDim->size();
            };

        void writeState(shared_ptr<VertexQuadraticEnergy> s, shared_ptr<NoseHooverChainNVT> nvt, double time=-1.0, int rec=-1);
        void readState(shared_ptr<VertexQuadraticEnergy> t, shared_ptr<NoseHooverChainNVT> nvt, int rec, bool geometry=true, bool restoreThermostat=true);

    protected:
        void SetDimVar();
        void GetDimVar();
    };

#endif
