#include "nvtAVMRestartDatabase.h"
#include "avmTopologyIO.h"
// Generated by Cursor. 2026-08-21
// NVT restart NetCDF for VertexQuadraticEnergy + NoseHooverChainNVT.

nvtAVMRestartDatabase::nvtAVMRestartDatabase(int nv, int nchain, string fn, NcFile::FileMode mode)
    : BaseDatabaseNetCDF(fn,mode),
      Nv(nv),
      Nchain(nchain),
      Nbath(nchain+1),
      Current(0)
    {
    switch(Mode)
        {
        case NcFile::ReadOnly:
            break;
        case NcFile::Write:
            GetDimVar();
            break;
        case NcFile::Replace:
            SetDimVar();
            break;
        case NcFile::New:
            SetDimVar();
            break;
        default:
            ;
        };
    }

void nvtAVMRestartDatabase::SetDimVar()
    {
    recDim  = File.add_dim("rec");
    NvDim   = File.add_dim("Nv", Nv);
    dofDim  = File.add_dim("dof", Nv*2);
    NvnDim  = File.add_dim("Nvn", Nv*3);
    boxDim  = File.add_dim("boxdim",4);
    unitDim = File.add_dim("unit",1);
    bathDim = File.add_dim("bathdof", Nbath*4);
    kesDim  = File.add_dim("kes", 2);

    posVar       = File.add_var("pos",       ncDouble, recDim, dofDim);
    velVar       = File.add_var("velocity",  ncDouble, recDim, dofDim);
    vneighVar    = File.add_var("Vneighs",   ncInt,    recDim, NvnDim);
    vcneighVar   = File.add_var("VertexCellNeighbors", ncInt, recDim, NvnDim);
    BoxMatrixVar = File.add_var("BoxMatrix", ncDouble, recDim, boxDim);
    timeVar      = File.add_var("time",      ncDouble, recDim, unitDim);
    bathVar      = File.add_var("nhBath",    ncDouble, recDim, bathDim);
    kesVar       = File.add_var("nhKES",     ncDouble, recDim, kesDim);
    nhStepVar    = File.add_var("nhTimestep",ncDouble, recDim, unitDim);
    nchainVar    = File.add_var("nchain",    ncDouble, recDim, unitDim);
    }

void nvtAVMRestartDatabase::GetDimVar()
    {
    recDim = File.get_dim("rec");
    boxDim = File.get_dim("boxdim");
    NvDim  = File.get_dim("Nv");
    dofDim = File.get_dim("dof");
    NvnDim = File.get_dim("Nvn");
    unitDim = File.get_dim("unit");
    bathDim = File.get_dim("bathdof");
    kesDim  = File.get_dim("kes");
    posVar = File.get_var("pos");
    velVar = File.get_var("velocity");
    vneighVar = File.get_var("Vneighs");
    vcneighVar = File.get_var("VertexCellNeighbors");
    BoxMatrixVar = File.get_var("BoxMatrix");
    timeVar = File.get_var("time");
    bathVar = File.get_var("nhBath");
    kesVar = File.get_var("nhKES");
    nhStepVar = File.get_var("nhTimestep");
    nchainVar = File.get_var("nchain");
    }

void nvtAVMRestartDatabase::writeState(shared_ptr<VertexQuadraticEnergy> s, shared_ptr<NoseHooverChainNVT> nvt, double time, int rec)
    {
    Records += 1;
    if(rec<0) rec = recDim->size();
    if (time < 0) time = s->currentTime;

    std::vector<double> boxdat(4,0.0);
    double x11,x12,x21,x22;
    s->Box->getBoxDims(x11,x12,x21,x22);
    boxdat[0]=x11; boxdat[1]=x12; boxdat[2]=x21; boxdat[3]=x22;

    vector<double> posdat, veldat;
    vector<int> vndat, vcndat;
    AVMTopologyIO::packPositions(s, posdat);
    AVMTopologyIO::packVelocities(s, veldat);
    AVMTopologyIO::packNeighbors(s, vndat, vcndat);

    int nBath = nvt->BathVariables.getNumElements();
    vector<double> bathdat(4*nBath, 0.0);
    {
    ArrayHandle<double4> h_bv(nvt->BathVariables,access_location::host,access_mode::read);
    for (int ii = 0; ii < nBath; ++ii)
        {
        bathdat[4*ii]   = h_bv.data[ii].x;
        bathdat[4*ii+1] = h_bv.data[ii].y;
        bathdat[4*ii+2] = h_bv.data[ii].z;
        bathdat[4*ii+3] = h_bv.data[ii].w;
        };
    };
    vector<double> kesdat(2,0.0);
    {
    ArrayHandle<double> h_kes(nvt->kineticEnergyScaleFactor,access_location::host,access_mode::read);
    kesdat[0] = h_kes.data[0];
    kesdat[1] = h_kes.data[1];
    };
    double nhStep = (double)nvt->getTimestep();
    double nch = (double)nvt->getNchain();

    timeVar     ->put_rec(&time, rec);
    posVar      ->put_rec(&posdat[0], rec);
    velVar      ->put_rec(&veldat[0], rec);
    vneighVar   ->put_rec(&vndat[0], rec);
    vcneighVar  ->put_rec(&vcndat[0], rec);
    BoxMatrixVar->put_rec(&boxdat[0], rec);
    bathVar     ->put_rec(&bathdat[0], rec);
    kesVar      ->put_rec(&kesdat[0], rec);
    nhStepVar   ->put_rec(&nhStep, rec);
    nchainVar   ->put_rec(&nch, rec);
    File.sync();
    }

void nvtAVMRestartDatabase::readState(shared_ptr<VertexQuadraticEnergy> t, shared_ptr<NoseHooverChainNVT> nvt, int rec, bool geometry, bool restoreThermostat)
    {
    GetDimVar();

    timeVar->set_cur(rec);
    timeVar->get(&t->currentTime,1,1);

    BoxMatrixVar->set_cur(rec);
    std::vector<double> boxdata(4,0.0);
    BoxMatrixVar->get(&boxdata[0],1, boxDim->size());
    t->Box->setGeneral(boxdata[0],boxdata[1],boxdata[2],boxdata[3]);

    posVar->set_cur(rec);
    velVar->set_cur(rec);
    vneighVar->set_cur(rec);
    vcneighVar->set_cur(rec);
    vector<double> posdat(2*Nv,0.0);
    vector<double> veldat(2*Nv,0.0);
    posVar->get(&posdat[0],1, dofDim->size());
    velVar->get(&veldat[0],1, dofDim->size());
    // ncInt fields: read as int. A double buffer does not convert and yields garbage tags.
    vector<int> vndat(3*Nv,0);
    vector<int> vcndat(3*Nv,0);
    vneighVar->get(&vndat[0],1, NvnDim->size());
    vcneighVar->get(&vcndat[0],1, NvnDim->size());

    AVMTopologyIO::resetIdentityTags(t);
    AVMTopologyIO::unpackPositions(t, posdat);
    AVMTopologyIO::unpackVelocities(t, veldat);
    AVMTopologyIO::unpackNeighborsAndCells(t, vndat, vcndat);

    if (restoreThermostat && nvt)
        {
        vector<double> bathdat(4*Nbath,0.0);
        vector<double> kesdat(2,0.0);
        double nhStep = 0.0;
        bathVar->set_cur(rec);
        kesVar->set_cur(rec);
        nhStepVar->set_cur(rec);
        bathVar->get(&bathdat[0],1, bathDim->size());
        kesVar->get(&kesdat[0],1, kesDim->size());
        nhStepVar->get(&nhStep,1,1);
        vector<double4> bath(Nbath);
        for (int ii = 0; ii < Nbath; ++ii)
            bath[ii] = make_double4(bathdat[4*ii], bathdat[4*ii+1], bathdat[4*ii+2], bathdat[4*ii+3]);
        nvt->restoreBathState(bath, kesdat[0], kesdat[1]);
        nvt->setTimestep((int)nhStep);
        };

    if (geometry)
        {
        t->computeGeometryCPU();
        t->getCellCentroidsCPU();
        };
    }
