#include "vertexTrajectoryDatabase.h"
#include "avmTopologyIO.h"
// Generated by Cursor. 2026-08-21
// Vertex-only trajectory NetCDF. Geometry and centroids are rebuilt on read.

vertexTrajectoryDatabase::vertexTrajectoryDatabase(int nv, string fn, NcFile::FileMode mode)
    : BaseDatabaseNetCDF(fn,mode),
      Nv(nv),
      Current(0)
    {
    switch(Mode)
        {
        case NcFile::ReadOnly:
            break;
        case NcFile::Write:
            GetDimVar();
            break;
        case NcFile::Replace:
            SetDimVar();
            break;
        case NcFile::New:
            SetDimVar();
            break;
        default:
            ;
        };
    }

void vertexTrajectoryDatabase::SetDimVar()
    {
    recDim  = File.add_dim("rec");
    NvDim   = File.add_dim("Nv", Nv);
    dofDim  = File.add_dim("dof", Nv*2);
    NvnDim  = File.add_dim("Nvn", Nv*3);
    boxDim  = File.add_dim("boxdim",4);
    unitDim = File.add_dim("unit",1);

    posVar       = File.add_var("pos",       ncDouble, recDim, dofDim);
    vneighVar    = File.add_var("Vneighs",   ncInt,    recDim, NvnDim);
    vcneighVar   = File.add_var("VertexCellNeighbors", ncInt, recDim, NvnDim);
    BoxMatrixVar = File.add_var("BoxMatrix", ncDouble, recDim, boxDim);
    timeVar      = File.add_var("time",      ncDouble, recDim, unitDim);
    }

void vertexTrajectoryDatabase::GetDimVar()
    {
    recDim = File.get_dim("rec");
    boxDim = File.get_dim("boxdim");
    NvDim  = File.get_dim("Nv");
    dofDim = File.get_dim("dof");
    NvnDim = File.get_dim("Nvn");
    unitDim = File.get_dim("unit");
    posVar = File.get_var("pos");
    vneighVar = File.get_var("Vneighs");
    vcneighVar = File.get_var("VertexCellNeighbors");
    BoxMatrixVar = File.get_var("BoxMatrix");
    timeVar = File.get_var("time");
    }

void vertexTrajectoryDatabase::writeState(STATE c, double time, int rec)
    {
    shared_ptr<VertexQuadraticEnergy> s = dynamic_pointer_cast<VertexQuadraticEnergy>(c);
    if (!s)
        return;
    Records += 1;
    if(rec<0) rec = recDim->size();
    if (time < 0) time = s->currentTime;

    std::vector<double> boxdat(4,0.0);
    double x11,x12,x21,x22;
    s->Box->getBoxDims(x11,x12,x21,x22);
    boxdat[0]=x11; boxdat[1]=x12; boxdat[2]=x21; boxdat[3]=x22;

    vector<double> posdat;
    vector<int> vndat, vcndat;
    AVMTopologyIO::packPositions(s, posdat);
    AVMTopologyIO::packNeighbors(s, vndat, vcndat);

    timeVar     ->put_rec(&time, rec);
    posVar      ->put_rec(&posdat[0], rec);
    vneighVar   ->put_rec(&vndat[0], rec);
    vcneighVar  ->put_rec(&vcndat[0], rec);
    BoxMatrixVar->put_rec(&boxdat[0], rec);
    File.sync();
    }

void vertexTrajectoryDatabase::readState(STATE c, int rec, bool geometry)
    {
    shared_ptr<VertexQuadraticEnergy> t = dynamic_pointer_cast<VertexQuadraticEnergy>(c);
    if (!t)
        return;
    GetDimVar();

    timeVar->set_cur(rec);
    timeVar->get(&t->currentTime,1,1);

    BoxMatrixVar->set_cur(rec);
    std::vector<double> boxdata(4,0.0);
    BoxMatrixVar->get(&boxdata[0],1, boxDim->size());
    t->Box->setGeneral(boxdata[0],boxdata[1],boxdata[2],boxdata[3]);

    posVar->set_cur(rec);
    vneighVar->set_cur(rec);
    vcneighVar->set_cur(rec);
    vector<double> posdat(2*Nv,0.0);
    vector<int> vndat(3*Nv,0);
    vector<int> vcndat(3*Nv,0);
    posVar->get(&posdat[0],1, dofDim->size());
    vneighVar->get(&vndat[0],1, NvnDim->size());
    vcneighVar->get(&vcndat[0],1, NvnDim->size());

    AVMTopologyIO::resetIdentityTags(t);
    AVMTopologyIO::unpackPositions(t, posdat);
    AVMTopologyIO::unpackNeighborsAndCells(t, vndat, vcndat);

    if (geometry)
        {
        t->computeGeometryCPU();
        t->getCellCentroidsCPU();
        };
    }
