#ifndef DATABASE_VERTEX_TRAJECTORY_H
#define DATABASE_VERTEX_TRAJECTORY_H

// Generated by Cursor. 2026-08-21
// Log-spaced AVM trajectories: vertex positions + topology only. Centroids are recomputed on read.

#include "vertexQuadraticEnergy.h"
#include "DatabaseNetCDF.h"

class vertexTrajectoryDatabase : public BaseDatabaseNetCDF
    {
    private:
        typedef shared_ptr<Simple2DCell> STATE;
        int Nv;
        NcDim *recDim, *NvDim, *dofDim, *NvnDim, *boxDim, *unitDim;
        NcVar *posVar, *vneighVar, *vcneighVar, *BoxMatrixVar, *timeVar;
        int Current;

    public:
        vertexTrajectoryDatabase(int nv, string fn="temp.nc", NcFile::FileMode mode=NcFile::ReadOnly);
        ~vertexTrajectoryDatabase(){File.close();};

        int GetNumRecs()
            {
            recDim = File.get_dim("rec");
            return recDim->size();
            };

        virtual void writeState(STATE c, double time = -1.0, int rec=-1);
        virtual void readState(STATE c, int rec, bool geometry=true);

    protected:
        void SetDimVar();
        void GetDimVar();
    };

#endif
